### ISSUE TITLE
Cannot use docker-java 3.0.14 with Spring Boot 2.0.0.RELEASE due to dependency conflicts

### ISSUE THREAD

**Issue by mark--** [docker-java/docker-java#1007]
We have a Spring Boot Project which uses docker-java for test suite setup. When we migrated to Spring Boot 2.0.0.RELEASE there were ClassNotFoundExceptions due to dependency conflicts for jersey-commons. We tried to fork docker-java in order to update the dependencies ourselves but could not build it due to problems with the Eclipse Virgo repository. Could you please update the dependencies to achieve compatibility with Spring Boot 2.x?

**Comment by KostyaSha** [comment]
we can't fullfill dependencies for all possible libs. You can shade library. Btw master (rc version) has changed classes, maybe it will help to workaround. 
Bundlor issues you can solve by removing maven plugin in your fork.

**Comment by mark--** [comment]
Thought so :-) - no problem. We will try out your suggestions.

**Comment by prasanna-g** [comment]
@mark--  Any luck, even I am facing the same issue with listing functions. It is throwing java.lang.NoSuchMethodError: javax.ws.rs.core.MultivaluedMap.addAll() exception. Any help would be appreciated..!!

**Comment by CyborTronik** [comment]
Same issue with: Spring boot 2.0.1.RELEASE docker-java:3.0.14

**Comment by DerTomm** [comment]
Release 3.1.0-rc-3 seems to solve this problem. No occurences in a Spring Boot 2.0.2 project anymore.

**Comment by zqd1016201951** [comment]
conflicts from the spring-cloud-starter-eureka，its dependency on javax.ws.rs jsr311-api，exclusion it will resolve the problem。

	    <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
            <exclusions>
            	<exclusion>
            	  	<groupId>javax.ws.rs</groupId>
  					<artifactId>jsr311-api</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
