### ISSUE TITLE
Cpu limit

### ISSUE THREAD

**Issue by ArtemPalahno** [docker-java/docker-java#1008]
Hello, guys are docker-java have opportunities to limit container CPU usage? Like following docker command 

`--cpus="1.5"` 
Because, i haven't find any info about this

**Comment by ArtemPalahno** [comment]
I've found the way how to do this in `UpdateContainerCmd`

**Comment by bio-boris** [comment]
@ArtemPalahno How did you figure out how to do it in the UpdateContainerCommand? Did you use withCPUPeriod and withQuota? I'm trying to figure out how to do this now.

**Comment by ArtemPalahno** [comment]
@bio-boris yes you right. I have used withCPUPeriod and withQuota together to simulating how works `--cpus
`

**Comment by yaochuancun** [comment]
@ArtemPalahno like this?I create a container first,then i set withCPUPeriod  and withQuota 
the code is:
        CreateContainerResponse container = dockerClient.createContainerCmd(imageName)
            .withMemory(1395864371L).withExposedPorts(tcpPort).withPortBindings(portBindings).withBinds(listBind).withExtraHosts(releasemanHosts).exec();
        String conId = container.getId();
        dockerClient.updateContainerCmd(conId).withCpuPeriod(50000).withCpuQuota(25000);

**Comment by ArtemPalahno** [comment]
@yaochuancun kind of. Firstly you need to create ` UpdateContainerCmd` instance , after `CreateContainerCmd` then config your container  via `CreateContainerCmd` instance  and  set up CpuQuota and CpuPeriod(as far as i know default value must be 100000) in ` UpdateContainerCmd` , finally execute in this order `CreateContainerResponse container = containerCmd.exec();
        containerUpdate.exec();
        dockerClient.startContainerCmd(container.getId()).exec();`

**Comment by yaochuancun** [comment]
@ArtemPalahno I write like this, but container start failed. Is there any error?
CreateContainerResponse container = dockerClient.createContainerCmd(imageName)
                .withMemory(1395864371L).withExposedPorts(tcpPort).withPortBindings(portBindings).withBinds(listBind).withExtraHosts(releasemanHosts).exec();
        dockerClient.updateContainerCmd(container.getId()).withCpuPeriod(100000).withCpuQuota(25000).exec();
        dockerClient.startContainerCmd(container.getId()).exec();

**Comment by bio-boris** [comment]
@yaochuancun I think the correct way to do it is in https://github.com/docker-java/docker-java/pull/867
Use setters on hostconfig, fill hostconfig object and set it on create command.

              HostConfig cpuMemoryLimiter = new HostConfig();
                cpuMemoryLimiter.withCpuQuota(10000);
                cpuMemoryLimiter.withCpuPeriod(10000);
                cpuMemoryLimiter.withMemory(209715200L); //b, k, m, g
                cpuMemoryLimiter.withMemoryReservation(209715200L);
                cntCmd.withHostConfig(cpuMemoryLimiter);

**Comment by bio-boris** [comment]
@ArtemPalahno Could you please share the formula for figuring out the equivalent of the --cpu flag? If I want half of the cores on a 2 core machine, or a 10 core machine, is it the same ratio between CPUQuota and CPUPeriod? Thank you.

**Comment by ArtemPalahno** [comment]
@bio-boris I don't completely sure that my formula correct,  but  i using something like this `  
 private static final int DEFAULT_CPU_PERIOD = 100000;
    private static final int CPU_QUOTA_CONST = 100000;       
  int cpuQuota = (int) (inputCores* CPU_QUOTA_CONST);
  hostConfig.withCpuQuota(cpuQuota).withCpuPeriod(DEFAULT_CPU_PERIOD);
`

**Comment by JonnyPtn** [comment]
These parameters aren't available when using windows containers - is there any chance of re-opening this?
