### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mydeadlyvenoms** [docker-java/docker-java#1011]
Hi everyone

Since the latest SNAPSHOT already provides service(s) integrations it would be really helpful if you could create a new release e.g., `3.0.15`.

Thank you very much!

**Comment by KostyaSha** [comment]
https://github.com/docker-java/docker-java/releases/tag/3.1.0-rc-1

**Comment by mydeadlyvenoms** [comment]
Hi @KostyaSha did you push the release to maven central?  It's not publicly hosted anywhere that I can find, if public @cdancy can create another shaded version.
