### ISSUE TITLE
Is there a forum to ask questions?

### ISSUE THREAD

**Issue by mytech1235** [docker-java/docker-java#1025]
Hi

I created an issue, which got closed immediately. Basically i am looking for help to resolve the issue i am facing. The issue i opened was https://github.com/docker-java/docker-java/issues/1024

As I am realizing i might be incorrectly using this issue system, is there a place where i can ask questions related to this library?

**Comment by KostyaSha** [comment]
Answer was provided, issue was closed. Please read in details and provide full information.

**Comment by mytech1235** [comment]
i did provide more information.
