### ISSUE TITLE
Unable to get the logs to splunk.

### ISSUE THREAD

**Issue by mytech1235** [docker-java/docker-java#1029]
Hi

I am launching a container using the docker-java api, most of it is working fine, except the logging part of it. I have the following code that I think should work, but it is not sending the logs to splunk. I have other containers running in docker on the same swarm (but not launched using docker-java api) that send the logs to splunk fine.

`CreateContainerCmd applySplunkConfiguration(CreateContainerCmd targetContainer,
                                                ImageExecutionInfo execInfo) {

        String splunkIndex = propertiesProvider.isInCDL() ? RuntimePropertiesProvider.SPLUNK_CDL_INDEX
                                                          : RuntimePropertiesProvider.SPLUNK_DCS_INDEX;
        String splunkTag = execInfo.imageId + "/" + execInfo.containerId;
        String splunkSourceType = execInfo.imageId + RuntimePropertiesProvider.SPLUNK_SOURCETYPE_SUFFIX;

        if(LOG.isInfoEnabled()) {
            LOG.info(String.format("Splunk: tag [%s], sourcetype [%s], index [%s]", splunkTag,
                                    splunkSourceType, splunkIndex));
        }

        Map<String, String> config = new HashMap<>();
        config.put(RuntimePropertiesProvider.SPLUNK_TOKEN_KEY, propertiesProvider.getSplunkToken());
        config.put(RuntimePropertiesProvider.SPLUNK_URL_KEY, propertiesProvider.getSplunkUrl());
        config.put(RuntimePropertiesProvider.SPLUNK_FORMAT_KEY,
                   RuntimePropertiesProvider.SPLUNK_FORMAT);
        config.put(RuntimePropertiesProvider.SPLUNK_INDEX_KEY, splunkIndex);
        config.put(RuntimePropertiesProvider.SPLUNK_SOURCETYPE_KEY, splunkSourceType);
        config.put(RuntimePropertiesProvider.SPLUNK_TAG_KEY, splunkTag);

        LogConfig logConfig = new LogConfig(LoggingType.SPLUNK, config);
        targetContainer = targetContainer.withLogConfig(logConfig);
        return targetContainer;
    }`

Anything I am missing here? I do not see any errors while starting the container after applying the above configuration.

I have turned on the http logging... but i cannot tell if the request is not correct, i do not know what the request should look like for the splunk configuration to work. Does any one have a sample request for create container with proper splunk configuration?

here is my request and response...

`
o.a.http.impl.execchain.MainClientExec   : Executing request POST /containers/create HTTP/1.1
o.a.http.impl.execchain.MainClientExec   : Target auth state: UNCHALLENGED
o.a.http.impl.execchain.MainClientExec   : Proxy auth state: UNCHALLENGED
org.apache.http.headers                  : http-outgoing-1 >> POST /containers/create HTTP/1.1
org.apache.http.headers                  : http-outgoing-1 >> Accept: application/json
org.apache.http.headers                  : http-outgoing-1 >> Content-Type: application/json
org.apache.http.headers                  : http-outgoing-1 >> User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5)
org.apache.http.headers                  : http-outgoing-1 >> Transfer-Encoding: chunked
org.apache.http.headers                  : http-outgoing-1 >> Host: docker-host:443
org.apache.http.headers                  : http-outgoing-1 >> Connection: Keep-Alive
org.apache.http.headers                  : http-outgoing-1 >> Accept-Encoding: gzip,deflate
org.apache.http.wire                     : http-outgoing-1 >> "POST /containers/create HTTP/1.1[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "Accept: application/json[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "Content-Type: application/json[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5)[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "Transfer-Encoding: chunked[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "Host: docker-host:443[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "ac[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "{"Env":["envType=null","APP_OPTS=XYZ-POD-17.3.0 ABCD12341"],"Image":"dtr.abc.com/talent/hello-world:latest","Volumes":{},"ExposedPorts":{},"HostConfig":{}}[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "0[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 >> "[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "HTTP/1.1 201 Created[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Api-Version: 1.30[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Api-Version: 1.30[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Cache-Control: no-cache, no-store, must-revalidate[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Content-Length: 73[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Content-Type: application/json[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Date: Thu, 03 May 2018 18:32:55 GMT[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Docker-Experimental: false[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "Ucp-Version: 2.2.3 (b3f6755b6)[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "[\r][\n]"
org.apache.http.wire                     : http-outgoing-1 << "{"Id":"4181ea88ddc1cd76dfcac45ac919436a3436b073fab3b577f4a53eb24176f05c"}"
org.apache.http.headers                  : http-outgoing-1 << HTTP/1.1 201 Created
org.apache.http.headers                  : http-outgoing-1 << Api-Version: 1.30
org.apache.http.headers                  : http-outgoing-1 << Api-Version: 1.30
org.apache.http.headers                  : http-outgoing-1 << Cache-Control: no-cache, no-store, must-revalidate
org.apache.http.headers                  : http-outgoing-1 << Content-Length: 73
org.apache.http.headers                  : http-outgoing-1 << Content-Type: application/json
org.apache.http.headers                  : http-outgoing-1 << Date: Thu, 03 May 2018 18:32:55 GMT
org.apache.http.headers                  : http-outgoing-1 << Docker-Experimental: false
org.apache.http.headers                  : http-outgoing-1 << Ucp-Version: 2.2.3 (b3f6755b6)`

**Comment by mytech1235** [comment]
Sounds like no one have any idea... or is my post not clear?

**Comment by mytech1235** [comment]
Is this a bug in the library, or I am doing something wrong?

**Comment by fengxx** [comment]
I think you need specify two extra properties
```
config.put("splunk-insecureskipverify", "true");
config.put("splunk-verify-connection", "false");
```

**Comment by mytech1235** [comment]
I figured out what the issue is. I was applying the splunk configuration after the container has been created.  As there were no errors i didn't realize the order was incorrect. i wish the API can show at least a warning that after the container has been created, no configuration can be applied to the create container command.
Here is what I had, this produced no errors but didnt work.
`CreateContainerCmd targetContainer = dockerClient.createContainerCmd(execInfo.getFullyQualifiedImageName());
        targetContainer = applyEnvironment(targetContainer, execInfo, args);
        // create the container.
        CreateContainerResponse targetContainerResponse = targetContainer.exec();
        targetContainer = applySplunkConfiguration(targetContainer, execInfo);
`

I changed the order of my methods, now it is obvious but there was no help from the API for me to find my order was incorrect.

`CreateContainerCmd targetContainer = dockerClient.createContainerCmd(execInfo.getFullyQualifiedImageName());
        targetContainer = applyEnvironment(targetContainer, execInfo, args);
        targetContainer = applySplunkConfiguration(targetContainer, execInfo);
        // create the container.
        CreateContainerResponse targetContainerResponse = targetContainer.exec();
`

**Comment by mytech1235** [comment]
I appreciate @fengxx for the response, i have not applied that change, but i appreciate the fact that someone responded. Thank You.
