### ISSUE TITLE
Convert Command Line Codes To Programmatic Java

### ISSUE THREAD

**Issue by cbaser** [docker-java/docker-java#1036]
Hello,
I have one command in Linux which is working. I want to use your client but I could not figure it out how.
`sudo docker build . -t tagName && docker run -it --network=host --add-host raspberrypi:address tagName`
Can you help me how I can change it with your client?
Thanks

**Comment by orzeh** [comment]
@cbaser read README and see [integration tests](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/cmd/BuildImageCmdIT.java#L273) for examples how to use this library
