### ISSUE TITLE
could not connect to registry with docker-java api

### ISSUE THREAD

**Issue by snaimuddin** [docker-java/docker-java#1045]
HI Team

iam not able to connect to docker registry with docker-java api
below is my code:
DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
					.withDockerHost("tcp://myregistry:5000")
					.withRegistryUsername("uname")
					.withRegistryPassword("password")
					.build();
DockerClient dockerclient = DockerClientBuilder.getInstance(config).build();
	Info info = dockerclient.infoCmd().exec();
when i tried to get info of docker am getting below exception ..

com.github.dockerjava.api.exception.NotFoundException: 404 page not found

**Comment by orzeh** [comment]
@snaimuddin you are probably connecting to Docker Registry instead of Docker Daemon. Verify URL, which you pass to `withDockerHost` method.

**Comment by snaimuddin** [comment]
@orzeh  we will have to conect to docker daemon or docker registry with this api ?
if it is with Docker Daemon then what will be url ? for example:

**Comment by orzeh** [comment]
@snaimuddin this library can be used to access Docker daemon API. The URL can vary and depends on your environment. Please check docker docs and integration tests here.

**Comment by snaimuddin** [comment]
@orzeh    withDockerHost in this method we should pass docker registry host or docker daemon ?

**Comment by snaimuddin** [comment]
@orzeh .okay good..we can use either way ..with Docker daemon or docker registry url...?

**Comment by mytech1235** [comment]
No you cannot, registry URL is different from the docker host.

The registry might be needed for pulling images, but the host is needed for you to create containers and run them.
