### ISSUE TITLE
Unhandled exception if Docker service is not running

### ISSUE THREAD

**Issue by DatPhanTien** [docker-java/docker-java#1049]
Dear, 

I would like to check a very simple use case, which is to determine whether Docker service is up and running on the node or not. If the service is not up and running, an exception should be thrown. 

So far, I could not find the method or the class which is capable of doing this.
Could you please help me with this issue.

Best regards
Dat

**Comment by orzeh** [comment]
@DatPhanTien please check the [`Ping`](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/cmd/PingCmdIT.java) command.

**Comment by DatPhanTien** [comment]
Dear,

Thanks for your response @orzeh .
I have tried that recently. I tested it with scenario 1) Docker is running and scenario 2) Docker is out. With scenario 1, it worked perfectly and returned. But with scenario 2, the exception is not handled by DockerException. Here is what I received:

`09:54:52.066 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection request: [route: {}->unix://localhost:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
09:54:52.066 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection leased: [id: 3][route: {}->unix://localhost:80][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
09:54:52.066 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:80
09:54:52.066 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-3: Shutdown connection
09:54:52.066 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-3: Close connection
09:54:52.066 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection released: [id: 3][route: {}->unix://localhost:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]

javax.ws.rs.ProcessingException: org.newsclub.net.unix.AFUNIXSocketException: Connection refused (socket: /Users/tpn6/Library/Containers/com.docker.docker/Data/s60)`

The test could not successfully finished since this exception is not handled. 
Do you have any idea for improving this?

Best 
Dat

**Comment by orzeh** [comment]
@DatPhanTien but there is not much you can do. Only if Ping command completes without error you may be sure Docker daemon is working OK. In any other case you can say that. Therefore it doesn't make any difference which exception you get, IMO.
