### ISSUE TITLE
Support 'squash' in images 

### ISSUE THREAD

**Issue by magnayn** [docker-java/docker-java#1057]
The new API includes a boolean squash option:

https://docs.docker.com/engine/api/v1.32/#operation/ImageBuild

This is highly useful feature..

**Comment by flyinprogrammer** [comment]
this might be going away FYI: https://github.com/moby/moby/issues/34565

**Comment by magnayn** [comment]
Oh god, the stupid it burns 🙄

Good to know though, thx.
