### ISSUE TITLE
thread leak in NettyDockerCmdExecFactory

### ISSUE THREAD

**Issue by alexeygrigorovaurea** [docker-java/docker-java#1068]
HI  i'm using jenkins 2.89.4 with docker plugin or  YADP (tried both on different instances)
I am using both windows and linux docker slaves
I'm facing up to  ~7k  of threads in monitoring plugin like this :

dockerjava-netty-10-174
sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:752)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/28352910/42294462-b3defb96-7fe9-11e8-9c04-8fb8be0c8db0.png)

Threads number is growing with ~1k per day in my case.
Any idea how to avoid this?

**Comment by KostyaSha** [comment]
Please fill issue to YADP.

**Comment by alexeygrigorovaurea** [comment]
HI @KostyaSha  docker-plugin  gives exactly same thread leak, so I guess it is a problem with docker-java since they are both rely on it. Isn't it the case?

**Comment by KostyaSha** [comment]
Java may behaviour different in jenkins, without clear failing code place nobody will be able to help here. Is it socket connection?

**Comment by alexeygrigorovaurea** [comment]
tcp

**Comment by KostyaSha** [comment]
3.1.0 may have additional fixes, i plan solve few PRs here and update YAD to use newer version of docker-java. So better fill issues against initial project.
