### ISSUE TITLE
Entry for "stackOrchestrator" in $HOME/.docker/config.json causes failures

### ISSUE THREAD

**Issue by asm2git** [docker-java/docker-java#1080]
I don't know if this is specific to Docker-for-Mac or just very versions of Docker, but there appears to be a new entry in $HOME/.docker/config.json:

        "stackOrchestrator" : "kubernetes"

Something, I believe in "new AuthConfig()," doesn't like this entry and gives me the following error:

        Failed to parse dockerCfgFile: /Users/myusername/.docker/config.json: Invalid Auth config file

Is there a work-around for this? Is this a known bug that someone already has plans to fix?

Thanks.

**Comment by kevwil** [comment]
Same problem here. Deleting the entry works for a while, until Docker updates the config file again.
