### ISSUE TITLE
ULimit support LONG

### ISSUE THREAD

**Issue by jxc6698** [docker-java/docker-java#1088]
DockerUlimit.java
```
public class DockerUlimit {

    @JsonProperty("Name")
    private String  name;

    @JsonProperty("Soft")
    private Integer soft;

    @JsonProperty("Hard")
    private Integer hard;
```
the type of soft/hard should be LONG

**Comment by KostyaSha** [comment]
Please PR if it still actual

**Comment by lhotari** [comment]
This is a real problem. It's valid to specify a number that doesn't fit in the bounds of an Integer for core ulimits, for example by providing `--ulimit core=99999999999:99999999999` on the command line.

**Comment by lhotari** [comment]
I made PR #1302 to resolve this issue.
