### ISSUE TITLE
Apache Karaf OSGi Failure: Missing Requirements

### ISSUE THREAD

**Issue by bradenhc** [docker-java/docker-java#1089]
I'm using docker-java v3.1.0-rc-4 on an RHEL 7 machine as part of an OSGi-based application that runs in Apache Karaf. The application is defined as a Karaf feature.

Support for docker-java in an OSGi environment was added according to #789. When I inspect the docker-java JAR I can see the `Export-Package` and `Import-Package` statements that should enable this. However, when installing the application into the Karaf runtime with a `feature:install`, I get a chain of errors about missing requirements with the last one relating to `com.github.dockerjava.api`:

```text
missing requirement [ ... ] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.github.dockerjava.api)(version>=3.1.0)(!(version>=4.0.0)))"
```
In a conversation between @PhilAndrew and @orzeh, #789 states that this API should work in Karaf. Has this been tested recently? How was the original PR tested in Karaf?

**Comment by bsideup** [comment]
please try the latest version
