### ISSUE TITLE
--runtime flag in createContainerCmd

### ISSUE THREAD

**Issue by anydoby** [docker-java/docker-java#1092]
Hello, 

I have a small question: we want to run a container with nvidia docker runtime and from the command line the invocation looks like this

```
docker run --runtime nvidia myimage 
```

I could not find anything that would allow sending this flag to the daemon. Is there a workaround or maybe I am missing something? 

Thank you in advance.

**Comment by mark800** [comment]
I have the same problem, could anybody help?

**Comment by klmntoth** [comment]
Hello!

You can do it by using a HostConfig like this for example:
```
CreateContainerResponse container = dockerClient.createContainerCmd(...)
    .withHostConfig(HostConfig.newHostConfig()
        .withRuntime("nvidia"))
    .exec();
```
