### ISSUE TITLE
How to set the memory reservation when creating a container.

### ISSUE THREAD

**Issue by mytech1235** [docker-java/docker-java#1102]
The remote api [spec for v 1.23](https://docs.docker.com/engine/api/v1.23/) provides a way to set the ``memoryReservation`` but i couldn't find  a way to set that using this api.

How can I set the memory-reservation?

**Comment by mytech1235** [comment]
I found UpdateContainerCmd which has the api to set memory reservation. Dont understand why this cannot be done with create command, it would be helpful if someone can explain.

**Comment by KostyaSha** [comment]
https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate 

com.github.dockerjava.api.command.CreateContainerCmd#withHostConfig
com.github.dockerjava.api.model.HostConfig#memoryReservation
