### ISSUE TITLE
Unable to use library with java 9 modules

### ISSUE THREAD

**Issue by guenhter** [docker-java/docker-java#1115]
Hi,

when using the library with java 9, the following error appears:

```
Error:java: the unnamed module reads package org.apache.http.impl.io from both docker.java and httpcore
```

I guess the cause is this class in your library:

```
org.apache.http.impl.io.ChunkedInputStream
```

Because it has the same namespace than the `httpcore` classes.

**Comment by aquator** [comment]
Crowded with this, it is very much annoying considering jdk8 passed eol.

**Comment by bsideup** [comment]
The class was removed in 3.2.0
