### ISSUE TITLE
Bind.java Parse does not account for Windows file paths

### ISSUE THREAD

**Issue by a4chet** [docker-java/docker-java#1118]
The [Bind.parse()](https://github.com/docker-java/docker-java/blob/80c62136df94502c627e9c40dc9cac2f2bfced0d/src/main/java/com/github/dockerjava/api/model/Bind.java#L98) function does not account for Windows paths that use colons to delimit the drive letter at the beginning of the path.

For example, a perfectly valid docker command line volume option (on Windows) would be `-v c:\temp:c:\logs` The Bind.parse() function assumes that the colons are used as delimiters between the host path & container path. Obviously on Windows this is not the case.

**Comment by pippocusini** [comment]
Hi,
Unfortunately I have the same problem. There is any update about the issue?

I'm using the **3.2.0-rc1** version.

Here the error that it gives when I Inspect Containers containing Windows Paths for binding:

`com.fasterxml.jackson.databind.JsonMappingException: Error parsing Bind 'C:\Work\BuildDeploy:C:\inetpub\wwwroot:rw' (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["HostConfig"]->com.github.dockerjava.api.model.HostConfig["Binds"])`

**Comment by bsideup** [comment]
We're currently applying some major changes to the library. Once we stabilize them, we will focus on bugfixes, including this one.

I hope you will understand it. Thanks!

@a4chet will you consider re-submitting your PR against current master? :)
