### ISSUE TITLE
Secrets handling is very cumbersome

### ISSUE THREAD

**Issue by Vampire** [docker-java/docker-java#1124]
If you want to add a secret to a service, this is really cumbersome.
You have to specify the `secretId`, `secretName`, `fileName`, `fileUid`, `fileGid` and `fileMode` or it will not work.
If you leave out the `secretId` or `secretName`, you get a `BadRequestException` with message `{"message":"rpc error: code = InvalidArgument desc = malformed secret reference"}`.
If you leave out the `fileName`, you get a `BadRequestException` with message `{"message":"rpc error: code = InvalidArgument desc = malformed file secret reference, invalid target file name provided"}`.
If you leave out the `fileUid` or `fileGid`, the command is successful, but the service just does not come up at all.
If you leave out the `fileMode`, the secret is mounted without any permissions, so even root cannot read it which makes it pretty useless.

I'd like to suggest adding some magic and some defaults:
- If `secretId` is given but no `secretName`, request the secret with the ID from the API and use its proper name automatically
- If `secretName` is given but no `secretId`, request the secret with the name from the API and use its proper ID automatically
- If `secretName` and `secretId` both are given, use them unchanged, if they don't match, Docker will complain

- Do not require any of the file properties to be set explicitly, but use as defaults
- the `secretName` as `fileName`
- `0` as uid
- `0` as gid
- `0444` as mode

These also are the defaults when using the commandline client and with this magic and defaults you could just do `.withSecrets([new ContainerSpecSecret().withSecretName('secret_name')])` just like you do `--secret secret_name` from the commandline instead of needing to do `.withSecrets([new ContainerSpecSecret().withSecretId('yvk83tj1g37qgwpgqjgu5outvs').withSecretName('secret_name').withFile(new ContainerSpecFile().withName('secret_name').withUid('0').withGid('0').withMode(0444))])`.

**Comment by Vampire** [comment]
Don't you like the idea?

**Comment by bsideup** [comment]
@Vampire `docker-java` is a low level library that wraps the Docker API. One can build a library on top of it, to provide higher level methods like "run" instead of "createContainerCmd + startContainerCmd + attachContainerCmd", or the secrets management.

Another prospect to explore would be to suggest making the secrets API easier... in Docker itself. Although I doubt they would be willing to do it.

**Comment by Vampire** [comment]
Even a low level API could have some convenience, couldn't it?
And the other commands are more similar to how the docker commandline commands behave, don't they?

**Comment by bsideup** [comment]
@Vampire Not really. Most of the commands follow 1:1 mapping to the Docker API.  There were some attempts at providing convenience, but they ended up being hard to maintain.

Given that `docker-java` is currently maintained by a single person, we have to make certain trade-offs, and not providing high level API is one of them.

**Comment by Vampire** [comment]
I see :-(
Once you know it, you can cater for it.
It is just pretty hard to find out, especially as the error message are not too helpful.

I personally wouldn't consider a few defaults here really "high-level", but well it is your project.
If you don't like the suggestion, just close the issue as wont-fix, so that at least people finding the ticket know that it will not get added and also no PR will be accepted.
