### ISSUE TITLE
Bug in Documentation: Ports.Binding should be new Ports.Binding

### ISSUE THREAD

**Issue by peter-gergely-horvath** [docker-java/docker-java#1129]
I believe the following samples in the documentation are incorrect:
```
Ports portBindings = new Ports();
portBindings.bind(tcp22, Ports.Binding(11022));
portBindings.bind(tcp23, Ports.Binding(11023));
```

based on my understanding, Ports.Binding should be instantiated here like this:
```
Ports portBindings = new Ports();
portBindings.bind(tcp22, new Ports.Binding(11022));
portBindings.bind(tcp23, new Ports.Binding(11023));
```

**Comment by KostyaSha** [comment]
Sorry, where did you found it?

**Comment by zpapez** [comment]
https://github.com/docker-java/docker-java/wiki#create-new-docker-container-and-start-it-with-exposed-ports

**Comment by zpapez** [comment]
@KostyaSha 
I prepared a fix for the documentation in my forked Wiki
https://github.com/zpapez/docker-java/wiki
Can you please check? I did not find a way to open a wiki pull request.
It is a bit related to https://github.com/docker-java/docker-java/issues/1175
but not covering the `withPortSpecs`

**Comment by bsideup** [comment]
Wiki is no longer used. Please see https://github.com/docker-java/docker-java/tree/master/docs
