### ISSUE TITLE
Feature request withEntrypoint

### ISSUE THREAD

**Issue by m451** [docker-java/docker-java#113]
Just noticed that a "withEntrypoint" method is missing from the createContainerCmd. This makes it currently impossible to override  the entrypoint defined in the image. 

I'll take a look at it but maybe somebody else is quicker then I am.

**Comment by marcuslinke** [comment]
@m451 Fixed with https://github.com/docker-java/docker-java/commit/b637b59d103659d4d5b09d8c57d14c6031aa4c8a
