### ISSUE TITLE
How can I get the stdout and stderr of BuildImageCmd?

### ISSUE THREAD

**Issue by mdanetzky** [docker-java/docker-java#1131]
LogContainerCmd allows logging of the stdout and stderr of a container. Is there a similar way to log the stdout and stderr of BuildImageCmd?

**Comment by anonymousGiraffe** [comment]
did you manage to collect a log from a done container?

**Comment by mdanetzky** [comment]
I managed to log only a running container:
```
dockerClient
.logContainerCmd(containerName)
.withStdErr(true)
.withStdOut(true)
.withFollowStream(true)
.withSince(now)
.exec(new ResultCallbackTemplate<LogContainerResultCallback, Frame>() {
    @Override
    public void onNext(Frame frame) {
        System.out.print(setup.getDockerLogPrefix() + "> " + new String(frame.getPayload()));
    }
});
```

**Comment by anonymousGiraffe** [comment]
Ok, i have tried your code, still doesnt work :(

**Comment by mdanetzky** [comment]
Right - it only logs a running container but does not log the image creation.

**Comment by anonymousGiraffe** [comment]
i tried it for running one as well.

**Comment by mdanetzky** [comment]
I use this code in the testing environment and it logs perfectly.

**Comment by anonymousGiraffe** [comment]
if i use the docker cli tool i can get the logs.

**Comment by mdanetzky** [comment]
Here are some examples, that helped me figure this out:
https://www.programcreek.com/java-api-examples/?api=com.github.dockerjava.api.command.LogContainerCmd

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/steps/DockerBuildImageStepFileCallable.java#L75-L90
