### ISSUE TITLE
 "Dockerfile is excluded by pattern" error seems incorrect

### ISSUE THREAD

**Issue by wenzowski** [docker-java/docker-java#1141]
Dupe of #286 by request.

The [Docker docs say](https://docs.docker.com/v17.09/engine/reference/builder/):
> You can even use the .dockerignore file to ignore the Dockerfile and .dockerignore files. This is useful if you are copying files from the root of the build context into your new container but do not want to include the Dockerfile or .dockerignore files (e.g. ADD . /someDir/).

To the maintainers of this project:
When #286 was closed, was an intentional choice made to create divergent functionality in `docker-java`, or was it unclear at the time that a `Dockerfile` may be validly excluded by a `.dockerignore` file?

**Comment by KostyaSha** [comment]
If docker allows, then code could be changed.

**Comment by h1nk** [comment]
This should definitely be changed as the behavior directly contradicts what users will read from the official Docker documentation.

**Comment by lddias** [comment]
Please fix this. I have to change all of my repos now to workaround this.

**Comment by GyrosGeier** [comment]
Indeed. This is a major issue moving from a shell script using Docker CLI to a Jenkins plugin using the Java API.

**Comment by GyrosGeier** [comment]
It is still a bug.

**Comment by stern-shawn** [comment]
This still appears to be a bug, ran into it in my workplace's CI/CD:

```console
11:09:15 ERROR: Process finished with exception
11:09:15 java.io.IOException: Dockerfile is excluded by pattern 'Dockerfile' in .dockerignore file
```

**Comment by torrescd** [comment]
It is still a bug.

**Comment by prashantsolanki3** [comment]
Still a bug
