### ISSUE TITLE
HealthCheck.java integer not big enough

### ISSUE THREAD

**Issue by Grisu118** [docker-java/docker-java#1143]
The startPeriod field is currently an Integer, docker uses nano seconds to represent this in the docker inspect command. So the max start period currently supported is 2.15 seconds. We cannot use the latest version because we use a start period of 60 seconds.

Version used of docker-java: 3.1.0-rc-7

> javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (60000000000) out of range of int at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 5520] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Config"]->com.github.dockerjava.api.model.ContainerConfig["Healthcheck"]->com.github.dockerjava.api.model.HealthCheck["StartPeriod"])

**Comment by KostyaSha** [comment]
Could you PR?
