### ISSUE TITLE
upgrade junixdocket dependency

### ISSUE THREAD

**Issue by david-noel** [docker-java/docker-java#1156]
Any chance junixsocket can be upgraded from 2.0.4 to at least 2.1.0?

I'm trying to get a fix for this issue rolled into docker-java.

https://github.com/kohlschutter/junixsocket/issues/45

Thanks

**Comment by KostyaSha** [comment]
please PR

**Comment by padas2** [comment]
I have a branch ready in my local system with the required changes but I do not have the required permissions. 

Someone grant me the permission to push my branch to this repo and I will raise a PR
