### ISSUE TITLE
--network host on docker run command

### ISSUE THREAD

**Issue by spaszek** [docker-java/docker-java#1157]
Hi,

is it possible to use `--network host` parameter while running `docker run` command through `docker-java` API?  

https://docs.docker.com/network/host/

similar how `docker build` does it now:
```
dockerClient.buildImageCmd().withNetworkMode("host");
```

**Comment by spaszek** [comment]
In case anyone is looking for a solution:
```java
 CreateContainerResponse container = dockerRule.getClient().createContainerCmd("busybox").withCmd("true")
                .withHostConfig(newHostConfig()
                        .withNetworkMode("host"))
                .exec();
```

source: com.github.dockerjava.cmd.StartContainerCmdIT#startContainerWithNetworkMode

**Comment by odravison** [comment]
Thanks, @spaszek ;)

**Comment by odravison** [comment]
A better way:

```
{...}
.withHostConfig((new HostConfig())
                    .withNetworkMode("host"))
{...}
```
