### ISSUE TITLE
Add getter method for the DOCKER_HOST in DefaultDockerClientConfig.Builder 

### ISSUE THREAD

**Issue by fegbers** [docker-java/docker-java#1167]
Hi,

we want to start some container on a remote host and need the DOCKER_HOST variable of a started container([project](https://github.com/springboot-testcontainer/springboot-testcontainer-common)). To enable all the features of the docker-client and also the right configuration order, we are using the [DefaultDockerClientConfig.createDefaultConfigBuilder() method](https://github.com/docker-java/docker-java/blob/31281e8e6e44efbdf215e9c2706bdd7d446b0f22/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L191). Unfortunately there is no getter method to retreive the resolved DOCKER_HOST variable. Therefore we are using reflection to gain access.

```java
   private static String getDockerHost()
    {
        try
        {
            Builder builder = DefaultDockerClientConfig.createDefaultConfigBuilder();
            Field declaredField = builder.getClass().getDeclaredField("dockerHost");
            declaredField.setAccessible(true);
            return ((URI) declaredField.get(builder)).getHost();
        }
        catch (Exception e)
        {
            ....
        }
    }
```

Is it possible to add a method? This would be great for some projects which just need the algorithms and not a docker client instance. 

Thanks for your time!

**Comment by gastendonk** [comment]
Is com.github.dockerjava.core.DefaultDockerClientConfig.getDockerHost() a solution for you?

**Comment by fegbers** [comment]
It sounds good to me!
Thanks for your reply

**Comment by mazu-rok** [comment]
> Is com.github.dockerjava.core.DefaultDockerClientConfig.getDockerHost() a solution for you?

Please, close this issue

**Comment by mazu-rok** [comment]
> It sounds good to me!
> Thanks for your reply

Please, close this issue

**Comment by fegbers** [comment]
> > It sounds good to me!
> > Thanks for your reply
> 
> Please, close this issue

Sorry, didn't saw the changes.
I will close this issue.
Thanks
