### ISSUE TITLE
Implements Exec-start and Exec-create

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#117]
I have downloaded latest version of docker-java and I have not found that exec-start and exec-create commands are available. As you said in the library description it offers a partial implementation of the full set of commands. Do you have any plan to implement them?

**Comment by andre1987** [comment]
@marcuslinke Is there any expected date for this feature?

**Comment by lordofthejars** [comment]
I will try (but I don't promise anything) to work this weekend.

**Comment by andre1987** [comment]
@lordofthejars Thanks

**Comment by andre1987** [comment]
@lordofthejars I have implemented its and its work :) If you need it now, you can find on my github https://github.com/andre1987/docker-java

@lordofthejars Only tests are missing. I will create tests on Monday and will create pull request.

**Comment by lordofthejars** [comment]
Ohh nice :) I will take a look as well, we need this feature for Arquillian Cube, so it is awesome we will have it next week :).

**Comment by andre1987** [comment]
@lordofthejars I have done creating tests for two commands. But I cannot create pull request :) I don't know how should to do this

**Comment by lordofthejars** [comment]
hehehe I have seen I can do it for you :P don't know why. Basicallygo to your project and push on pull request link on right menu and then push New Pull Request button. And you are done.

**Comment by andre1987** [comment]
Thanks @lordofthejars 
It's here https://github.com/docker-java/docker-java/pull/121

Also, I have tested it manually and it works without any problem :)

**Comment by andre1987** [comment]
I have added @marcuslinke as collaborator for my fork. I don't know if I need to do it. I have seen this message http://joxi.ru/xAeeWOdUpyBlAy after creating pull request

**Comment by lordofthejars** [comment]
Yeah, now we must way until @marcuslinke accepts the PR and release a new version. thanks for your work :+1:

**Comment by andre1987** [comment]
We also need this feature on our internal project :+1:

**Comment by marcuslinke** [comment]
@andre1987 Thanks for your contribution! I will review and merge it within the next few days.

**Comment by marcuslinke** [comment]
@andre1987 I've merged your PR with some minor adoptions. Thanks!

**Comment by andre1987** [comment]
@marcuslinke Thanks :+1:
