### ISSUE TITLE
upgrade to latest junix socket dependency (2.2)

### ISSUE THREAD

**Issue by saschaschefenacker** [docker-java/docker-java#1174]
As listed here:
https://github.com/docker-java/docker-java/pull/1159/files
the dependency was scaled up to a newer version, but not 2.2

As listed here:
https://github.com/bmuschko/gradle-docker-plugin/issues/394

version 2.2 supports win10

So please upgrade once again from 2.0 to 2.2
as also commented here: https://github.com/docker-java/docker-java/pull/1159/files#r258316287

**Comment by NWinocur** [comment]
Also affects Raspberry Pi 3B+ and other 32- & 64-bit ARM platforms.  Am trying to use a Raspberry Pi 3B+ as part of a CI/CD pipeline, and based on my troubleshooting so far, this appears to be the issue.

**Comment by tbouffard** [comment]
It looks like this is already available in the 3.1.2 release
See 235e91a66696fabd5dfb407eed27fc4679b1e49c and the [3.1.2 changelog](https://github.com/docker-java/docker-java/blob/master/CHANGELOG.md#312)
