### ISSUE TITLE
ExeStartCmd do not supported tty under JerseyDockerCmdExecFactory

### ISSUE THREAD

**Issue by jasonjoo2010** [docker-java/docker-java#1186]
I want to execute /bin/sh in container and get a `stdin` for future commend input.

But i found no input could be input into the executed shell process. After some time digging code i found the related code is only existed in :

```java
    protected Void execute0(ExecStartCmd command, ResultCallback<Frame> resultCallback) {
        WebTarget webTarget = getBaseResource().path("/exec/{id}/start").resolveTemplate("id", command.getExecId());

        webTarget.request().accept(MediaType.APPLICATION_JSON).post(command, command.getStdin(), resultCallback);

        return null;
    }
```

Which i need switch to `NettyDockerCmdExecFactory`.
But the certificate which tls connection to dockerd needed is self signed. And i found some reltated PR but not in current master branch.

Is there any other solution except forking the code and repackaging it?

Thanks

**Comment by KostyaSha** [comment]
You can set any ssl trust verification on your own code side.

**Comment by jasonjoo2010** [comment]
> You can set any ssl trust verification on your own code side.

Thanks for response.
`Jersey` doesn't support `stdin` as Netty implementation, does it? I don't know whether i understand it rightly.

`TrustManager` has been initialized in `LocalDirectorySSLConfig.init` but it seems like no effect in Netty implementation. I am trying to find the reason.

**Comment by jasonjoo2010** [comment]
@KostyaSha 

After download recent jdk with full source codes I dig the problem out.

The direct reason is in NettyDockerCmdExecFactory.enableHostNameVerification:

```java
sslParameters.setEndpointIdentificationAlgorithm("HTTPS");
```

After setting it in ssl parameters JDK will do addition check on endpoint identify in `AbstractTrustManagerWrapper.checkAdditionalTrust`.

Our docker's tls certificate only add host ip in `Subject` segment like:

```
Subject: CN=192.168.123.60
```

But `AbstractTrustManagerWrapper.checkAdditionalTrust` will do the addition check in `2.5.29.17` segment in extension part of certificate.

So there are two solutions:

1. Comment `enableHostNameVerification()` (Which has been tested)
2. Add the information required in extension part. (Which we will try next)

**Comment by jasonjoo2010** [comment]
Update:

Generate certificate using version 3 and add `subjectAltName=IP:${IP}` also fix the problem.

Maybe we could disable it when using `version 1` of certificate or as a configurable item.
Surely only in `NettyDockerCmdExecFactory`.

And should document that Jersey implementation `doesn't support stdin` when start a commend.

**Comment by bsideup** [comment]
Jersey now throws an exception when `stdin` is provided. Other transports (Netty, OkHttp, Apache HttpClient5) should work fine.
