### ISSUE TITLE
God,Help Me!How to Set Port mapping?such as,follow

### ISSUE THREAD

**Issue by iamzxj** [docker-java/docker-java#1188]
docker run -d -p 9988:80 -v /etc/docker/nginxs/demo.conf:/etc/nginx/conf.d/default.conf --name sims  jfcloud/sims

**Comment by iamzxj** [comment]
I solved it

**Comment by RaduFurnea** [comment]
Hi @iamzxj did you manage to solve it without using the deprecated methods (withPortBindings) ?

**Comment by bsideup** [comment]
@RaduFurnea most of the deprecated methods are available under `getHostConfig()`
