### ISSUE TITLE
Configured credentials are not used when pushing/pulling an image

### ISSUE THREAD

**Issue by bmuschko** [docker-java/docker-java#119]
I am looking for an example or test case that uses the Docker daemon but then pushes the image to the repository in the DockerHub registry instead of the local repository (or both). My `DockerClientConfig` looks as such:

    DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder()
        .withUri("https://my-docker-host.tld:2376")
        .withUsername("dockeruser")
        .withPassword("ilovedocker")
        .withEmail("dockeruser@github.com")
        .withServerAddress("https://index.docker.io/v1/")
        .build();

How is the `serverAddress` taken into account? I'd expect that it is used to define the target registry. Could you shed some light on this use case?

Do I need to define a tag that uses index.docker.io as part of the image tag as described on the [Docker API documentation page](https://docs.docker.com/reference/api/docker_remote_api_v1.15/#push-an-image-on-the-registry)? If I try that, a `com.github.dockerjava.core.InvalidRepositoryNameException` is thrown. Shouldn't that be possible?

Let me know if I am missing something completely here.

**Comment by gesellix** [comment]
@bmuschko happy new year :)

I guess the auth command only checks if your credentials are valid, but it doesn't mean you have a valid session for subsequent commands. It looks like you need to use the push command like this:

```
AuthConfig auth = new AuthConfig()
auth.setUsername(...)
auth.setPassword(...)
...
dockerClient.pushImageCmd("...").withAuthConfig(auth).exec()
```

**Comment by bmuschko** [comment]
@gesellix Happy New Year to you, too! Using the method `withAuthConfig` seems to do it. I saw it existed but I didn't follow through. Thanks for pointing me to it again. However, it raises the question on why there are the methods on `DockerClientConfig` at all then. Maybe the set registry values are only used under a certain condition. I will need to have a deeper look at the push command in the next couple of days.

**Comment by bmuschko** [comment]
> However, it raises the question on why there are the methods on DockerClientConfig at all then.

@marcuslinke Would you mind commenting on my question?

**Comment by marcuslinke** [comment]
@bmuschko Sorry for late reply first... However, it seems like a bug to me. Auth configuration of ```DockerClientConfig``` is not passed into the command instance here https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/DockerClientImpl.java#L127

This was probably introduced with multiple refactorings of the configuraton stuff. Will fix it soon.

**Comment by marcuslinke** [comment]
@bmuschko Should be fixed with https://github.com/docker-java/docker-java/commit/99b3367e99c50b22e709eaa83a3f30f96f2928be

**Comment by bmuschko** [comment]
@marcuslinke Thanks, I think that should do it. You should probably verify the functionality by writing an integration test for pushing and pulling to a registry. :-)

**Comment by marcuslinke** [comment]
@bmuschko There are test cases for pushing/pulling already but i had a .dockercfg file locally with the right credentials so it worked for me.
