### ISSUE TITLE
inspectContainerCmd print out the error even though the NotFoundException is caught

### ISSUE THREAD

**Issue by ywalterh** [docker-java/docker-java#1193]
https://github.com/docker-java/docker-java/blob/c5c89327108abdc50aa41d7711d4743b8bac75fe/src/main/java/com/github/dockerjava/core/async/ResultCallbackTemplate.java#L54

This line is printing out the NotFoundException even if the exception is caught. In this example:

```
public class TestUnmanagedException {

    private DockerClient dockerClient;

    @Before
    public void setup() {
        dockerClient = DockerClientBuilder.getInstance()
            .withDockerCmdExecFactory(new NettyDockerCmdExecFactory()).build();
    }

    @Test
    public void TestUnmanagedException() {
        try {
            InspectContainerResponse insepectResponse =
                dockerClient.inspectContainerCmd("nonexst").exec();
        } catch (Exception e) {
            // surpress exception
        }
    }

}
```

This is causing some unnecessary output even if the exception is caught. Is this intended behavior? Thanks for the help!

**Comment by MichaelSp** [comment]
Same here, but only seem to occur with `NettyDockerCmdExecFactory`
