### ISSUE TITLE
Why void  from load image command executed? Can't we return the official response result?

### ISSUE THREAD

**Issue by vangogh-ken** [docker-java/docker-java#1194]
It's should be key information of loading an image into docker

HTTP/1.1 200 OK
Content-Type: application/json
Transfer-Encoding: chunked

{"stream":"Loaded image: busybox:latest\n"}

**Comment by TannerYoung** [comment]
This would be useful for my use case (loading an image from a tar file, then using test-containers). There are a couple of workarounds which are all annoying.

1) Know both the file path name and the resulting image name.
2) Know the file path name, run LoadImageCmd, and simultaneously untar the file and inspect the manifest.json programmatically. This introduces an unnecessary dependency on both untar and json parsing.

**Comment by zhengxianquan** [comment]
@vangogh-ken Hello, I have encountered the same problem now, need to get the return value of loadImageCmd, get the image name and tag. Is there any good solution?

**Comment by codeseedr** [comment]
Any plans on returning the identifier of the loaded image? It looks like a clear omission to me.

**Comment by codeseedr** [comment]
Seems like the command response does not include image ID... Reported the issue upstream: https://github.com/docker/cli/issues/2212

**Comment by codeseedr** [comment]
Bump.

**Comment by AgentOak** [comment]
Bump

**Comment by codeseedr** [comment]
Can I ask everybody interested in getting this fixed to thumb up/comment on the prerequisite docker issue: https://github.com/docker/cli/issues/2212? Thank you!

**Comment by codeseedr** [comment]
Lack of activity does not mean that the issue has become invalid. Or there's no one interested in getting it fixed.

**Comment by bsideup** [comment]
> there's no one interested in getting it fixed.

If there is anyone who is willing to work on this they are more than welcome to!
Although [there doesn't seem to be enough activity in the upstream issue](https://github.com/docker/cli/issues/2212)

**Comment by AgentOak** [comment]
Still not stale

**Comment by codeseedr** [comment]
Bump.

**Comment by bsideup** [comment]
There is no point in bumping unless it gets implemented on the Docker API side:

https://github.com/docker/cli/issues/2212#issuecomment-562120589

**Comment by codeseedr** [comment]
What are the chances it gets implemented if the upstream issue eventually gets fixed but this one would have already been stale for a long time?

**Comment by bsideup** [comment]
There wilk be another "Support this new API" issue :)

**Comment by codeseedr** [comment]
OK, sounds good.

**Comment by pollappeng** [comment]
> This would be useful for my use case (loading an image from a tar file, then using test-containers). There are a couple of workarounds which are all annoying.
> 
> 1. Know both the file path name and the resulting image name.

@TannerYoung - Mind sharing how you were able to accomplish this workaround? It seems pretty reasonable to me.

**Comment by vipingupta5352** [comment]
> This would be useful for my use case (loading an image from a tar file, then using test-containers). There are a couple of workarounds which are all annoying.
> 
> 1. Know both the file path name and the resulting image name.
> 2. Know the file path name, run LoadImageCmd, and simultaneously untar the file and inspect the manifest.json programmatically. This introduces an unnecessary dependency on both untar and json parsing.

@TannerYoung  can you please share how did you implement this workaround.
