### ISSUE TITLE
Please fix Wiki page: withBinds -> withHostConfig

### ISSUE THREAD

**Issue by gastendonk** [docker-java/docker-java#1195]
CreateContainerCmd.withBinds() does not exist any more. withHostConfig() must be used instead. Please update the Wiki page ( https://github.com/docker-java/docker-java/wiki ).

        HostConfig hostConfig = new HostConfig().withBinds(new Bind("host dir", new Volume("container dir")));
...
                .withHostConfig(hostConfig)

**Comment by xue8** [comment]
thx

**Comment by peavers** [comment]
Just spent 45 minutes working this out.

**Comment by MartinVerges** [comment]
please fix that and thanks to @gastendonk

**Comment by bsideup** [comment]
Wiki is no longer used. Please see https://github.com/docker-java/docker-java/tree/master/docs
