### ISSUE TITLE
On JDK Version

### ISSUE THREAD

**Issue by ghost** [docker-java/docker-java#1198]
Can't docker-java work on JDK8? I need to use docker-java, but my project is JDK8. How should I deal with this problem?

**Comment by hugares** [comment]
The minimum java version is 7, what is preventing you from using docker-java with java 8?

**Comment by Alex-Vol-SV** [comment]
The recent upgrade of jersey-core to version 2.30 has introduced Java 11 bytecodes into docker-java. I believe jersey has removed support for Java 8 since 2.29.

**Comment by bsideup** [comment]
@Alex-Vol-SV I don't think this is correct:
https://github.com/eclipse-ee4j/jersey/blob/2.30/pom.xml#L2055

I just tried running some of the docker-java tests and they run fine on Java 8.

**Comment by bsideup** [comment]
@ghost docker-java work fine on Java 8 and higher.

**Comment by Alex-Vol-SV** [comment]
There may be some other unfortunate secondary dependency update, I tried the docker-java-shaded build against the latest docker-java and it has a Java 11 bytecode issue. I wiil do some more drill down there. The shaded build pulls all of docker-java and dependencies into a single uber jar for inclusion in the gradle-docker-plugin.

**Comment by bsideup** [comment]
@Alex-Vol-SV we do not ship `docker-java-shaded` artifacts. Please report to the project you're using.
