### ISSUE TITLE
Equivalent of "docker service create --with-registry-auth”?

### ISSUE THREAD

**Issue by TomGrill** [docker-java/docker-java#1205]
I could not find in doc or source. How would I do this command:

```docker service create --with-registry-auth .....```

How to pass the `--with-registry-auth` with docker-java? The flag will pass the repository credentials to the nodes.

I also opened SO question: https://stackoverflow.com/questions/56706612/docker-java-equivalent-of-docker-service-create-with-registry-auth

**Comment by yanxiaochuan** [comment]
Have you solved your problem?I had the same problem

**Comment by TomGrill** [comment]
Not yet :(
