### ISSUE TITLE
How to find the CPU MEMORY usage with docker-java client

### ISSUE THREAD

**Issue by udit0612** [docker-java/docker-java#1206]
I want to execute the docker API to get the list of CPU and memory usage with docker-java

**GET /v1.24/containers/redis1/stats HTTP/1.1**

I didn't find any suitable command for docker stats

```
DockerClient dockerClient = DockerClientBuilder.getInstance().build();
dockerClient.statsCmd(containerId);
```
But i didn't able to find output

dockerClient.statsCmd(containerId).exec(resultCallback);

I also tried to create the object of resultCallback 
Can you please help me with that

**Comment by martin-endress** [comment]
Hi @udit0612,
try the following:
```java
public Statistics getNextStatistics() throws ProfilingException {
    AsyncResultCallback<Statistics> callback = new AsyncResultCallback<>();
    client.statsCmd(containerId).exec(callback);
    Statistics stats;
    try {
        stats = callback.awaitResult();
        callback.close();
    } catch (RuntimeException | IOException e) {
        // you may want to throw an exception here
    }
    return stats; // this may be null or invalid if the container has terminated
}
```
Hope it helps,
Martin

**Comment by udit0612** [comment]
Thanks it works

**Comment by sawyersong2** [comment]
> Hi @udit0612,
> try the following:
> 
> ```java
> public Statistics getNextStatistics() {
>     AsyncResultCallback<Statistics> callback = new AsyncResultCallback<>();
>     client.statsCmd(containerId).exec(callback);
>     Statistics stats;
>     try {
>         stats = callback.awaitResult();
>         callback.close();
>     } catch (RuntimeException | IOException e) {
>         // you may want to throw an exception here
>     }
>     return stats; // this may be null or invalid if the container has terminated
> }
> ```
> 
> Hope it helps,
> Martin

Thank you very much
