### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [docker-java/docker-java#1208]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/github/dockerjava/core/KeystoreSSLConfig.java: Line number => 59: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by KostyaSha** [comment]
` public static KeyStore getInstance(String type)  throws KeyStoreException`
