### ISSUE TITLE
NotFoundException message is empty since 3.1.3

### ISSUE THREAD

**Issue by hugares** [docker-java/docker-java#1222]
Before version 3.1.3 removing an unexisting container was throwing an NotFoundException with a message, example: `{"message":"No such container: abcdefgh1234567890"}`.

Since version 3.1.3, the message of the NotFoundException is null.

This issue is preventing to upgrade from version 3.1.2 to 3.1.3 in bmuschko/gradle-docker-plugin, see failing tests of PR https://github.com/bmuschko/gradle-docker-plugin/pull/840

This is the commit causing the issue: https://github.com/docker-java/docker-java/commit/32b4db656a428fa6cd1f5b64e124954e9d187130

**Comment by KostyaSha** [comment]
From commit i don't understand what could be wrong. Only when messages exists it extracted from json, in other cases it's like before

**Comment by hugares** [comment]
I suspect that `message = node.textValue();` return null at line 85

**Comment by KostyaSha** [comment]
```
     * Does <b>NOT</b> do any conversions for non-String value nodes;
     * for non-String values (ones for which {@link #isTextual} returns
     * false) null will be returned.
```

**Comment by hugares** [comment]
Shall we revert the commit until it is fixed?

**Comment by hugares** [comment]
FYI @sschuberth

**Comment by KostyaSha** [comment]
Better add `isTextual` check

**Comment by hugares** [comment]
Ok, I will test that

**Comment by KostyaSha** [comment]
> Ok, I will test that

do you have this error under debugger?

**Comment by hugares** [comment]
No, the error was caught by functional tests of  https://github.com/bmuschko/gradle-docker-plugin. I do not have debugger but I can add print statement ans rerun the tests.

**Comment by hugares** [comment]
I added isTextual check and same thing, the exception message is null. I really need a debugger so I will check how I could attach one to the functional tests.

**Comment by hugares** [comment]
Ok, I know what is going on. The added code read the `entityStream` for a second time without reset it it. `mapper.readTree(entityStream)` returns null as documented:

```
* If no content is found from input (end-of-input), Java
* <code>null</code> will be returned.
```
The `entityStream` was already read and converted into a String so we should create the JSON object from that String.

I will push a fix soon

**Comment by hugares** [comment]
Thanks for the review and merge!

Any estimate when you will release 3.1.4?

**Comment by sschuberth** [comment]
Thanks @hugares for identifying and fixing my mistake!
