### ISSUE TITLE
Remove Guava dependency

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#124]
Hi I have downloaded Docker-Java code and I have commented Guava dependency and I have seen that it is only used for two reasons, to generate a toString, for escaping url path. IMHO adding a dependency of 2MB for only these three features it seems a bit big. Maybe removing this big dependency and add a self implementation of both methods would fit better the project. First because of download artifects you require to run it, and second and most important because you are going to avoid conflicts with developers, for example if one project needs an old version of guava and cannot run with the one provided by docker-java or for example because company have a policy to not use guava (which I know some companies who have it).

I can help on this but without removing jersey-guava because it is a dependency that comes from jersey-client.

**Comment by albers** [comment]
Jersey has an optional transitive dependency on guava. Please have a look on that so that removing guava does not result in feature loss.
Apart from that, I fully agree. Libs should have a small dependency footprint.

**Comment by lordofthejars** [comment]
So you mean we could even remove jersey-guava and jersey client will continue working?

**Comment by albers** [comment]
I don't think so. jersey-guava is not optional. But its dependency to guava _is_.
My concern is about the impact on Jersey that might result from of removing guava

**Comment by albers** [comment]
I did not look into the sources so far, my comments are based on merely looking at the POMs.

**Comment by m451** [comment]
I validated that jersey ideed is useing guava, but a re-packaged version of it. So you should be fine when the few parts mentioned by @lordofthejars are removed. Screenshot with dep. hierarchy attached. 
![dockerguava](https://cloud.githubusercontent.com/assets/2482535/5727549/36b862c8-9b64-11e4-899e-372b411858a6.png)

**Comment by lordofthejars** [comment]
Correct, jersey-guava is a repackeged, I think we could work on this.

**Comment by m451** [comment]
Just took a look at it. The methods/classes used are: 

com.google.common.base.Preconditions.checkNotNull
com.google.common.base.Objects.toStringHelper
com.google.common.net.UrlEscapers.urlPathSegmentEscaper

com.google.common.collect.ImmutableSet
com.google.common.collect.ImmutableMap
com.google.common.base.Joiner

Seems to be possible to get rid of guava.

**Comment by marcuslinke** [comment]
So most problematic will be with ```com.google.common.net.UrlEscapers.urlPathSegmentEscaper```. Somebody knows an alternative?

**Comment by m451** [comment]
Why not using the jersey-guava:2.11 dependency for that job? It's based on guava 14.0.1 so there would be some tests to do, but you would get rid of ~2MB in any case and rid of a additional dependency as long as jersey is using guava. The only thing to check is that the explicitly used jersey-guava:2.11 dep. is the same that the currentl jersey dep. is using.

Probably not a "final" solution but a efficient one.

**Comment by marcuslinke** [comment]
Sadly it does not contain ```UrlEscapers.urlPathSegmentEscaper```...

**Comment by m451** [comment]
Hmm, that's a shame. But It's licensed under Apache v.2 which is good! https://github.com/google/guava

It should be possible to just use the part of the source which is needed for the UrlEscapers.urlPathSegmentEscaper. No need to reinvent the wheel as long as you comply with the terms of Apache v2. IANAL but it should be enough in case of guava to state a modification notice.

**Comment by marcuslinke** [comment]
Fixed with https://github.com/docker-java/docker-java/pull/134

**Comment by lordofthejars** [comment]
Thanks :)
