### ISSUE TITLE
Time to Introduce Release Drafter?

### ISSUE THREAD

**Issue by oleg-nenashev** [docker-java/docker-java#1257]
Changelogs are missing for the last few releases, and it is a problem since there are some potentially breaking changes in recent releases. 

In the Jenkins project we are using the Release Drafter GitHub app, and it works really well (it generates GitHub Releases drafts based on PR titles and labels). Our docs and sample config: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc, https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml

Would be great to introduce automated changelog management in this repo

CC @KostyaSha @bsideup

**Comment by bsideup** [comment]
Integrated 👍
