### ISSUE TITLE
JsonStreamProcessor<T> can not get precpu_stats

### ISSUE THREAD

**Issue by MASEZHAO** [docker-java/docker-java#1264]
request url : http://127.0.0.1:2375/v1.37/containers/57eba6ccf565/stats?stream=false
response contains:
"precpu_stats": {
    "cpu_usage": {
      "total_usage": 55323343846,
      "percpu_usage": [
        55322511137,
        832709,
        0,
        0,
        0,
        0
      ],
      "usage_in_kernelmode": 50940000000,
      "usage_in_usermode": 5250000000
    },
    "system_cpu_usage": 109824610000000

but when i use docker api  

dockerClient.statsCmd(containerId).exec(callback);
Statistics stats = callback.awaitResult();

stats.getPreCpuStats().getSystemCpuUsage() is null
stats..getPreCpuStats().getCpuUsage().getTotalUsage() is 0

debugger:
class : JsonStreamProcessor<T>
method: processResponseStream
line : 45  ObjectNode objectNode = OBJECT_MAPPER.readTree(jp);
objectNode  precpu_stats is 0

version 3.1.2

**Comment by Arisstath** [comment]
Use `withNoStream(true)` before calling `exec(callback)`.
