### ISSUE TITLE
How to build an image using docker-java

### ISSUE THREAD

**Issue by ShangCunShanFu** [docker-java/docker-java#1265]
I don't know how to build an image using docker-java.
I thinkthat I should invoke "com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec#exec",but sadly,I don't know to write the Dockerfile that can use in docker-java.Is there a Dockerfile demo?

**Comment by tbadgu** [comment]
@ShangCunShanFu You can create a dockerfile to build an image in similar manner as you would do it with Docker CLI and then actually build the image using docker-java. PLease check below wiki example for how to build the image from dockerfile using docker-java.
https://github.com/docker-java/docker-java/wiki#build-image-from-dockerfile
