### ISSUE TITLE
Question about running with -it

### ISSUE THREAD

**Issue by UnfamousThomas** [docker-java/docker-java#1266]
Hello. I am trying to start a container with -it and then attach to it.

I figured .withTty would work but that does not seem to be the case.
I am using this command: `docker run -d -it --network bungee --name lobby localhost:5000/release-lobby` to run the container, and when I do docker attach it displays the console. However, using the api:

> DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().withRegistryUrl("localhost:5000").build();
>         DockerClient dockerClient = DockerClientBuilder.getInstance(config)
>                 .build();
>         CreateContainerResponse container = dockerClient.createContainerCmd(image)
>                 .withHostConfig((new HostConfig())
>                .withNetworkMode("bungee"))
>                 .withTty(true)
>                 .withName("lobby1")
>                 .withImage("localhost:5000/release-lobby")
>                 .exec();
>         dockerClient.startContainerCmd(container.getId()).exec();

It creates the container, however when attached to it, does not display the console.

Any tips?

**Comment by UnfamousThomas** [comment]
Any knowledgeable people have any ideas with this?

**Comment by Fejcvk** [comment]
@UnfamousThomas I know it is outdated but maybe someone will encounter this while looking for an answer. You have to add param ```withStdinOpen(true)``` to CreateContainerCmd, and after starting the container you have to exec ```dockerClient.attachContainerCmd``` with params like 
```java
               .withStdErr(true)
                .withStdOut(true)
                .withFollowStream(true)
                .withStdIn(in)
                .exec(callback(
```
To receive output from Docker (mimic -it behaviour of Docker CLI) this ```callback``` is essential. In my case it looks like
```java

class AttachContainerCallback extends ResultCallback.Adapter<Frame

    @Override
    public void onNext(Frame item) {

        System.out.print(new String(item.getPayload()));
        super.onNext(item);
    } 
```
Lastly you have to Scann input from your console and send it through the stream to container [like in this test case](https://github.com/docker-java/docker-java/blob/c3d03d6bc2770cf57769479bcfa07ca32344ecda/docker-java/src/test/java/com/github/dockerjava/cmd/AttachContainerCmdIT.java#L46)
