### ISSUE TITLE
please add support for the --gpus option

### ISSUE THREAD

**Issue by detmar-krause** [docker-java/docker-java#1273]
Docker 19.03 supports the --gpus option. Please add this option, too.

**Comment by hturki** [comment]
I submitted https://github.com/docker-java/docker-java/pull/1303 to allow for GPU support. As a workaround in the interim, it's possible to create a subclass of HostConfig which contains the DeviceRequest field referenced in my PR, and then just pass that to the standard "withHostConfig" methods in startContainerCmd, ie something like:

        String containerId = dockerClient.createContainerCmd(<image>)
                .withCmd(<foo>)
                .withHostConfig(HostConfigWithDevice.newHostConfig()
                        .withDeviceRequests(ImmutableList.of(new DeviceRequest().withCapabilities(ImmutableList.of(
                                ImmutableList.of("gpu"))))))
                .withTty(true)
                .exec();

**Comment by tonyskulk** [comment]
@hturki Thanks for your work! I was also looking for an option to set the --gpus param. Now I found your merge request but I do not understand how it works. 

Let´s say I want to specify something like: 

    docker run --gpus all

or 

    docker run --gpus 4

Is this possible with your enhancement and how would I do this?

**Comment by longerking** [comment]
@tonyskulk    I encountered the same problem, do you have a solution?

**Comment by eswisa** [comment]
@longerking @tonyskulk 
working for me, hope it helps.
@tonyskulk - you used `nvidea`, and didn't ask for the `gpu` capability
```
HostConfig hostConfig = HostConfig.newHostConfig()
    .withDeviceRequests(ImmutableList.of(new DeviceRequest()
        .withDriver("nvidia")
        .withCapabilities(ImmutableList.of(ImmutableList.of("gpu")))
        .withDeviceIds(ImmutableList.of("0"))
    )
);
```

**Comment by yaronr** [comment]
I'm able to request a specific count of GPUs as follows, but how do I specify 'all'?
If I don't specify '.withCount' then there's no device request in the output from docker inspect.
```
hostConf.withDeviceRequests(ImmutableList.of(new DeviceRequest().withDriver("nvidia")
                                                                                  .withCapabilities(ImmutableList.of(ImmutableList.of("gpu")))
                                                                                  .withCount(4)
```
