### ISSUE TITLE
where is the image tarball after i run DockerClient.saveImageCmd?

### ISSUE THREAD

**Issue by gjj2016** [docker-java/docker-java#1296]
With `docker-java` version 3.1.1.
Here is my test code:
![image](https://user-images.githubusercontent.com/19387141/71053531-a292fe80-2189-11ea-9030-32be69f3762f.png)
And Here is the result:
![image](https://user-images.githubusercontent.com/19387141/71053552-ba6a8280-2189-11ea-88cd-addf6e7c7dba.png)
But where can i find the image tarball?

**Comment by karlitobrigante** [comment]
saveImageCmd().exec() returns an InputStream that you're responsible for saving.

```kotlin
dockerClient.saveImageCmd(dockerImageTagName).exec().use {
    Files.copy(it, dockerImagePath, StandardCopyOption.REPLACE_EXISTING)
}
```
