### ISSUE TITLE
How to calculate cpu usage in %

### ISSUE THREAD

**Issue by olegtikhonov** [docker-java/docker-java#1327]
Hi guys,
started to use your client for docker container monitoring. 
What I'm trying to do is to find a way how to calculate cpu usage in percents.
Similar to
`docker stats --all --format "table {{.Name}}\t{{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}\t{{.BlockIO}}" $(docker ps | awk '{if(NR>1) print $1}') --no-stream`
It gives:
`NAME                                                                                                            CONTAINER           CPU %               MEM USAGE / LIMIT     NET I/O             BLOCK I/O`
Thanks in advance

**Comment by bsideup** [comment]
I will close as it is not an issue. Consider asking on StackOverflow since it is a generic question about Docker's API.
