### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by Liyakhat-Ali** [docker-java/docker-java#1329]
Hello,
While using api getting below error, Issue with `exec()` following is the code

```
DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().build();
DockerClient dockerClient = DockerClientBuilder.getInstance(config).build();
logger.info("Stopping container: " + instanceId);
dockerClient.stopContainerCmd(instanceId).exec();
logger.info("Removing container: " + instanceId);
dockerClient.removeContainerCmd(instanceId).exec();	

```

**Error**
`Exception in thread "main" java.lang.NoSuchMethodError: javax.ws.rs.core.UriBuilder.resolveTemplate(Ljava/lang/String;Ljava/lang/Object;Z)Ljavax/ws/rs/core/UriBuilder;`

**Comment by bsideup** [comment]
Please share more details. Which version of docker-java you're running, what dependencies do you have, etc etc
