### ISSUE TITLE
Feature Req: support stack operations.

### ISSUE THREAD

**Issue by zysaaa** [docker-java/docker-java#1330]
I know that Docker does not currently provide stack-related API, but is it possible to support stack operations through secondary encapsulation of service-related operations.
For instance, for  **docker stack rm some-stack**:  iterate all the services, find the services which have label : **com.docker.stack.namespace**(see docker/docker/cli/compose/convert/compose.go:14) and delete these services.
The idea came from this project:  https://github.com/gesellix/docker-client.

**Comment by bsideup** [comment]
`docker-java` provides 1:1 mapping to Docker's API, so, unless Docker adds such API, there are no plans to add it to `docker-java`. One can write a library on top of `docker-java` that will be calling said APIs and do the operations.
