### ISSUE TITLE
API for building an image should support parameter "extrahosts"

### ISSUE THREAD

**Issue by bmuschko** [docker-java/docker-java#1339]
Currently, the API for [building an image](https://docs.docker.com/engine/api/v1.30/#operation/ImageBuild) does not expose a method for setting the "extrahosts" parameter. Expose a new method to `BuildImageCmd` for sending along the parameter.

**Comment by Danushka96** [comment]
I will work on this.

**Comment by bmuschko** [comment]
I guess this issue should be closed now that the PR has been merged.

**Comment by KostyaSha** [comment]
yeap, PR had no magic word https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
closing manually
