### ISSUE TITLE
Calculate Memory Percent 

### ISSUE THREAD

**Issue by cleverchou** [docker-java/docker-java#1353]
In docker run  "docker stats"
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
b438ff8629e5        my-apache-app       0.00%               8.566MiB / 2.921GiB   0.29%               31kB / 9.74kB       6.18MB / 0B         82
the memory percent will be  0.29%
But, in docker-jave:
stats.getMemoryStats().getLimit().longValue(), get value1:3136389120
stats.getMemoryStats().getUsage().longValue(),get value2:15519744
the memory percent will be  0.49%  ( = value2/value1 )
Is that wrong?

**Comment by bsideup** [comment]
`docker-java` returns what Docker API returns. Check https://docs.docker.com/engine/api/v1.40/ for more info and consider reporting an issue on Docker's issue tracker if you think the values are wrong.
