### ISSUE TITLE
Add support for docker config command in docker swarm mode

### ISSUE THREAD

**Issue by Sinton** [docker-java/docker-java#1354]
something like listSecretsCmd()
about official api doc https://docs.docker.com/engine/api/v1.39/#tag/Config

**Comment by indiketa** [comment]
Starting to work on it

**Comment by trajano** [comment]
@indiketa can you add support to get data as string?  I think most use cases would store the config data as text.

Something like

```
    /**
     * This gets the decoded data as UTF-8 string.
     *
     * @return decoded data
     */
    public String getDataAsString() {
        return new String(getData(), StandardCharsets.UTF_8);
    }
```
