### ISSUE TITLE
Update Wiki page

### ISSUE THREAD

**Issue by raminqaf** [docker-java/docker-java#1359]
Hello everyone, 
I am starting to use your client for my project. I was going through the wiki page and it's really poor. Most of the method calls are deprecated or do not work. Please update the wiki page for better user experience. Thanks!

**Comment by caigentan** [comment]
Hello, I think that completely updating the wiki page is a heavy and complicated process. I am also using docker-java, and the project carries a full range of examples, such as: [https://github.com/docker-java/docker-java/blob/master/docker-java/src/test/java/com/github/dockerjava/cmd/StartContainerCmdIT.java](url) , which I usually consult will also go through: [https://godoc.org/github.com/fsouza/go-dockerclient](url) to check some information about other APIs. Hope this helps you a little.

**Comment by qlaall** [comment]
agree with you

**Comment by raminqaf** [comment]
Thanks @caigentan , but I can not find anything in the links you provided me.

**Comment by bsideup** [comment]
We plan to rework the docs and make them available as Markdown files next to the project's sources, so that everyone can contribute.

**Comment by caigentan** [comment]
> Thanks @caigentan , but I can not find anything in the links you provided me.
sorry，Try copying and pasting the following link to the browser 

1. https://github.com/docker-java/docker-java/blob/master/docker-java/src/test/java/com/github/dockerjava/cmd/StartContainerCmdIT.java

2. https://godoc.org/github.com/fsouza/go-dockerclient

**Comment by caigentan** [comment]
> Thanks @caigentan , but I can not find anything in the links you provided me.

sorry，Try this：

1. https://github.com/docker-java/docker-java/blob/master/docker-java/src/test/java/com/github/dockerjava/cmd/StartContainerCmdIT.java

2. https://godoc.org/github.com/fsouza/go-dockerclient

**Comment by bsideup** [comment]
Wiki is no longer used. Please see https://github.com/docker-java/docker-java/tree/master/docs
