### ISSUE TITLE
What did EventsResultsCallback get deprecated for?

### ISSUE THREAD

**Issue by esend7881** [docker-java/docker-java#1362]
https://github.com/docker-java/docker-java/blob/9be9c5e5d0f673a5b7ac417bf4a0f930b185f734/docker-java-core/src/main/java/com/github/dockerjava/core/command/EventsResultCallback.java#L17

And what should I used instead? I can't seem to tell.

**Comment by esend7881** [comment]
Nevermind, it seems to have been folded into HostConfig

**Comment by Hendrik-H** [comment]
`com.github.dockerjava.core.async.ResultCallbackTemplate` is deprecated and replaced by `com.github.dockerjava.api.async.ResultCallbackTemplate`. For some reason there is no replacement of `com.github.dockerjava.core.command.EventsResultCallback`. But you can copy the class and change the import to the new `ResultCallbackTemplate` class and then it's clean. A proper replacement would of course still be nice ...

**Comment by bsideup** [comment]
`EventsResultCallback` was not re-created because it does not have any logic in it and can be replaced with a generic `ResultCallback.Adapter`

**Comment by Hendrik-H** [comment]
thanks, that works. I guess a hint to that would be helpful in the deprecation annotation.
