### ISSUE TITLE
Container Remove Problem

### ISSUE THREAD

**Issue by Alemiz112** [docker-java/docker-java#1364]
Hello, Im unable to remove container by id. Everytime it throws exception, but container id is right.

This is how I create container. Returned id is than stored for feature remove.
```java
public String createContainer(String image, String[] exposedPorts, String[] envVariables){
        //Custom code here
        CreateContainerCmd cmd = this.client.createContainerCmd(image)
                .withTty(true)
                .withStdinOpen(true)
                .withExposedPorts(exposedList)
                .withHostConfig(HostConfig.newHostConfig().withPortBindings(portBindings));
        if (envVariables != null) cmd.withEnv(envVariables);

        CreateContainerResponse container = cmd.exec();
        this.startContainer(container.getId());
        return container.getId();
}

public void removeContainer(String id, boolean removeVolumes){
        try {
            this.client.removeContainerCmd(id).withRemoveVolumes(removeVolumes).exec();
        }catch (Exception e){
            this.plugin.getLogger().warning("§eWarning: Bad container ID! Unknown ID: "+id);
        }
}
```
But when I than do `removeContainer(id, true)` It throws an exception.
Thanks.

**Comment by caigentan** [comment]
Hello, when I tried to use your example, I found that I can run as expected without errors, so I think there may be a small problem with the unspecified variable definition in your code snippet. Maybe you can refer to the following two examples：
1.https://github.com/docker-java/docker-java/blob/master/docker-java/src/test/java/com/github/dockerjava/cmd/CreateContainerCmdIT.java
2. https://github.com/docker-java/docker-java/blob/master/docker-java/src/test/java/com/github/dockerjava/cmd/RemoveContainerCmdImplIT.java
hope it is of help to you.
