### ISSUE TITLE
docker-java How do I roll back the updated service

### ISSUE THREAD

**Issue by akumacs** [docker-java/docker-java#1375]
List<Service> list = docker.listServiceCmd().exec();
Service service  = list.get(0); 
TaskSpec taskSpec = new TaskSpec().withContainerSpec(new ContainerSpec().withImage(imgName));
 ServiceSpec updateServiceSpec = service.getSpec().withTaskTemplate(taskSpec);
	docker.updateServiceCmd(service.getId(),updateServiceSpec)
        .withVersion(service.getVersion().getIndex()).exec();

This is the update service I wrote.

**Comment by bsideup** [comment]
See https://docs.docker.com/engine/api/v1.40/#
