### ISSUE TITLE
Tasks do not include NetworkAttachments

### ISSUE THREAD

**Issue by trajano** [docker-java/docker-java#1376]
According to https://docs.docker.com/engine/api/v1.40/#tag/Task the result should contain `NetworksAttachments` in the result structure

**Comment by msiemens** [comment]
This is still an issue...

**Comment by bsideup** [comment]
FYI starting with 3.2.11, one can obtain any field of the response by using `getRawValues()`

**Comment by msiemens** [comment]
Yes, but it's really cumbersome to parse the NetworkAttachments contents as it's multiple layers of nested casts and map access operations.

Would you be open to a contribution that would add NetworkAttachments to the model so they can be parsed more easily?
