### ISSUE TITLE
 Multiple repository configuration

### ISSUE THREAD

**Issue by tobiasstadler** [docker-java/docker-java#1377]
In my project we are using images from quay.io and a private repository. The private repository is username/password protected. If I specify -D registry.url=private_registry -Dregistry.username=... -Dregistry.password=... on the command line, the docker-java client uses the provided username and password for accessing quay.io. Is there a way to use the username/password only for the private registry?

**Comment by bsideup** [comment]
You can implement your own `DockerClientConfig#effectiveAuthConfig`. Alternatively, use `docker login`.

**Comment by lamba92** [comment]
> You can implement your own DockerClientConfig#effectiveAuthConfig

Could you show an example?

**Comment by kiview** [comment]
As an example, that's how it is done in Testcontainers:
https://github.com/testcontainers/testcontainers-java/blob/de1324ed2800eff4da326d0c23d281399d006bc0/core/src/main/java/org/testcontainers/dockerclient/AuthDelegatingDockerClientConfig.java#L27-L49
