### ISSUE TITLE
How to run a container with --rm flag?

### ISSUE THREAD

**Issue by Hixon10** [docker-java/docker-java#1379]
Hello!

Is it possible to run a container with `--rm` flag, using docker-java? 

https://docs.docker.com/engine/reference/run/#clean-up---rm

**Comment by KostyaSha** [comment]
Docker api has no `--rm` you need control start/stop/delete lifecycle yourself

**Comment by Dominilk** [comment]
Hi!

According to this StackOverflow answer "--rm" has been moved to daemon side meaning that it should be accessible through the docker API. So it would make things a lot easier if it were implemented in this project.

https://stackoverflow.com/questions/24764197/how-can-i-run-containers-detached-and-have-them-automatically-removed-when-they

**Comment by bsideup** [comment]
See HostConfig#withAutoRemove :)

**Comment by Dominilk** [comment]
Thanks, I have been playing around since yesterday couldn't get it to work, just realized that I was compiling old code.
