### ISSUE TITLE
PushImageResultCallback missing in API Package

### ISSUE THREAD

**Issue by jansenmccloud** [docker-java/docker-java#1380]
I've upgraded to docker-java version 3.2.1 and saw that the class PushImageResultCallback was marked as deprecated:
(https://github.com/docker-java/docker-java/blob/3.2.1/docker-java-core/src/main/java/com/github/dockerjava/core/command/PushImageResultCallback.java)

in commit 9be9c5e5d0f673a5b7ac417bf4a0f930b185f734 the message says, that the class was moved to API package, but actually it isn't there.

Do you forgot to move the class (like you correctly did with the PullImageResultCallback )
or was this on purpose?

Workaround would be to copy the implementation of the deprecated PushImageResultCallback to an own class.

----

Beside a tiny constructive feedback about the usage of the docker-java libraries regarding deprecations:
* as a developer that just uses the docker-java libraries, it's really annoying to work with methods with incomplete javadoc (or none at all)
* example regarding this issue: 
i saw that the class PushImageResultCallback was deprecated in code, but actually had no information about that it was just moved. So i needed to look into the git repo, request a blame, look into the commit message and compare to the old version. Those steps could be avoided when putting a little message into the javadoc like "@deprecated moved to docker-api library"

**Comment by bsideup** [comment]
`PushImageResultCallback` is a trivial callback that can be implemented with `ResultCallback.Adapter`, so we decided to not have a dedicated class for it.

Re the Javadocs part:
Yes, the library desperately needs an improvement in this area. `3.x` branch is approaching a maintenance phase, and the future development will be focused on a new, `4.x` one.

It will have a new API, and we will try to ensure that it is properly documented.

**Comment by jansenmccloud** [comment]
ok, fine for me.
I guess the issue could be closed, then :)
