### ISSUE TITLE
Buildkit support?

### ISSUE THREAD

**Issue by nigelgbanks** [docker-java/docker-java#1381]
Could buildkit support be added  https://docs.docker.com/develop/develop-images/build_enhancements/

**Comment by nigelgbanks** [comment]
Looks like this isn't as easy to implement as adding an additional property, see https://github.com/docker/docker-py/issues/2230 and https://github.com/docker/compose/issues/6440. Turns out this requires a different API that requires establishing a session with the remote API?

I can't seem to find much in the way of documentation on how to use BuildKit with the remote API: https://docs.docker.com/engine/api/v1.40/#operation/ImageBuild.

Relevant code:
https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/command/BuildImageCmd.java

**Comment by tkrah** [comment]
Can this one maybe be considered again?

https://docs.docker.com/engine/deprecated/#legacy-builder-for-linux-images

The legacy builder will be removed eventually and this will break here, right?
