### ISSUE TITLE
QUERY: Deprecated Callback classes

### ISSUE THREAD

**Issue by nheitz** [docker-java/docker-java#1389]
A number of Callback classes (specifically, the LogContainerResultCallback) have been deprecated.  Some, like WaitContainerResultCallback have been migrated to the api module, but I don't see any alternative for the log callback.  DO i simply continue to use the deprecated one, or is there a recommended alternative?

**Comment by bsideup** [comment]
Callbacks that make sense were migrated to the `.api.*` package.
Others make no sense anymore given the presence of a new, generic `ResultCallback.Adapter` - consider using it instead of the deprecated (and to be removed!) ones.
