### ISSUE TITLE
Error on the wiki page with examples

### ISSUE THREAD

**Issue by commandercool** [docker-java/docker-java#1394]
There is an error in the code snipped on the wiki page: https://github.com/docker-java/docker-java/wiki

I believe `Intialize docker client (simple)` should go as follows:
```
DockerClient client = DockerClientBuilder.getInstance("tcp://localhost:2375").build();
```

**Comment by bsideup** [comment]
Wiki is no longer used. Please see https://github.com/docker-java/docker-java/tree/master/docs
