### ISSUE TITLE
what to use in place of deprecated methods ?

### ISSUE THREAD

**Issue by kameshsampath** [docker-java/docker-java#1395]
I see the methods **withNetworkMode** and **withPortBindings** are deprecated as of version 3.2.1. What are their replacements ??

```java
CreateContainerResponse containerResponse =
				client.createContainerCmd("alpine/socat")
						.withNetworkMode("mynetwork")
						.withName(containerName)
						.withExposedPorts(exposedPort)
						.withPortSpecs(portSpec)
						.withPortBindings(portBinding)
						.withCmd("-dd", socatListen, socatConnect)
						.exec();
```

**Comment by qoobic** [comment]
Similar to the issue I raised (#1393). Where methods are deprecated it would be useful to have the replacement/alternative described in the documentation.

**Comment by bsideup** [comment]
Duplicate of #1281

**Comment by kameshsampath** [comment]
@qoobic  and @bsideup  thanks for pointers but has the alternate API for `portBindings`?
