### ISSUE TITLE
Please revert ad7881a

### ISSUE THREAD

**Issue by magnayn** [docker-java/docker-java#140]
Guava library has been removed - and yet, it's not because it wasn't used, because you've had to copy Preconditions into the source tree. And now my patchsets don't apply, because I'm using Optional<> (a highly useful API feature).

**Comment by marcuslinke** [comment]
It was mainly removed because of its huge memory footprint.

See discussion here https://github.com/docker-java/docker-java/issues/124

What about using ```jersey.repacked.com.google.common.base.Optional``` from jersey-guava instead?

**Comment by magnayn** [comment]
So instead of using a library that is public, maintained and well-regarded,
we get to statically snapshot bits and pieces out of it? I.E: so client
applications end up with *2* definitions of things like Preconditions and
Optional ?

Yuck!

**Comment by marcuslinke** [comment]
@magnayn OK. I understand your objection. But as you may notice jersey itself has repackaged guava already within its ```jersey-guava.jar```. Why did they do this?

Guava documentation itself mentions to rip out the relevant parts if needed:
See https://code.google.com/p/guava-libraries/wiki/UsingProGuardWithGuava

```Preconditions.java``` may be removed from our own sources also by moving to ```jersey.repacked.com.google.common.base.Preconditions```. So there will be no duplications anymore.

**Comment by marcuslinke** [comment]
Removed ```Preconditions.java```in favor of using ```jersey.repacked.com.google.common.base.Preconditions``` now. https://github.com/docker-java/docker-java/commit/11ae37f1fabc6e3dc0a929bfbda3021f27f8c8f9

**Comment by magnayn** [comment]
I don't find anything Jersey does to be a compelling argument - indeed I find their packaging into a million tiny fragments a significant PITA (as well as their seemingly never-ending NIH syndrome - I suspect their isolation of has more to do with that than other concerns). Producing a jersey-guava.jar (or indeed a docker-guava.jar) is potentially a good option, but repackaging guava inside that is a bad one.

So - provided that it' can be agreed that guava is a 'good' library, then I think doing this kind of (static) repackaging is an anti-pattern, and there's better ways of achieving the same goal. Guava use should be *encouraged* - it has many other good parts, in particular things like string splitting, immutability, functional iterators, and (the one I was using and this patch nixed) optional.

So the only downside is - it's a 2.2Mb Jar. To which my initial reaction is somewhat along the lines of 'really? 2.2Mb is an issue for you? In 2015?'. Secondly, for large numbers of users, it's actually zero-cost, because guava is used a lot (the dependency should probably declare a wide range of acceptable versions rather than '18.0'). 

But assuming I think it's a worthwhile usecase to be running docker-java on wristwatch, or whatever other usecase it is that 2.2Mb of *diskspace* is an issue for - there's 3 other options :

- Run proguard or any static analysis tool on your *output* binary. This will 'strip' it down to the bare minimum (and not just guava, it'll minify everything). Disk constrained clients should probably be doing this as a matter of course anyway.
- Produce a separate docker-guava.jar, containing just the guava classes you'd like. That allows clients to specify a maven stanza that excludes the default transitive guava, and includes your docker-guava stripped edition. With some work you could likely automate this.
- Produce a separate, additional docker-java-xxx-nodeps.jar, but utilising maven to build you an uberjar, and shading (maven-shade-plugin) the dependencies. That'd satisfy the 'java on my wristwatch' brigade who are scared of static analysis tools like proguard.

Set against this, by repackaging classes inside docker-java:
- You sacrifice disk space (which I don't care about) for memory footprint (that I do). I'll now have *3* separate implementations of Preconditions floating around by JVM. 
- Relying on Jersey's Preconditions is arguably worse, as that's now coupling any classes in docker-java that use it directly to jersey. What happens when a point release removes it altogether?
- It's bad news for other constructs like Optional<T> - because of methods like 

  abstract Optional<T> or(Optional<? extends T> secondChoice);

(I.E: your client code is going to be awful if you have multiple Optional<> type definitions around)
- You create a barrier to using other library features (I must Cut&Paste)
- You create a maintenance headache (what if bugs are found in the initial library?)
- You can find yourself having accidentally forked a library (new feature gets added or bug gets fixed in code that originally came from guava). Even supposing the licenses are compatible (the same, in this instance), you find one or more author unwilling to sign the google CLA.

**Comment by marcuslinke** [comment]
@lordofthejars @m451, @albers So, what all of you think of adding guava dependency again?

**Comment by lordofthejars** [comment]
I won't do it because docker-client is a general library not a product, so it is going to be used by several clients, and in this case you are forcing them to use one concrete version of guava. What's happening if user which is developing a product needs another version of guava? Or if there are a rule in the company which says that you need to avoid using guava, ... As a general purpose library you need to add as less dependencies to external libraries as possible, for this reason we are working in docker-client to remove jersey dependency as well.

But of course it is my opinion of what a library should be.

**Comment by m451** [comment]
Well, I must agree with @lordofthejars. For me - personally - it would do no harm if it's re-added (even though it would add size and memory). But in general a library should include as less dependencies as possible. It's a lib, not a framework.

What I would agree with in general is that some more parts - @magnayn was not very specific here - should be considered to be interfaces and the lib may provide a default concrete implementation. This way @magnayn and other would be able to use a concrete lib on top of docker-java if the default implementation dosn't fit in whatever he's trying to build.

It would keep the default implementation slick but flexible. Best of both worlds - but quite a lot of work though.

**Comment by magnayn** [comment]
> and in this case you are forcing them to use one concrete version of guava.

No, you're not.

Firstly, the dependency - for a library - *ought* to be a 'any version greater than'
  <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>[11.0,)</version>
        </dependency>

And of course any locally-declared dependency would take precedence anyway. And secondly you can <exclude> this dep if you don't want it, and substitute your own minified version, as described, or ship a 'nodeps' version if you please.

Removing jersey is a red herring. You haven't /removed/ guava, you've just statically shaded it into a package - which has all the disadvantages that I describe.

"What if there is a rule in the company to not use guava" - but we still ARE using it. 

Removing jersey is probably also stupid - you're going to end up reinventing the wheel all over again and fixing all the same bugs. By all means reimplement the API as a separate client, I'd rather stick to an implementation that's had some significant amount of testing applied to it.

This drives the library in a totally 'cart before horse' fashion. Guava is in wide use - because, for example, jersey have repackaged guava, all applications that themselves *also* use guava now have a totally useless extra 1.1Mb clogging up their classpath and, more importantly, memory, because they're different classfiles.

**Comment by magnayn** [comment]
> it would do no harm if it's re-added (even though it would add size and memory)

In your use-cases (where you're not already using guava) it adds *disk space* but has no effect whatsoever on memory. The JVM loads classes dynamically.

In my use-cases, it's worse for both disk space *and* memory, as I have multiply duplicated classes in different classpath locations.

**Comment by lordofthejars** [comment]
No it is not stupid removing jersey because there are other people who usese resteasy or cxf and we have had some problems in these users when trying to use with docker-java because of multiple providers in classpath.

**Comment by gesellix** [comment]
Instead of trying to find an implementation for `Optional` and such, what about removing the need for those abstractions? Sometimes they are only a way to write less code at the expense of increased dependencies, while they don't change actual behaviour. I must admit that I didn't check the use case in docker-java for Optional and the other classes, I only want to add another thought.

**Comment by marcuslinke** [comment]
@gesellix Until now ```Optional``` is not used in master but in @magnayn forks. 

I think the main point is that guava was removed because it was used only for some helper classes that could be reimplemented on our own easily. You will find something like ```Preconditions``` in almost every java project. So for the reason of laziness it was copied into the own sources instead of re-implement this functionality. That's it. So the real question is whether we should make use of guava functionality at all.

While thinking of all of this: Removing dependencies just to prevent eventual dependency conflicts isn't a good idea. It doesn't solve the general problem. What if removing jersey and guava but still having ```org.apache.httpcomponents.httpclient```dependency for example. What if someone needs a different  version of THAT library in the classpath? The only way to overcome this general problem would be to have no dependencies at all which isn't a good idea also.

@lordofthejars Maybe your problem with jersey should be solved at the classloading level instead?

**Comment by magnayn** [comment]
You already have an API / Impl separation, there's probably nothing stopping alternative implementations that don't use jersey2. I doubt anyone is arguing against being able to do that - heck, I'm not exactly jersey's biggest fan. 

Sure, of course you can generate APIs without Optional<>s. But it's a good abstraction - particularly for APIs as it's self-documenting and fits very nicely into fluent interfaces. So good, in fact, that it's largely adopted wholesale in Java 1.8. But trying to strip literally everything out smacks of "Reductio ad absurdum" - surely it's better to build on good quality libraries that are likely to increase overall code quality?

**Comment by marcuslinke** [comment]
I think we could switch to guava back again if really needed without a problem. Closing for now.

**Comment by flandr** [comment]
I really think that this issue (reverting the removal of Guava or the later switch to using the Jersey repackaged exports) is worth reopening. The Jersey repackaged bundle is a nightmare. Consider the following package contents for `Optional` in the version currently pulled in by this project (2.11):

    continuity:nater:~/Downloads$ jar tf jersey-guava-2.11.jar  | grep Optional
    jersey/repackaged/com/google/common/base/Optional.class
    continuity:nater:~/Downloads$ javap -cp jersey-guava-2.11.jar jersey/repackaged/com/google/common/base/Optional
    Compiled from "Optional.java"
    public abstract class jersey.repackaged.com.google.common.base.Optional<T> implements java.io.Serializable {
      public static <T extends java/lang/Object> jersey.repackaged.com.google.common.base.Optional<T> absent();
      public static <T extends java/lang/Object> jersey.repackaged.com.google.common.base.Optional<T> of(T);
      public static <T extends java/lang/Object> jersey.repackaged.com.google.common.base.Optional<T> fromNullable(T);
      jersey.repackaged.com.google.common.base.Optional();
      public abstract T orNull();
    }

Since Jersey doesn't actually use Guava optionals, they aren't packaged in the bundle.
