### ISSUE TITLE
Integration tests on CI

### ISSUE THREAD

**Issue by sclassen** [docker-java/docker-java#141]
I would be willing to invest some time to get the integration tests running on circle CI.
They offer beta state support of docker in their build environments (https://circleci.com/docs/docker)

Are you interested in running the integration tests on a CI?
Would you be willing to switch from travis to circle CI if the integration tests can be run there?

**Comment by marcuslinke** [comment]
@sclassen Sounds interesting and i'm really interested. As long as it's free there wouldn't be any problem to switch. But since docker-java integration tests starts and stops many containers i doubt that it would be useful in terms of costs. (..."first container is free"...). Second I guess this service is for testing containers only. No access to docker remote API and/or socket....

**Comment by sclassen** [comment]
I go for it and try what is possible.
The "first container is free" is about build containers and not docker containers. I couldn't find anything about a limited number of docker containers you can start.

Anyway I will report back once I have succeeded or failed...

**Comment by sclassen** [comment]
OK.

I have the integration tests running using HTTP to connect to docker.
At least most of them are running. The following are failing and I excluded them for CircleCI.
I will try to get the running ones to work with HTTPS and/or unix sockets. Once I am done with this I think i will clean up the configuration and create a merge request.
I think some of the failing tests are due to the fact, that CircleCI has not the newest docker version. Others are caused by a known issue - https://github.com/docker/docker/issues/9939.

Failing tests:
---------------

ExecCreateCmdImplTest.execCreateTest
 - Exec is not supported by the lxc driver

ExecStartCmdImplTest.execStartTest
 - Exec is not supported by the lxc driver

KillContainerCmdImplTest.killContainer
 - Killed container has ExitCode 0

ListImagesCmdImplTest.listDanglingImages
 - https://github.com/docker/docker/issues/9939

RemoveContainerCmdImplTest.removeContainer
 - https://github.com/docker/docker/issues/9939

RemoveImageCmdImplTest.removeImage
 - https://github.com/docker/docker/issues/9939

ContainerDiffCmdImplTest.testContainerDiff
 - too many diffs
     [{"Kind":0,"Path":"/dev"}
     ,{"Kind":1,"Path":"/dev/fuse"}
     ,{"Kind":1,"Path":"/dev/ptmx"}
     ,{"Kind":1,"Path":"/dev/tty"}
     ,{"Kind":1,"Path":"/dev/tty1"}
     ,{"Kind":1,"Path":"/dev/stdout"}
     ,{"Kind":1,"Path":"/dev/urandom"}
     ,{"Kind":1,"Path":"/dev/full"}
     ,{"Kind":1,"Path":"/dev/kmsg"}
     ,{"Kind":1,"Path":"/dev/null"}
     ,{"Kind":1,"Path":"/dev/stdin"}
     ,{"Kind":1,"Path":"/dev/stderr"}
     ,{"Kind":1,"Path":"/dev/zero"}
     ,{"Kind":1,"Path":"/dev/fd"}
     ,{"Kind":1,"Path":"/dev/random"}
     ,{"Kind":1,"Path":"/test"}
     ]

BuildImageCmdImplTest.testDockerIgnore
 - ignore is not working

StopContainerCmdImplTest.testStopContainer
 - Stopped container has ExitCode 0
