### ISSUE TITLE
used version 3.2.2  some jar may be update

### ISSUE THREAD

**Issue by stromyin** [docker-java/docker-java#1410]
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method org.glassfish.jersey.message.internal.HeaderUtils.asStringHeadersSingleValue(Ljavax/ws/rs/core/MultivaluedMap;Ljavax/ws/rs/core/Configuration;)Ljava/util/Map; but it does not exist. Its class, org.glassfish.jersey.message.internal.HeaderUtils, is available from the following locations:

    jar:file:/home/app/checker/nsrep-checker-0.0.1.jar!/BOOT-INF/lib/jersey-common-2.25.1.jar!/org/glassfish/jersey/message/internal/HeaderUtils.class

It was loaded from the following location:

    jar:file:/home/app/checker/nsrep-checker-0.0.1.jar!/BOOT-INF/lib/jersey-common-2.25.1.jar!/

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.glassfish.jersey.message.internal.HeaderUtils

**Comment by bsideup** [comment]
Please configure your build tool to fix the classpath conflicts. Out of scope of `docker-java`.
