### ISSUE TITLE
How can i push image to local registry

### ISSUE THREAD

**Issue by myxland** [docker-java/docker-java#1413]
i create local registry and want push image into it with [pushImageCmd].
now i can find the image with command [docker images],
but can't find by the url [http://xxx.xxx.xxx.xxx:5000/v2]
can anybody help~~

**Comment by myxland** [comment]
i got it.closed

**Comment by dmmax** [comment]
Hi @myxland 
How did you resolve it?

**Comment by SoulofSZY** [comment]
how?
