### ISSUE TITLE
Get logs from a service

### ISSUE THREAD

**Issue by qoobic** [docker-java/docker-java#1417]
Hello,

I have been trying in vain to obtain logs from a service through the client code. I can retrieve the logs from my service via CURL on the command line (`curl http://localhost:2375/services/my-service-name/logs?stdout=true --output -`) but via the docker-java client I am unable to do so. My code is:
```
        StringBuilder sb = new StringBuilder();
        dockerClient.logServiceCmd(serviceName)
                .withStdout(true)
                .exec(new ResultCallback.Adapter<>() {
                    @Override
                    public void onNext(Frame frame)
                    {
                        sb.append(new String(frame.getPayload()));
                    }
                }).awaitCompletion();

        return sb.toString();
```
Any help would be much appreciated. Are there any docs indicating how this should be done as I could not find any?

Thanks
Jay

**Comment by bsideup** [comment]
@qoobic which version of `docker-java` are you using? What do you see in the logs? Please share more info, otherwise we're unable to help.

**Comment by qoobic** [comment]
Thanks for the response @bsideup.

After doing some further testing, it seems there is nothing wrong with this code - I tested against a service which I started on the command line and it my code returns the logs, so that is good.

My problem was caused by the fact I am running a test which creates a service then checks the logs, but I was checking the logs before the service containers had started.

I have found I can check for the status of the task/container via the `listTasksCmd` so I will use that to determine when the logs are available.

My question around docs is outstanding - it would be good if there were at least some basic examples available?

**Comment by bsideup** [comment]
@qoobic glad that you solved it!

> My question around docs is outstanding - it would be good if there were at least some basic examples available?

Perhaps a test for this functionality would be a great contribution, so that we protect ourselves from regressions but also provide an example of how the API is used. WDYT? :)

**Comment by qoobic** [comment]
@bsideup I could add a test but, as I'm new to the project, some advice on where to put it would be appreciated.

I still think adding some documentation for inclusion on the README would be of benefit for new users.

**Comment by bsideup** [comment]
@qoobic have a look at other Swarm tests (they all extend `SwarmCmdIT` class) for the inspiration.

There are _some_ docs (linked from README), just not on the contributing process. I will consider adding it 👍
