### ISSUE TITLE
Podman support?

### ISSUE THREAD

**Issue by c-goes** [docker-java/docker-java#1423]
I’d like to help with Podman support now that first stable version of their Docker like API is released. However I’m unsure where to start. Do you accept PR for CI integration testing with Podman?

**Comment by bsideup** [comment]
Hi @c-goes,

We could run our CI with Podman in addition to Docker, but there are no plans to "support Podman", since it is Podman's responsibility to ensure that the compatibility level works correctly.

**Comment by c-goes** [comment]
H @bsideup 
Thank you for the answer. I will report to podman project when I find problems
