### ISSUE TITLE
docker-java is using deprecated docker API for filtering images

### ISSUE THREAD

**Issue by skorhone** [docker-java/docker-java#1424]
Current implementation uses an API operation that has been dropped from API documentation after 1.24.

To find images by name, implementation currently executes query:

/images/json?filter=image name

In more recent docker versions query should be:

/images/json?filters=reference=image name

Use of deprecated api cause compatibility issues with tools that aim to provide docker compatible api (such as podman)

**Comment by skorhone** [comment]
containers/libpod#6797

**Comment by bsideup** [comment]
Since the current implementation works with _all_ Docker versions, I see no reason to change it.

docker-java is a library for Docker.
If other systems claim that they are compatible, then... well... they should be :)

**Comment by skorhone** [comment]
You are relying on a feature that is not documented and is this subject to change in any release of Docker. Even it works now there's no guarantee that it works in next release. If you think it's a defect in docker documentation and API should be supported, create an issue there.

If you update to more recent version of docker api sooner rather than later, those relying on docker-java do not have to first wait for an update and then perform emergency patching when their build system breaks after docker update

**Comment by bsideup** [comment]
You will be surprised how many production non-deprecated APIs of Docker are not documented :)

**Comment by skorhone** [comment]
Are you sure that this won't change your opinion: moby/moby#40491

**Comment by bsideup** [comment]
@skorhone well, yes and no.

As long as v1.24 (our baseline) is supported by Docker, there is no problem in using it:

> The parameter remains available when using API version 1.40 or below.

Once v1.24 is deprecated, we'd be happy to raise the baseline to whatever lowest version is supported
