### ISSUE TITLE
Adopt Semantic Versioning and move to version 1.0

### ISSUE THREAD

**Issue by alexec** [docker-java/docker-java#143]
Hi guys,

Can I request we use [Semantic Versioning](http://semver.org/). It'll make it easier to determine if a change is risky!

Also, how about being version 1.0? It's pretty stable and fully featured.

Alex

**Comment by marcuslinke** [comment]
Good idea @alexec. Just switched to 1.0.0-SNAPSHOT as the next release will include API breaking changes.
