### ISSUE TITLE
The sample code cannot be executed

### ISSUE THREAD

**Issue by bqlwx111** [docker-java/docker-java#1430]
DockerHttpClient httpClient = new ApacheDockerHttpClient.Builder()
                .dockerHost(config.getDockerHost())
                .sslConfig(config.getSSLConfig())
                .build();
The code above version 3.2.5 cannot be executed

**Comment by bqlwx111** [comment]
ApacheDockerHttpClient，This interface or class does not exist

**Comment by bsideup** [comment]
It does exist, in the `docker-java-transport-httpclient5` module. See https://github.com/docker-java/docker-java/blob/master/docs/transports.md
