### ISSUE TITLE
关于一点小疑问

### ISSUE THREAD

**Issue by doublexiaofeng** [docker-java/docker-java#1431]
你好，请问这个项目是否支持在容器执行shell脚本并返回执行的结果？

**Comment by bsideup** [comment]
Sorry, but `docker-java` is an English speaking community.

**Comment by doublexiaofeng** [comment]
sorry, does this project support the execution of shell scripts in the container and return the execution results?

**Comment by bsideup** [comment]
@doublexiaofeng yes, see `ExecCreateCmd`/`ExecStartCmd`

**Comment by doublexiaofeng** [comment]
thank you

**Comment by doublexiaofeng** [comment]
This error occurs when I run the test method: Error:osgi : [docker Java] bundler failed: error generating manifest, how can I solve this problem
