### ISSUE TITLE
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl

### ISSUE THREAD

**Issue by KaustavRayProgrammer** [docker-java/docker-java#1436]
We are using this library to do 'docker pull' from docker hub and to check whether an image with a given name already exists. We need this to work in Linux, Mac and Windows having the latest version of docker installed. But in several cases, we have hit the error mentioned in the title and that error is coming from jersey-client that is internally used by this library. 
We have tested using docker-java 3.1.5 and the latest 3.2.5 and on docker 19.03.5 and also the latest docker. The latest docker version varies on different platforms as mentioned below:
- Linux (19.03.12)
- Mac (19.03.8)
- Windows (19.03.8)

I have attached a screenshot that shows the results of our tests.

![b0a75507-5994-44e0-b2d1-89136b9c817b](https://user-images.githubusercontent.com/25818055/87544706-8ece5d00-c6c4-11ea-83fd-07d536efcbd2.PNG)

I am sharing a code snippet of what we are trying:
`
DockerClient dockerClient;

dockerClient = DockerClientBuilder.getInstance().build();

String imageName = "SOME_IMAGE_NAME";
List<Image> images = dockerClient.listImagesCmd().withImageNameFilter(imageName).exec();
if(!images.isEmpty()){
			dockerClient.removeImageCmd(images.get(0).getId());
		}
dockerClient.pullImageCmd(imageName).exec(new PullImageResultCallback()).awaitCompletion(DOCKER_PULL_WAIT_TIME, TimeUnit.SECONDS);
`

We are using Java 8.

**Comment by bsideup** [comment]
@KaustavRayProgrammer consider trying some transport other than Jersey:
https://github.com/docker-java/docker-java/blob/master/docs/transports.md

docker-java 3.2.5 should even print a warning about the usage of the Jersey transport which is implicitly set when you do `DockerClientBuilder.getInstance().build()`.

**Comment by KaustavRayProgrammer** [comment]
@bsideup  Thanks a lot for your response. I was following https://github.com/docker-java/docker-java/blob/master/docs/getting_started.md  but it was not compiling for me.
I am not able to call DockerClientImpl.getInstance() with 2 arguments as shown in the tutorial. I can only pass the config but not the client. 
Can you point me to a working example of how to use a non-default transport with docker-java? I want to use Apache HttpClient 5 considering that it is so good that it can be made default in future.

I have added version 3.2.5 of docker-java and docker-java-transport-httpclient5 as maven dependencies.

**Comment by bsideup** [comment]
@KaustavRayProgrammer I can assure you that the method is there:
https://javadoc.io/static/com.github.docker-java/docker-java-core/3.2.5/com/github/dockerjava/core/DockerClientImpl.html#getInstance-com.github.dockerjava.core.DockerClientConfig-com.github.dockerjava.transport.DockerHttpClient-

**Comment by KaustavRayProgrammer** [comment]
@bsideup Yes, it was an issue where the old environment was getting retained. After doing maven clean, I got that method working. And by using apache httpclient 5, my original case is solved and it is tested on Windows and Linux with the 2 different versions of docker. Tomorrow we will test on Mac and if it works, I will close this issue here.
Thank you for your suggestion of using some transport other than jersey.
