### ISSUE TITLE
Docs and troubleshooting

### ISSUE THREAD

**Issue by winthrop-polk** [docker-java/docker-java#1437]
I'm not sure if this is a bug report or a support request; 48 hours and I haven't been able to do hello world stuff, create iamge.

I've been trying to use this package to do the following, **locally on windows at first than on azure/gcloud**:

- **create image from docker file**: ideally without using a docker file... I figure with a package like this you could define all parameters in a object instead, which would allow me to treat my server containers like all other objects which I thought would be pretty cool... I've been just trying to get an image created with a dockerfile recently because I'm not sure if the prior is even possible with this (no docs I found say).
- build it
- push it
- mount it
- etc

But I can't seem to create an image. Errors range from "can't find docker file" to " unexpected EOF" to completing without error but no image showing up locally.

Worth noting, I'm trying to use kotlin not java... is that my problem? Also, I need this to work regardless of how it's deployed Jar/War/uncompressed.

Here is the folder structure... docker client/http tests work locally, the following content is in Docker.kt and the svrDB is my dockerfile.
![image](https://user-images.githubusercontent.com/43882515/87688172-a5bc9000-c754-11ea-9e13-981377836a7e.png)

Here is what I got so far, it's a mess from trial and error. If I was smart I'd just use the gradle docker plugin and move along... but it seems a shame not to do this in code if possible, to treat my docker servers like objects would be fantastic!

```

package com.app.build.containers

import com.github.dockerjava.api.command.BuildImageResultCallback
import com.github.dockerjava.core.DefaultDockerClientConfig
import com.github.dockerjava.core.DockerClientConfig
import com.github.dockerjava.core.DockerClientImpl
import com.github.dockerjava.httpclient5.ApacheDockerHttpClient
import com.github.dockerjava.transport.DockerHttpClient
import java.io.File

const val projectName: String = "srcBuild"

class DockerApi {
    private val config: DockerClientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder()
        .withDockerHost("tcp://localhost:2375")
        //.withDockerTlsVerify(true)
        //.withDockerCertPath("/home/user/.docker")
        //.withRegistryUsername("admin")
        //.withRegistryPassword("password")
        //.withRegistryEmail("gunslingor@gmail.com")
        //.withRegistryUrl("https://index.docker.io/v1/")
        .build()

    val httpClient: DockerHttpClient = ApacheDockerHttpClient.Builder()
        .dockerHost(config.dockerHost)
        .sslConfig(config.sslConfig)
        .build()

    val dockerClient = DockerClientImpl.getInstance(config, httpClient)!!
    val file = DockerApi::class.java.classLoader.getResourceAsStream("dockerfiles/svrDB")

}

fun main(){
    val dockerApi = DockerApi()
    val clientDocker = dockerApi.dockerClient
    val result = clientDocker.infoCmd().exec()
    //val filePath = dockerApi.file
    //print(filePath)

    clientDocker.createImageCmd("test", dockerApi.file).exec()
    clientDocker.listImagesCmd()
/*
    clientDocker.buildImageCmd(dockerApi.file)
        //.withPull(true)
        //.withNoCache(true)
        //.withTags(setOf("app_dck_dev_svr_build"))
        .exec(BuildImageResultCallback())
        .awaitImageId();

 */
}

```

**Comment by bsideup** [comment]
hey @winthrop-polk,

Have you checked docker-java's tests? You will find a plenty of examples:

https://github.com/docker-java/docker-java/blob/master/docker-java/src/test/java/com/github/dockerjava/cmd/BuildImageCmdIT.java

**Comment by winthrop-polk** [comment]
I have not but I will review it in more detail... I don't usually like to dig into someone else's code to understand their package, Packages should be atomic by the time they get to me and well documented with instructions... nothing less efficient than reverse engineering IMHO. So the real process to use this package is to download the entire code base correct? If so, do I still need to download your compiled packages too via gradle? Seems silly to do both... where should I put your project and what IDE should I be using? I don't see the idea folder so assume it shouldn't be intelliJ... lot to manually string together otherwise.

**Comment by jonpeterson** [comment]
He simply linked you a test to use as an example; he didn't tell you you needed to compile from source to use the library. I have used this library in multiple projects for over a year and I think it is quite well-written. If you feel the documentation isn't good enough, how about you put in a PR after you "reverse engineer" it. You sound quite pretentious "threatening" an open source project that you are going to take your business to the CLI.

And to also answer your question that you posted in the Kotlin Slack (I'm assuming it was you), yes this library works perfectly fine with Kotlin.

**Comment by winthrop-polk** [comment]
Not threatening, what could I possibly threaten on the internet? Sorry if I gave you a threatening impression, was not my intention. Just moving fast solving problems anyway I can... trying to do the job of 50 with 1 person.

Regardless I'm just saying maybe it's best to stick with what I know works easily for every tool at the CLI level I've ever seen. I'm obviously doing something wrong here with this package, there isn't much code all pretty much copied from the examples. I'm using many CLI tools already that don't have such a package... so I blame myself only for taking a left turn here not you.

**Comment by winthrop-polk** [comment]
"So the real process to use this package is to download the entire code base correct? If so, do I still need to download your compiled packages too via gradle?" 

- honest questions: when drilling into code I'll often hit a brick wall of compiled java; I have seen people include entire packages like this uncompiled and somehow associated it to their project without actually including it, so that intelliJ is able to effectively drill into the compiled code in appearance... which could make learning it easier... is that what you suggest?

**Comment by jonpeterson** [comment]
Many libraries, like this one, publish a sources.jar along side the bytecode JAR that IntelliJ (or most IDEs) automatically downloads and uses when you try to pivot into the code. By simply including the docker-java artifact coordinates on the compile scope of my Gradle project and then ctrl+click (or cmd+click on Mac), IntelliJ will open attempt to download the sources JAR and open that class's source. I'm not sure why yours isn't doing that. If you look at Maven Central, you'll see the sources and javadoc JARs are published. https://repo1.maven.org/maven2/com/github/docker-java/docker-java/3.2.5/

IRT to your actual issue, there are two ways to pass build information to the Docker daemon API. One way is to pass a path on the filesystem to the Dockerfile and an optional directory for where the build context directory is (if not specified, then it is assumed where the Dockerfile is). I believe (not sure) that this actually just a shortcut for the second way to be invoked, which is to send a tarball to the API. The tarball contains the Dockerfile and the directory of files in the build context path. The docker-java's BuildImageCmd mirrors these two ways: filesystem path or tarball InputStream.

You are trying to pass a Dockerfile via classpath resource via InputStream, but it is expecting a tarball (hence the EOF exception). The fact that you can't pass a Dockerfile via InputStream isn't a shortcoming of this library, it is mirroring exactly how the Docker API works in that it needs a Dockerfile along with a build directory in tarball form.

If you really need to get a Dockerfile from the classpath, then you'll need to write it to a temp file, or you'll need to build a tarball byte array in memory and send it.

Example of the former:
```
fun main() {
    val client = DockerClientBuilder
        .getInstance(
            DefaultDockerClientConfig.createDefaultConfigBuilder().build()
        )
        .build()

    val buildDir = File("myBuildDir")
    buildDir.mkdirs()
    val tmpFile = File.createTempFile("dockerfile-", "tmp", buildDir)
    try {
        tmpFile.writeBytes(ClassLoader.getSystemResourceAsStream("someDockerfile").readAllBytes())
        client.buildImageCmd(tmpFile)
            .withTags(setOf("blah"))
            .exec(BuildImageResultCallback())
            .awaitImageId()
            .also { id -> println("build image with ID: $id") }
    } finally {
        tmpFile.delete()
        buildDir.deleteRecursively()
    }
}
```

**Comment by winthrop-polk** [comment]
"I'm not sure why yours isn't doing that."... it generally does, but very often I just see a class declaration and something like /* compiled code */ next to it (really probably compiled C or something, not this package I guess)... but I did hit a layer of abstraction I can't follow; one issue I know I have: how does one find all possible instances of an interface? Just little things... probably kotlin/java specific, slows me down I think.

"If you really need to get a Dockerfile from the classpath" - not sure about this, this was recommended to me. I need it to work in jars/wars/where-evers, this worked for all my needs when I was running CLI docker commands from kotlin, so although I still wanna use this package that exercise does help sort things out I think. Totally all ears for alternatives. I think I might me missing some knowledge on how java handles resources, it isn't gradle.

`val workingDir = File(DockerApi::class.java.classLoader.getResource("dockerfiles")!!.file)`

"expecting a tarball" - that may be the problem then, all this time... my assumption it wanted a normal file input stream; someone else mentioned a temp file though I still don't fully understand the need for it, obviously prefer to avoid.

Reference
```
`CreateImageCmd createImageCmd(@Nonnull String repository, @Nonnull InputStream imageStream);`
BuildImageCmd buildImageCmd(InputStream tarInputStream);
```

I jump languages so much, you guys can probably tell my issues are really java related... or not, I don't know... all I know is docker CLI took about 45 minutes to learn what I needed and I'm really struggling with this package. The gradle plugin worked good for me, but trying to go beyond that.

**Comment by bsideup** [comment]
@winthrop-polk `docker-java` is a low level library that allows calling the Docker API. You need to understand the API to be able to work with it.

> all I know is docker CLI took about 45 minutes to learn what I needed and I'm really struggling with this package

Docker CLI _wraps_ the API and provides high-level commands on top of it (like `docker run` which is a combination of "create container" + "start container" + "attach to container").

> . I don't seem to understand why HTTP is even needed, or why it still wouldn't be as simple as defining a connection and running something like "docker.image.build("test2", "svrDB")" against it. 

You're free to find (or create) a library on top of docker-java which will give you `docker.image.build(...)`-like experience. This, however, is out of scope of `docker-java`.

> question: many of those tests relly on dockerRule, where is that coming from?

This is a class in the same source set. I would suggest to learn a little bit more about Java, how projects are structured, etc etc. 
docker-java is a standard Maven project and you should have no issues grasping it once you get enough knowledge of Java and Maven-based Java projects.

**Comment by winthrop-polk** [comment]
**### Just academic discussion at this point, I still haven't gotten anything working.**

One thing I should probably clarify: I'm really in devOps mode, not coder mode... I'm stringing together all the packages, sub-projects, modules, CI/CD, folder structures, hello worlds and tests, deployment, etc... so learning the internals of a package isn't really my goal ATM.

I spent another 12 hours yesterday trying to get hello world examples, create/build image, to work (in comparison it took me 1 hour to do it with CLI, 2 hours to do it with the matching gradle plugin and 2 hours to do it with palantir plugin where I actually completed my DB server image... I keep hitting limitations with the tools though, like palantir can only generate 1 dockerfile called dockerfile at a time while "bens" gradle plugin is great, the code was getting too long for a build file IMHO so I started looking at this... CLI works fine, I suspect the HTTP interface to docker does too, only reason I am not using it is because this exists)...

I need to understand the original docker API (not CLI) to understand this SDK, I'm pretty surprised to hear that... I wouldn't even think the CLI would be required since these are interfaces to something more fundamental that differ so immensely in application/purpose/implementation/etc (CLI/HTTP/JAVA), I'm surprised I have to know one to know the other is all I am saying, zero offense intended. Honestly, I don't recall ever using HTTP to interface with something locally but I know that's docker not you guys.

Honest question: Since docker offers the HTTP API, what advantage does this package offer to just interfacing with it directly like a typical rest/equivalent service? My code base is going to have to interface with a number of HTTP APIs  aas well as directly with large third party VPN'd databases, most don't have packages like this. Any opinion appreciated.

Note: I skipped maven to learn gradle, before that I was using shell and bash scripts or code for automation. Really have no need or desire to learn maven ATM, until the need arises in some future contract.

I made zero progress yesterday, I tried to follow the tests but it isn't easy, can't really trace code in git hub and intelliJ doesn't seem to want to download the tests by default (wanted to run them locally). Downloading packages, starting new projects, rigging it up, all just to understand how to use the basics is definitely a line I can't cross... I've already spent too much time on this, It's just this package sure seems to be the standard for what I'm trying to do... no idea why I'm having such an issue, probably something obvious but I can only give it one more day or I might be fired, lol jk... really trying here, sacrificing a Saturday.

**Comment by bsideup** [comment]
@winthrop-polk 

> Since docker offers the HTTP API, what advantage does this package offer to just interfacing with it directly like a typical rest/equivalent service?

docker-java gives you a type safe access to the exposed API methods, implements different transport options (tcp, unix socket, npipe), supports framing, stdin injection (which is an unusual use of the HTTP transport and sometimes is uneasy to achieve with the HTTP clients available on JVM).
That said, you of course can try communicating with it directly. Maybe it will give you a better understanding why docker-java exists on a first place.

> I need to understand the original docker API (not CLI) to understand this SDK, I'm pretty surprised to hear that

Well, yeah, it is kinda a prerequisite. The SDK is focused on the low level aspect, while tools like https://www.testcontainers.org can use it to introduce simpler abstractions.

> I can only give it one more day or I might be fired, lol jk

You seems to be working on a big project, probably a commercial one. if you _really_ need to get it done ASAP, consider _hiring_ somebody to help you.
FOSS projects do not mean that the community will write code for you and/or owe anything to you.
It is just the model where you can get what you want by investing enough of _your_ time into solving the problem you're having.

----
P.S. I am alone seeing a pattern here?

> I spent another 12 hours yesterday trying to get hello world examples,

> Note: I skipped maven to learn gradle

> I made zero progress yesterday

> all just to understand how to use the basics is definitely a line I can't cross

> I've already spent too much time on this

**Comment by winthrop-polk** [comment]
Yeah.. the pattern is clear I guess, and I have seen some pretty odd HTTP services out there which I am getting the impression this one could be a part of that group. Time to move on. Thanks for the help. Sorry for buggin.

**Comment by jonpeterson** [comment]
> P.S. I am alone seeing a pattern here?

Nope.
