### ISSUE TITLE
Executing ListContainersCmd with LabelFilter hangs

### ISSUE THREAD

**Issue by yatinpatil1986** [docker-java/docker-java#1444]
Hey,

I am using Docker-Java -3.0.14 for my project. I have a use case where I want to check if a specific container exists, and if it does not, I create and launch a container. To support this, I was trying to list containers using ListContainersCmd with an Label filer. Following is my code for the same:

```
val containers = dockerClient.listContainersCmd()
    .withLabelFilter(ImmutableMap.of("name", containerName))
    .withShowAll(true)
    .exec()
```
However the this command hangs and never returns. If I remove the `withLabelFilter`, this code works fine. Is this a known issue for Docker-Java-3.0.14? Or is there an alternative approach to implementing this?

My docker client is using `NettyDockerCmdExecFactory`:

```
@Provides
@Singleton
fun dockerClient(): DockerClient {
    val dockerClientConfig: DockerClientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder()
            .withDockerTlsVerify(false)
            .build()

    val dockerCmdExecFactory: DockerCmdExecFactory = NettyDockerCmdExecFactory()
            .withConnectTimeout(5000)

    return DockerClientBuilder.getInstance(dockerClientConfig)
            .withDockerCmdExecFactory(dockerCmdExecFactory)
            .build()
}
```

**Comment by bsideup** [comment]
Please try the latest docker-java. Also, check the transport docs.

**Comment by yatinpatil1986** [comment]
Actually NVM, this was an issue on how I had setup dependencies. Resolving.
