### ISSUE TITLE
Add transport using Java11 built-in http client

### ISSUE THREAD

**Issue by asolntsev** [docker-java/docker-java#1450]
Java 11 has built-in http client (see `java.net.http.HttpRequest`).
We would like to use it, thus eliminating need for 3rd-party dependencies like OkHttp, ApacheHttp etc. 

I can prepare PR by myself if you approve this is the right idea.

**Comment by bsideup** [comment]
@asolntsev thanks for raising this question!

I did consider having a transport that is based on JDK's `HttpClient`, but unfortunately it does not support all the features needed, such as:
- custom socket factory (for unix socket / npipe / ssh)
- stdin hijacking

I did a quick research tho, so maybe I missed something.

The Apache HttpClient5 transport should be a good reference transport if you're willing to give the JDK's transport a try 👍

**Comment by asolntsev** [comment]
Are these features often needed?
If they are optional, we can leave them unimplemented. Not a big deal, maybe?

**Comment by bsideup** [comment]
without custom socket factory, you won't be able to:
- use it on Mac
- use it on Windows
- use in on Linux over unix socket (default)

basically, only TCP communication will be supported, which isn't something you will find by default anywhere.

without stdin hijacking:
- no "attach to running container with stdin"
- no "exec with stdin"

these aren't the most used APIs but there were quite a few requests to support it back when Jersey was the only transport. That's how Netty transport was added.

**Comment by asolntsev** [comment]
Thank you for sharing the information. It seems to be non-trivial. Not this time. :)
