### ISSUE TITLE
ApacheDockerHttpClient builder support customize httpclient's RequestConfig and PoolingHttpClientConnectionManager

### ISSUE THREAD

**Issue by richard-yao** [docker-java/docker-java#1451]
Hi guys, I am using docker-java to implement my business, I love this library and I found I cannot cusomize ApacheDockerHttpClient' HttpClient request configs.
I am initializing ApacheDockerHttpClient instance with this code:
```java
return new ApacheDockerHttpClient.Builder()
                .dockerHost(dockerClientConfig.getDockerHost())
                .sslConfig(dockerClientConfig.getSSLConfig())
                .build();
```
I have view the source code, and may be you guys can change the ApacheDockerHttpClientImpl scope to support caller change ```httpClient``` properties?

Just return HttpClientBuilder instead HttpClient will be more flexiable
```java
httpClient = HttpClients.custom()
            .setRequestExecutor(new HijackingHttpRequestExecutor(null))
            .setConnectionManager(new PoolingHttpClientConnectionManager(
                socketFactoryRegistry,
                new ManagedHttpClientConnectionFactory(
                    null,
                    null,
                    null,
                    null,
                    message -> {
                        Header transferEncodingHeader = message.getFirstHeader(HttpHeaders.TRANSFER_ENCODING);
                        if (transferEncodingHeader != null) {
                            if ("identity".equalsIgnoreCase(transferEncodingHeader.getValue())) {
                                return ContentLengthStrategy.UNDEFINED;
                            }
                        }
                        return DefaultContentLengthStrategy.INSTANCE.determineLength(message);
                    },
                    null
                )
            ))
            .build();
```

Thanks

**Comment by richard-yao** [comment]
I am using docker-java with latest version 3.2.5

**Comment by bsideup** [comment]
Hi @richard-yao,

Could you please describe which properties you want to customize? Is there anything that does not work for you with the default ones?

**Comment by richard-yao** [comment]
Hi @bsideup 

Thanks for your answer.

I want to change the default max connections per route property in PoolingHttpClientConnectionManager class, I have used httpclient in other business service, I noticed that in PoolingHttpClientConnectionManager source code
```java
public static final int DEFAULT_MAX_TOTAL_CONNECTIONS = 25;
public static final int DEFAULT_MAX_CONNECTIONS_PER_ROUTE = 5;
```
I want customize these parameters to fit different machine's performance.

And the ```HttpClients.custom().build()``` method using default RequestConfig with these parameters:
```java
private static final Timeout DEFAULT_CONNECTION_REQUEST_TIMEOUT = Timeout.ofMinutes(3);
private static final Timeout DEFAULT_CONNECT_TIMEOUT = Timeout.ofMinutes(3);
private static final TimeValue DEFAULT_CONN_KEEP_ALIVE = TimeValue.ofMinutes(3);
```
The default timeout for my business is not very suitable, I want to decrease the connectTimeout

**Comment by uuidcode** [comment]
I have a same issue.

https://github.com/docker-java/docker-java/issues/1443

**Comment by daigaigai520** [comment]
why closed?
