### ISSUE TITLE
The new image created by createImageCmd function is not the same as the original image in tarball

### ISSUE THREAD

**Issue by Tianny** [docker-java/docker-java#1456]
when I use createImageCmd, I found the new image created by createImageCmd from tarball looks like different from the original image in tarball.

For example, I defined CMD instructions in the original image in tarball, but when I run the new created image by createImageCmd function, the container produces error.

I think something wrong when use createImageCmd. The new image is not the same as the image in tarball.

**Comment by skyscraper23** [comment]
Hi,@Tianny . I have encountered the same problem recently.Could you share your solution, please? Thanks!

**Comment by Tianny** [comment]
> Hi,@Tianny . I have encountered the same problem recently.Could you share your solution, please? Thanks!

If you want load image from tarball, use loadImageCmd.

For example:

```java
    public static void main(String[] args) throws FileNotFoundException {

        InputStream tarInputStream = new FileInputStream("/Users/apple/Desktop/test/load-save.tar");

        try {
            new DockerUtil().dockerClient.loadImageCmd(tarInputStream).exec().wait(1);
            List<Image> images = new DockerUtil().dockerClient.listImagesCmd().exec().subList(0, 1);
            Image image = images.get(0);
            String imageId = image.getId();
            new DockerUtil().dockerClient.tagImageCmd(imageId, "dd", "latest").exec().wait(1);
            new DockerUtil().dockerClient.removeImageCmd(imageId).exec().wait(1);


        } catch (Exception e) {
            System.out.println("Hello Error");
            System.out.println(e.getMessage());
        }

    }
```

**Comment by skyscraper23** [comment]
> > Hi,@Tianny . I have encountered the same problem recently.Could you share your solution, please? Thanks!
> 
> If you want load image from tarball, use loadImageCmd.
> 
> For example:
> 
> ```java
>     public static void main(String[] args) throws FileNotFoundException {
> 
>         InputStream tarInputStream = new FileInputStream("/Users/apple/Desktop/test/load-save.tar");
> 
>         try {
>             new DockerUtil().dockerClient.loadImageCmd(tarInputStream).exec().wait(1);
>             List<Image> images = new DockerUtil().dockerClient.listImagesCmd().exec().subList(0, 1);
>             Image image = images.get(0);
>             String imageId = image.getId();
>             new DockerUtil().dockerClient.tagImageCmd(imageId, "dd", "latest").exec().wait(1);
>             new DockerUtil().dockerClient.removeImageCmd(imageId).exec().wait(1);
> 
> 
>         } catch (Exception e) {
>             System.out.println("Hello Error");
>             System.out.println(e.getMessage());
>         }
> 
>     }
> ```
Thank you for your reply! I have tried and succeeded.
But is the first image returned by listImagesCmd()  always the one just loaded by loadImageCmd()?
Actually I am considering concurrency, if two users upload image at the same time ...
So I want to know is there a way to get the imageId ?
