### ISSUE TITLE
com.github.dockerjava.api.exception.DockerClientException: Failed to read build context directory:

### ISSUE THREAD

**Issue by feesx** [docker-java/docker-java#1459]
build docker error：
com.github.dockerjava.api.exception.DockerClientException: Failed to read build context directory: 

but directory is exist

docker-java version：3.1.5

**Comment by sayid10** [comment]
How did you solve this problem

**Comment by shenzhuangzhi1** [comment]
How did you solve this problem

**Comment by zimmortor** [comment]
How did you solve this problem

**Comment by ftomassetti** [comment]
Same here. Getting the same exception, no idea how to solve it
