### ISSUE TITLE
Support for Docker Content Trust via the java client

### ISSUE THREAD

**Issue by kashfat-khan** [docker-java/docker-java#1460]
Hi,

This might not be an issue but more of a guidance.

We use the docker-java client in one of our projects and I was looking to see if there are any references to enable the DCT feature while pulling images.
We are using community edition of docker so cannot do it at docker engine level. 

Thanks
Kashfat

**Comment by GregoryIvo** [comment]
I am looking for the feature as well, cant seem to find it via API-docs.  Did you happen to find a resolution?
