### ISSUE TITLE
Couldn't connect to Google Container Registry 

### ISSUE THREAD

**Issue by foxwendy** [docker-java/docker-java#1461]
docker-java:  'com.github.docker-java', name: 'docker-java', version: '3.2.5'

The follow code lists images from public docker hub, not really the specified GCR.  What's the right way to list image from our specified GCR?

    DefaultDockerClientConfig config = DefaultDockerClientConfig
                                          .createDefaultConfigBuilder()
                                          .withRegistryUrl("http://eu.gcr.io/data-infrastructure-test-env")
                                          .withDockerConfig("/home/me/.docker/config.json")
                                          .build();

    DockerClient dockerClient = DockerClientBuilder.getInstance(config).build();
    List<SearchItem> items = dockerClient.searchImagesCmd("daas").exec();
    List<String> images = new ArrayList<>();
    for (SearchItem searchItem : items){
      images.add(searchItem.getName());
    }

**Comment by bsideup** [comment]
AFAIK you cannot use GCR as a Docker Engine.

Also see #1458.
