### ISSUE TITLE
java.io.IOException: native write() failed : Broken pipe

### ISSUE THREAD

**Issue by asarkar** [docker-java/docker-java#1465]
I'm using the [bmuschko/gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) to build an image for a Spring Boot application. The plugin uses `docker-java` for the remote tasks.
```
FROM azul/zulu-openjdk-alpine:11
ADD libs/app-0.0.1-SNAPSHOT.jar /app/
ADD distributions/health-probe.tgz /
RUN mv /health-probe* /scripts
ENTRYPOINT ["java"]
CMD ["-jar", "/app/app-0.0.1-SNAPSHOT.jar"]
```

This `Dockerfile` can be used to successfully build an image from the command line but fails with the following exception when ran from Gradle:
```
Error during callback
java.lang.RuntimeException: java.io.IOException: native write() failed : Broken pipe
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:153)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:8)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: native write() failed : Broken pipe
        at com.github.dockerjava.httpclient5.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:319)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
```

Also filed corresponding bug https://github.com/bmuschko/gradle-docker-plugin/issues/972.
```
java --version
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
```

Gradle 6.6.1.

**Comment by asarkar** [comment]
After more investigation, it seems to be an issue on Mac only. I see this in the Docker for Mac logs:
```
error forwarding client's request to Docker: write unix ->/Users/me/Library/Containers/com.docker.docker/Data/docker.raw.sock: write: broken pipe
```
There are many reports of "broken pipe" in various projects, none helpful.

**Comment by bmuschko** [comment]
@bsideup Do you have an idea what could be going on here?

**Comment by Deepakkoli93** [comment]
@asarkar did you find a workaround? I'm getting the same error.

**Comment by asarkar** [comment]
@Deepakkoli93 I didn’t. docker-java is broken for Mac.

**Comment by bsideup** [comment]
@bmuschko I don't, sorry :( Seems to be happening when Docker writes the response - something that is very hard to debug on our side.

@asarkar let's not exaggerate - docker-java works absolutely fine on Mac (and also being developed on a Mac, just so you know). This particular edge case may not even be caused by docker-java, as there are some errors on Docker for Mac's side - worth checking with them, too.

**Comment by asarkar** [comment]
@bsideup Thanks for reopening the ticket. That said, Docker Desktop for Mac is the only supported way to run Docker on Mac, so if something in it is conflicting with docker-java, it’s not an edge case, it’s the only case that exists.

**Comment by bsideup** [comment]
> Docker Desktop for Mac is the only supported way to run Docker on Mac

It is not.

> if something in it is conflicting with docker-java, it’s not an edge case, it’s the only case that exists.

I was referring to your imagine building issue. Overall, image building work on Mac with docker-java (see docker-java's tests, btw), just it looks like you're hitting some edge case that needs to be deducted and reproduced. But this doesn't mean that "docker-java is broken for Mac".

**Comment by Deepakkoli93** [comment]
This is what is confusing me - I have two gradle projects and it works for one for doesn't for the other. Image building shouldn't depend on the project itself, am i missing something?

**Comment by asarkar** [comment]
@Deepakkoli93 Have you tried reducing the two projects to bare min in order to make comparison possible? If those are multimodule projects, start deleting modules one by one. You don’t even need any source code in order to reproduce this problem.

That said, whether the time spent would lead to anything fruitful is anyone’s guess. I get the impression that there isn’t a burning interest in investigating this problem.

**Comment by bsideup** [comment]
@asarkar as there isn't a burning interest in providing a minimal reproducer, I am afraid there isn't much to investigate :) Image building is covered with tests and works fine on Mac, so, unless a reproducer can be provided, that will help catching the edge case that causes this to fail, not much can be done here.

**Comment by asarkar** [comment]
@Deepakkoli93 I didn't use Micronaut when I found this issue, neither is my app named in CamelCase. Are you saying Micronaut uses [bmuschko/gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) under the hood?

**Comment by Deepakkoli93** [comment]
> @Deepakkoli93 I didn't use Micronaut when I found this issue, neither is my app named in CamelCase. Are you saying Micronaut uses [bmuschko/gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) under the hood?

yes, for building docker native images

**Comment by Deepakkoli93** [comment]
It turns out that docker image names can [only contain lowercase letters.](https://stackoverflow.com/questions/36858837/lowercase-images-names-in-docker)

@asarkar Maybe you can try to see how you are naming the image you are trying to build.
In micronaut's case it takes the name from `rootProject.name` in `settings.gradle`

**Comment by asarkar** [comment]
> you can try to see how you are naming the image you are trying to build

I have. It builds fine manually (`docker build`) using the `Dockerfile` generated by the plugin.

**Comment by bsideup** [comment]
@Deepakkoli93 it is indeed the limitation applied by Docker, and something that would explain the error and why it does not reproduce with other image builds.

@asarkar when you're building it manually, you're passing the image name yourself. While, with gradle-docker-plugin, the image name is picked by the plugin. So this may be the cause. Have you tried enabling debug logs?

**Comment by asarkar** [comment]
@bsideup The image builds fine using the plugin on our Linux CI servers. This is an issue that only happens on a Mac.

**Comment by T-Hellmund** [comment]
I stumbled upon the same issue. 
As @Deepakkoli93 said, the naming convention for docker images is all characters to be lowercase.

I did not find the stacktrace to be helpful here. Would another error message coming from docker-java here make sense?

**Comment by JohnnyMoonlight** [comment]
I stumbled upon the same issue.
As @Deepakkoli93 said, the naming convention for docker images is all characters to be lowercase.

I did not find the stacktrace to be helpful here. Would another error message coming from docker-java here make sense?

**Comment by davinchia** [comment]
This might be a different case, but it looks like this is happening for us [on Linux](https://github.com/airbytehq/airbyte/runs/5259048660?check_suite_focus=true#step:10:2124) from time to time

**Comment by marcmolla** [comment]
> I can confirm, the Camel Case rootProject.name caused this for me also.

In my case it was the Image Tag in Camel Case. Thanks for the hint!
