### ISSUE TITLE
Question about DockerClient thread safeness ?

### ISSUE THREAD

**Issue by gordon00** [docker-java/docker-java#1469]
Hi everybody,

I am about to use your library but i am wondering if DockerClient is ThreadSafe.
I saw this post : [testcontainers/testcontainers-java/issues/44] saying it's not ThreadSafe and there is no external documentation nor javadoc to validate ou invalidate that assertion.

I want to use httpclient implementation.

Thanks

**Comment by bsideup** [comment]
Yes, it is thread safe now. It wasn't the case many years ago, but, for the past 2 or 3 years, it is :)

**Comment by gordon00** [comment]
Great, thank you for your reply @bsideup
