### ISSUE TITLE
Question : docker exec implemented ?

### ISSUE THREAD

**Issue by gordon00** [docker-java/docker-java#1470]
Hi everyone,

Maybe I am mistaken, but i can't find a way to run that kind of command through DockerClient api.
I would like to run and get the result of that kind of command : 

`docker exec -it <container_name> bash -c 'ls -al'`

The real bash command would be a little more complicated but that's only for example purpose.
Is it possible ?

Thanks

**Comment by bsideup** [comment]
@gordon00 see `ExecCreateCmd`/`ExecStartCmd`. Keep in mind that docker-java is a low level library and that's how Docker API works under the good (docker CLI calls the same commands)

**Comment by gordon00** [comment]
Oops I am confused.
It works like a charm.
Thanks @bsideup
