### ISSUE TITLE
Where's the latest source code?

### ISSUE THREAD

**Issue by kdvolder** [docker-java/docker-java#1472]
Maven central already has version 3.2.5 available. For example: https://mvnrepository.com/artifact/com.github.docker-java/docker-java-transport-zerodep/3.2.5

The master branch in this repo seems to be at 3.2.2. See: https://github.com/docker-java/docker-java/blob/master/docker-java-transport-zerodep/pom.xml#L7

This is a bit confusing, where's the source code for 3.2.5 or 3.2.6.SNAPSHOT assuming that's going to be the next released version.

I am trying to poke around a bit and see if maybe I can do PR for https://github.com/docker-java/docker-java/issues/1466

But it's probably best if that would be based on the latest source code rather than something old.

**Comment by bsideup** [comment]
@kdvolder you will find the latest released version in README:
https://github.com/docker-java/docker-java/blob/master/README.md

the version is POM is artificial, we override it on release:
https://github.com/docker-java/docker-java/blob/c3661f3da85ebf4f9caea5a75d1c9224d2937876/.github/workflows/release.yml#L19

I will change it to `0-SNAPSHOT` soon to not confuse 👍

**Comment by kdvolder** [comment]
Okay, thanks for clarifying. This is somewhat confusing, not sure if setting it to 0 is much better, maybe it would be clearer just to add a comment alongside the version in the pom. I.e. 

```
<!-- This version is overridden at build time -->
```
