### ISSUE TITLE
DOCKER_HOST is not used

### ISSUE THREAD

**Issue by ruddy32** [docker-java/docker-java#1478]
Using TestContainer 1.14.3 with Docker-Java 3.2.5, it seems that DOCKER_HOST is used by TestContainer, but Docker-Java ignore it.

Here is two log link that describe TestContainer information and Docker-Java exception :
- https://github.com/testcontainers/testcontainers-java/issues/2088#issuecomment-717536450
- https://github.com/testcontainers/testcontainers-java/issues/2088#issuecomment-717766461

TestContainer and Docker-Java do not used the same docker socket. Is-it a normal docker-java behavior ?

**Comment by bsideup** [comment]
Please see the answers in the issue you linked.
