### ISSUE TITLE
pullImageCmd does not use registry from DockerClientConfig

### ISSUE THREAD

**Issue by zenbones** [docker-java/docker-java#1479]
dockerClient.pullImageCmd(<image respoitory:tag>).start().awaitCompletion() results in...

Exception in thread com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: Get https://registry-1.docker.io/v2/library/ubuntu/manifests/bionic: unauthorized: incorrect username or password

...which is not the registry set in my DockerClientConfig used to create the dockerClient. I've tried .withRegistry() and .withRespository() (what's the difference anyway?) with no avail, same error, so it seems those are ignored. Shouldn't this call inherit the registry and auth from the client config? Shouldn't the override of withRegistry() work?

**Comment by zenbones** [comment]
Turns out that adding this works...

.withAuthConfig(new AuthConfig().withRegistryAddress(<same host as in client config>))

...which seems like a workaround to a bug, because the config .setRegistryUrl() should have been sufficient, as should .withRegistry() on the command.

**Comment by dmmax** [comment]
Faced the same issue.
What's more, I tried to use `withRegistry()` but looks like it still tries to connect to the host `https://registry-1.docker.io`

I use the code below
```java
      AuthConfig config = new AuthConfig().withRegistryAddress(request.registryAddress());
      request.credentials().ifPresent(creds -> config.withUsername(creds.userName()).withPassword(creds.password()));

      PullImageCmd pullImageCmd = dockerClient
          .pullImageCmd(request.imageName())
          .withTag(request.imageTag())
          .withAuthConfig(config)
          .withRegistry(request.registryAddress());
```

**Comment by dmmax** [comment]
I provided a solution with resolving the issue when someone wants to pull an image from a private docker registry (e.g. nexus repository)
https://github.com/docker-java/docker-java/issues/1471

**Comment by rorytorneymf** [comment]
I'm also seeing this same issue using versions 3.2.6 and 3.2.5. 

None of the following works for me for trying to set the docker registry. It always uses `https://index.docker.io/v1/` instead of `my-registry`:

1) Setting the registryUrl on the client config:

```
DockerClientConfig dockerClientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder().withRegistryUrl("my-registry").build();
DockerClient dockerClient = DockerClientBuilder.getInstance(dockerClientConfig).build();
```

2) Setting the registry on the `AuthConfig`, and on the `PullImageCmd`:

```
AuthConfig config = new AuthConfig().withRegistryAddress("my-registry");

PullImageCmd pullImageCmd = dockerClient
          .pullImageCmd("some-image")
          .withAuthConfig(config)
          .withRegistry("my-registry");
```

**Comment by bsideup** [comment]
@rorytorneymf when you pass `withAuthConfig`, it won't automatically prefix the image name with registry, so you still need too refer to the image as `registry.corp.org/some-image`.

**Comment by mzach99** [comment]
This is still an issue.  You shouldn't have to pass the registry into the command in a different way when you specify an `AuthConfig`.
