### ISSUE TITLE
Logs are stopping after 10MB and never continue

### ISSUE THREAD

**Issue by ohadasulin** [docker-java/docker-java#1489]
I want to dump log into a file but logs are truncated after 10MB of data on the stream.

My code:
```java
DefaultDockerClientConfig dockerClientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder().withDockerHost("tcp://x.x.x.x:2375")
    .withDockerTlsVerify(false).build();

DockerHttpClient httpClient = new ApacheDockerHttpClient.Builder()
    .dockerHost(dockerClientConfig.getDockerHost())
    .build();
dockerClient = DockerClientBuilder
    .getInstance(dockerClientConfig)
    .withDockerHttpClient(httpClient).build();

String serviceName = "kafka_kafka";
final LogSwarmObjectCmd logSwarmObjectCmd = dockerClient.logServiceCmd(serviceName)
    .withStdout(Boolean.TRUE).withFollow(true);



log.debug("Service {}, dumping logs start", serviceName);
LogToFileResultCallback resultCallback = logSwarmObjectCmd.exec(new LogToFileResultCallback(Paths.get("/tmp"), serviceName));
Thread.sleep(100000000);
```

in the callback, I just write to a file this way:
```java
Writer writer = ...

String strToWrite = new String(frame.getPayload(), charset);
writer.write(writer, strToWrite);
```

my file appears as if it was stopped mid-processing: 
```bash
-bash-4.2# tail -n 1 /tmp/kafka_kafka.stdout.log 
[2020-11-09 10:07:14,745] INFO [GroupCoordinator 1001]: Removed 0 offsets associated with delet
-bash-4.2# 
```
and file stops growing at 10MB (consistently)
```bash
-bash-4.2# ls -lh /tmp/kafka_kafka.stdout.log
-rw-r--r--. 1 root root 10M Nov 11 12:54 /tmp/kafka_kafka.stdout.log
```

Is there any way to remove the limitation (my file should be much bigger ~80MB)?

**Comment by jrietdijk** [comment]
How did you configure the log driver in docker? We have had an issue when set max-file=1. Then the logging stops as soon as the max-size is reached

**Comment by ohadasulin** [comment]
```json
  "log-opts": {
    "mode": "non-blocking",
    "max-buffer-size": "1m",
    "max-size": "10m",
    "max-file": "3",
    "labels": "{{.ImageName}}/{{.Name}}/{{.ID}}"
    }
```
`max-file` is set to `3` as you can see.
Maybe the limit is when we reach `max-size`? Seems like `max-file` is ignored...

**Comment by jrietdijk** [comment]
Which version of docker are you using?

**Comment by ohadasulin** [comment]
```> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.0.1)

Server:
 Containers: 19
  Running: 19
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 19.03.1
```

**Comment by ohadasulin** [comment]
Why was this closed?

**Comment by bsideup** [comment]
@ohadasulin this does not look like docker-java's issue, since you have the log truncated to 10Mb. What you observe is Docker API's behaviour - consider reporting to them if you feel that something is wrong with it.

The issue got closed as stale, see stale bot's previous comment.

**Comment by ohadasulin** [comment]
@bsideup you were absolutely right. 
This is a general Docker issue and was fixed in https://github.com/moby/moby/pull/39360.
For anyone else who bumps into this issue, `19.03.14` has this issue fixed.
