### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by gaborantal** [docker-java/docker-java#1497]
Hello!

I am new here, and would like to use this Java API. However, I couldn't manage to find any relevant documentation about using this library. There some code snippets here in the issues, and some in the README, but there isn't any real documentation, the code itself is not documentated at all. I would like to create a container and read the logs from the container periodically. The mentioned LogContainerResultCallback is now deprecated, however I cannot find any matching documentation about how to switch to the new version of Results adapters. So it would be a huge help if a documentation of the basic things would be available. Maybe just I couldn't find it, but I'm searching the web for hours now, still I don't have a working example.

Thanks for the help

**Comment by ketansgaikwad05** [comment]
@gaborantal  did you find a solution? I am also facing the same challange.

**Comment by jo851kol** [comment]
[https://www.baeldung.com/docker-java-api](This) guide covers the basics :)
