### ISSUE TITLE
How to get errors from startContainerCommand?

### ISSUE THREAD

**Issue by rorytorneymf** [docker-java/docker-java#1508]
If I'm running this command to start a container, cp some directories to a volume, and exit the container:

```
DockerClient dockerClient = new DockerClient();
CreateContainerCmd createContainerCmd = dockerClient.createContainerCmd("my-docker-image");
CreateContainerResponse createContainerResponse = createContainerCmd.withCmd("/bin/sh", "-c", "/bin/cp -r /maven/* /usr/share/tomcat/webapps " + VOLUME_BIND_PATH).withEntrypoint("").exec();
dockerClient.startContainerCmd(createContainerCmd.getId()).exec();
```
How do I get any errors that may have occurred when executing the command? For example:

` /bin/cp: cannot stat '/maven/*': No such file or directory`

I didn't see any options using `startContainerCmd` to specify a callback or anything. I know I can examine the logs, but just wondering if there is another way to get the result code of the cmds?

What'd I ideally like to do is this:

- Start container
- If /maven/ directory exists, cp to the VOLUME_BIND_PATH, throw an exception if directory exists, but the cp command failed
- If /maven/ directory does not exist, do nothing
- If /usr/share/tomcat/webapps directory exists, cp to the VOLUME_BIND_PATH, throw an exception if directory exists, but the cp command failed
- If /usr/share/tomcat/webapps directory does not exist, do nothing
- Stop container

**Comment by bsideup** [comment]
@rorytorneymf see https://docs.docker.com/engine/api/v1.40/#operation/ContainerAttach and https://docs.docker.com/engine/api/v1.40/#operation/ContainerWait
