### ISSUE TITLE
Incorrect @JsonProperty annotation in ContainerSpec

### ISSUE THREAD

**Issue by dvallant** [docker-java/docker-java#1511]
I found an incorrect annotation in class ContainerSpec for the healthcheck property.The property should by "Health**c**heck" and not "Health**C**heck".
I wanted to fix the bug and create a PR, but I'm a little confused about the version number in the parent pom. Why is this 3.2.2-SNAPSHOT and not 3.2.7-SNAPSHOT?

Here is a code snipped:
```java
    @JsonProperty("Healthcheck")
    private HealthCheck healthCheck;
```

**Comment by bsideup** [comment]
Hi @dvallant,

Sure, feel free to contribute. The `master` branch contains the sources for the upcoming release. Also, I just changed the version in POMs to `0-SNAPSHOT` to not confuse people (as [it will be changed during the release](https://github.com/docker-java/docker-java/blob/cd69879d4c8d4d8c26a5bdcfcca9a5b30e516ca0/.github/workflows/release.yml#L19) anyways)
