### ISSUE TITLE
com.github.dockerjava.core.InvocationBuilder.AsyncResultCallback 是否可以提供一个带有超时的awaitResult()

### ISSUE THREAD

**Issue by RichurLiu** [docker-java/docker-java#1512]
com.github.dockerjava.core.InvocationBuilder.AsyncResultCallback 是否可以提供一个带有超时的awaitResult()
类似于
public A_RES_T awaitResult(long timeout) {
            try {
                resultReady.await(timeout, TimeUnit.MILLISECONDS);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            throwFirstError();
            return result;
        }

**Comment by bsideup** [comment]
docker-java is an English speaking communities, only reports in English are accepted.
