### ISSUE TITLE
With Docker 20.10.0 listImages filter no longer works

### ISSUE THREAD

**Issue by Yannic92** [docker-java/docker-java#1516]
With 20.10.0 docker removed the filter parameter when listing images.

https://docs.docker.com/engine/deprecated/#filter-param-for-imagesjson-endpoint

This causes 

```
return dockerClient.listImagesCmd()
  .withImageNameFilter("mongo:4.2")
  .exec()
  .stream()
  .findFirst()
  .map(Image::getId);
```

to return the ID of the first image out of ALL images.

My current workaround for this is

```
try{
  return Optional.ofNullable(dockerClient.inspectImageCmd("mongo:4.2").exec().getId());
} catch (final NotFoundException e) {
  return Optional.empty();
}
```

**Comment by bsideup** [comment]
Yes, that's correct (they removed the deprecated param)

There are several options:
1. set the API version 1.40 or lower (make sure to update to docker-java 3.2.7)
2. Use inspectImageCmd instead of list + filter
3. getFilters().put("reference, Arrays.asList("my/image))

**Comment by Yannic92** [comment]
Great! Wasn't aware that 3.2.7 is already available.

I couldn't find it on [Maven central](https://mvnrepository.com/artifact/com.github.docker-java/docker-java).
I assume it will be published within the next days?

Thank you for providing the 3rd method. I wasn't aware of this.

**Comment by bsideup** [comment]
Happy to help!

The release is on jcenter amd will be synced to Maven Central soon (later today)

**Comment by tandr** [comment]
@bsideup Given the original issue example, how would it look like in 3 cases you have suggested, sorry?

**Comment by Tianny** [comment]
> @bsideup Given the original issue example, how would it look like in 3 cases you have suggested, sorry?

```
 ListImagesCmd listImagesCmd = dockerClient.listImagesCmd();
 listImagesCmd.getFilters().put("reference", Arrays.asList("my/image"));
List<Image> images = a.withShowAll(true).exec();
```
