### ISSUE TITLE
(Add) Information about Thread safety

### ISSUE THREAD

**Issue by derteufelqwe** [docker-java/docker-java#1519]
**Description**
There are no information about thread safety at all.
Is the _DockerClient_ (Apache HttpClient 5) thread safe?
Can I use one instance and share it across all of my threads whithout any problems? I don't share objects like Containers between threads.

Currently I've just assumed that I can do so, but my docker client seems to break if I do so.

**Comment by bsideup** [comment]
Yes, it is thread safe unless explicitly stated otherwise.

**Comment by derteufelqwe** [comment]
Thanks for the quick response. Where do I find such information?

And can I find information about other limitations somewhere? Maybe about the event streams?
