### ISSUE TITLE
Wrong SSLConfig Class

### ISSUE THREAD

**Issue by KyleAure** [docker-java/docker-java#1522]
It seems that the SSLConfig class referenced in: 
https://github.com/docker-java/docker-java/blob/4387250b17fee090bf5be4ee2e2a795dd663dd80/docker-java-core/src/main/java/com/github/dockerjava/core/DockerClientConfig.java#L41

Still refers to the deprecated com.github.dockerjava.core.SSLConfig class
Instead of com.github.dockerjava.transport.SSLConfig class

Is this intentional?

**Comment by bsideup** [comment]
@KyleAure yes, I did it intentionally to avoid a breaking change in a widely used `DockerClientConfig`.
