### ISSUE TITLE
listImagesCmd().withImageNameFilter does not filter with docker server 20.10.1

### ISSUE THREAD

**Issue by detmar-krause** [docker-java/docker-java#1523]
List<Image> images = dockerClient.listImagesCmd().withImageNameFilter(_dockerImage).exec();
docker-java 3.2.7 works fine with docker server 19.03.14
With docker server 20.10.1 the filter does not work any more. The image list is now filled with all local images.

**Comment by bsideup** [comment]
`withImageNameFilter` was deprecated and removed in API version 1.41. Either set the API version to 1.40 or lower or avoid using it by either setting the reference filter or replacing with `inspectImageCmd`

**Comment by vmassol** [comment]
@bsideup thanks for the workarounds. Could you elaborate about what it means to `setting the reference filter`? Would that be the canonical way to find if a given image exists locally?

Note: I've tried using `inspectImageCmd` but it throws an exception and using a try/catch doesn't seem the best possible API to use to verify if a local image exists.

Thanks a lot

**Comment by vmassol** [comment]
FTR I now have:

```
        DockerClient dockerClient = getDockerClient();

        // If the image doesn't exist locally, pull it.
        if (!isLocalImagePresent(this.configuration.getDockerImageName(), dockerClient)) {
...
```

with:

```
    private boolean isLocalImagePresent(String imageName, DockerClient dockerClient)
    {
        boolean exists = true;
        try {
            dockerClient.inspectImageCmd(imageName).exec();
        } catch (NotFoundException e) {
            exists = false;
        }
        return exists;
    }
```

**Comment by bsideup** [comment]
@vmassol the image name query parameter got replaced with `reference` filter, you can do something like this:
```java
ListImagesCmd listImagesCmd = DockerClientFactory.instance().client().listImagesCmd();
listImagesCmd.getFilters().put("reference", List.of(dockerImageName));
java.util.List<Image> images = listImagesCmd.exec();
```

That said, `inspectImageCmd` is indeed a better alternative if you only need to check whether an image is present or not :)
https://github.com/testcontainers/testcontainers-java/pull/3575

**Comment by vmassol** [comment]
> That said, inspectImageCmd is indeed a better alternative if you only need to check whether an image is present or not :)
> testcontainers/testcontainers-java#3575

ok, I'll trust you on that then :)

Now, maybe there's a better way to do what I'm doing and there's a way to tell the `createContainerCmd` to automatically pull if the image is not present locally? I remember I searched for that and couldn't find it back then, which is why I listed local images and a manual pull.

```
            container = dockerClient.createContainerCmd(this.configuration.getDockerImageName())
                .withCmd(this.configuration.getDockerCommands())
                .withHostConfig(HostConfig.newHostConfig()
                    .withBinds(
                        // Make sure it also works when XWiki is running in Docker
                        new Bind(DOCKER_SOCK, new Volume(DOCKER_SOCK)),
                        // Make the LaTeX source visible to the container, in the right place
                        new Bind(latexDirectory.getAbsolutePath(), new Volume("/data"), AccessMode.rw))
                )
                .exec();
```

Thanks

**Comment by bsideup** [comment]
@vmassol no, Docker's API does support "create & pull if missing". Docker CLI does it in two steps as well (and Testcontainers, of course ;))

**Comment by vmassol** [comment]
ok great, thanks for the confirmation.

**Comment by hankchan101** [comment]
save my ass
