### ISSUE TITLE
Unrecognized field "LowerDir"

### ISSUE THREAD

**Issue by yahavi** [docker-java/docker-java#1526]
I'm getting the below error using `pushImageCmd`:

> [dockerjava-netty-3-1] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "LowerDir" (class com.github.dockerjava.api.command.GraphData), not marked as ignorable (5 known properties: "DeviceId", "RootDir", "dir", "DeviceSize", "DeviceName"])

I guess a solution same as https://github.com/docker-java/docker-java/pull/585 will work here.

**Versions:**
Docker Java: 3.2.7
OS: macOS 11.0.1
Docker repository: Artifactory 7.11.2

**Comment by xuhuanfeng** [comment]
+1 
It seem that the api is not support `overlay2`,  according to the `docker inspect` command, there has LowerDir、MergedDir、UpperDir、WorkDir properties, but the `GrahpData` contain none :(
