### ISSUE TITLE
Error when updating service: {"message":"invalid service version '': strconv.ParseUint: parsing \"\": invalid syntax"}

### ISSUE THREAD

**Issue by fkrivsky** [docker-java/docker-java#1528]
Hi,

I'm trying to update existing service using following code:
```
protected static void restartProxy(){
	var config = buildConfig();  
	DockerClient dockerClient = DockerClientImpl.getInstance(config, buildClient(config));  
	var bupsvc = dockerClient.listServicesCmd().withNameFilter(Arrays.asList("bupx_proxy")).exec().get(0);  
        log.info(version.toString());
	dockerClient.updateServiceCmd(bupsvc.getId(), bupsvc.getSpec()).exec();  
}
```

However, I'm always getting back the aforementioned error:
`Exception in thread "main" com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"invalid service version '': strconv.ParseUint: parsing \"\": invalid syntax"}`

Output of the line `log.info(version.toString())` is: `INFO: 2504654`

docker-java version: 3.2.7

**Comment by tduverge** [comment]
Hi,

Same issue for me,

I did this to fix it : 

```
   dockerClient
       .updateServiceCmd(serviceToUpdate.getId(), serviceSpec)
       .withVersion(serviceToUpdate.getVersion().getIndex())
       .exec();
```

**Comment by fkrivsky** [comment]
@tduverge - thank you, this workaround helped! 

Still feels like an issue though as the version info is already passed along in the service specs so this step is redundant and counter-intuitive.

**Comment by fkrivsky** [comment]
So I'm not sure, do the devs share the same view?
