### ISSUE TITLE
Boot2Docker - WebApplication Testing

### ISSUE THREAD

**Issue by srini1010** [docker-java/docker-java#153]
Hi 

 I am successfully able to create the container, ship my war file and start the Apache Tomcat server. I have done the port binding as well, but when I try to access my web application running in the docker I am getting connection timeout error. Can you please let me know how I can keep the docker container active and run it as a daemon. Also, is there an example to test web applications?

Thanks!

Rgds
Srini

**Comment by marcuslinke** [comment]
@srini1010 A container is running as long it's entrypoint/cmd is executed. Please take a look at 
https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L259

The passed command here is ```sleep 9999``` so the container will run 9999 seconds after it is started.


In your case you have to declare tomcat startup via entrypoint/cmd and expose the tomcat http port while creating the container and bind it to the host port when starting it. See

https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L185

how to expose and bind ports.

Hope that helps.

**Comment by srini1010** [comment]
@marcuslinke
Thanks for your reply. I have done these already and it is not working.
1. binded port 8080 of apache tomcat running in container to my host using below code: ExposedPort tcp8080 = ExposedPort.tcp(8080);
CreateContainerResponse container = dockerClient.createContainerCmd(imageId).withExposedPorts(tcp8080).exec();
Ports portBindings = new Ports();
portBindings.bind(tcp8080, Ports.Binding(8080));
dockerClient.startContainerCmd(container.getId()).withPortBindings(portBindings).exec();

2. I am using a docker file to create the image. In the docker file I have provided the command to run when the container is started. The command is to run a shell script which will set the JRE home and start the Apache Tomcat server.
CMD ["startTomcat.sh"]
startTomcat.sh
#!/bin/sh
export JRE_HOME=/usr/local/bin/jre1.8.0_25
/usr/local/bin/apache-tomcat-8.0.18/bin/startup.sh
echo "Successfully started tomcat"

When the container is started I am able to get the response "Successfully started tomcat" in my Integration test but after that when I try to access the WebService I have deployed I am getting connection refused error. I am not sure where I am going wrong here. Can you please help?

**Comment by marcuslinke** [comment]
@srini1010 Can you check if ```docker ps``` shows the container with the appropriate port binding? If the binding is OK you could use https://github.com/jpetazzo/nsenter. With it you can enter a running docker container and inspect it from within. You should check whether tomcat is running and listens at the right port  by looking at the tomcat logs and make use of  the usual system utilities like ```netstat```, ```ps``` and so on.

**Comment by marcuslinke** [comment]
@srini1010 Are you sure port 8080 on the host isn't already in use?
