### ISSUE TITLE
about logContainerCmd (docker logs)

### ISSUE THREAD

**Issue by rackshift** [docker-java/docker-java#1532]
Hi, i have bean working on a tool which is IPMITOOL based on docker container,here are my codes,
first use image and entrypoint to create a container then start, when i use dockerClient.logContainerCmd to get docker logs 
i got nothing, but when i debug on the code of  " StringBuffer sb = new StringBuffer();" i can get the logs, i have no idea what
happened ,  i saw the countdownlatch to await thread,but it couldnt work?anyone could hep?

private void runCmd(Instruction instruction, Map<String, String> s) {
        String containerId = client.createContainerCmd(s.get("image")).withCmd(s.get("cmd").split(" ")).exec().getId();
        client.startContainerCmd(containerId).exec();

        LogContainerCmd logContainerCmd = client.logContainerCmd(containerId);
        logContainerCmd.withStdOut(true).withStdErr(true);
        StringBuffer sb = new StringBuffer();

        try {
            logContainerCmd.exec(new ResultCallback.Adapter<Frame>() {
                @Override
                public void onNext(Frame item) {
                    sb.append(item.toString());
                }
            }).awaitCompletion(10 ,TimeUnit.MINUTES);
            addInstructionLog(instruction.getId(), sb.toString());
        } catch (InterruptedException e) {
            addInstructionLog(instruction.getId(), "error：" + e);
        }

        client.removeContainerCmd(containerId).exec();
    }

**Comment by bsideup** [comment]
@rackshift consider using `withFollowStream` and `withSince(0)`.

See https://docs.docker.com/engine/api/v1.40/#operation/ContainerLogs for more details.
