### ISSUE TITLE
Problems encountered in junit testing

### ISSUE THREAD

**Issue by wuziyangGitHub** [docker-java/docker-java#1533]
Hello, I ran into some problems while writing the junit test, I want to consult with you
Why can't all the binding be realized in the container with the help of docker-java to bind the port

code:
`
@Test
    public void create_container_not_bind_port_test(){
        Ports ports = new Ports();
        ports.bind(ExposedPort.tcp(5901), Ports.Binding.bindPortRange(6080,6090));
        ports.bind(ExposedPort.tcp(6901), Ports.Binding.bindPortRange(6080,6090));

        CreateContainerResponse exec = dockerClient.createContainerCmd("nutsllc/vnc-centos-gnome")
                .withHostConfig(HostConfig.newHostConfig().withPortBindings(ports)) 
                .withName(containerName) 
                .withEnv("VNC_PASSWORD=123456") 
                .exec();
        String containerId = exec.getId();
        dockerClient.startContainerCmd(containerId).exec();
        System.out.println(exec);
    }
`

result:
`
CONTAINER ID        IMAGE                     STATUS              PORTS                                                                                
99b01323db89        nutsllc/vnc-centos-gnome           Up 3 seconds        3389/tcp, 5900/tcp, 0.0.0.0:6080->5901/tcp                                               
`

**Comment by bsideup** [comment]
Bindings only bind the port. It also need to be exposed.

Also, consider using https://testcontainers.org for your testing needs, to avoid having to deal with Docker API's low level details.
