### ISSUE TITLE
Next release of Docker-Java

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#154]
Hi Marcus to not send you a private email I decided to ask this question as issue. Do you have any plan to release the next version of Docker-Java. I said that because I think that current stable version has a really important bug related with closing connections. This error is fixed in master and I would like to know when you are planning to release it so we can update it in Arquillian Cube and release a new version as well.

Thank you so much.

**Comment by marcuslinke** [comment]
@lordofthejars I will prepare a new release within the next few days.

**Comment by lordofthejars** [comment]
That s great thank you so much we are going to prepare a release of
arquillian Cube too
El dc., 18 de febr., 2015 a les 20.55 marcuslinke <notifications@github.com>
va escriure:

**Comment by marcuslinke** [comment]
@lordofthejars I've just released v1.0.0. It will be available from maven central in a couple of hours.

**Comment by lordofthejars** [comment]
Thank you so much
El dg., 22 de febr., 2015 a les 20.34 marcuslinke <notifications@github.com>
va escriure:
