### ISSUE TITLE
Caused by: java.net.SocketException: A socket operation encountered an idle network.

### ISSUE THREAD

**Issue by Nathan-Guillaume** [docker-java/docker-java#1543]
Hello, I have a problem, when my application is running, an error appears. Thank you

My code : https://pastebin.com/TexdWzdz
My error : https://pastebin.com/txCSMriF

**Comment by bsideup** [comment]
Hi @Nathan-Guillaume,

Please make sure that your issue reports contain enough information, like the version of libraries that you're using, that you did, ideally a reproducer attached, etc etc

"I have a problem" is not an issue report ;)

**Comment by Nathan-Guillaume** [comment]
it's updated, sorry

**Comment by Nathan-Guillaume** [comment]
@bsideup Have you a solution ? Thanks

**Comment by bsideup** [comment]
It looks like you're having some weird network issue not caused by docker-java, as this code works perfectly fine.
