### ISSUE TITLE
LGPL code in the library

### ISSUE THREAD

**Issue by hyandell** [docker-java/docker-java#1557]
Looking at https://github.com/docker-java/docker-java/blob/master/docker-java-transport-httpclient5/src/main/java/com/github/dockerjava/httpclient5/UnixDomainSocket.java - it appears to be an LGPL-2.1 file that is also noting that is based on original BSD work. It does not look to be saying that only BSD applies. That feels like it clashes with your overall licensing of Apache-2.0.

**Comment by bsideup** [comment]
Hi @hyandell,

Our assumption was that it is okay to include a single LGPL file, as long as we keep the header.

That said, we should really consider using Spring Boot's version (which is Apache-2.0):
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-buildpack-platform/src/main/java/org/springframework/boot/buildpack/platform/socket/LinuxDomainSocket.java

Thanks for reporting!

**Comment by hyandell** [comment]
On the assumption; it's one of those discussions with your legal team items. Using a publicly available policy I'm involved with, it would be a concern for the ASF: https://www.apache.org/legal/resolved.html#weak-copyleft-licenses

**Comment by bsideup** [comment]
@hyandell thanks again for reporting! The code is no longer there and we're using the Apache 2.0 implementation borrowed from Spring Boot, see https://github.com/docker-java/docker-java/pull/1566
