### ISSUE TITLE
Issue trying to build from docker-machine

### ISSUE THREAD

**Issue by Auriium** [docker-java/docker-java#1564]
Trying to make a docker client using my docker-machine ip tcp://192.168.99.102:2376 but get this exception, which makes me think that URI doesn't like numbers

java.lang.IllegalArgumentException: Illegal character in authority at index 6: tcp://192.168.99.102:2376

    at java.net.URI.create (URI.java:883)
    at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.withDockerHost (DefaultDockerClientConfig.java:356)
    at me.aurium.tick.docker.source.DockerClientProducer.produce (DockerClientProducer.java:20)
    at me.aurium.tick.CommonTickFactory.produce (CommonTickFactory.java:33)
    at me.aurium.tick.integrated.PopulateGoalMojo.execute (PopulateGoalMojo.java:41)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

**Comment by bsideup** [comment]
I just tested and `URI.create("tcp://192.168.99.102:2376")​` works perfectly fine. Make sure that there are no special characters or anything like that.

**Comment by Auriium** [comment]
I think the DockerClientConfig accepts a string, not a URI, is the issue. If you could add an api method accepting a URI that would be good

**Comment by bsideup** [comment]
the string is parsed with `URI.create` right after accepting it:
https://github.com/docker-java/docker-java/blob/f9d2db6efff4d7fc7092b53209027d6846de1894/docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L356

so I don't think this is the issue, and letting you provide an instance of `URI` won't change much. Have you tried to debug and check what's inside the string?

**Comment by Auriium** [comment]
Yep, i debug what the string is, and based on this code

`public DockerClient produce(ClientOptions options) {

        logger.info("(TICK) Url is: " + source.getUrl());
        
        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
                .withDockerHost(source.getUrl())
                .withDockerTlsVerify(options.isWithTLS())
                .build();

`

 the URI is 
 
 `[INFO] (TICK) Url is: tcp://172.17.0.1:2376

[ERROR] Error occurred during tick lifecycle: 
java.lang.IllegalArgumentException: Illegal character in authority at index 6: tcp://172.17.0.1:2376` (Directly after this exception is thrown)

**Comment by bsideup** [comment]
well, this does not answer the question "what's inside that string". `URI.parse` works with this string if I type it, which means that most probably there are some invisible special characters or something like that.

You can also try:
```java
logger.info("(TICK) Url is: " + URI.create(source.getUrl()));
```

**Comment by Auriium** [comment]
That's interesting, it seems to cause the exception with the above code meaning that there is some invisible character. That's an issue on my side, so i'll go fix that haha
