### ISSUE TITLE
DockerCmdExecFactoryImpl - SSLConnectionSocketFactory Hostname verifier

### ISSUE THREAD

**Issue by agovindaraju** [docker-java/docker-java#160]
It is good to have provided an option to override the Hostname verifier so that the client applications can control it. Because of this reason I need to have my custom implementation which on every upgrade to latest api cause troubles.

In getSchemeRegistry() some option for the client application to set the Hostname verifier.

**Comment by KostyaSha** [comment]
@agovindaraju could you show your code as example?

**Comment by agovindaraju** [comment]
Sorry for the late reply. I missed this notification. I am not sure whether it is helpful right now. But I am attaching the file which I had for reference.
[VroDockerCmdExecFactoryImpl.txt](https://github.com/docker-java/docker-java/files/83996/VroDockerCmdExecFactoryImpl.txt)

**Comment by bsideup** [comment]
See `SSLConfig#getSSLContext`
