### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by Auriium** [docker-java/docker-java#1605]
I keep getting this exception here when trying to create a mariadb box - I've made sure to pull the image beforehand as well.

`[ERROR] Error occured during lifecycle: 
com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: mariadb:10.5.9"}
`

using the code

`CreateContainerResponse response = client.createContainerCmd(terms.getDockerImageName())
                .withName(terms.getCreationName())
                .withEnv(terms.getParameters())
                .withHostConfig(new HostConfig()
                        .withPortBindings(terms.getBinding())
                )
                .exec();`
                
                please advise!

**Comment by bsideup** [comment]
>  I've made sure to pull the image beforehand as well

Since the error comes from Docker, it looks like you did not pull the image before creating the container. Consider sharing more code.

**Comment by Auriium** [comment]
I made sure that the docker image was loaded via the code below before execution. The verification code works and the loadBlocking simply just invokes the pull command.

`Arguments terms = termActual.creationArguments();

        if (strategy.shouldLoad(terms.getDockerImageName())) {
            logger.info("(TICK) Attempting to pull image with name: " + terms.getDockerImageName());

            strategy.loadBlocking(terms.getDockerImageName());

            logger.info("(TICK) image load finished!");
        }

        logger.info("(TICK) Initializing container with image: " + terms.getDockerImageName() + "! Assuming image is present!");

        CreateContainerResponse response = client.createContainerCmd(terms.getDockerImageName())
                .withName(terms.getCreationName())
                .withEnv(terms.getParameters())
                .withHostConfig(new HostConfig()
                        .withPortBindings(terms.getBinding())
                )
                .exec();

        client.startContainerCmd(response.getId()).exec();

        return termActual.creation(location,client,options,response.getId());`
        
As for docker not having the image or the pull not working, 

![image](https://user-images.githubusercontent.com/29739282/113832184-3866ea00-973d-11eb-86fe-541c7c3c8000.png)

The docker very clearly has the correct image

**Comment by bsideup** [comment]
Then I would suggest reporting to Docker, as createContainerCmd simply calls Docker's API, and the error comes from Docker.
