### ISSUE TITLE
incorrect docker host on windows 10

### ISSUE THREAD

**Issue by moglideveloper** [docker-java/docker-java#1606]
Default values as mentioned in https://github.com/docker-java/docker-java/blob/master/docs/getting_started.md

> There are a couple of configuration items, all of which have sensible defaults:
> 
> DOCKER_HOST The Docker Host URL, e.g. tcp://localhost:2376 or unix:///var/run/docker.sock

Below simplified code gives same docker host on macOS and windows :-

```
package docker.java.examples;

import com.github.dockerjava.core.DefaultDockerClientConfig;
import com.github.dockerjava.core.DockerClientConfig;

public class DockerJavaExample {

    public static void main(String[] args) {

        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().build();
        String os = System.getProperty("os.name");
        System.out.println("os : " + os + " docker url : " + config.getDockerHost());
    }
}
```

**Windows Output :-**

`os : Windows 10 docker url : unix:///var/run/docker.sock`

**Mac OS Output :-**

`os : Mac OS X docker url : unix:///var/run/docker.sock`

Kindly confirm, weather above two values**(tcp://localhost:2376 or unix:///var/run/docker.sock)** are for different operating system.

**Comment by bsideup** [comment]
docker-java does not auto-detect Docker and simply defaults to `tcp://localhost:2376` when TLS mode is set, or `unix:///var/run/docker.sock` otherwise.

**Comment by joffrey-bion** [comment]
Couldn't the `unix://` default be instead OS-dependent? If the OS is windows, the fallback could be `npipe:////./pipe/docker_engine` instead of `unix:///var/run/docker.sock` URI.

**Comment by bsideup** [comment]
@joffrey-bion we accept contributions :)

**Comment by joffrey-bion** [comment]
Thanks! I will probably PR something then. I just prefer to discuss first in general 😉
