### ISSUE TITLE
set Include.NON_EMPTY is not working

### ISSUE THREAD

**Issue by lxitgto** [docker-java/docker-java#1608]
I have some code like this

> containerResponse = dockerClient.createContainerCmd(image)
>                     .withCmd(cmd)
>                     .withHostConfig(hostConfig)
>                     .withWorkingDir(workspace)
>                     .withEntrypoint(entrypoint)
>                     .exec();

sometimes cmd is empty list or blank string, so I tried set Include.NON_EMPTY in ObjectMapper

> DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
>                 .withDockerHost("tcp://127.0.0.1:2375")
>                 .withApiVersion("v1.39")
>                 .build();
>         config.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
>         DockerClient dockerClient = DockerClientBuilder
>                 .getInstance(config)
>                 .build();

but It's not working, still send ""Cmd":[""],"Healthcheck":null,"ArgsEscaped":null" to docker api

**Comment by bsideup** [comment]
`config.getObjectMapper()` returns a _copy_, not the original mapper.

**Comment by lxitgto** [comment]
Got it. I change code like this:

```
var createContainerCmd = dockerClient.createContainerCmd(image)
                .withWorkingDir(workspace)
                .withHostConfig(hostConfig);
        if (!env.isEmpty()) {
            createContainerCmd.withEnv(env);
        }
var containerResponse = createContainerCmd.exec();
```

it's working. thanks.
