### ISSUE TITLE
Piecing back together a large message from FramedInputStreamConsumer

### ISSUE THREAD

**Issue by duckmatt** [docker-java/docker-java#1615]
Within `FramedInputStreamConsumer` if the response's body is over 1024 bytes it gets chopped up into frames (of 1024 bytes). If I have a callback provided (via the constructor) consuming the frames it doesn't seem like there's a way of relating the frames of individual responses, for example in the case of largish logs we may want to piece them back together from the callback. 

I was thinking possibly of something along the lines of having an integer added to the frame so we know which frame it is per response, e.g. frame 1 of 1, frame 1 of 2, frame 2 of 2. What are your thoughts and am I maybe taking the wrong approach trying to attempt this in the first place?

The related section of code:

https://github.com/docker-java/docker-java/blob/0306031832432454fbbdbf5c20e16fe881c7b065/docker-java-core/src/main/java/com/github/dockerjava/core/FramedInputStreamConsumer.java#L59-L81

**Comment by bsideup** [comment]
@duckmatt since the emission of frames is sequential, you can rely on it and do the counting yourself.

Also, have a look at https://github.com/testcontainers/testcontainers-java/blob/1.15.3/core/src/main/java/org/testcontainers/containers/output/FrameConsumerResultCallback.java for an inspiration.
