### ISSUE TITLE
Optionally replace junixsocket with JEP-380

### ISSUE THREAD

**Issue by Sineaggi** [docker-java/docker-java#1626]
Now that [JEP-380](https://openjdk.java.net/jeps/380) has shipped in java 16, we should be able to replace the current usage of junixsocket with `SocketChannel` and `UnixDomainSocketAddress` for users of java 16 and above.

**Comment by bsideup** [comment]
Hi @Sineaggi,

Thanks for checking, looks very promising! I am setting up Java 16 on my machine, but could you please check, perhaps there is some Java 8-compatible factory that calls `UnixDomainSocketAddress.of(path)`, so that we can avoid figuring out the linking question? Thanks in advance!

**Comment by Sineaggi** [comment]
A quick glance at the docs and Find Usages in Intellij unfortunately doesn't reveal any factory methods.

**Comment by bsideup** [comment]
Implemented in #1627
