### ISSUE TITLE
how can I pass a configuration file ?

### ISSUE THREAD

**Issue by samirakhelifi** [docker-java/docker-java#1628]
Here's my java class:
@SpringBootApplication
public class DemoApplication {
    public static void main(String[] args) {
        try {

            DefaultDockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
                    .withDockerHost("tcp://localhost:2375").build();
            DockerClient dockerClient = DockerClientBuilder.getInstance(config).build();
            CreateContainerResponse container
                    = dockerClient.createContainerCmd("appium/appium")
                    .withPortBindings(PortBinding.parse("4723:4723"))
                    .withName("appium-node")                                                                                                                                                        .withEnv("CONNECT_TO_GRID=true","privileged","APPIUM_PORT=4723","SELENIUM_HOST=172.17.0.2","SELENIUM_PORT=4444")

                    .exec();

            dockerClient.startContainerCmd(container.getId()).exec();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    ;
    }

and i want to pass a json configuration file:

my file ----> androidconfig.json:
{
    "capabilities": [
        {
          "deviceName": "Galaxy A8",
          "udid": "520081efb8a0757f",
          "platformName": "android",
          "version":"9.0",
          "maxInstances": 1
       }
    ],
  "configuration": {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://127.0.0.1:4723/wd/hub",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "172.17.0.2",
    "role": "node"
    }
}

how can i do that please?

**Comment by bsideup** [comment]
Hi @samirakhelifi,

docker-java is a low level library that simply wraps [the Docker API](https://docs.docker.com/engine/api/v1.40/). Please refer to the API documentation to find how to perform various operations.

Also, if you need it for testing, you may want to use [the Testcontainers project](https://www.testcontainers.org) that provides high level abstractions on top of docker-java.

**Comment by samirakhelifi** [comment]
Hello sir,
Okay you have .withDevices() parameter but it lacks documentation how can i
use it please?
Regards.

Le lun. 17 mai 2021 à 08:07, Sergei Egorov ***@***.***> a
écrit :

**Comment by bsideup** [comment]
@samirakhelifi please refer to Docker's API.
