### ISSUE TITLE
Volumes can not be bound when creating a container

### ISSUE THREAD

**Issue by nesneros** [docker-java/docker-java#164]
It is not possible to bind a volume when a container is create. On the command line you can do something like

```docker create -v /host/path:/container/path image```

AFAIKS that is not possible with docker-java. Instead you have to start a container if you want to bind a volume. That is very inconvenient if you for example use [Data Only Containers](http://container42.com/2013/12/16/persistent-volumes-with-docker-container-as-volume-pattern/).

If you take a look at the documentation of the Docker rest api, there is a change from 1.15 to 1.16 that the container start api doesn't take any configurations arguments in v1.16. It is all in the create api. [1.15](https://docs.docker.com/reference/api/docker_remote_api_v1.15/#start-a-container) vs. [1.16](https://docs.docker.com/reference/api/docker_remote_api_v1.16/#start-a-container).

In the docker-java api the create command has a method ```withVolumes(Volume... volumes)``` and the start command has a method ```withBinds(Bind... binds)```. Is there a good reason for the differences? As I see it the withBinds method is the general one and should also be on the create command.

/Jan

**Comment by marcuslinke** [comment]
@nesneros Thanks for reporting! Will take a look at this soon.

**Comment by marcuslinke** [comment]
@nesneros The create command also has ```withBinds()``` method although it is currently a bit hidden. 
See ```HostConfig``` of create command please. 

All this confusing access path results from the evolution of the docker rest API in the past. So maybe the docker-java API needs some cleanup to reflect latest docker API more precisely.

**Comment by KostyaSha** [comment]
Javadocs will be appreciated, because library looks like spaghetti.
