### ISSUE TITLE
idea docker plugin connect failed

### ISSUE THREAD

**Issue by weiweili666** [docker-java/docker-java#1645]
idea version 2020.2.1
docker plugin 202.6948.69  
add ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock
problem: 
     when i configure docker configuration, meet the problem with 'com.fasterxml.jackson.core.JsonParseException: Unexpected character  (" (code 60)): expected a valid value (JSON String, Number ,Array , Object or token 'null','true' or 'false') at [Source : (com.github.dockerjava.core.DefaultInvocationBuilder$2);line:1,cloumn:2 ]

**Comment by bsideup** [comment]
Please report to IDEA's Docker plugin
