### ISSUE TITLE
Incomplete docker log message

### ISSUE THREAD

**Issue by yuting-liu** [docker-java/docker-java#1647]
Hey team, 
we are using docker-java for docker logs and docker metrics ingestion.

The issue we encountered is that when a large amount of logs are ingested through `logContainerCmd`, one single log message will be splited in the middle of the message like this:
```
05/24/2021 16:31:12 2021-05-24T23:
05/24/2021 16:31:12 31:09:82XX - - [07/Mar/2016:17:53:45 -0000] "GET /twiki/bin/search/Main/SearchResult?scope=text&regex=on&search=Office%20*Locations[^A-Za-z] HTTP 1.1" 200 7771
```

This bug is introduced with PR https://github.com/docker-java/docker-java/pull/1351/
As switching from `FrameStreamProcessor` to `FramedInputStreamConsumer`, logs are no longer ingested into `Frame` with complete log messages.

Currently we have to downgrade to version 3.2.8 to 3.2.1 so as to not breaking customers' log.

CC @bsideup can we make some change accordingly to have `logContainerCmd` still using the old Frame processor?

**Comment by bsideup** [comment]
Hi @yuting-liu,

Thanks for reporting! This one is a bit challenging to debug, if you have any additional information and, ideally, a reproducer, that would be greatly appreciated. Especially if we can write a unit test for `FramedInputStreamConsumer` that will cover this case.

Thanks in advance!
