### ISSUE TITLE
Docker java latest version(3.2.8) still using older Jersey version(2.30.1)

### ISSUE THREAD

**Issue by iamkishlayverma** [docker-java/docker-java#1651]
Docker java latest version(3.2.8) still using older Jersey version(2.30.1) because of which facing some compatibility issues.

**Comment by bsideup** [comment]
Hi @iamkishlayverma,

Please see https://github.com/docker-java/docker-java/blob/master/docs/transports.md

The Jersey transport isn't actively supported and most probably will be removed in a near future.
Consider using some other transport according to that table.

**Comment by bsureshr** [comment]
Is it possible to configure one of the above listed transport part ? It would be great to have one example how can we configure httpclient5

**Comment by bsideup** [comment]
See `DockerClientImpl.getInstance(DockerClientConfig, DockerHttpClient)` and `ZerodepDockerHttpClient.Builder` and others.
