### ISSUE TITLE
BuildImageCmd.withPlatform(String) for comma-separated os/arch value

### ISSUE THREAD

**Issue by bmuschko** [docker-java/docker-java#1659]
I was trying to use the method `BuildImageCmd.withPlatform(String)` with the value `darwin,linux/amd64/v8,linux/amd64`. It seems like the regex validation of the execution does not allow commas or slashes which are quite common for [defining a platform](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images).

```
com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"\"darwin,linux\" is an invalid component of \"darwin,linux/amd64/v8,linux/amd64\": platform specifier component must match \"^[A-Za-z0-9_-]+$\": invalid argument"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:237)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Is this a bug or am I doing something wrong? I am using version 3.2.8.

**Comment by bsideup** [comment]
Hi @bmuschko,

As the 400 error comes from Docker, this doesn't look like docker-java's problem, and the validation happens on the server side.
Have you tried to inspect the payloads sent by Docker CLI and check what they sent?

**Comment by bmuschko** [comment]
Got it. Let me have a deeper look. How do you usually inspect the payload from the CLI?

**Comment by bsideup** [comment]
@bmuschko usually, I just start a `socat` in the tracing mode :)
https://blog.mikesir87.io/2018/10/using-socat-to-see-docker-socket-traffic/

**Comment by bmuschko** [comment]
Perfect thanks. Looks like that `platform` parameter only supports providing a single platform and not a comma-separated list.
