### ISSUE TITLE
When calling createContainerCmd and encountering an exception, the resulting unstarted container is not removed

### ISSUE THREAD

**Issue by Auriium** [docker-java/docker-java#1675]
Is there a way to remove the resulting container? Either by try/catch block or some other way.

**Comment by bsideup** [comment]
Hi @Auriium,

docker-java is a client for Docker API, and, if such functionality is missing in Docker's API, you would either need to build it yourself, or use some other Java libraries that build on top of docker-java, e.g. http://github.com/testcontainers/testcontainers-java for testing.

**Comment by Auriium** [comment]
The issue is that there is nothing provided by the exceptions that will let me build that functionality in - i cannot get the ID of the container on exception in order to shut it down.

**Comment by bsideup** [comment]
@Auriium then consider reporting to Docker about this limitation of their API, or finding an ingenious solution.

I would share how we do it in Testcontainers, but you said that it ["had too many issues and didn't fall within code quality standards of the organization"](https://github.com/docker-java/docker-java/issues/1565#issuecomment-806175303), so I will let you figuring out a perfect solution within your code quality standards. Good luck!

**Comment by Auriium** [comment]
Thank you! I figured out a solution that works just fine!
