### ISSUE TITLE
exec cuts off some(!) input streams to a magic size

### ISSUE THREAD

**Issue by veselov** [docker-java/docker-java#1685]
OK, this one has really sent me spinning... 

java-docker: 3.2.11
docker: ce-20.10.3-3.fc31

Showcase code: https://github.com/veselov/DockerTest/tree/magic-98304

I've ran into this trying to restore postgres dumps from a stream. The import operation seemed to have been cut off. So I tried to investigate.

AFAICS, the input stream just stops dead at some point, and returns EOF to the container-side read. Which point it decides to stop at remains a mystery, but seems to be somewhat related to blocks of data aligning on some magic boundary.

Whether it happens or not seems to be related to how even the source stream is. I have a data producing stream in my code, which produces little bits of data every read (`MyStream`), this stream works fine (all data received by container). If a stream does have a large buffer which is properly filled (`fullStream()`, or gunzip of Java resource stream), the stream is likely to be cut off.

I verified that running `cat data | docker exec -i wc` always works as expected.

See https://github.com/veselov/DockerTest/blob/f463c530ce0cc87adc996e81d80eafdada172611/src/main/java/org/example/App.java#L111 where changing the input showcases the problem.

The workaround seems to be to forcefully meter the stream to a really small buffer. The last line in that block uses a 14 byte buffer, which seems to work fine. It doesn't translate to 14 byte reads on the container side, interestingly, but creates an uneven pattern of how many bytes are released to it with every read.

The container-side I/O trace is downloaded after every run to 1.trs.tar, so you can observe the read pattern and cut-off fact.

**Comment by bsideup** [comment]
Hi @veselov, I see that you're using the Netty transport. Have you tried others? See https://github.com/docker-java/docker-java/blob/master/docs/transports.md for more info

**Comment by veselov** [comment]
Hi @bsideup, no I haven't, because then #1448 will prevent stdin from being useful, unless I'm missing something. I've tried different HTTP clients - but I'm not sure it matters if netty exec factory is being used.

**Comment by bsideup** [comment]
@veselov it actually matters a lot, because Netty goes through a completely different route, while other transports use the new `DockerHttpClient` abstraction

**Comment by veselov** [comment]
@bsideup Right, so unless I'm missing something, I think we are saying the same thing.

I can not avoid using Netty because otherwise `stdin` won't work (#1448). `stdin` won't close with OkHTTP/Apache HTTP clients, and Jersey doesn't support stream hijacking. Since I'm forced to use Netty through the exec factory, specifying the HTTP client won't matter (for the exec calls).
