### ISSUE TITLE
Docker Swarm Machine Compose

### ISSUE THREAD

**Issue by m451** [docker-java/docker-java#172]
Hi guys, 

I wonder if you got any plans implementing the new tools released by Docker. I was thinking of seperate projekts / repos within the docker-java github account which eventually use the base that docker-java already provides or act as addon libs for the docker-java project. 

What do you think?

**Comment by hassanmudassir-rzt** [comment]
Is there any java API for docker compose?

**Comment by KostyaSha** [comment]
> //EDIT: forget it, I just realized there is no remote api for compose or machine. Swarm already works with docker-java besides a few issues that are more related to swarm then to docker-java. Wonder why there is no remote API but I'll close this till I figured out / it's available.
