### ISSUE TITLE
Upgrading from 0.10.3

### ISSUE THREAD

**Issue by mpataylor** [docker-java/docker-java#1739]
I'm trying to upgrade from 0.10.3 to 3.2.7. (Why not the latest? Because that was the latest when I started.) I am not a prgrammer (I'm a HW engineer) and so have been making slow progress. I have managed to make some changes (they compile, but I have no idea whether they work or not, yet.) But this line has me completely stumped:

        InputStream response =
                dockerClient.attachContainerCmd(container.getId()).withLogs(true).withStdErr().withStdOut()
                        .withFollowStream().exec();

I have managed to get round one error by changing it to

        InputStream response =
                dockerClient.attachContainerCmd(container.getId()).withLogs(true).withStdErr(true).withStdOut(true)
                        .withFollowStream(true).exec(new AttachContainerResultCallback());

(but my IDE says that AttachContainerResultCallback is deprecated.) I have been looking for days now (on and off), to find some method that returns an InputStream . But there doesn't seem to be one. 

I saw a 2013 request about this kind of thing for help from the guy who originally wrote this code. The answerer was surprised that he was trying to get at the output from the docker container. Is this now something that is no longer possible?

**Comment by bsideup** [comment]
Try `ResultCallback.Adapter` (see `AttachContainerResultCallback`'s deprecation notice)
