### ISSUE TITLE
Add .dockerignore support to BuildImageCmd

### ISSUE THREAD

**Issue by dougborg** [docker-java/docker-java#174]
It looks like there is already a `TODO: ` comment in the BuildImageCmd for this (https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/BuildImageCmd.java#14), but I thought I would raise an issue for it as well. Is this something you already have an implementation plan for? Let me know if you have (even very general) ideas for how to tackle it. I am up to help if I can.

**Comment by marcuslinke** [comment]
@dougborg This is already implemented here:

https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/dockerfile/Dockerfile.java#L119

**Comment by marcuslinke** [comment]
@dougborg Maybe it's not working as expected. Feel free to open another issue then. Thanks!

**Comment by dougborg** [comment]
Thanks for such a fast follow-up! I am investigating this further now, and I am not exactly sure where this is breaking down.

I use docker-java via bmuschko's gradle-docker-plugin (https://github.com/bmuschko/gradle-docker-plugin). I tried updating the docker-java dependency to the latest (1.0.1-SNAPSHOT), but I am getting the same behavior as before with the default version of docker-java included by the plugin: a docker image built with `docker build` results in a smaller image than building the same `Dockerfile` via the gradle plugin. Further investigation revealed the exclusion patterns in the `.dockerignore` file were not being respected (i get the contents of the `.git` and `.gradle` folder included in the docker image). However, this may be an issue with the gradle-docker-plugin. I'll let you know what I find out.
