### ISSUE TITLE
DockerCmdExecFactoryImpl fails when not using SSL

### ISSUE THREAD

**Issue by AndrewGuenther** [docker-java/docker-java#176]
It would be really nice to be able to use the default DockerCmdExecFactory without having to use SSL.

As far as I can tell [this line](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/jaxrs/DockerCmdExecFactoryImpl.java#L72) will always fail if no SSL certs are given.

Including code here for convenience:
```java
        SSLContext sslContext;
        try {
            sslContext = dockerClientConfig.getSslConfig().getSSLContext();
        } catch(Exception ex) {
            throw new DockerClientException("Error in SSL Configuration", ex);
        }
```

**Comment by marcuslinke** [comment]
@AndrewGuenther Should be fixed now. Please test. Thanks!
