### ISSUE TITLE
ETA release 1.0.1

### ISSUE THREAD

**Issue by bmuschko** [docker-java/docker-java#177]
Hi,

When can we expect the final release of version 1.0.1? I'd need to have this [commit](https://github.com/docker-java/docker-java/commit/c88167b52d46926523522be25f5626885ba51783) which requires authentication setup in 1.0.0 but it's actually not mandatory.

Thanks for your hard work,

Ben

**Comment by marcuslinke** [comment]
So as it is requested hopefully I'm able to prepare a new release until mid of the week.

Regards

Marcus

**Comment by bmuschko** [comment]
Thanks for the info!

**Comment by bmuschko** [comment]
Ping?!

**Comment by marcuslinke** [comment]
Following the semantic versioning scheme finally I've released v1.1.0 . Sorry for the delay but i was kind of busy last days.

**Comment by bmuschko** [comment]
Thanks!
