### ISSUE TITLE
NameParser validation is not correct

### ISSUE THREAD

**Issue by magnayn** [docker-java/docker-java#182]
E.g:
```java
  if (!VALID_REPO_PATTERN.matcher(name).matches()) {
            throw new InvalidRepositoryNameException(String.format(
                    "Invalid repository name (%s), only [a-z0-9-_.] are allowed", name));
        }
```
Disallows names with hyphens, which *are* allowed.

Correct set seem to be here:

https://github.com/docker/docker/blob/master/registry/v2/regexp.go

**Comment by KostyaSha** [comment]
just for information, patterns were changed between some docker versions :angry:

**Comment by marcuslinke** [comment]
Fixed by https://github.com/docker-java/docker-java/pull/298
