### ISSUE TITLE
ResultCallback not executed on WaitContainerCmd

### ISSUE THREAD

**Issue by doetlingerlukas** [docker-java/docker-java#1831]
There seems to be a problem using the `WaitContainerCmd` with a custom callback. Although the container is running, `onNext()` is never called.

The blocking version of `WaitContainerCmd` works as expected.

I can reproduce the issue on multiple systems with both tcp and unix socket connection using `docker-java-transport-httpclient5` and version `3.2.13`.

My code looks like this:

```
ResultCallback.Adapter<WaitResponse> callback = new ResultCallback.Adapter<WaitResponse>() {
  public void onNext(WaitResponse waitResponse) {
    promise.complete(imageName);
  }
};

client.waitContainerCmd(containerId).exec(callback);
```

**Comment by bsideup** [comment]
Hi @doetlingerlukas! Could you please provide a test case similar to https://github.com/docker-java/docker-java/blob/8253a999825d430df35148da835b37f1d731df0f/docker-java/src/test/java/com/github/dockerjava/cmd/WaitContainerCmdIT.java#L28 that will demonstrate the issue?

The existing tests seem to be working.

**Comment by bsideup** [comment]
> Although the container is running, `onNext()` is never called.

Note that `WaitContainerCmd` waits for container to stop:
https://docs.docker.com/engine/api/v1.37/#operation/ContainerWait

**Comment by doetlingerlukas** [comment]
Well, I had a look at those tests and built my code like that. However, the containers used in my scenario are not supposed to exit, so the error is on my side.

Guess I should have taken a look into the Docker docs first.
Thanks @bsideup for helping me find my issue!
