### ISSUE TITLE
DockerClientBuilder.getInstance() getting NoClassDefFoundError 

### ISSUE THREAD

**Issue by MichelleGong2000** [docker-java/docker-java#1874]
Hi,
Would you please help to see why I got NoClassDefFoundError for the following code:
DockerClient dockerClient = DockerClientBuilder.getInstance().build();

App is not a maven project.  I had all the jar files in .classpath file.  Thank you so much!
        <classpathentry kind="lib" path="jars/docker-java-3.2.13.jar"/>
	<classpathentry kind="lib" path="jars/docker-java-api-3.2.13.jar"/>
	<classpathentry kind="lib" path="jars/docker-java-transport-jersey-3.2.13.jar"/>
	<classpathentry kind="lib" path="jars/docker-java-transport-netty-3.2.13.jar"/>
	<classpathentry kind="lib" path="jars/docker-java-transport-3.2.13.jar"/>

**Comment by rwmajor2** [comment]
@MichelleGong2000 Can you provide more detail on the exact error?
