### ISSUE TITLE
Trouble getting TLS to work

### ISSUE THREAD

**Issue by itsharis** [docker-java/docker-java#1883]
I have successfully configured docker to run using TLS using the following properties.

```
{
   "experimental":true,
   "hosts":[ "tcp://ab.c.d.e:2375", "unix:///var/run/docker.sock" ],
   "tls": true,
   "tlscert": "/home/user/docker-cert/server-cert.pem",
   "tlskey": "/home/user/docker-cert/server-key.pem"
}
```

However i am having issues configuring the docker-java library to use TLS. This is how i am creating the DockerClientConfig. I have generated the cert/keystore following the documentation here:
https://docs.docker.com/engine/security/protect-access/

```
DockerClientConfig config = DefaultDockerClientConfig
	.createDefaultConfigBuilder()
	.withDockerTlsVerify(true)
	.withDockerCertPath("/home/user/keystore/")
	.withDockerHost("tcp://ab.c.d.e:2375")
	.build();
```
Under the cert path, i have a certificate named `docker.crt`

I get the following error when trying to do a Ping:

```com.github.dockerjava.api.exception.BadRequestException: Status 400: Client sent an HTTP request to an HTTPS server.```

**Comment by sql4653** [comment]
我也遇到了同样的问题。但是阅读源码后你会发现需要修改证书的名称才可以认证。在LocalDirectorySSLConfig中，证书名称分别固定为：ca.pem、key.pem、cert.pem
`    @Override
    public SSLContext getSSLContext() {

        boolean certificatesExist = CertificateUtils.verifyCertificatesExist(dockerCertPath);

        if (certificatesExist) {

            try {

                Security.addProvider(new BouncyCastleProvider());

                String caPemPath = dockerCertPath + File.separator + "ca.pem";
                String keyPemPath = dockerCertPath + File.separator + "key.pem";
                String certPemPath = dockerCertPath + File.separator + "cert.pem";

                String keypem = new String(Files.readAllBytes(Paths.get(keyPemPath)));
                String certpem = new String(Files.readAllBytes(Paths.get(certPemPath)));
                String capem = new String(Files.readAllBytes(Paths.get(caPemPath)));

                String kmfAlgorithm = AccessController.doPrivileged(getSystemProperty("ssl.keyManagerFactory.algorithm",
                    KeyManagerFactory.getDefaultAlgorithm()));
                KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(kmfAlgorithm);
                keyManagerFactory.init(CertificateUtils.createKeyStore(keypem, certpem), "docker".toCharArray());

                String tmfAlgorithm = AccessController.doPrivileged(getSystemProperty("ssl.trustManagerFactory.algorithm",
                    TrustManagerFactory.getDefaultAlgorithm()));
                TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(tmfAlgorithm);
                trustManagerFactory.init(CertificateUtils.createTrustStore(capem));

                SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
                sslContext.init(keyManagerFactory.getKeyManagers(), trustManagerFactory.getTrustManagers(), null);

                return sslContext;

            } catch (Exception e) {
                throw new DockerClientException(e.getMessage(), e);
            }

        }

        return null;

    }`
