### ISSUE TITLE
Support  --cap-add in swarm?

### ISSUE THREAD

**Issue by CenGinHong** [docker-java/docker-java#1884]
I try to use the client to run the command like:
`docker service create --cap-add=ALL -p 8080:80 nginx`

But I found there seems to be no method in client  to set `CapabilityAdd` in swarm

**Comment by vipchenwei** [comment]
How did you do it？

**Comment by riebecj** [comment]
Is there any way to reopen this issue? It should be something that us supported, since `CAP_ADD` has been supported in swarm mode since API v1.41
