### ISSUE TITLE
Registry names split to max 2 parts

### ISSUE THREAD

**Issue by jgriffiths1993** [docker-java/docker-java#190]
`...api/model/identifier.java`

The repository name is split to `namespace/repository` without taking into account the potential domain as the first part.

`docker.registry:8080/namespace/repository:tagage` is completely valid, with the first part indicating the registry domain:port to which images should be pushed (or pulled).

Unlike the other parts (at least, in docker v1.5) there does not appear to be a regexp for this.

However, to complicate things, we can have a 2 part repository name with a registry (assuming namespace of 'library', I believe) - e.g. `docker.registry:8080/mysuperrepo:megatag`.

In this case, a registry is identified by the inclusion of either a dot or a port number (/:[0-9]+$/).

When tagging an image with three parts, the above is enforced for the first part (a dot or a port number) or an error is thrown.

The domain requirements by the docker client has no character limits and can include almost anything. I'd suggest limiting it to valid domains (not necessarily fully-qualified) including either a dot or a port as I expect the requirements will change as docker matures.

Please validate this as a defect and I'll submit a PR :smile_cat:

**Comment by marcuslinke** [comment]
@jgriffiths1993 Thanks for finding! Would be nice to get a PR.

**Comment by jgriffiths1993** [comment]
Would it be best to introduce a helper class for image names, or a Docker Image Name class?

**Comment by marcuslinke** [comment]
IMO it would be good to have a Docker Image Name class.

**Comment by jgriffiths1993** [comment]
This should hopefully have enough validation etc: https://github.com/jgriffiths1993/docker-java/commit/bfde13452a7b621bd68429017a63c2f07a85d39f - make inline comments etc. if you want anything changed before I make a PR :smile_cat: 

It's all based on the docker/docker source for v1.5+

**Comment by marcuslinke** [comment]
@jgriffiths1993 Thanks! Great work. LGTM so far. Would be interesting to see how it integrates with the current API. So I'm awaiting your PR. ;-)

Sorry for the delay but i was i bit busy last days...

**Comment by marcuslinke** [comment]
Closed in favor of https://github.com/docker-java/docker-java/issues/300
