### ISSUE TITLE
Whether docker-java supports buildkit

### ISSUE THREAD

**Issue by 1993captain** [docker-java/docker-java#1904]
Dockerfile has the following content：

#syntax=docker/dockerfile:experimental
FROM python:latest
COPY . /data
WORKDIR /data
RUN --mount=type=cache,mode=0755,target=/root/.cache/pip pip3 install -r requirements.txt
......

There is no problem executing the docker build command directly on the server,but building through docker-java's buildImageCmd api will report an error "the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled".(Buildkit has been configured)

**Comment by FluxCapacitor2** [comment]
Currently it seems like the Docker API doesn't support this, see these GitHub issues:
https://github.com/docker/for-linux/issues/1136
https://github.com/moby/moby/issues/41711
Unfortunately, until this is implemented in the Docker Engine API, you probably have to use a workaround like the [Docker CLI](https://github.com/docker/cli) or [Docker Compose](https://docs.docker.com/compose/).
