### ISSUE TITLE
Unable to mock docker-client

### ISSUE THREAD

**Issue by rwmajor2** [docker-java/docker-java#1908]
I am trying to mock DockerClient with my integration, but seems like it is impossible.  Does anyone have any examples of how to do this?  Even a simple `docker.pingCmd().exec()` would be useful.

**Comment by bsideup** [comment]
The client is not designed for mocking given the complexity, but consider mocking `DockerCmdExecFactory` instead. See `DockerClientImpl#withDockerCmdExecFactory`.
