### ISSUE TITLE
Needed Jakarta version of docker library, forked it

### ISSUE THREAD

**Issue by JD-CSTx** [docker-java/docker-java#1911]
Out team migrated from Java EE to Jakarta EE, so we needed docker libraries which also use jakarta packages instead of javax packages. So I just forked this project and replaced javax with jakarta.

The fork: https://github.com/JD-CSTx/docker-java

I had one failing test, but that test failed also in the original, unchanged code, so I'm really not that concerned about it. We need the Docker Java Client for integration tests, and it did run now very often without any errors.

The original plan for the fork was to provide a version which builds seperate JARs with "jakarta" classifiers, but due to the complicated structure of the project that was abandoned. It uses the default version number, which is "0-SNAPSHOT".

I don't plan to maintain this parallel to the official project, and would rather prefer it if the original project would somehow integrate my fork.

**Comment by bsideup** [comment]
Hi @JD-CSTx,

Please see this page: https://github.com/docker-java/docker-java/blob/master/docs/transports.md

Jersey transport is no longer maintained and will eventually be removed, and other transports do not have a dependency on Java EE / Jakarta EE. So I would highly recommend using one of the supported transports 👍
