### ISSUE TITLE
What is the latest docker API version supported ？

### ISSUE THREAD

**Issue by vipchenwei** [docker-java/docker-java#1920]
is 1.3.7？

**Comment by sick-cat** [comment]
![image](https://user-images.githubusercontent.com/31824316/184869923-65aa331b-3993-4d00-99c1-0c8bc3516188.png)

**Comment by sick-cat** [comment]
![image](https://user-images.githubusercontent.com/31824316/184872796-c3757e32-23de-4baf-afcb-b68300303ab6.png)

**Comment by eddumelendez** [comment]
docker-java works with the latest docker API 1.41 very well but you may find that not all operations are supported. is this related to #1921?
