### ISSUE TITLE
Do you support  for V1.4.1 “Get data usage information”  Interface

### ISSUE THREAD

**Issue by vipchenwei** [docker-java/docker-java#1921]

**Comment by eddumelendez** [comment]
Hi  @vipchenwei, we currently do not support such an operation but looks like @executed is working on it and we will be glad to review it.

**Comment by executed** [comment]
stuck on IT tests. Please check my question on Gitter, any assistance would be much appreciated

**Comment by vipchenwei** [comment]
@eddumelendez  ok,thank you very much!
