### ISSUE TITLE
Test Smell: the wrong parameter order in ''assertEquals'' assertion

### ISSUE THREAD

**Issue by TestSmell** [docker-java/docker-java#1923]
Hi!

Description:
we detect that some assertions in your test code have the wrong parameter orders.
For example, the test case named ''copyFromContainerBinaryFile()'' in ''CopyArchiveFromContainerCmdIT.java'' writes the ''assertEquals'' assertion as
![image](https://user-images.githubusercontent.com/110402847/184608370-93eb6bdc-b356-4199-856c-81e1fc82fe26.png)
However, referring to the API documentation of ''org.junit.Assert’’ is ''assertEquals(Object expected, Object actual)''.

Negative:
Using ''assertEquals()'' with the wrong parameter order is a bad test practice.
Because once the test case fails, the ''assertEquals()'' assertion with the wrong parameter order will give the wrong log information.
The log information will say:’’ java.lang.AssertionError: expected [actual value] but found [ excepted value]’’, where it should have said "java.lang.AssertionError: expected [excepted value] but found [actual value]''.
This is confusing, to say the least, and you shouldn't have to deal with a possible misdirection of that message.

solution:
Generally, the excepted value should be a known value, such as a real number, a string, etc.
The actual value should be the result of the method-under-test.
The best way to eliminate the test smell is to exchange the parameter in ''assertEquals'' assertions.

We list other test cases with the same problem as follows:
1. copyFromContainerBinaryFile() in CopyArchiveFromContainerCmdIT.java
2. version() in VersionCmdIT.java
3. configuredInstanceAuthConfig() in DockerClientImplTest.java
4. defaults() in DefaultDockerClientConfigTest.java
5. assertTarArchiveEntryIsExecutableFile() in CompressArchiveUtilTest.java
6. serializeCapability() in CapabilityTest.java ...

**Comment by eddumelendez** [comment]
Hi @TestSmell ! thanks for raising the issue! are you willing to contribute and fix those?

**Comment by albers** [comment]
This is probably a leftover from the times when [TestNG](https://testng.org/doc/) was used for testing. TestNG's `assertEquals` has reversed parameter order in comparison to JUnit.
The switch to JUnit was in #909.
