### ISSUE TITLE
List Images Command withNameFilter returns all Images

### ISSUE THREAD

**Issue by franziseidl** [docker-java/docker-java#1935]
Hides Image with the given Name instead of showing it, as expected

**Comment by eddumelendez** [comment]
@franziseidl thanks for raising this issue! I think this is due to you are testing against docker server API 1.41 which removed the `filter` query param.

I just submit a #1941 supporting `reference` query param

**Comment by wys199703** [comment]
Hi，when is about to release to support docker api 1.41 to fix this problem by reference param?
