### ISSUE TITLE
Wiki page contains mistakes

### ISSUE THREAD

**Issue by AlienOnEarth** [docker-java/docker-java#195]
Hi,

The wiki page for docker-java client has a section for start, wait and stop the container. There seem to be   some mistakes in that section.

1.) There should be container.getid() instead of container.id

ContainerCreateResponse container = dockerClient.createContainerCmd("busybox")
   .withCmd("touch", "/test")
   .exec();

dockerClient.startContainerCmd(container.id).exec();
dockerClient.waitContainerCmd(container.id).exec();
dockerClient.stopContainerCmd(container.id).exec();

2.) The waitContainerCmd goes into the infinite loop. It should be wait for stop not for start. The following sequence works just fine.

dockerClient.startContainerCmd(container.id).exec();
dockerClient.stopContainerCmd(container.id).exec();
dockerClient.waitContainerCmd(container.id).exec();

Thanks,
Jack

**Comment by marcuslinke** [comment]
@AlienOnEarth Thanks for finding. Of course you are right! I will modify the wiki accordingly.
