### ISSUE TITLE
Allow specifying Dockerfile outside of the context root

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#198]
Currently, the library seems to require that the Dockerfile is located within the build context.  There is no particular reason this needs to be the case, as the build context is copied into a tar InputStream before being sent to the docker server.  Thus, the optionally specified Dockerfile could be added to this InputStream from outside the build context.

This would be particularly useful for situations in which the Dockerfile is being built by a build process into a 'build' directory, but the build context, probably with lots of checked in files, is somewhere else.  Copying the build context files into the 'build' directory is expensive (space and time) and, depending on the build system, difficult to get right if the files are read-only.

To fix this, I think the code in Dockerfile.ScannedResult.buildDockerFolderTar() would need to be changed slightly to accommodate a Dockerfile outside the build context.  Possibly this could be accomplished with some special handling of the Dockerfile in CompressArchiveUtil.archiveTARFiles()

**Comment by KostyaSha** [comment]
Docker API contains 'remote' option, wouldn't it help you?

**Comment by PatrickHuetter** [comment]
This is really important as it seems to be a problem also here: https://github.com/bmuschko/gradle-docker-plugin/issues/187#issuecomment-214267178 (the plugin is using the docker-java library).

It's really inflexible with Dockerfiles always within the context.

**Comment by wilx** [comment]
These bots are evil.

**Comment by bsideup** [comment]
@wilx I would ask the same question and use the same label anyways ;) This issue is 5 years old, things have changed and it may not be relevant anymore.
