### ISSUE TITLE
getPorts() empty on stopped container

### ISSUE THREAD

**Issue by bdauvissat** [docker-java/docker-java#1999]
Hello. 
Thanks for this project. 
I'm using docker-java 3.2.12 
When I try to get informations on a container, if it's running, I can get the ports but when stopped, the array is empty.
I load the container like 
``` java
        List<Container> containers = getClient().listContainersCmd()
                .withIdFilter(List.of(id))
                .withShowAll(true)
                .exec();
```

and then 
```
Container container = containers.get(0);
ContainerPort[] ports = container.getPorts();
```

Is that the intended behaviour ?

**Comment by neandrake** [comment]
When a container is stopped it will not be bound to any ports. It won't have an IP or MAC address either. The behavior you're seeing also matches `docker container ls --all` as it will not show/list any ports for stopped containers.

**Comment by eddumelendez** [comment]
docker-java is a client that talks with the docker daemon. If the container is running, the information available can be fetched using docker-java, `ports` is available in this case. When the container is stopped then no ports to fetch.
