### ISSUE TITLE
Support Unix Socket Connections

### ISSUE THREAD

**Issue by mfulgo** [docker-java/docker-java#20]
This is a feature request:

It would be nice if the client also supported a socket connection (defaulting to `/var/run/docker.sock`). That way, you wouldn't have to make any changes to the docker configuration, and it would just work out of the box.

The more configuration steps we can eliminate when using this in a CI build environment, the better.

**Comment by gesellix** [comment]
@jglick @lordofthejars unix socket support will be available with the next docker-java release.

**Comment by marcuslinke** [comment]
just published 0.10.5 with unix socket support.

**Comment by albers** [comment]
@jglick this might be of interest for you.

**Comment by jglick** [comment]
Yes, saw this, thanks!
