### ISSUE TITLE
com.github.dockerjava.api.model.PullResponseItem#isPullSuccessIndicated fails to check for "Exists" status

### ISSUE THREAD

**Issue by AndyGee** [docker-java/docker-java#2010]
com.github.dockerjava.api.model.PullResponseItem#isPullSuccessIndicated checks for several success states, but misses "Exists" and treats this status as a failure.

Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Exists

If would be great if the success status codes could be a configurable list that the library user could append to.

**Comment by eddumelendez** [comment]
@AndyGee thanks for reporting this issue! is the full status `Already exists`? I look at [moby](https://github.com/moby/moby) and just found that one.

**Comment by AndyGee** [comment]
@eddumelendez Sorry for the late reply. On Win at least, it is "Exists" - However, I'm currently using the above workaround in all our projects, which are also built on ios and ubuntu based systems.

**Comment by AndyGee** [comment]
@eddumelendez another workaround is of course to delete the image, but that's kind of drastic ;-) - Interestingly the IMAGE_UP_TO_DATE is not the status here, which is what I'd expect given that the image is actually up to date.

**Comment by AndyGee** [comment]
![image](https://user-images.githubusercontent.com/2536412/214066809-36b03b0c-0ba6-406d-966f-65a0c9f007c1.png)
