### ISSUE TITLE
Error connecting to more than one docker server simultaneously

### ISSUE THREAD

**Issue by rtimush** [docker-java/docker-java#202]
If you try to create two clients
```java
DockerClient client1 = new DockerClientBuilder.getInstance(config1).build()
DockerClient client2 = new DockerClientBuilder.getInstance(config2).build()
```
then both will connect to `config2`.
A workaround is to create a new instance of `DockerCmdExecFactory` for each client which is very unintuitive:
```java
DockerClient client1 = new DockerClientBuilder.getInstance(config1)
    .withDockerCmdExecFactory(new DockerCmdExecFactoryImpl()).build()
DockerClient client2 = new DockerClientBuilder.getInstance(config2)
    .withDockerCmdExecFactory(new DockerCmdExecFactoryImpl()).build()
```

**Comment by marcuslinke** [comment]
@rtimush After looking at the current sources I don't see how your code example will lead to the described error. What version of docker-java do you use?

**Comment by rtimush** [comment]
I faced the issue on 1.0.0, but it seems that on the master branch the code is the same. The [DockerClientBuilder.build()](https://github.com/docker-java/docker-java/blob/cc5331d7de228601fa817f0212ee107953470075/src/main/java/com/github/dockerjava/core/DockerClientBuilder.java#L63) method locates a singleton instance of a `DockerCmdExecFactory` with a `ServiceLoader`. Then this shared factory is configured twice with the [init()](https://github.com/docker-java/docker-java/blob/408a320adefea160881dbf5036eaab09aa21a4f9/src/main/java/com/github/dockerjava/jaxrs/DockerCmdExecFactoryImpl.java#L45) method.

**Comment by marcuslinke** [comment]
OK. Now i got it. So sharing of the ```ServiceLoader``` is the problem here. Thanks for reporting. I wonder why this hasn't raised up before. I will provide a fix soon.

**Comment by rtimush** [comment]
I didn't tested it, but probably creating a new ServiceLoader every time can be very expensive. In my opinion a better approach would be to use ServiceLoader to locate a stateless factory of DockerCmdExecFactory instances (if there is a reason to use ServiceLoader at all).

**Comment by marcuslinke** [comment]
You are probably right about this but I guess nobody will create masses of client instances so performance should be equal here. Although ```ServiceLoader``` isn't really needed i don't want to change classloading behaviour because somebody might rely on this.

**Comment by marcuslinke** [comment]
@rtimush Should be fixed now. Please test. Thanks!
