### ISSUE TITLE
Release 3.2.14 broken due to LoadImageAsyncCmd change

### ISSUE THREAD

**Issue by pabloFuente** [docker-java/docker-java#2022]
When updating my Spring Boot application's dependency to docker-java from **3.2.13** to **3.2.14**, it fails to start with the following error:

```
Caused by: java.lang.ClassNotFoundException: com.github.dockerjava.api.command.LoadImageAsyncCmd
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

The nested exception that one of my Beans throws is the following one:

```
nested exception is java.lang.NoClassDefFoundError: com/github/dockerjava/api/command/LoadImageAsyncCmd
```

This must be related for sure with this PR that made it into the 3.2.14 release just  a few days ago: https://github.com/docker-java/docker-java/pull/1982.

**Comment by eddumelendez** [comment]
can you share a project which reproduces the issue? I haven't had issues when upgrading.

**Comment by pabloFuente** [comment]
I cannot provide the project in which I'm seeing the error, as it is proprietary. What I can assure is that I am not using the class **`LoadImageAsyncCmd`** directly (it is not explicitely imported anywhere into the code). And that rolling back to 3.2.13 gets rid of the ClassNotFoundException exception.

The piece of code that triggers the exception is the call to **`DockerClientBuilder#build`** method:

```java
DockerClientConfig dockerClientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder().build();
DockerHttpClient dockerHttpClient = new JerseyDockerHttpClient.Builder()
		.dockerHost(dockerClientConfig.getDockerHost()).sslConfig(dockerClientConfig.getSSLConfig()).build();
this.dockerClient = DockerClientBuilder.getInstance(dockerClientConfig).withDockerHttpClient(dockerHttpClient)
		.build();
```

Exactly these lines in class `DockerClientBuilder`:

https://github.com/docker-java/docker-java/blob/0306031832432454fbbdbf5c20e16fe881c7b065/docker-java/src/main/java/com/github/dockerjava/core/DockerClientBuilder.java#L87-L90

Whenever those lines are executed, the `java.lang.ClassNotFoundException` is thrown and the application fails to start.

**Comment by eddumelendez** [comment]
Please check that all your docker-java dependencies are using `3.2.14`. You may have a previous version for `docker-java-api`

In maven use `mvn dependency:tree` and in gradle use `./gradlew dependencies`

**Comment by eddumelendez** [comment]
Closing due to there is no response. Feel free to re-open if there is still an issue.
