### ISSUE TITLE
Providing private registry url/credential tries using those credentials to auth against public registry

### ISSUE THREAD

**Issue by StFS** [docker-java/docker-java#2040]
I reported a bug on testcontainers ([see here](https://github.com/testcontainers/testcontainers-java/issues/6403)) where providing a private registry url/credentials as an environment variable (by providing `-Dregistry.url=foobar.myregistry.com -Dregistry.username=fluff -Dregistry.password=bunny` as command line options to my maven build) resulted in testcontainers not being able to retrieve public images from the public registry.

The errors we were seeing were "incorrect username/password" errors, meaning that the private registry credentials were being used to attempt to authenticate against the public docker registry.

This should of course not happen and could be considered a security issue (credential leaking where you're unwittingly sending your secret credentials to a party that should not be getting those secrets).

It was eventually determined that this was not a bug with testcontainers and should be reported here instead.

Steps to reproduce, further explanation and some investigation/discussion are available in the [testcontainers issue](https://github.com/testcontainers/testcontainers-java/issues/6403).

**Comment by StFS** [comment]
There's also discussion about this in testcontainers slack: https://testcontainers.slack.com/archives/C1SUBPZK6/p1673350403349039

**Comment by jrichardsz** [comment]
Hi. This is only a wrapper of docker engine, so if public images cannot be downloaded after set a private registry , it could be an error in the created Dockerfile. Could you provide a [reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) to help you? Also you could create a private image in https://hub.docker.com  to reproduce your issue
