### ISSUE TITLE
Using docker-java from a client running on a docker container 

### ISSUE THREAD

**Issue by vakkanti** [docker-java/docker-java#209]
Created a web application that uses docker-java API to connect to Docker (boot2Docker) on the same machine. set params like DOCKER_CERT_PATH and DOCKER_HOST in system ENV variables. Was able to invoke API.

However, when I deploy the same war file inside a container running on Docker, I am experiencing connectivity issues as  below, tried with http and https as well, but not successful. suggest how to invoke docker java API when running the client from inside a docker container

javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: tcp protocol is not supported
	org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:513)
	org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
	org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)

**Comment by marcuslinke** [comment]
It shouldn't make any difference whether you start docker-java from within a container or not. I guess the container environment differs somehow and docker-java is picking up the wrong url. Be aware that docker-java is configured via config file in general but picks up some environment variables also.
