### ISSUE TITLE
JerseyDockerHttpClient is deprecated

### ISSUE THREAD

**Issue by knightdreams6** [docker-java/docker-java#2104]
JerseyDockerHttpClient is deprecated and what should be used instead

**Comment by knightdreams6** [comment]
I want to use this project in jdk17 environment.

Looking forward to your reply.

**Comment by eddumelendez** [comment]
Hi, as mentioned and the end of https://github.com/docker-java/docker-java/blob/main/docs/transports.md `docker-java-transport-httpclient5` should be used
