### ISSUE TITLE
Restart container missing signal argument

### ISSUE THREAD

**Issue by slinkydeveloper** [docker-java/docker-java#2123]
Hi,
The restart container method is missing a signal argument https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerRestart, similar to what's in `kill`: https://javadoc.io/static/com.github.docker-java/docker-java-api/3.3.0/com/github/dockerjava/api/command/KillContainerCmd.html#withSignal-java.lang.String-

**Comment by eddumelendez** [comment]
PR is welcome
