### ISSUE TITLE
docker-compose command support

### ISSUE THREAD

**Issue by wfy-belief** [docker-java/docker-java#2131]
I want to use docker-compose by yaml in java sdk, how can i operator it 🙋

**Comment by eddumelendez** [comment]
docker-java doesn't use the CLI, it uses the [Docker API](https://docs.docker.com/engine/api/v1.43) and there is no endpoint for it. It depends on your use case but [Testcontainers offers limited support for docker compose](https://java.testcontainers.org/modules/docker_compose/) in your tests.
