### ISSUE TITLE
Datatype of field returned in InspectImageResponse incorrect

### ISSUE THREAD

**Issue by hkuyam007** [docker-java/docker-java#214]
My image has a few onbuild commands. When I used the docker-java api to execute Inspect Image command on the image, it was throwing int to String dataconversion error.

That's because the field onBuild inside class ContainerConfig, which in turn is used inside InspectImageCmd is defined as an int, should really be a String. I chanaged the datatype locally to String to remove the error / exception.

My Image has a bunch of onBuild commands like the following -

"OnBuild": [
            "ADD $SOURCE_ARTIFACT_DIR $ARTIFACT_DIR/",
            "ADD $SOURCE_SCRIPT_DIR $SCRIPT_DIR/",
            "ADD $SOURCE_TEST_DIR $TEST_DIR/",
            "RUN cp $ARTIFACT_DIR/* $TOMCAT_HOME/webapps/"

**Comment by marcuslinke** [comment]
@hkuyam007 I'm not aware of this 'OnBuild' property. So it should contain the content from the Dockerfile?

**Comment by marcuslinke** [comment]
I'm asking because i want to write a test case for it.

**Comment by hkuyam007** [comment]
Sorry for the delayed response and thanks for responding!
I can see that you have already referenced this in a fix. Nonetheless to answer your question -

When the command "docker inspect <image-name/id>" is executed, it returns all details of the image, as you might already be knowing. 
If the Docker file (from which the Image was built previously) contained some ONBUILD instructions, the argument of those instruction(s) are also returned as array in JSON format in the output of docker inspect command.
The code is assuming that the array would be an int array which is incorrect, because it would really be a string, for example -
ONBUILD ADD ./source ./destination
Therefore the value of the argument in this case would be the whole string "ADD ./source ./destination"

**Comment by docker-java-maintain** [comment]
@hkuyam007 I didn't even know about this Dockerfile instruction. Interesting... Thanks for your input. Just released v1.3.0 which includes the fix already.
