### ISSUE TITLE
Missing LogConfig option in HostConfig

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#218]
...as described here [create container](https://docs.docker.com/reference/api/docker_remote_api_v1.18/)

See https://github.com/docker/docker/issues/12211

**Comment by cdancy** [comment]
The gradle-docker-plugin depends on this library and I'd like to expose the functionality there but can't until it's here first. If no one is working on this I'll gladly take it on..

**Comment by marcuslinke** [comment]
Any help is really appreciated. I'm await your PR... :)

**Comment by marcuslinke** [comment]
https://github.com/docker-java/docker-java/pull/272
