### ISSUE TITLE
Numeric value 14573918182 out of range of int(-2147483648 - 2147483647)  InspectContainerResponse["SizeRootFs"]

### ISSUE THREAD

**Issue by liylongg** [docker-java/docker-java#2237]
使用这个方法InspectContainerResponse containerResponse = dockerClient.inspectContainerCmd(containerId).withSize(true).exec()时，会报这个错误，Numeric value 14573918182 out of range of int(-2147483648 - 2147483647) InspectContainerResponse["SizeRootFs"]， InspectContainerResponse 中的 SizeRootFs 属性是一个 Integer 类型，会转换异常

**Comment by eddumelendez** [comment]
See https://github.com/docker-java/docker-java/pull/2230
