### ISSUE TITLE
DockerClientImplementation to implement Autoclosable

### ISSUE THREAD

**Issue by Khazrak** [docker-java/docker-java#228]
The DockerClientImplementation implements Closable which means that that the close-method throws a IOException. Since the minimum Java version is 7 we could use the try-with-resources IF we use the AutoClosable-interface.

**Comment by KostyaSha** [comment]
:+1:

**Comment by KostyaSha** [comment]
`public interface Closeable extends AutoCloseable {`
What is the problem to use it?

**Comment by marcuslinke** [comment]
OK, I see. Will revert this commit. Thanks!
