### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration

### ISSUE THREAD

**Issue by ass-hcc** [docker-java/docker-java#2284]
版本：springboot-3.2， docker-java-3.3.4

**Comment by ass-hcc** [comment]
添加 javax.ws.rs-api 2.1.1 依赖，报错变成：
java.lang.LinkageError: ClassCastException: attempting to castjar:file:/D:/maven/respository/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/D:/maven/respository/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class

**Comment by alkaphreak** [comment]
# Initial Error:

Encountered a NoClassDefFoundError when building with Docker Java API.

```text
java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
    at com.github.dockerjava.jaxrs.JerseyDockerHttpClient$Builder.build(JerseyDockerHttpClient.java:124)
    at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:106)
    ...
```

# Attempted Solution:

Added the javax.ws.rs-api dependency to my .kts file:

```text
implementation("javax.ws.rs:javax.ws.rs-api:2.1.1")
```

# New Error After Adding Dependency:

Encountered a LinkageError related to ClientBuilder.

```text
java.lang.LinkageError: ClassCastException: attempting to cast jar:file:/home/alkaphreak/.gradle/caches/modules-2/files-2.1/javax.ws.rs/javax.ws.rs-api/2.1.1/d3466bc9321fe84f268a1adb3b90373fc14b0eb5/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class
    at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:81)
    at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.<init>(JerseyDockerHttpClient.java:257)
    ...
```

Build Script (build.gradle.kts):

```text
// Relevant parts of the build script
dependencies {
    // Other dependencies...
    implementation("com.github.docker-java:docker-java:3.3.4")
    implementation("com.github.docker-java:docker-java-transport-httpclient5:3.3.4")
    implementation("javax.ws.rs:javax.ws.rs-api:2.1.1")
}
```

# Resolution Attempts :

Tried using a resolutionStrategy to force the version without success.

```text
// Apply a resolution strategy to force a single version of the dependency
configurations.all {
    resolutionStrategy {
        // Force usage of a specific version of 'javax.ws.rs-api'
        force("javax.ws.rs:javax.ws.rs-api:2.1.1")
    }
}
```

# Request for Help:

I'm unable to resolve the LinkageError after adding the javax.ws.rs-api dependency.
If anyone has insights or suggestions on how to fix this issue, please advise.

**Comment by ass-hcc** [comment]
You can try using “withDockerCmdExecFactory(new NettyDockerCmdExecFactory())” to create a docker client

**Comment by alkaphreak** [comment]
Nice it works. `withDockerCmdExecFactory` is deprecated, if i wanna use `withDockerHttpClient` how do i setup that ?

**Comment by Submergence** [comment]
I met same probelm, while I try javax.ws.rs 2.0.0. It worked but returned same error in next day.

**Comment by eddumelendez** [comment]
It is recommended to use Apache HttpClient 5 instead of Jersey transport. See https://github.com/docker-java/docker-java/blob/main/docs/transports.md#jersey
