### ISSUE TITLE
Check current code base against up-to-date docker remote API

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#229]
There are incompatibilities because of outdated docker remote API docs here:

https://docs.docker.com/reference/api/docker_remote_api_v1.18/

See https://github.com/docker/docker/issues/13466

Check the current docker-java code base against this up-to-date API reference:

https://github.com/docker/docker/blob/master/docs/sources/reference/api/docker_remote_api_v1.18.md

**Comment by KostyaSha** [comment]
https://github.com/docker/docker/pull/13936

**Comment by KostyaSha** [comment]
It here now https://github.com/docker/docker/tree/master/docs/reference/api

**Comment by KostyaSha** [comment]
@marcuslinke what do you think about putting `@since 1.16`  for fields?

**Comment by marcuslinke** [comment]
The problem here is that docker remote API reference doesn't have a complete changelog. Tracking changes manually is some kind of overkill for me.

**Comment by KostyaSha** [comment]
@marcuslinke https://gist.github.com/KostyaSha/500d85cc61c0527e89a7 but i think vimdiff will be more siutable and such info can be requested during PR review.

**Comment by marcuslinke** [comment]
I like the idea but keep in mind the information should be complete for ALL fields then. I don't have the time to investigate this.

**Comment by KostyaSha** [comment]
What do you mean under complete?

**Comment by marcuslinke** [comment]
I mean all fields in the whole API needs a `@since` then.

**Comment by KostyaSha** [comment]
@marcuslinke only interface i think, javadoc will be inherited then AFAIR

**Comment by marcuslinke** [comment]
Thats not only interfaces but some model classes (like `HostConfig` and so on) also...

**Comment by KostyaSha** [comment]
Taking BuildCmd for update

**Comment by marcuslinke** [comment]
Closing this as syncing with current remote API version is an epic issue that will (probably) never end.
