### ISSUE TITLE
Get Container ERR/OUT/IN

### ISSUE THREAD

**Issue by 1ikeadragon** [docker-java/docker-java#2301]
Hi, I'm a beginner, creating a container and attaching to in/out. Container is getting created fine, but how to capture the output? Code I'm using:

```java

DockerClient client = Client.clientInit();
        CreateContainerResponse container = client.createContainerCmd("python:slim")
                .withCmd("/bin/sh","-c","uname -a")
                .withAttachStderr(true)
                .withAttachStdin(true)
                .withName("sandbox-dev")
                .exec();
        client.startContainerCmd(container.getId()).exec();
```
Also, how to get the STDERR/STDOUT/ attach to STDIN via `docker exec` equivalent code?

PS- clientInit is defined:

```java
public class Client {
    public static DockerClient clientInit(){
        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().build();
        ZerodepDockerHttpClient httpClient = new ZerodepDockerHttpClient.Builder().dockerHost(config.getDockerHost()).build();
        return DockerClientImpl.getInstance(config,httpClient);
    }
}
```

**Comment by debxrshi** [comment]
@fujiwarazz yeah I found a solution but it's really bad code. Have you found any solution?

**Comment by fujiwarazz** [comment]
you can try client init with ApacheHttp5 instead

**Comment by debxrshi** [comment]
@fujiwarazz why?

**Comment by raunaqpahwa** [comment]
Hey @debxrshi and @fujiwarazz this might help-
[https://github.com/raunaqpahwa/CodeExecutionEngine/blob/440f46869bf229aabc73d280a655bdca64f36530/src/main/java/com/raunaqpahwa/codeexecutor/services/impl/JavaCodeExecutionStrategy.java#L58](url)

You can pass a custom callback while executing command in the docker container and that will help you fetch stdout and stderr.
