### ISSUE TITLE
Connection Error: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect

### ISSUE THREAD

**Issue by WildePizza** [docker-java/docker-java#2307]
Im using docker desktop on windows and have "Expose daemon on tcp://localhost:2375 without TLS" enabled but when i run this:
```
        config = DefaultDockerClientConfig.createDefaultConfigBuilder()
                .withDockerHost("tcp://localhost:2375")
                .build();
        try (DockerClient dockerClient = DockerClientBuilder.getInstance(config).build()) {
            dockerClient.listContainersCmd().exec().forEach(container -> {
                System.out.println("Container ID: " + container.getId());
            });
            System.out.println("Done!");
        }
```
        
i get this error: Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect

**Comment by nisemono13** [comment]
I ran into this issue too, and I suspect it was due to a version upgrade. Previously using server version 18.09.0, docker-java+apacheDockerHttpClient can connect properly remotely. But now the new docker is installed, the server version is 25.0.3, and the error you mentioned appears

**Comment by WildePizza** [comment]
I've recently just reset my pc and now everything works fine

**Comment by envomp** [comment]
Bumping the docker-java dependency version to the latest fixed the issue for me
