### ISSUE TITLE
Binding volumes

### ISSUE THREAD

**Issue by nateweisz** [docker-java/docker-java#2312]
Given a `CreateContainerCmd` how could I bind a volume from a directory, "/opt/test/example-folder/" to "/home/example" in the docker container?

**Comment by flowt-au** [comment]
I am pretty new to docker-java and had a similar question. Using version 3.3.6. I have a solution which works on my OSX dev machine, but is not yet tested on Linux nor in production. I will report back in a few days on that. 

I am using this within a Quarkus app (just FYI).

This is what I did:
```java
    String bindSource = "/absolute/path/to/source/folder"; // eg "/opt/test/example-folder/"
    
    // Check bindSource exits and mkdir() it if it doesn't. (not shown here)...

    // Create a map for the options
    Map<String, String> options = new HashMap<>();
    options.put("type", "none");
    options.put("device", bindSource);
    options.put("o", "bind");

    // Create a name for the volume
    String volumeName = "myVolumeName";

    // Get a client we can use to interact with the Docker Daemon, however you currently do that.
    // Build config and httpClient (not shown) ...
    DockerClient dockerClient = DockerClientImpl.getInstance(config, httpClient);

    // Create a new volume with the options
    CreateVolumeResponse volume = dockerClient.createVolumeCmd()
        .withName(volumeName)
        .withDriverOpts(options)
        .exec();
   
    // Now the volume exists, we can bind it.

    // The path inside the container
    String bindDestination = "/path/in/container"; // eg "/home/example"

    // Make a new Bind
    Bind bind = new Bind(volumeName, new Volume(bindDestination)

    // Create the host config, which includes the volume bind
    HostConfig hostConfig = HostConfig.newHostConfig()
        .withNetworkMode("my-net")
        // .with other bits as needed...
        .withBinds(bind);

      // Create the container
      CreateContainerResponse container = dockerClient.createContainerCmd(imageName)
          .withName(containerName)
          .withEnv(envArgs)
          .withHostConfig(hostConfig) // The host config has the volume definition from above
          .exec();
```
Hope that helps. Maybe there is another way but that is the best I can find for now.

Cheers,
Murray

**Comment by flowt-au** [comment]
PS: 
The reason I am unsure about this on Linux (Ubuntu) is that previously I tried to make a simple Bind Mount (no docker volume creation) like the following, instead of the kind outlined above:
```java
String bindSource = "/absolute/path/to/source/folder";
String bindDestination = "/path/in/container";
Bind bind = new Bind(bindSource, new Volume(bindDestination))
```
which worked on my Mac, but I had permission issues on my Ubuntu machine because the user inside the Docker container was not the same as the user on the Host machine. I am hoping that by creating an actual docker volume and using that instead that Docker will resolve the permission issues. 

Hence my comment about getting back to you.

Murray

**Comment by flowt-au** [comment]
Ok. This is what I have found now I have tested on Ubuntu 22.04.

Both the `bind mount` and `volume mount` approaches above work as far as docker is concerned. i.e. with either approach I can bind a folder on the host to a folder inside the container. It seems they are functionally equivalent.

The permission issue is the same using either approach. I am on a learning curve with Linux permissions. What I realised was that the `bindSource` folder was ending up with permissions like this: `drwxrwxr-x` (ie no write permission for the "others" group). The docker container counts as an "other" as far as the host is concerned, so it could not write to the folder.

I did the following to solve this, and I think it is safe from a security perspective, and am happy to take advice if there is a more secure way of achieving this outcome.

Whether I make a bind mount or volume mount, once I ensure the `bindSource` folder exists (see the code above), I call the following function to set the permissions on the `bindSource`. 

```java
setFilePermission(bindSource);
```

Those permissions are reflected in the container's `bindDestination` folder (ie the "linked" source folder), and I can now view, read and write the files in that folder in the docker container and the host folder reflects the changes when I write a file from inside the container.
```java
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.PosixFilePermission;

/**
 * Set the file permissions for the container's file repo directory.
 * @param filePath
 */
private void setFilePermission(String filePath) {
  Path directory = Paths.get(filePath);

  try {
    Set<PosixFilePermission> perms = new HashSet<>();

    // FYI: If you leave any of these out, the permission will be removed.
    // So, if you ONLY set perms.add(PosixFilePermission.OTHERS_WRITE);
    // then the permissions will look like: d-------w-

    // FYI: re security. In Linux, 'x' execute permission is required to access a directory.
    // The files IN that directory are not executable unless the file itself is an executable and has 'x' permission.

    // add owners permission
    perms.add(PosixFilePermission.OWNER_READ);
    perms.add(PosixFilePermission.OWNER_WRITE);
    perms.add(PosixFilePermission.OWNER_EXECUTE);
    // add group permissions
    perms.add(PosixFilePermission.GROUP_READ);
    perms.add(PosixFilePermission.GROUP_WRITE);
    perms.add(PosixFilePermission.GROUP_EXECUTE);
    // add others permissions
    perms.add(PosixFilePermission.OTHERS_READ);

    // This is the one not normally set and we need it for the container to be able to write to this directory.
    perms.add(PosixFilePermission.OTHERS_WRITE);

    perms.add(PosixFilePermission.OTHERS_EXECUTE);

    Files.setPosixFilePermissions(directory, perms);
  } catch (IOException e) {
    e.printStackTrace();
  }
}

Please tell me if this can be improved or if there are security issues here.
Thanks,
Murray
```

**Comment by nateweisz** [comment]
Hey Murray. Thank's for helping me with this!!

**Comment by flowt-au** [comment]
No worries, please report back if there are any issues with this approach. I am still learning and the docker-java docs are a bit light-on in terms of this level of detail. :-)
