### ISSUE TITLE
Unit Testing (Mockito and Junit)

### ISSUE THREAD

**Issue by nader-elyadata** [docker-java/docker-java#2315]
Hello, I was attempting to test my service which uses Docker Java API. When it comes to the mocking aspect of the API, I have encountered numerous errors. Can anyone provide guidance on how to mock the DockerClient?

**Comment by BillOTei** [comment]
did you find your luck somewhere?

**Comment by nader-elyadata** [comment]
Hey @BillOTei,

I came up with a workaround (though not ideal) that mocks the entire Docker client and its methods. I've attached an example for your reference.

![image](https://github.com/docker-java/docker-java/assets/157314609/0f7e8c35-1b15-40c2-af65-5a380df81031)

**Comment by BillOTei** [comment]
> ```
> Hey @BillOTei,
> ```
> 
> I came up with a workaround (though not ideal) that mocks the entire Docker client and its methods. I've attached an example for your reference.
> 
> ![image](https://private-user-images.githubusercontent.com/157314609/332811369-0f7e8c35-1b15-40c2-af65-5a380df81031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODQ1MDAsIm5iZiI6MTcxNjM4NDIwMCwicGF0aCI6Ii8xNTczMTQ2MDkvMzMyODExMzY5LTBmN2U4YzM1LTFiMTUtNDBjMi1hZjY1LTVhMzgwZGY4MTAzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxMzIzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDJlZDUxNWRlNTIzNjcxOWVlODdhOGZkOGEyYWIxMTBiZDllMTE0OGI4OGE1NDMwZjQ2ZTg1N2IwMjk1OTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xt9h0B-_JESWc6Ce1s2XXw-l_TQ1zxXTWeJT5DFi_CQ)

thanks very much for that, I was about to do something similar.
