### ISSUE TITLE
How to calculate CPU percentage using docker java SDK

### ISSUE THREAD

**Issue by iumairhasan** [docker-java/docker-java#2357]
### Description
I'm trying to calculate CPU percentage using docker java SDK from [CpuStatsConfig](https://javadoc.io/static/com.github.docker-java/docker-java-api/3.2.11/com/github/dockerjava/api/model/CpuStatsConfig.html) (Source code [Statistics.java#L56](https://github.com/docker-java/docker-java/blob/main/docker-java-api/src/main/java/com/github/dockerjava/api/model/Statistics.java#L56) does not have any document either). I see this object has `CpuStats` and `PreCpuStats`, which are supposed to be used to calculate CPU percent usage. However, I did not find any documentation on what exactly does this `PreCpuStats` represents in java object. 

I also looked into couple of resources from github [1] and got to the formula of getting cpu usage, but I wanted to confirm if thats the right approach here.

1. Can you help me understanding what is `PreCpuStats` and how to interpret this object? to take a step further, if you can help me how to interpret `pre` values (read, preread) from [Statistics.java#L56](https://github.com/docker-java/docker-java/blob/main/docker-java-api/src/main/java/com/github/dockerjava/api/model/Statistics.java#L56) that would be great.
2. Can you help me with right way to calculate CPU percentage using docker SDK? The nearest most understandable approach I came across is from [github.com/moby/moby/stats_helpers.go#L175-L188](https://github.com/moby/moby/blob/eb131c5383db8cac633919f82abad86c99bffbe5/cli/command/container/stats_helpers.go#L175-L188)
3. I'm also looking for any resource/documentation to understand docker java SDK. if there is any you can link me, then that would be a great helpful resource for me.

[1] -
a. https://github.com/docker-java/docker-java/issues/1270
b. https://github.com/moby/moby/blob/eb131c5383db8cac633919f82abad86c99bffbe5/cli/command/container/stats_helpers.go#L175-L188

Thanks,
Umair

**Comment by eddumelendez** [comment]
Hi, check the Docker Engine API https://docs.docker.com/reference/api/engine/version/v1.47/#tag/Container/operation/ContainerStats
