### ISSUE TITLE
Documentation request for docker java SDK

### ISSUE THREAD

**Issue by iumairhasan** [docker-java/docker-java#2367]
Hi, I'm trying to capture block I/O statistics using docker java SDK, but I dont find its documentation anywhere, and I could not interpret much with the code implementation of API model ([BlkioStatEntry](https://github.com/docker-java/docker-java/blob/main/docker-java-api/src/main/java/com/github/dockerjava/api/model/BlkioStatEntry.java), [Statistics](https://github.com/docker-java/docker-java/blob/main/docker-java-api/src/main/java/com/github/dockerjava/api/model/Statistics.java#L44)). I see a reference to other go doc in `BlkioStatEntry`, but that link does not work anymore. I also looked into [javadocs documentation](https://javadoc.io/doc/com.github.docker-java/docker-java/3.1.0-rc-5/com/github/dockerjava/api/model/BlkioStatsConfig.html), but that didn't help me either.

1. Is it possible to get any documentation reference for docker java SDK?
2. Specifically, for the problem I'm trying to solve, I'm looking to understand [BlkioStatsConfig](https://github.com/docker-java/docker-java/blob/main/docker-java-api/src/main/java/com/github/dockerjava/api/model/BlkioStatsConfig.java) and its methods like `getIoServiceBytesRecursive`,  `getIoServicedRecursive`, `getIoTimeRecursive`, etc. to understand what are the useful metrics that I should capture in my application; What is the unit of time in output of `getIoTimeRecursive`, etc
3. Is there a documentation on what does the different `op` object represents in [BlkioStatEntry](https://github.com/docker-java/docker-java/blob/main/docker-java-api/src/main/java/com/github/dockerjava/api/model/BlkioStatEntry.java#L45)? From the log it has `read, write, sync, async, discard, and total`, but having some sort of documentation on these values would help us simplify docker SDK for our use case

Any help related to documentation is much appreciated.
Thanks,
Umair

**Comment by iumairhasan** [comment]
While finding related documentation I stumbled upon linux related blkio docs - https://www.kernel.org/doc/Documentation/cgroup-v1/blkio-controller.txt

I wonder if docker sdk's `BlkioStatsConfig` follows same definitions

**Comment by eddumelendez** [comment]
Unfortunately, the [Docker engine API](https://docs.docker.com/reference/api/engine/version/v1.47/) doesn't provide that information either.
