### ISSUE TITLE
EventCallback::isReceiving()

### ISSUE THREAD

**Issue by yaronr** [docker-java/docker-java#237]
Hi

As documentation is missing and I didn't find any mailing list, I'm posting this here. I hope that's ok.
EventCallback::isReceiving() - what does it do? what happens if 'false'?
is it called per event, or once?
Can I return 'false' sometimes, when I don't want to receive events, and 'true' other times?

Thanks
Great project BTW

**Comment by marcuslinke** [comment]
`isReceiving()` is called per event. If `false` is returned by the callback it signals that it is not interested in receiving events anymore. The underlying `Inputstream` is closed  and reading thread is cancelled  then. There is no chance to switch back to receiving events anymore. 

The naming of the method name is somewhat suboptimal. Maybe this will change in a next release, so the callback has explicitely to call `close()` on an `Closeable` object passed while initialization.

**Comment by yaronr** [comment]
Thanks. Makes sense :)
BTW, while on the subject of documentation: Is there support for Docker labels?

**Comment by marcuslinke** [comment]
Labels are currently not supported. But hey, I'm open for a PR. ;-)

**Comment by yaronr** [comment]
I may actually pick that up. I like this project :)
Thanks M8
