### ISSUE TITLE
Auto exposed ports not working as expected

### ISSUE THREAD

**Issue by yaronr** [docker-java/docker-java#238]
```
Ports ports = new Ports();

 ports.bind(new ExposedPort(80), Ports.Binding(null));

CreateContainerCmd createCmd = dockerClient.createContainerCmd(...).....withPortBindings(ports).withPublishAllPorts(true)
```

...
docker ps
    PORTS
    80/TCP

I expected some mapping, like 0.0.0.0:2375->80/tcp

**Comment by yaronr** [comment]
Adding to that:
If I specify:
    Ports.Binding("0.0.0.0", null));

I get:
    0.0.0.0:0->80/tcp 

In other words, it does not pick a random port on its own.

**Comment by marcuslinke** [comment]
@yaronr This has to work as expected as there is a test case for it that successfully completes. Maybe you used some option of the start container command? In this case all configuration from create will be overridden.

**Comment by yaronr** [comment]
@marcuslinke 
This is my (almost) honest-to-god code :)

		Ports ports = new Ports();

		if (getServices() != null) {
			for (Service s : getServices()) {
				ports.bind(new ExposedPort(s.getPort()), Ports.Binding("0.0.0.0", null)); //i've tried all sorts of variations here
			}
		}

		CreateContainerCmd createCmd = dockerClient.createContainerCmd(getImage()).withEnv(getEnvVars()).withName(getName()).withCmd(getCmd()).withCpuShares(getCpuQuota()).withPortBindings(ports).withPublishAllPorts(true);

		CreateContainerResponse response = createCmd.exec();

		synchronized (containerToTask) {
			dockerClient.startContainerCmd(createCmd.getName()).exec();
			containerToTask.put(response.getId(), task);
		}

**Comment by marcuslinke** [comment]
The code looks good to me. Please take a look at https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L229

This works with docker v1.6.2:

```
> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                          NAMES
0b3b94c98213        busybox:latest      "sleep 9999"        5 hours ago         Up 7 seconds        0.0.0.0:32770->22/tcp, 0.0.0.0:32771->23/tcp   prickly_goldstine
```
Could you check the test code in your environment please?

**Comment by yaronr** [comment]
Ok, now it's working.
A few questions:

1) I assumed that it's not required to have both .withExposedPort and .withPortBindings. Can you please explain?
2) I also find .withPublishAllPorts unclear, in this context... is it equivalent to '-p' - and it publishes all ports defined in the dockerfile?

10x

**Comment by KostyaSha** [comment]
Had the same issues, maybe something is handled on docker-client side and docker-java should provide some helpers...
My experiments showed that you should manually define both, portspec and portbinding if you want expose port from running container. 
Docker cli has all the same as API options
```
 -P, --publish-all=false     Publish all exposed ports to random ports
 -p, --publish=[]            Publish a container's port(s) to the host
  --expose=[]                 Expose a port or a range of ports
```
Somebody should try compare behaviour...

**Comment by marcuslinke** [comment]
As I understand, exposed ports are configured in the Dockerfile normally but can be modified when creating a container from the image. So exposing ports is optional if the image already exposes the right ports. That corresponds to the CLI where `--expose` is not needed normally.

**Comment by KostyaSha** [comment]
but `--expose=10000` (additional port) + `-P` doesn't work AFAIR... will try experiment after release...

**Comment by kpnarayanan** [comment]
Hi,

I used the example in this link https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L229 to generate a mapping between container and host port however it does not work for me.

I want to have an output as shown in the comments described by Marcus Linke on June 6 2015.

In the code I have an exposed port and its respective bindings.  

May I kindly know how should I generate the following using the docker java client *0.0.0.0:port binding ->exposed port / tcp*? Any quick suggestions from the forum will be of help.

Thanks,
Krishnaprasad
