### ISSUE TITLE
Stats CMD - why is it async?

### ISSUE THREAD

**Issue by slnowak** [docker-java/docker-java#242]
I'm using 1.3.1-SNAPSHOT, which introduces StatsCmd. 

Could you please explain why the API for that command is async (or to be more specific - why is it derived from EventsCmdApi)? 

I've seen another pull request, by another guy - https://github.com/docker-java/docker-java/pull/227 and it's implemented in a synchronous way. 
It makes more sense to me - I've already tried merged version and no matter what, I'm only getting one statistics event. 
In such a case, all those callback methods like onCompletion, isReceiving are useless and the whole callback way only complicates the usage.

So, am I missing something? Could you please elaborate?
Oh, btw, here's the code snippet 
https://gist.github.com/slnowak/a9e26daaa566310b1cd4
onStats method executes exacly once, onCompletion executes always with 1.

As far as I know, to check statistics, you only need to perform GET on /containers/id/stats and it returns json result. How does it differ from, for example, performing GET on /contaiers and why there is a need for async here?

**Comment by marcuslinke** [comment]
After looking into this it seems you are right. There is a misleading description in the docker remote api documentation that says `This endpoint returns a live stream of a container's resource usage statistics.` Therefore both the creator of the stats implementation @patelrit (https://github.com/docker-java/docker-java/pull/189) as well as me as the reviewer assumed a streaming behavior here.

**Comment by slnowak** [comment]
Yeah, I know - I was reading docs yesterday, thought it's some kind of web socket stream or whatever.
Anyway - would you fix this?

**Comment by marcuslinke** [comment]
Sure I will fix it. But I'm a bit busy this week...

**Comment by slnowak** [comment]
There's no need to hurry, I will wait ;)
I may create a pull request to remove changes from https://github.com/docker-java/docker-java/pull/189 and apply https://github.com/docker-java/docker-java/pull/227 if you want, but I'm kind of busy also ;)

**Comment by slnowak** [comment]
Ok, there's one interesting case here - if container with given ID is stopped, then the rest call blocks and returns as soon as container is running again. 

So maybe there is a need for an async request, but I think not in the way it is implemented now. 
What do you think?

**Comment by marcuslinke** [comment]
One of the main goal of this callback-driven async API design was the ability to abort the processing of an infinitely streaming response (aka `Transfer-Encoding: chunked`) at any time. As the stats endpoint does no streaming at all i think it would be best to simplify the API in a synchronous manner.

**Comment by slnowak** [comment]
So maybe there should be at least check whether a container is stopped or not and if it is, an exception should be thrown?

**Comment by marcuslinke** [comment]
I do not like this idea as it demands an additional request to the remote api and wouldn't help if the container is stopped in between. In opposite to my statement above maybe it would be better to leave the callback logic then and just simplify the callback interface as you suggested?

**Comment by slnowak** [comment]
It will leave the interface with only one method, so I think returning a promise would more appropiate here, but this is only my opinion. 
I think people who use your library & docker more often than me should vote on it.

**Comment by marcuslinke** [comment]
Thanks for you input. Returning a promise/future prevents the client from aborting the (long running) operation. Thats why I would favor the callback solution.

**Comment by slnowak** [comment]
On the other hand, docker API doesn't protect you from retrieving stats on stopped container, it just blocks. So maybe a library should behave exactly the same and just mention it in docs? But I don't like the idea to be honest.

Oh, and one last thing: what do you mean by saying "Returning a promise/future prevents the client from aborting the (long running) operation. "? I don't get it ;_:

Thanks

**Comment by marcuslinke** [comment]
Ehm... Forget about it. Seems I was confused yesterday...  So the remaining argument for the callback based `stats` API is to have similar APIs for different commands (`stats` & `events` command).

FYI: The `log` and `attach` commands needs to be refectored to provide a callback-driven API also as the reponses may streamed infinitely in some use cases.

**Comment by marcuslinke** [comment]
New API will be introduced with the next release ( > 1.4.0).
