### ISSUE TITLE
Refactor primitive type fields to be of object type in JSON request objects

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#246]
... otherwise there could be submitted wrong values for untouched fields.

**Comment by KostyaSha** [comment]
And the same for Integer and all field with initialisers like https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/CreateContainerCmdImpl.java#L51 ? Btw where `@JsonIgnore` must be set and where not?

**Comment by marcuslinke** [comment]
Already fixed. See #313
