### ISSUE TITLE
FrameReader has problems when Buffer is only partially filled

### ISSUE THREAD

**Issue by chrisphe** [docker-java/docker-java#252]
On some platforms (e.g. Windows), the Stream IO means the buffer is not completely filled on the first read. The behaviour should be modified to check if the buffer is partially filled for header or frame and allow the buffer to fill completely before processing it.

**Comment by chrisphe** [comment]
Patch https://github.com/docker-java/docker-java/pull/251

**Comment by alexec** [comment]
Merged.

**Comment by chrisphe** [comment]
Thanks for the quick response. Regards Chris
