### ISSUE TITLE
Support for attaching Stdin when execStart

### ISSUE THREAD

**Issue by missedone** [docker-java/docker-java#253]
Hi folks

in my case, i'd like to execture a block of bash scripts when 'docker exec', the way to approach that, i think, is to attach stdin, and send the block of bash scripts through the output stream.

but i find execStart only return an inputStream, there is noway to send data when execStart.

so could you implement this, or is there any other way to workaround this?
thanks

**Comment by missedone** [comment]
looks like spotify/docker-client has the similar issue: https://github.com/spotify/docker-client/issues/156
as using apache httpclient while it does not support hijacking, and i don't see any plan that when will httpclient support websockets/hijacking

**Comment by zhaopengme** [comment]
@missedone 我也遇到这样的问题了,你现在有没有什么思路呢?考虑过用ws吗?

**Comment by missedone** [comment]
for docker execStart API call, i just created a quick and dirty http hijacking with java.net.Socket:
https://gist.github.com/missedone/76517e618486db746056

here is a simple usage:
```
        ExecCreateCmdResponse execCreateResp = dck.execCreateCmd(cid).withCmd("bash")
                .withAttachStderr().withAttachStdout().withAttachStdin().withTty(false).exec();

        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");

        HttpHijack ws = new HttpHijack(new URI("http://127.0.0.1:2376/v1.19/exec/" + execCreateResp.getId() + "/start"));
        String payload = "{\"Detach\": false,\"Tty\": false}";
        ws.post(headers, payload);

        String request = "date > /tmp/nick2; cat /tmp/nick2; exit $?;";
        InputStream input = ws.send(request);

        Thread.sleep(3000);
        InspectExecResponse execResp = dck.inspectExecCmd(execCreateResp.getId()).exec();
        log.info("exec inspect: {}", execResp);

        String response = IOUtils.readLines(input).toString();
        log.info(response);
```

i will refactor the code to be more production ready later

**Comment by marcuslinke** [comment]
Thanks for investigating! I'm curious if and how this will integrate with current codebase.

**Comment by missedone** [comment]
@marcuslinke
i take this code as prototype, not perfect, i would like to think more on the http hijack impl, will consider the integration with docker–java later

**Comment by marcuslinke** [comment]
FYI: Meanwhile I experiment with netty as foundation framework (https://github.com/docker-java/docker-java/tree/netty). Currently most features are implemented now like UNIX sockets, SSL/https and of course http hijacking that is needed for passing STDIN to the container. All existing tests passed successfully but still some needed features are missing namely http(s) proxy support and automatic redirection (and maybe some more). 

@KostyaSha After this is done I plan to merge into master as alternative `DockerCmdExecFactory` implementation, so users might use (and test) it. WDYT?

**Comment by KostyaSha** [comment]
@marcuslinke @bsideup has some view point about rx/reactive java. Let's wait for his comments for netty branch.

**Comment by marcuslinke** [comment]
Closing this as of merging https://github.com/docker-java/docker-java/pull/397
