### ISSUE TITLE
Add LogConfig attribute on create container

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#255]
Add LogConfig attribute on create container

**Comment by KostyaSha** [comment]
Please provide links to documentation for requested options

**Comment by lordofthejars** [comment]
https://docs.docker.com/reference/api/docker_remote_api_v1.19/ on Create A Container Section, Example Request.

**Comment by marcuslinke** [comment]
see https://github.com/docker-java/docker-java/issues/218
