### ISSUE TITLE
Add SecurityOpt attribute on create container

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#256]
Add SecurityOpt attribute on create container

**Comment by KostyaSha** [comment]
still missing :( In what API version does it appeared?

**Comment by lordofthejars** [comment]
At docker remote 1.18 was already there.

**Comment by labkey-matthewb** [comment]
Is there a work-around?  Is there a generic "withOption()" or something like that?

**Comment by KostyaSha** [comment]
PR with test case will be welcome

**Comment by tdudgeon** [comment]
This indeed would be useful. 
For instance, to mount the docker socket in a selinux environment you need to use the --security-opt option. See https://danwalsh.livejournal.com/74095.html

In the meantime is there a workaround to allow this?

**Comment by bsideup** [comment]
See `HostConfig#securityOpts`
