### ISSUE TITLE
withHostConfig should not override instance

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#258]
Currently if you call withHostConfig method (https://github.com/docker-java/docker-java/blob/9b29ba736a9f5a3c799337b20e4f0d5d1dcd2d3c/src/main/java/com/github/dockerjava/core/command/CreateContainerCmdImpl.java#L450) you are unsetting previous values. Since you can set then directly from CreateBuilder or withHostConfig it seems not a good decision to override them so I suggest that instead of overriding it simply appends.

The other option is that all options that appear from hostconfig can be also set from Container builder. For example readOnlyRootFs cannot be set

**Comment by marcuslinke** [comment]
So the best option is to remove the `withHostConfig` method while introducing all host config related options at the root level.

**Comment by lordofthejars** [comment]
well I would say standardize the way, if you think that removing withHostConfig is the easier way then it is ok, but at least if two options are offered then they should be consistent with output. Of course removing one of the options is the best way to avoid this problem.

**Comment by marcuslinke** [comment]
https://github.com/docker-java/docker-java/pull/272
