### ISSUE TITLE
Ability to specify connect timeout in DockerClientConfig

### ISSUE THREAD

**Issue by dmironenko** [docker-java/docker-java#265]
Please add ability to set connect timeout in DockerClientConfig

**Comment by KostyaSha** [comment]
Duplicates #72 ?

**Comment by marcuslinke** [comment]
See https://github.com/docker-java/docker-java/pull/282

**Comment by marcuslinke** [comment]
Implemented now in v.2.0.0. See https://github.com/docker-java/docker-java/wiki#intialize-docker-client-advanced

**Comment by dmironenko** [comment]
great! thanks
