### ISSUE TITLE
Concurrent DockerCmdExecFactory.getDefaultDockerCmdExecFactory fails on reload

### ISSUE THREAD

**Issue by Kindrat** [docker-java/docker-java#266]
When you try to create Docker client concurrently it's possible to get RuntimeException in getDefaultDockerCmdExecFactory method when one thread has already checked that iterator is not empty, and other calls serviceLoader.reload(). First thread reuses invalidated iterator and fails.

**Comment by marcuslinke** [comment]
Merged https://github.com/docker-java/docker-java/pull/268
