### ISSUE TITLE
No method available to check container is present or not

### ISSUE THREAD

**Issue by rohitkadam19** [docker-java/docker-java#274]
I can get all the containers and from those I can check if particular container is available or not.
I am not able to find any method which will return true/false if container is available.
This is more like enhancement request.
I am using docker-java 1.4.0 and docker 1.7.0.

**Comment by marcuslinke** [comment]
You could try to inspect the container. If the container doesn't exist a `NotFoundException` is thrown.

**Comment by rohitkadam19** [comment]
Yes, currently using the same way.
