### ISSUE TITLE
buildImageCmd fails for some reason

### ISSUE THREAD

**Issue by timur87** [docker-java/docker-java#276]
I create a tar from images using .withImageStream and from this .tar, I try to build image again using .buildImageCmd. However, the operation fails with "Cannot locate specified Dockerfile: Dockerfile" exception although I pass an InputStream.

**Comment by marcuslinke** [comment]
To build an image with `.buildImageCmd` you need a Dockerfile in place. I don't know what you mean with "create a tar from images using .withImageStream". Post some example code that illustrates what you are trying to achive please.

**Comment by timur87** [comment]
Thanks for the response! I was hoping to execute the following by executing that command:  "Load a tarball with a set of images and tags into docker" [1]

But I noticed that this is a different command and probably the load request ist not supported yet. Right? I want to extract somehow the image or a Dockerfile of a image and then rebuild it from that image in another container using the Java API. Can you think of any other ways of achieving this? 



[1] https://docs.docker.com/reference/api/docker_remote_api_v1.19/#load-a-tarball-with-a-set-of-images-and-tags-into-docker

**Comment by marcuslinke** [comment]
Sorry, loading images from a tarball is currently not implemented yet, as it is a rare usecase. I wonder what you are trying to achieve. Typically an image is pushed to a registry and can be pulled from everywhere right after that so there is no need to export and import images normally.
