### ISSUE TITLE
Slow performance on buildImageCmd()

### ISSUE THREAD

**Issue by mkuzmin** [docker-java/docker-java#283]
I'm a user of [Docker plugin for Gradle](https://github.com/bmuschko/gradle-docker-plugin), which relies on your library.

I've met a performance issue in my Gradle build (https://github.com/bmuschko/gradle-docker-plugin/issues/88), but can also reproduce it calling your library directly.

My Dockerfile is minimal:
```
FROM java:jre
ADD TeamCity/ /opt/teamcity-server/
```
But a content of the directory is rather large: it's *over 2000 files, 600 Mb* in common.

Calling Docker build from a command line takes about 2-3 minutes, and produces 10-30% of CPU workload.

Running the same build using docker-java takes over 20 minutes, and loads CPU for 85-100%.

Here is a Groovy script which reproduces the issue: https://gist.github.com/mkuzmin/6d675411bf668e46d800#file-docker-java-groovy

An here is a stack dump: 
https://gist.github.com/mkuzmin/6d675411bf668e46d800#file-groovy-stack-dump-txt

I'm using:
Ubuntu 14.04
OpenJDK 1.7.0_79
Docker 1.7.1

**Comment by marcuslinke** [comment]
Thanks for reporting. But to reproduce it locally it needs a build context comparable in size and number of files. Would it be possible for you to provide the compressed `TeamCity` folder somewhere?

**Comment by marcuslinke** [comment]
Hmmm. Maybe docker-java doesn't compress the build context before uploading...

**Comment by marcuslinke** [comment]
OK. The build context was uploaded uncompressed until now. I've created a branch which fixes this and introduces GZIP compression (https://github.com/docker-java/docker-java/tree/issue-283). Would it be possible for you to test with this branch please?

**Comment by mkuzmin** [comment]
Thank you for so rapid response!

I've tested that out. The performance is much better, but now my Gradle build fails with `NullPointerException` ([stacktrace](https://gist.github.com/mkuzmin/6d675411bf668e46d800#file-stacktrace-pr284-txt)). That may be а backward-incompatible change in your PR, or a bug in gradle plugin code. I've [asked](https://github.com/bmuschko/gradle-docker-plugin/issues/88#issuecomment-125885036) @bmuschko to look into that.

**Comment by KostyaSha** [comment]
```
Caused by: java.lang.NullPointerException
        at com.bmuschko.gradle.docker.response.image.BuildImageResponseHandler.handle(BuildImageResponseHandler.groovy:33)
```

**Comment by marcuslinke** [comment]
Closing as I merged the fix into master now.
