### ISSUE TITLE
"Dockerfile is excluded by pattern" error seems incorrect

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#286]
I have a .dockerignore file that includes the following:

```
*
!Dockerfile
```

But I am getting an error message:

```Dockerfile is excluded by pattern '*' on line 1 in .dockerignore file```

However, my reading of the docker docs (https://docs.docker.com/reference/builder/#dockerignore-file) indicates that this should be ok, in particular:

> The placement of ! exception rules influences the matching algorithm; the last line of the .dockerignore that matches a particular file determines whether it is included or excluded.

Additionally, the docs go on to say

> You can even use the .dockerignore file to ignore the Dockerfile and .dockerignore files. This is useful if you are copying files from the root of the build context into your new container but do not want to include the Dockerfile or .dockerignore files (e.g. ADD . /someDir/).

**Comment by wenzowski** [comment]
Hey @marcuslinke it looks like you solved for the `!Dockerfile` use case, but missed the full scope of this bug –

The Docker docs say
> You can even use the .dockerignore file to ignore the Dockerfile and .dockerignore files. This is useful if you are copying files from the root of the build context into your new container but do not want to include the Dockerfile or .dockerignore files (e.g. ADD . /someDir/).

Was that an intentional choice to create divergent functionality in `docker-java`, or did you miss the fact that a `Dockerfile` may be validly excluded by a `.dockerignore` file?

**Comment by KostyaSha** [comment]
@wenzowski please feel new issue if you have any problems

**Comment by wenzowski** [comment]
@KostyaSha Did not want to open an issue if the choice was deliberate; happy to do so if that fits process of this project
