### ISSUE TITLE
Build FROM private registry broken with docker 1.7.x 

### ISSUE THREAD

**Issue by marcust** [docker-java/docker-java#288]
I initially reported that against Docker 1.7.0 itself as https://github.com/docker/docker/issues/14092 but apparently they just fixed their own client in 1.7.1. As docker-py fixed that themselfes (https://github.com/docker/docker-py/commit/f8ad2dabf21be0d3c07e7d289fb09fb4d93de9a4) the correct way actually seems to be to fix that in docker-java itself. I spoke to @vdemeester on IRC and he said that it is more or less expected behaviour.

(Ping @alexec just that you know that orchestration and maven-plugin currently broken for docker 1.7.x and private registries)

**Comment by marcuslinke** [comment]
So actually I'm a bit lost of what has been changed here concretely. In my understanding basically its a change of the structure of the X-Registry-Config JSON object, right?

Old format:

```
{
   "configs":  {
      "https://index.docker.io/v1/": {
            "username": "",
            "password": "",
            "email": "",
            "serveraddress": "",
            "auth": ""
      }
   }
}
```
New format:
```
{
   "https://index.docker.io/v1/": {
         "username": "",
         "password": "",
         "email": "",
         "serveraddress": "",
         "auth": ""
   }
}
```

**Comment by gesellix** [comment]
afaik it's a change in the local config files.

old format (`~/.dockercfg`):

```
{
  "https://index.docker.io/v1/": {
      "auth": "-base64-encoded-username:password-",
      "email": "foo@example.com"
  }
}
```

new format (`~/.docker/config.json`):

```
{
  "auths": {
    "https://index.docker.io/v1/": {
        "auth": "-base64-encoded-username:password-",
        "email": "foo@example.com"
    }
  }
}
```

**Comment by marcuslinke** [comment]
OK, so config file format and location has changed but what I try to understand is what has been changed in the X-Registry-Config header. Looking at https://github.com/docker/docker-py/commit/f8ad2dabf21be0d3c07e7d289fb09fb4d93de9a4 they just removed the "configs" wrapper.

**Comment by gesellix** [comment]
ah yes, now I'm confused, too...

**Comment by marcuslinke** [comment]
Now that I've reproduced the issue as integration test it seems just removing the "configs" wrapper element off of the X-Registry-Config header works at least with registry v2. Will provide a fix soon.
