### ISSUE TITLE
Push images with dash in image namespace name

### ISSUE THREAD

**Issue by HelmutZechmann** [docker-java/docker-java#290]
Hi, 

I am using the [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) which is based on this library.

Using the plugin I observe the following problem (see [issue 93](https://github.com/bmuschko/gradle-docker-plugin/issues/93)):

When I try to push an image with a dash in the namespace name using DockerPushImage, I get the following error message:

    Invalid namespace name (cdh-images), only [a-z0-9_] are allowed, size between 4 and 30

The follwoing does not work:

    task pushWithDatasetManagementImage(type: DockerPushImage) {
        imageName '<repository-ip>:5000/cdh-images/dashes-are-allowed-here'
    }

This works:

    docker push <repository-ip>:5000/cdh-images/dashes-are-allowed-here
This works:

    task pushWithDatasetManagementImage(type: DockerPushImage) {
        imageName '<repository-ip>:5000/cdh_images/dashes-are-allowed-here'
    }

[bmuschko](https://github.com/bmuschko) commented the issue with:

    The error message is triggered by the underlying Docker Java library.

**Comment by marcuslinke** [comment]
Related: https://github.com/docker-java/docker-java/issues/182

**Comment by KostyaSha** [comment]
seems i also hit it, though name/tag repository parsers are not obviously implemented.
@marcuslinke maybe review abstractions?

**Comment by marcuslinke** [comment]
@KostyaSha I'm currently trying to fix the issue first. After that (and adding appropriate tests for `NameParser`) a review/refactoring of the image name abstracting classes like `NameParser`, `Identifier`, `Repository` is needed i think.

**Comment by marcuslinke** [comment]
FYI: This is what I've found about repository name validation in docker so far: https://github.com/docker/distribution/blob/master/registry/api/v2/names.go
