### ISSUE TITLE
Updates to Remote API 1.20 copy operations

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#292]
Recently the Docker Remote API 1.20 has been released . Basically it changes the way the files are copied from host to container and also from container to host:

V1.20 What's new: https://docs.docker.com/reference/api/docker_remote_api/

**Comment by igorspasic** [comment]
There is v1.21 already https://docs.docker.com/reference/api/docker_remote_api_v1.21/

**Comment by marcuslinke** [comment]
Fixed via https://github.com/docker-java/docker-java/pull/347
