### ISSUE TITLE
Refactor/review handling of registry names

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#300]
The current classes responsible for registry name parsing/validating namely `NameParser`, `Identifier`, `Repository` and so on needs to be reviewed/refactored. Ideally we can create a (simple) object model for that purpose.

**Comment by marcuslinke** [comment]
Maybe @jgriffiths1993 work (https://github.com/jgriffiths1993/docker-java/commit/bfde13452a7b621bd68429017a63c2f07a85d39f) wil be useful

**Comment by KostyaSha** [comment]
it what i mean :) afair @jgriffiths1993 tried contribute such things into docker-plugin but it was delayed...

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/pull/202

**Comment by KostyaSha** [comment]
This becomes critical as i want implement in Auth support for pulls from registry in my docker plugin.
I think we need place `DockerImageFullName` under Utils that will have all parse options. Imho it should store:
- registry URI
- namespace
- image name
- tag 
- digest? never used them

Unspecified, but expected by docker client values should provide effective/real getters because Auth against docker-hub is default URI and `library` is default namespace.

Then related docker-java objects can support this class as additional setter.

@marcuslinke wdyt?

**Comment by KostyaSha** [comment]
Example of docker-java independent realisation https://github.com/jenkinsci/docker-commons-plugin/blob/master/src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java#L74-L84

**Comment by marcuslinke** [comment]
The problem with this class would be that it can't be used anywhere. Some commands  let you pass only image-Id or image-name for example because other things like tag and registry URI are not relevant/needed for it. I don't like the idea to pass this `DockerImageFullName` object to those commands. So the best would be to have classes for all fragments of `DockerImageFullName`. So we need `RegistryURI`, `Namespace`, `ImageIdentifier`, `Tag`and `Digest' i think. Does it make sense?

**Comment by KostyaSha** [comment]
@marcuslinke doesn't content of this objects overlap between each other?

**Comment by marcuslinke** [comment]
Sorry, what do you mean. Could you provide an example?

**Comment by KostyaSha** [comment]
`Identifier` contains     
```
public final Repository repository;
public final Optional<String> tag;
```
Repository contains (why it appends http?):
```
public class Repository {
    public final String name;
    public URL getURL() throws MalformedURLException {
        return new URL("http://" + name); 
    }
}
```

**Comment by KostyaSha** [comment]
Yes, having setters for more wider object can be bad, i can use library in the next way, parse once user entered image into Object and then get needed for API methods pieces of info from this wrapper object. 

M.. and there is a `NameParser`...
I will try sketch object and PR in a few minutes.

**Comment by KostyaSha** [comment]
Filled https://github.com/docker-java/docker-java/pull/364

**Comment by KostyaSha** [comment]
As i see `NameParser` with `ReposTag` and `HostnameReposName` is used only for `com.github.dockerjava.core.DockerClientConfig#effectiveAuthConfig`
