### ISSUE TITLE
NPE in callback routines

### ISSUE THREAD

**Issue by black20000** [docker-java/docker-java#302]
In some callback functions there is a bug which causes an NPE if an error occurs during command execution. E.g. in PushImageResultCallback.java:43

        if (latestItem == null || latestItem.isErrorIndicated()) {
            throw new DockerClientException("Could not push image: " + latestItem.getError());
        }

If latestItem is null, the subsequent call to latestItem.getErrror() throws an NPE.

Similar bugs are in these classes:
BuildImageResultCallback.java
PullImageResultCallback.java
PushImageResultCallback.java

**Comment by marcuslinke** [comment]
If `lastItem` is null the second condition is not evaluated.

**Comment by KostyaSha** [comment]
@marcuslinke 
```
if (latestItem == null )) {
        throw new DockerClientException("Could not push image: " + latestItem.getError());
    }
```

**Comment by marcuslinke** [comment]
Sorry, I was in a hurry so I overlooked it. Thanks for reporting!
