### ISSUE TITLE
Exception on execution may be lost

### ISSUE THREAD

**Issue by black20000** [docker-java/docker-java#303]
In class AbstrSyncDockerCmdExec there is a finally block which throws an exception. This could hide an exception which is thrown in the try block, in case the close statement throws an error.

        } finally {
            try {
                command.close();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

The original exception must not lost

**Comment by marcuslinke** [comment]
It doesn't hide the original exception as it is wrapped in a `RuntimeException`. So whats the problem with this?

**Comment by KostyaSha** [comment]
@marcuslinke  try {} may raise error , but finally executed nevertheless and it has also throw.

**Comment by marcuslinke** [comment]
Hmmm. OK, now I got it. But I wonder how to solve this problem. The `command.close()` must be called definitely.

**Comment by marcuslinke** [comment]
Command could implement `AutoCloseable` and then implement it via `try-with-resource`...

**Comment by KostyaSha** [comment]
@marcuslinke as usual
```
Stream stream = null;
try {
   stream = new Stream();
} catch () {
some logic
 } finally() {
 if (stream != null) {
  stream.close();
}
```
Don't care about IOException as it remote library and any call may raise it

**Comment by black20000** [comment]
You should care about IOException when closing the stream. Else the same happens as in the current situation (IOException of close will be thrown to the caller)

    Stream stream = null;
    try {
       stream = new Stream();
    } catch () {
    some logic
     } finally() {
     if (stream != null) {
      try {
        stream.close();
      } catch (IOException) {
        // log it, but don't throw exceptions
      }
    }

**Comment by KostyaSha** [comment]
@black20000 if exception appeared, then you can't trust to this stream, imho any IOException should be reported to client.

**Comment by KostyaSha** [comment]
Or seems it really need to be suppressed https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
