### ISSUE TITLE
Incorrect kill event received

### ISSUE THREAD

**Issue by yaronr** [docker-java/docker-java#309]
Hi

I'm listening on Docker events, and receiving a kill event immediately after starting a container through docker-java:
com.github.dockerjava.api.model.Event@33d0248a[status=kill,id=0d81ab45dfa0e5348c2fcff53f1f3dd420bc7389cc7234fede09c614a42df34d,from=yaronr/elasticsearch,time=1440490502,node=<null>]

However, this is a 'false event', since the container is up and running.

(Am I possibly misunderstanding what 'kill' event means?)

BTW. When a container is killed (docker kill), will there be a kill + stop events? or just kill?

Docker version 1.7.1
docker-java 2.0.0 and 2.0.1

**Comment by marcuslinke** [comment]
@yaronr Could you please check whether the same counts for the docker CLI? `docker-java` is just passing the events coming from the docker remote API so it should behave the same as the CLI.

In my understanding the different event types reflecting the various  remote API calls, so `kill` events will be sent when `kill container` is called and `stop` events occurs if `stop container` is called. Following this logic `docker kill <container>` should produce `kill` event only.

**Comment by marcuslinke** [comment]
FYI: You may get unexpected events in the case of time differences between client and docker host especially when you query events within a limited time range. This was causing issues with the integration tests at least.
