### ISSUE TITLE
allow specific ssl key/cert to be specified

### ISSUE THREAD

**Issue by fawaf** [docker-java/docker-java#311]
allow specific ssl key/cert to be specified in addition to just using the docker cert path.

**Comment by KostyaSha** [comment]
Oops, i created duplicated issue #367 :(

**Comment by KostyaSha** [comment]
@gnowxilef let's move discussion to #367

**Comment by gnowxilef** [comment]
this issue is different from #367 i think. this refers specifically to specifying the actual path to the ssl cert/key. unless i don't understand what your issue is referring to.

**Comment by KostyaSha** [comment]
@gnowxilef sorry, what kind of ssl certs and for what they are required?

**Comment by gnowxilef** [comment]
the cert and key is for the communication between the client and the server. they are normal x509 certs/key pairs.

**Comment by gnowxilef** [comment]
more specifically, currently, only a cert path can be specified, and the code assumes that the cert is located at `cert.pem`, the key at `key.pem`, and the ca at `ca.pem`.

**Comment by KostyaSha** [comment]
But it expected by docker-client format? What is your use case with using other cert names?

**Comment by gnowxilef** [comment]
afaik, the docker client supports specifying the exact path to what cert/key you want to use. (e.g. `docker --tlscacert=/opt/docker/custom-ca.pem --tlscert=/opt/docker/somecert.pem --tlskey=/opt/docker/somekey.pem blah ...`)

**Comment by gnowxilef** [comment]
different cert names means that we can name the cert/key by fqdn, for example, so we know exactly what that cert would be, instead of having to look at the contents of `cert.pem` to determine what CN it contains.

**Comment by bsideup** [comment]
See `SSLConfig#getSSLContext`
