### ISSUE TITLE
Wiki error

### ISSUE THREAD

**Issue by MarcoLotz** [docker-java/docker-java#312]
on the Line:
ContainerCreateResponse container = dockerClient.createContainerCmd("busybox")
   .withCmd("touch", "/test")
   .exec();

Should be:
CreateContainerResponse container = dockerClient.createContainerCmd("busybox")
   .withCmd("touch", "/test")
   .exec();

I was unable to fork the wiki to solve it.

**Comment by marcuslinke** [comment]
Thanks for reporting! Fixed.
