### ISSUE TITLE
incompatible with docker 1.8.1 .docker/config.json file format

### ISSUE THREAD

**Issue by josephlbarnett** [docker-java/docker-java#316]
docker 1.6.2 stores auth information in ~/.dockercfg file in the following format:

{ "<remote-url-name>": {"auth": "<authtoken>", "email": "email@address.com"}}

but docker 1.8.1 stores it in ~/.docker/config.json in the following format:

{"auths": { "<remote-url-name>": {"auth": "<authtoken>", "email": "email@address.com"}}}

docker-java can't parse the latter form even when pointed at the file via DOCKER_CFG_PATH env variable, and so can't authenticate to secure remote repositories

**Comment by jbarnettwomply** [comment]
seems that something is also different in the format of the auth token itself -- making a copy of the file and removing the top level "auths" element results in docker-java sending an X-Registry-Config header, but:
1) the header is different than one sent from a docker 1.6.2-created ~/.dockercfg file, and I get 403 errors when trying to pull images from a secure quay.io repo
2) even if I point docker-java at the 1.6.2-created ~/.dockercfg, and it sends the same header, i still get a 403

my docker 1.6.2 install is on an ubuntu machine doing an apt-get install from the wily universe repository, and my docker 1.8.1 is a mac machine running docker-machine/docker toolbox.  not sure if there are other platform-specific issues preventing this from working?

**Comment by marcuslinke** [comment]
Currently docker-java supports reading of old fashioned docker v1.6.2 `~/.dockercfg` file format but sends docker 1.8.1 compatible `X-Registry-Config` header.

**Comment by marcuslinke** [comment]
Maybe reading from config files like `~/.dockercfg` or `~/.docker/config.json` should be dropped as it seems out of scope of docker-java. As docker-java is just a docker remote API client library and NOT a docker CLI implementation support for reading and writing of CLI config files is questionable.

**Comment by jbarnettwomply** [comment]
Would you scope the actual auth config as part of docker-java or part of any application using it then?  ie, should alexec's maven plugin provide docker-java with auth info that it stores in maven-land (probably in ~/.m2/settings.xml), or should docker-java have its own config for auth?

**Comment by marcuslinke** [comment]
docker-java should only provide programmatic API for passing `AuthConfigurations` object to the appropriate commands. Reading and writing from/to config files should be handled externally.

**Comment by KostyaSha** [comment]
> docker-java should only provide programmatic API for passing AuthConfigurations object to the appropriate commands. Reading and writing from/to config files should be handled externally.

But library can provide some helper utils :)

**Comment by marcuslinke** [comment]
That might make sense ;)

**Comment by marcust** [comment]
Maybe splitting up the actual client and helper classes into different projects would make sense, this way it's easier to version both in case only the docker cli changes and not the daemon, as it happened in the past.

**Comment by llamahunter** [comment]
It would be really useful if docker-java could also read the newer .docker/config.json file if it exists.  That way, it would be easier for devs to move between command line and docker-java based tools.

**Comment by zifik** [comment]
Can this be done sooner than later? It's a real bugger trying to use latest of docker with private repo.

https://github.com/docker-java/docker-java/issues/806

**Comment by aitorpazos** [comment]
> It would be really useful if docker-java could also read the newer .docker/config.json file if it exists. That way, it would be easier for devs to move between command line and docker-java based tools.

I think it totally make sense to get a common behavior among different tools in one particular environment. Otherwise, what you get is multiple tools and libraries behaving differently. Chances are that you end up combining the usage of docker-java and docker CLI in pipelines and during DEV work.

I think AWS CLI and libraries are a good example for this. They all follow the same approach regarding which environment variables they read, what files they read and what the precedence order is.
