### ISSUE TITLE
How do I stream the output of a docker pull with 2.1.0?

### ISSUE THREAD

**Issue by frankscholten** [docker-java/docker-java#317]
First of all great work on docker-java! We use docker-java in [Mini-Mesos](https://github.com/ContainerSolutions/mini-mesos) extensively.

We are considering upgrading to 2.1.0 and ny question is how do I get the output from a docker pull using the new event API. We currently use this kind of code

```
InputStream responsePullImages = dockerClient.pullImageCmd(imageName).withTag(registryTag).exec();
ResponseCollector.collectResponse(responsePullImages);
```

where ``ResponseCollector`` is a little util for logging the stream contents.

Thanks!

**Comment by marcuslinke** [comment]
You have to inherit `PullImageResultCallback`, override `onNext(...)` method with your logging code and pass the callback to the `exec(...)` method of the `PullImageCmd`. The call to `exec(...)` is non-blocking now and returns the callback instance you have passed in. At the callback instance you can call `awaitSuccess()` if you want to wait for successful pull.

```
client.pullImageCmd(image).exec(new PullImageResultCallback {
   public void onNext(PullResponseItem item) {
      super.onNext(item);
      // your logging code goes here
   }
}).awaitSuccess();
