### ISSUE TITLE
SSL Folder bottleneck

### ISSUE THREAD

**Issue by MarcoLotz** [docker-java/docker-java#318]
Even with SSL disabled, the existence of a folder with certificates on ~/[user name]/.docker increases the dockerClient initialization time on more than 350ms. This should not happen is SSL connection is disabled.

Currently I am experiencing 1,5 seconds average for startup with the folder, should I change it to .old.docker, the time decreases to 1,15 seconds.

I am not able to reduce the startup time to make it less than a second. is there any way to do it?
Looks like the python API runs faster than this, that's why I am wondering if there's anything else that should be done.

**Comment by MarcoLotz** [comment]
Making some benchmarks, looks like the static method on the DockerClientBuilder class consumes literally half of the time when creating a docker client. This is due to the iterable - probably because it is a lazy iterator, but I am not sure about this.

docker-java API:
static reload = 0 ms.
static iterates = 253 ms.
static total= 253 ms.

Docker java spent on getInstance(): 111 ms.
Docker java spent on build(): 259 ms.
Client init time: 626 ms.

The time for other APIs (on other languages and java) is less than 300ms. How can we improve the speed on docker-java?

**Comment by KostyaSha** [comment]
@MarcoLotz could you run under some performance analysing tool?

**Comment by MarcoLotz** [comment]
@KostyaSha Any (free) one of preference? I can try to run it here. I am accessing both localhost and a remote host - running also docker-java on two machines that are not in the same network - and am having the same performance on both clients.

Taking a close look, maybe would be interesting to change that java.serviceloader() call
more info on: http://stackoverflow.com/questions/7039467/java-serviceloader-with-multiple-classloaders

**Comment by KostyaSha** [comment]
AFAIR https://www.ej-technologies.com/products/jprofiler/overview.html has 30 days, create minimal code for initialisaing docker-java connection and then analyse results.

**Comment by marcuslinke** [comment]
If the service loader stuff is really the cause we might remove it hence there is currently (and probably will be) only one implementation. As I remember this was introduced in preparation of having multiple ones but later this idea was abandoned.

**Comment by MarcoLotz** [comment]
Found a nice solution for it :)
Reduces the time from 300 ms to 24 ms (leaving the bottleneck only on the build() and getInstance() time). This reduces the time to half.
Need to add import org.apache.xbean.finder.ResourceFinder tho.

Should you approve this modification, I will make the commit and change the pom for it.


ResourceFinder finder = new ResourceFinder("META-INF/services/");
        
        try {
			
        	List impls = finder.findAllImplementations(DockerCmdExecFactory.class);
			for (Object factory : impls)
			{
				factoryClass = (Class<? extends DockerCmdExecFactory>) factory;
			}
			stop = System.currentTimeMillis() - start;
			System.out.println("static iterates = " + stop);
			        
			System.out.println("static total= " + (System.currentTimeMillis()-startTotal));
			        
		} catch (ClassNotFoundException | IOException e) {
			throw new RuntimeException("Fatal: Cannot find '" + DockerCmdExecFactory.class.getName() + "' on META-INF/services/");
		}

**Comment by marcuslinke** [comment]
Thanks for the investigations, but I don't want to add apache xbean dependency just for this purpose. As I already stated we currently do not need the dynamic class loading so I would rather remove it.

**Comment by MarcoLotz** [comment]
You are totally right. I've run a few other checks after and although the time on this section of the code reduces, the getInstance() on DockerClient takes a lot longer - due to a newInstance() call. Hopefully I will run jprofiler today and provide more info. Just wondering, in your machine current settings - how long is it taking to build a DockerClient with:

```
DockerClient dockerClient = DockerClientBuilder.getInstance("http://127.0.0.1:23785").build();
```
and to get Info?

```
Info dockerJavaInfo = dockerClient.infoCmd().exec();
```

**Comment by KostyaSha** [comment]
@MarcoLotz any updates?

**Comment by marcuslinke** [comment]
Closed because of https://github.com/docker-java/docker-java/issues/349
