### ISSUE TITLE
Invalid maven test run

### ISSUE THREAD

**Issue by Kindrat** [docker-java/docker-java#319]
Have anyone tried running tests with maven? Should there be something more complex, than simple `mvn clean test` ? Docs include only -DskipTests recommendations.

Just asking, because I get

    Exception in thread "main" java.lang.NoClassDefFoundError: org/testng/CommandLineArgs
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:118)

during test run, and it seems, testng version is very outdated...

**Comment by marcuslinke** [comment]
I usually do `mvn clean install` which works without a problem here.

**Comment by Kindrat** [comment]
Seems like some cache problem in maven. Sorry. But nevertheless, mb it is worth to update dependencies? I may commit and send pull request.

**Comment by KostyaSha** [comment]
@Kindrat please provide full output, command and it's output

**Comment by Kindrat** [comment]
It's building now without NoClassDefFoundError.

**Comment by marcuslinke** [comment]
Great. Could you say something about the reason?

**Comment by Kindrat** [comment]
Seems like maven cache problems. It was saying class does not exist in testng < 6.0.

**Comment by marcuslinke** [comment]
OK, so closing this now.
