### ISSUE TITLE
jackson marshalling exception with ResponseItem.ProgressDetail

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#322]
I'm getting the following exception with version 2.1.0 of docker-java

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "start" (class com.github.dockerjava.api.model.ResponseItem$ProgressDetail), not marked as ignorable (2 known properties: , "total", "current"])

Looking at the code, it appears the fields are annotated with 'ignoreUnknown = false', yet there seems to be an unknown 'start' field coming back from the docker registry.  Our registry is artifactory, btw, not the docker-registry or docker.io, so it may be sending back some extra fields to be 'helpful'.

This annotation seems too strict?

Interesting, this error does *not* occur when running on my OS X laptop.  It only happens on the build machine running an old version of jenkins, java and linux.  Unfortunately, getting them to upgrade can take months.

Any ideas?

**Comment by llamahunter** [comment]
Looked into this in more detail. This really seems like a docker-java bug.  In particular, the 'start' field has been on the ProgressDetail message for a loooong time:
https://github.com/docker/docker/blob/master/pkg/jsonmessage/jsonmessage.go

yet the docker-java code both does not list the field, and does not ignore unknown fields
https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/ResponseItem.java

Unclear why I am just hitting this now, and only on linux.

**Comment by llamahunter** [comment]
Hmm... looking at jsonmessage.go, it also appears that ResponseItem.java is missing a number of other optional fields that might also cause it to blow up someday.

- stream
- from
- time

**Comment by marcuslinke** [comment]
Thanks for reporting!

**Comment by llamahunter** [comment]
In the middle of testing a small fix (adding 'start' field to ProgressDetail).  Will submit pull request if it fixes things.  Not addressing the other missing fields, since not sure when/how they manifest.

**Comment by marcuslinke** [comment]
Nice! Could you fix the ignore unknown properties = false issue also please? Thanks!

**Comment by llamahunter** [comment]
Um... sure.  Tho, someone seems to have gone through a lot of trouble to mark them *not* ignored.

**Comment by llamahunter** [comment]
Wow, it was a lot more work than it should have been to plumb that one small change through the layers of gradle plugins and -SNAPSHOT configurations. I hope you don't mind if I go through the 'ignore unknown properties' change, especially since I'm unsure what the original intent was there.

**Comment by marcuslinke** [comment]
Thanks. As I see, only `start` field is missing in `ProgressDetail`. Other missing fields like `stream` are present in `BuildResponseItem` for example. So this specific field should be moved to its base class `ResponseItem` then. 

FYI: All these models aren't designed by spec but rather by probing against a running docker host. The 'ignore unknown properties' setting was introduced to detect incompatibilities with these model classes. Thanks for pointing to the docker sources, so this can be fixed now.

So what we have to do now is to modify the model classes to match the spec. This should be done in  a single PR. So either you are able do this work within your PR or I will close it and create a fresh one soon.

As I'm currently busy I would prefer the first solution... ;-)

**Comment by llamahunter** [comment]
Not clear what you're getting at.  The 'start' field is not on ResponseItem.  It's a field on the ProgressDetail.  From the go code:

<pre>
// JSONMessage defines a message struct. It describes
// the created time, where it from, status, ID of the
// message. It's used for docker events.
type JSONMessage struct {
	Stream          string        `json:"stream,omitempty"`
	Status          string        `json:"status,omitempty"`
	Progress        *JSONProgress `json:"progressDetail,omitempty"`
	ProgressMessage string        `json:"progress,omitempty"` //deprecated
	ID              string        `json:"id,omitempty"`
	From            string        `json:"from,omitempty"`
	Time            int64         `json:"time,omitempty"`
	Error           *JSONError    `json:"errorDetail,omitempty"`
	ErrorMessage    string        `json:"error,omitempty"` //deprecated
}

// JSONProgress describes a Progress. terminalFd is the fd of the current terminal,
// Start is the initial value for the operation. Current is the current status and
// value of the progress made towards Total. Total is the end value describing when
// we made 100% progress for an operation.
type JSONProgress struct {
	terminalFd uintptr
	Current    int64 `json:"current,omitempty"`
	Total      int64 `json:"total,omitempty"`
	Start      int64 `json:"start,omitempty"`
}
</pre>

**Comment by llamahunter** [comment]
Note also that fields like current/total/start are defined as int64 in go, but are being stored in int types in Java.  They probably should be in longs.

**Comment by KostyaSha** [comment]
Yes, please use long, it is mistakes that docker-java uses int in many places.

**Comment by llamahunter** [comment]
Ok, so, I might take a stab at this.  You want me to remove all the ignore unknown property annotations on POJOs for which I am able to identify Go code describing the message payload?

**Comment by llamahunter** [comment]
When's the next release planned?

**Comment by marcuslinke** [comment]
Just released v2.1.1. It will be available in maven central in a few hours.

**Comment by llamahunter** [comment]
Hmm... still not seeing it in maven central.  Latest version listed is 2.1.0.
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22docker-java%22

**Comment by marcuslinke** [comment]
It's already in Sonatype repo: https://oss.sonatype.org/#nexus-search;quick~docker-java
Seems to be an issue regarding synchronization with maven central... Lets wait a few hours more before opening a ticket.

**Comment by llamahunter** [comment]
Still not there.  From some docs I read, t's supposed to take only a few hours, but it's been almost 12 since it hit sonatype (Thu Sep 17 2015 22:18:07 GMT-0700). The last build 2.1.0 appears to have made it to maven central in about 7 hours. :-/

**Comment by docker-java-maintain** [comment]
@llamahunter Ok, opened a ticket at sonatype: https://issues.sonatype.org/browse/OSSRH-17772

**Comment by marcuslinke** [comment]
Seems it finally arrived central (http://repo1.maven.org/maven2/com/github/docker-java/docker-java/2.1.1/) but is not indexed at search.maven.org. So builds should work now.

**Comment by KostyaSha** [comment]
@marcuslinke should i also update docker-plugin? :)

**Comment by marcuslinke** [comment]
@KostyaSha You should definitely... :)
