### ISSUE TITLE
support binary wrapping

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#328]
Low prio, but will it be possible to provide binary wrapping for docker commands? Seems current CMD objects can produce `toBinaryString()` but it will require additional stream handling.

**Comment by marcuslinke** [comment]
Could you shortly describe the use case please?

**Comment by KostyaSha** [comment]
Jenkins usually do integrations in 2 ways:
- wrapping binary with CmdRun
- using native APIs

Sometimes it makes sense to call binary, sometimes to use library routines.
