### ISSUE TITLE
Support for Volume API

### ISSUE THREAD

**Issue by wlan0** [docker-java/docker-java#329]
Docker 1.8 allows Volume Plugins
Docker 1.9 exposes Volume APIs - https://github.com/docker/docker/pull/14242

Is support for this already being worked on?

**Comment by marcuslinke** [comment]
No, this is not implemented yet. Documentation is here:

https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md
https://docs.docker.com/extend/plugins_volume/

Seems this needs an additional `VolumeDriver` field in the `HostConfig` of `CreateContainerCmd` only. Any hints/suggestions?

**Comment by wlan0** [comment]
Going forward, docker will provide apis for creating, updating, listing and deleting volumes. These APIs are collectively called as Volume APIs. This feature is already available in docker:master (added as a part of this commit - https://github.com/docker/docker/pull/14242) and is a part of the docker 1.9 milestone. The support for this in docker-java will be needed.

`VolumeDriver` field in `CreateContainerCmd` is going to be deprecated starting from docker 1.9. (https://github.com/docker/docker/issues/16069). Maybe, this shouldn't be implemented?

Along with changes to the container create fields, the docker inspect json format has also changed in these releases. Particularly, a new field called "Mounts" is added to the inspect response. This field contains information about where the volumes are present on the host, and which driver is used, etc..

**Comment by KostyaSha** [comment]
Is 1.9 already released?

**Comment by marcuslinke** [comment]
Thanks for the info. Docker remote API documentation regarding volumes endpoint: https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.21.md#24-volumes

**Comment by marcuslinke** [comment]
@KostyaSha Seems v1.8.2 is current release version.

**Comment by lordofthejars** [comment]
Already released on docker 1.9 http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#2-4-volumes
