### ISSUE TITLE
http vs tcp

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#331]
Sorry if it silly question, but what changed and when about url format that docker binary accepts? Should docker-java follow such change?

**Comment by marcuslinke** [comment]
@KostyaSha Sorry, what do you mean?

**Comment by KostyaSha** [comment]
@marcuslinke  docker docs using `tcp://addr:port`, docker-java uses `http://addr:port`

**Comment by KostyaSha** [comment]
https://github.com/docker/docker/blob/634a848b8e3bdd8aed834559f3b2e0dfc7f5ae3a/docs/articles/https.md#connecting-to-the-secure-docker-port-using-curl
seems docker client and demon uses `tcp` as scheme and tls or not is controlled by flags. In the same time it's https or http protocols. Weird logic...

**Comment by KostyaSha** [comment]
https://github.com/docker/docker/blob/bc48194ded4892d277345e45defee66a24f36399/api/client/cli.go#L123-L142

**Comment by marcuslinke** [comment]
AFAIK docker also accepts `http` and `https` scheme directly. So we could support `tcp` scheme additionally.

**Comment by KostyaSha** [comment]
no, it accepts only tcp. If docker-java will support it, then it wouldn't know how initialize connection (tls or none), because this thing configured in docker client with additional flags

**Comment by marcuslinke** [comment]
The current situation with docker-java is as follows: Someone is using an `https` url but doesn't configure a docker cert path. Or someone is using an `http` url but has configured a cert path. What should we do in this cases? By accepting only `tcp` url docker prevents this. Whether `http` or `https` is used is exclusively determined via the DOCKER_TLS_VERIFY variable. I think we should do the same.

**Comment by KostyaSha** [comment]
For now i made this hack https://github.com/jenkinsci/docker-plugin/commit/c4e7fa85b19b423a104201007ba4846783a861ac#diff-7e2d4a96a7b46e715006636ce5f7a79bR33

**Comment by marcuslinke** [comment]
wip

**Comment by marcuslinke** [comment]
Fixed via Refactoring of DockerClientConfig #447

**Comment by KostyaSha** [comment]
:+1:
