### ISSUE TITLE
How do I write to the STDIN of a `docker exec`?

### ISSUE THREAD

**Issue by jhftrifork** [docker-java/docker-java#334]
I want to use docker-java to do the equivalent of this:

```
> echo bar | docker exec -i 9b39f2b359da tee /foo.txt
bar
> docker exec -i 9b39f2b359da cat /foo.txt
bar
```

How do I do this?

**Comment by marcuslinke** [comment]
Sadly this is currently not possible. See https://github.com/docker-java/docker-java/issues/253
