### ISSUE TITLE
What is the equivalent to docker run --rm <image> <command>?

### ISSUE THREAD

**Issue by colameo** [docker-java/docker-java#336]
Hi everybody,

what is the equivalent to <code>docker run <b>--rm</b></code> ?

Thanks
Serano

**Comment by KostyaSha** [comment]
You should analyse docker-client  code https://github.com/docker/docker/blob/634a848b8e3bdd8aed834559f3b2e0dfc7f5ae3a/api/client/run.go#L223-L239 
Docker java is only a library around API and if you see no option in plain API, you should check for custom command in go client.

**Comment by marcuslinke** [comment]
As @KostyaSha stated this is implemented via the wait container command in the docker client.
