### ISSUE TITLE
The response of time is too long 

### ISSUE THREAD

**Issue by jamesmarva** [docker-java/docker-java#338]
I hava some problems of this code, it have too much time to execute, is it some problem in my program???
```
CreateContainerResponse container = mDockerClient.createContainerCmd("scidbcoord:0.4")
				.withEnv("IP=" + ip)
				.withTty(true)
				.withName(containerName)
				.withNetworkMode("none")
				.withHostName("marva.james")
				.exec();


ExecCreateCmdResponse mExecCreateCmdResponse = mDockerClient.execCreateCmd(containerName)
					.withAttachStdout(true)
					.withCmd("service", "postgresql", "start")
					.exec();
			mDockerClient.execStartCmd(mExecCreateCmdResponse.getId())
					.withTty(true)
					.exec();
			
			mExecCreateCmdResponse = mDockerClient.execCreateCmd(containerName)
					.withAttachStdout(true)
					.withCmd("su", "-", "scidb", "-s", "/tmp/start_scidb.sh")
					.exec();
			mDockerClient.execStartCmd(mExecCreateCmdResponse.getId())
					.withTty(true)
					.exec();
```

and to stop container
```
ExecCreateCmdResponse mExecCreateCmdResponse = mDockerClient.execCreateCmd(containerName)
				.withAttachStdout(true)
				.withCmd("su", "-", "scidb", "-s", "/tmp/stop_scidb.sh")
				.exec();
		mDockerClient.execStartCmd(mExecCreateCmdResponse.getId())
			.withTty(true)
			.exec();
		mDockerClient.stopContainerCmd(containerName).withTimeout(3).exec();
```

**Comment by marcuslinke** [comment]
What do you mean by ' too long' and which part of your example code is affected?

**Comment by jamesmarva** [comment]
When I use this 

```
ExecCreateCmdResponse mExecCreateCmdResponse = mDockerClient.execCreateCmd(containerName)
.withAttachStdout(true)
.withCmd("su", "-", "scidb", "-s", "/tmp/stop_scidb.sh")
.exec();
```
this code begin to is too long, and the response of the code is too long.

**Comment by jamesmarva** [comment]
![Image of my](https://bitbucket-assetroot.s3.amazonaws.com/repository/4RqjgB/814787064-360%E6%88%AA%E5%9B%BE-47861356.jpg?Signature=Z6SBHcaR8MQ2qmUMi6NsKBB6oOc%3D&Expires=1444226711&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82)

**Comment by jamesmarva** [comment]
![Image of stop](https://bitbucket-assetroot.s3.amazonaws.com/repository/4RqjgB/1104314053-stopexecute.jpg?Signature=dk1XvUoOLN26nqZTJzbyW%2FOxTys%3D&Expires=1444227025&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82)

The picture expresses the program stop executing.

I think it maybe some reasons :
1. my code is to execute the shell in container. it will depend on the shell that executed in the container.
2. my compute the the rest resource is not enough.

**Comment by KostyaSha** [comment]
Image not available
