### ISSUE TITLE
Provide a way to get progress reports during build/push/pull operations

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#342]
Currently, the progress reports returned from the docker daemon during build/push/pull operations are dropped on the floor (unless one provides a DEBUG slf4j configuration for the relevant class, which then returns way too much ill formatted info).

Is there any plan to provide a way to pipe the progress reports to users of docker-java, so that they could, in turn, capture and/or display them to users?  Perhaps via a Queue<> object provided to the relevant ResultCallbackTemplate<> subclass that it can use from the onNext() method?

**Comment by KostyaSha** [comment]
It exists just override onNext, see callbacks

**Comment by llamahunter** [comment]
Well, that requires the downstream users of docker-java to understand the nuances of docker daemon communication.  It  would be nice if docker-java did some of the work here filtering/converting the progress updates into a useful form.

**Comment by smiklosovic** [comment]
could you elaborate on existing actual implementation more specifically please?

**Comment by blackat** [comment]
Hello,
thanks for the great lib first of all.
I have a question about the override, when I want to print the progress `item.getProgress()` the method has been deprecated, is there another way to trace the progress?

Is there a good reason to not use it?

Thanks 😉

**Comment by KostyaSha** [comment]
deprecation is happening according to docker api. Please look at docker api
docs and then to available library methods
