### ISSUE TITLE
Client Server Authentication

### ISSUE THREAD

**Issue by kamaljeetrathi** [docker-java/docker-java#343]
I just want to authenticate my client and server in docker using rest api.
I have docker installed in my local machine and using https://docs.docker.com/articles/https/
link for security.
I am bit confuse in the above link which command to fire where.
And also how can i seprate my client and server at my local machine.

**Comment by nmcb** [comment]
Having the same problem here, running on Mac OS X 10.11, docker-machine version 0.4.1 (e2c88d6).
We did convert the cert.pem into cert.p12 and imported it into Java's keystore using the keytool. Curl works:

```
docker-machine create --driver virtualbox default
VBoxManage controlvm default natpf1 report_api,tcp,127.0.0.1,52376,,2376

cd ~/.docker/machine/certs
openssl pkcs12 -export -inkey key.pem -in cert.pem -name docker-machine-client-side -out cert.p12 -password pass:docker

curl -v --insecure --cert ~/.docker/machine/certs/cert.p12:docker --key ~/.docker/machine/certs/key.pem https://localhost:52376/images/json
```

But docker-java throws a javax.net.ssl.SSLException on the (docker generated) certificate.

```
Caused by: javax.net.ssl.SSLException: Certificate for <localhost> doesn't contain CN or DNS subjectAlt
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:178)
	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
```

**Comment by marcuslinke** [comment]
Maybe this helps? https://groups.google.com/forum/?#!topic/docker-java-dev/6B13qxZ4eBM

**Comment by KostyaSha** [comment]
1) docker-java supports reading certs from cert dir into runtime in-memory keystore that allow operating docker-java successfully. 
2) Not sure how keys conversion should work and how this 2 types of certificate correlate (could you point on some doc?)
3) If you want path custom keys from java code, then it will be https://github.com/docker-java/docker-java/issues/367 question.

If it doesn't solve your problem please reopen issue.

**Comment by sray7965** [comment]
Guys what about if I am using some REST client like Feign to connect to a docker daemon and lets say that TLS is enabled in Docker daemon. Now, Feign has the capability to send a token per REST request it makes. My question is where will Feign get the token from, will it get the token from CA.
