### ISSUE TITLE
Discus moving docker-maven-plugin to docker-java?

### ISSUE THREAD

**Issue by alexec** [docker-java/docker-java#352]
Hi guys,

I'd like to look to make it easier to move https://github.com/alexec/docker-maven-plugin into more of a community ownership. I get a few PRs from people such as @marcust and I'd like to be able do things like merge PRs, investigate issues, create releases and so forth. Would docker-java be the place for this?

Alex

**Comment by KostyaSha** [comment]
> I'd like to be able do things like merge PRs, investigate issues, create releases and so forth.

@alexec  you can do it in your repo. I had no time for review but seems docker-maven-plugin depends on orchestration project. 
Imho if plugin is highly used, using docker-java library then it can be hosted under docker-java organisation (it allows creating teams).

**Comment by marcust** [comment]
I actually like the idea to move the orchestration and the maven plug in to docker Java, then we'd have the whole chain in one organization. I could join the orchestration and maven plug in team if @alexec is ok with that.

**Comment by KostyaSha** [comment]
I also started discussion with spotify guys cc @davidxia  about merging efforts in one library. Seems they also have https://github.com/spotify/docker-maven-plugin how this two maven plugins correlates? Will it be possible to combine efforts?

**Comment by marcust** [comment]
@KostyaSha @davidxia we evaluated both plugins earlier this year and decided for @alexec implementation.
IIRC spotify's plugin lacks the whole orchestration part that the other one has. Basically it is a subset of the alexc plugin.

**Comment by gesellix** [comment]
just as a side note: when trying to consolidate docker-java and a docker-maven plugin under a single organisation, you might also consider to ask @bmuschko if he wants the https://github.com/bmuschko/gradle-docker-plugin/ to also be moved to a more community driven repo.
