### ISSUE TITLE
What's the correct way to handle image push failures?

### ISSUE THREAD

**Issue by romanek-adam** [docker-java/docker-java#353]
Please see a relevant discussion in bmuschko/gradle-docker-plugin#113. Is it correct to expect that PushImageResultCallback.awaitSuccess() would throw an exception on image push failure? Or should it be handled in a different way?

**Comment by marcuslinke** [comment]
There should be thrown an exception if the push fails. See https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/PushImageResultCallback.java#L46

Maybe in your specific case there is no `error` or `errorDetail` returned so the push will be handled as successful. So what we need to analyze is a log of the full docker response. If you could reproduce the same situation by using the docker CLI this will be fine.

**Comment by romanek-adam** [comment]
I have never reproduced it using docker CLI - it only appears when using docker-java.

**Comment by marcuslinke** [comment]
@romanek-adam We need the concrete docker response to analyze. Would it be possible for you to reproduce with docker CLI and post the response here?

**Comment by romanek-adam** [comment]
I'm sorry, I wasn't able to reproduce this with docker CLI.
