### ISSUE TITLE
Support for Network API

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#356]
Docker 1.9 has been released with new multihost network API http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#2-5-networks

**Comment by KostyaSha** [comment]
Feel free to provide PR

**Comment by lordofthejars** [comment]
During devoxx hackergarten we are going to publish this issue. I have just opened the issue to have somewhere the list of things to do.

**Comment by KostyaSha** [comment]
Obviously any API change is TODO for library.

**Comment by marcuslinke** [comment]
@lordofthejars Any news? Do you have started already?

**Comment by lordofthejars** [comment]
Not yet, it has been a busy weeks, but I would like to help on this, if there is no rush, then I would do it.

**Comment by akeely** [comment]
I need this for a project that I'm doing, so I starting working on it. If anyone else is already doing it, let me know and I can help out where I can. Otherwise, I'm very open to feedback on my work!

**Comment by lordofthejars** [comment]
Great!!! I had no time to spend on this, so busy on other projects, so please feel free to work on this and thank you very much for having time to implement this :)

**Comment by marcuslinke** [comment]
Work started on branch https://github.com/docker-java/docker-java/tree/issue-356

**Comment by marcuslinke** [comment]
https://github.com/docker-java/docker-java/pull/417 List networks API

**Comment by marcuslinke** [comment]
Closing as https://github.com/docker-java/docker-java/pull/425 is merged into master.
