### ISSUE TITLE
Poor Read Performance in Dockerfile.ScannedResult

### ISSUE THREAD

**Issue by s-webb** [docker-java/docker-java#358]
In the buildDockerFolderTar method in Dockerfile.ScannedResult, an anonymous subclass of InputStream is created. The subclass overrides only the single-byte variant of the read method:

                // line 139, Dockerfile.java
                return new InputStream() {
                    @Override
                    public int read() throws IOException {
                        return tarInputStream.read();
                    }

                    @Override
                    public void close() throws IOException {
                        IOUtils.closeQuietly(tarInputStream);
                        FileUtils.deleteQuietly(tarFile);
                    }
                };

For some setups, this causes slow but acceptable performance, on others performance is completely unacceptable (e.g. 2mins plus to read a 40MB file).

This can be fixed by also overriding the bulk read method, i.e.

                    @Override
                    public int read(byte [] buff, int offset, int len) throws IOException {
                        return tarInputStream.read(buff, offset, len);
                    }

I can provide a gist to demonstrate if necessary, but hopefully the problem and fix are self-explanatory enough without.

**Comment by KostyaSha** [comment]
> I can provide a gist

Please provide Pull Request as it standard method of changes contribution. Also please describe how it can be tested to exclude such regression in future.

**Comment by s-webb** [comment]
Added a PR here - https://github.com/docker-java/docker-java/pull/359

A test would be to use the inner class to read a non-trivial file (say 10MB) and assert that it can be done within a reasonable amount of time. A 40MB file was being read in 25 millis with the fix, but 11000 millis withou, so a 10MB file should be read easily within, say, 500 millis, even allowing for GC pauses and contention.

Might need a little refactoring to make the affected code easily testable.

**Comment by marcuslinke** [comment]
Merged. Thanks!
