### ISSUE TITLE
SSLContext for keys from variables

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#367]
For jenkins docker related plugin working on credentials binding. Trying implement Auth that will work on: private, public + cacert.
Though i still don't understand how much types of authentication docker host and registry has.

**Comment by hawky-4s-** [comment]
I think you could use our implementation for authentication against private registry and docker hub (when you add an email field for docker hub). We use basic auth (nginx proxy) for the private registry.

**Comment by marcuslinke** [comment]
I don't think this is a library issue. As `DockerClientConfig' allows you to pass an `SSLConfig` this could be implemented easily by library users.

**Comment by KostyaSha** [comment]
@marcuslinke that not an issue, that a thing that can be shared i.e. this way will be used by 2 jenkins docker plugins and can be useful for anybody else. It just additional helper class.

**Comment by marcuslinke** [comment]
OK.

**Comment by marcuslinke** [comment]
@KostyaSha As people wait for 3.0.0 release I think we should remove some of the issues from https://github.com/docker-java/docker-java/milestones/3.0.0. This issue is definitely not needed in 3.0.0. Maybe others too?

**Comment by KostyaSha** [comment]
sure

**Comment by KostyaSha** [comment]
I think solved now.
