### ISSUE TITLE
Exec start command API needs method to pass InputStream for containers STDIN

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#369]
We could replace existing `withAttachStdin(boolean stdin)` method with `withAttachStdin(InputStream stdin)`. As attaching STDIN is currently not possible the implementation could throw a `UnsupportedOperationException` for now.

**Comment by KostyaSha** [comment]
Wouldn't withAttachStdin work without iostream? This is a value that you can send to daemon and it will (?) accept it even if sending to stdin is not possible?

**Comment by marcuslinke** [comment]
Related: https://github.com/docker-java/docker-java/issues/370

**Comment by marcuslinke** [comment]
We need to pass an `InputStream` to the commands exec for future STDIN  redirection. Instead to have 2 independent methods, we could trigger the http param `attachStdin` in dependence of the presence of that `InputStream`.

**Comment by KostyaSha** [comment]
I mean we should firstly check whether docker may work i.e. for `createcontainer` with `true` for stdin, but without attaching to it and what will be the difference i.e. if not attaching stdin. Will for example bash or some other tool that expecting stdin fail?.

**Comment by marcuslinke** [comment]
Hmm, interesting question. We should evaluate that first. If this is not a problem in terms of an exception we shouldn't check this in the library i think.

**Comment by marcuslinke** [comment]
I will develop some test cases for this.

**Comment by KostyaSha** [comment]
AFAIR when you run docker with stdin but didn't attach it, it will wait for stdin and it will be possible to attach to it later with docker attach. So `true` looks like a valid value, probably additional `withAttachStdin(IOstream)` should internally call `withAttachStdin(true)`

**Comment by marcuslinke** [comment]
OK. Seems I was confused while creating the initial comment. Exec create command has `withAttachStdin` method and exec start command needs a method to pass the appropriate `InputStream`. When exec create is issued with `withAttachStdin(false)` the `InputStream` will not attached to STDIN of the container.

**Comment by marcuslinke** [comment]
Fixed via 87e398a
