### ISSUE TITLE
InspectContainerResponse is missing some properties

### ISSUE THREAD

**Issue by patelrit** [docker-java/docker-java#371]
Several useful properties are missing from the Status object in Inspect response:
- Status
- Restarting
- OOMKilled
- Dead
- Error

"State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 30555,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-11-18T00:10:33.264501227Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },

**Comment by KostyaSha** [comment]
in what api version does they appeared?

**Comment by patelrit** [comment]
Most of these properties have been in the inspect response since version
1.19

sudo docker version

Client version: 1.7.0

Client API version: 1.19

Go version (client): go1.4.2

Git commit (client): 0baf609

OS/Arch (client): linux/amd64

Server version: 1.7.0

Server API version: 1.19

Go version (server): go1.4.2

Git commit (server): 0baf609

OS/Arch (server): linux/amd64

ubuntu@ip-10-10-129-55:~$ sudo docker inspect d3377a2140e3

[

{

    "Id":
"d3377a2140e3150437ade73442633b5689b7aa922f6b953fb5e34013b8de4ea6",

    "Created": "2015-11-18T16:41:19.618214342Z",

    "Path": "catalina.sh",

    "Args": [

        "run"

    ],

    "State": {

        "Running": true,

        "Paused": false,

*        "Restarting": false,*

*        "OOMKilled": false,*

*        "Dead": false,*

        "Pid": 2188,

        "ExitCode": 0,

*        "Error": "",*

        "StartedAt": "2015-11-18T16:41:19.807255012Z",

        "FinishedAt": "0001-01-01T00:00:00Z"

    },

On Wed, Nov 18, 2015 at 1:09 AM, Kanstantsin Shautsou <
notifications@github.com> wrote:

> in what api version does they appeared?
>
> Sent from my iPad
>
> > On Nov 18, 2015, at 9:28 AM, Ritesh Patel <notifications@github.com>
> wrote:
> >
> > Several useful properties are missing from the Status object in Inspect
> response:
> >
> > Status
> > Restarting
> > OOMKilled
> > Dead
> > Error
> > "State": {
> > "Status": "running",
> > "Running": true,
> > "Paused": false,
> > "Restarting": false,
> > "OOMKilled": false,
> > "Dead": false,
> > "Pid": 30555,
> > "ExitCode": 0,
> > "Error": "",
> > "StartedAt": "2015-11-18T00:10:33.264501227Z",
> > "FinishedAt": "0001-01-01T00:00:00Z"
> > },
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-java/docker-java/issues/371#issuecomment-157650830>
> .
>



-- 
Ritesh
Founder @ Nirmata <http://nirmata.com/>

**Comment by patelrit** [comment]
Any update on this issue? Is there anything else that needs to be done? Was hoping this fix made it to Dec release. We have customers who are awaiting fixed based on these changes. If there is additional refactoring to be done, can it be decoupled from the properties support?

**Comment by KostyaSha** [comment]
@patelrit should be available in master and 2.x branch, please build them and verify.
