### ISSUE TITLE
Non streaming stats

### ISSUE THREAD

**Issue by geoand** [docker-java/docker-java#375]
Currently the `StatsCmd` works wonderfully with the regular streaming mode of the `/container/(id)/stats` API call.

However since `v1.19`, the same Docker API call introduced a new query param named `stream` that controls whether or not the response should be a  stream or just the latest stats results. The default value of the param is `true` which ensures backward compatibility.

It would be great if the non-streaming functionality could be introduced. 
I could definitely help out with this, but it would be great to hear your thoughts on how this feature would be implemented (meaning that since the result will not be streamed, the Async behavior of the current `StatsCmd` implementation would not make much sense)

**Comment by marcuslinke** [comment]
Is it technically working with the current async API? In this case we could add another `exec()` method that returns the first `Statistic` object that is coming from the async API.

**Comment by KostyaSha** [comment]
@marcuslinke if callback is not specified, then it should return single statistics object without `stream` parameter. When stream required it should return progressive output that library handle with user callbacks.

**Comment by geoand** [comment]
@KostyaSha That sounds like a great solution!

**Comment by KostyaSha** [comment]
The question will be how abort this stream as it infinite.

**Comment by geoand** [comment]
I am pretty sure that the stream was infinite when the query param did not exist. 
It's just that since `v1.19` you can have the API return a single call instead of an infinite stream.

**Comment by marcuslinke** [comment]
We could also add a method `awaitStatistics()` to the callback. I think this would be the best option.
