### ISSUE TITLE
Legacy registry message on pull results in error status

### ISSUE THREAD

**Issue by zachmarshall** [docker-java/docker-java#380]
When using a newer docker version to pull from a v1 docker registry, the docker API can respond with

> registry/image: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

This occurs even though the pull was successful to the remote API. When this happens, `PullResponseItem` does not recognize this status message as successful.

**Comment by KostyaSha** [comment]
Picked in both branches. Thanks for PRs!
