### ISSUE TITLE
Missing http proxy configuration support

### ISSUE THREAD

**Issue by doronl** [docker-java/docker-java#384]
I didn't see option to set in the client any proxy settings in the DockerClientConfig there are no such options

**Comment by KostyaSha** [comment]
@marcuslinke why bug? :)

**Comment by marcuslinke** [comment]
For me its a bug as the user can't set it in any way and http proxies are common in corporate environments. So better call it a bug instead of an enhancement... ;)

**Comment by marcuslinke** [comment]
@doronl @KostyaSha: How about implementing this via the usual system properties like `http.proxyHost` ?

**Comment by KostyaSha** [comment]
System properties wouldn't work for normal applications that handle such
things from code sides.

2015-11-30 22:48 GMT+03:00 marcuslinke <notifications@github.com>:

**Comment by marcuslinke** [comment]
I think proxy configuration is environment configuration usually. It should be configured at the jvm level not the application level. In our company we set the `http.proxy...` variables via _JAVA_OPTIONS environment variable. This way there is (mostly) no need to configure each running (java) application separately. So I think docker-java should respect these variables.

**Comment by marcuslinke** [comment]
@doronl Could you test with https://github.com/docker-java/docker-java/tree/issue-384 please? This branch contains basic http(s) proxy support by evaluating the appropriate system properties. See https://github.com/docker-java/docker-java/pull/386 for details.

**Comment by doronl** [comment]
Thanks! I will try to test tomorrow.

Regards,
Doron
בתאריך 1 בדצמ 2015 22:26,‏ "marcuslinke" <notifications@github.com> כתב:

**Comment by doronl** [comment]
I tested with a small test I made (actually I altered one of your unit
tests...), using VM paramters -Dhttp.proxyHost=MyProxyHost
-Dhttp.proxyPort=MyPorxyPort and it worked!

When can you commit the change so I may consume it in my regular maven
project?

Thanks!
 Doron

**Comment by KostyaSha** [comment]
@doronl seems we have a problem with 2 versions. We planned 3.0 as refactored (more time) + features and 2.1.X as hotfixes. But people adding new features into 2.x. This becomes bit annoying :) Can't say exactly to what branch it will be picked and released. (Maybe we will do massive commits syncs, but want avoid).

**Comment by doronl** [comment]
I understand, its OK for now as this is still a research project am doing.

Thanks for the quick response!
Doron
