### ISSUE TITLE
Slow perfomance when using docker-java client

### ISSUE THREAD

**Issue by lsamayoa** [docker-java/docker-java#390]
Hello guys, I have been using this client for a while now. But I think it is very slow when executing commands even when pointing to a local docker instance. I know this could be just a missconfiguration in my client but I haven't been able to find out what is it that it takes so long to execute a simple command.

**Comment by KostyaSha** [comment]
@lsamayoa please:
- provide more information, 
- try compare the same command with binary executed command, 
- try wrote your case as a test case and provide a PR
- compare with logs on docker side (what command was executed and what expected timings)

**Comment by marcuslinke** [comment]
Maybe related: https://github.com/docker-java/docker-java/pull/402

**Comment by lsamayoa** [comment]
I am running docker through a VM and switching on/off a VPN causes its network to get weird and client performance slow down, when I restart the VM and performance goes back to normal. Guess it got something to do with my networking environment than the client itself

**Comment by KostyaSha** [comment]
Next time please verify your DNS, they usually not updated right after jumping between networks.
