### ISSUE TITLE
The withRemoveVolumes of removeContainerCmd does not become effective.

### ISSUE THREAD

**Issue by wzhyh** [docker-java/docker-java#394]
For help:
boolean is_delete_volume = true;
dockerClient.removeContainerCmd(container_id)).withRemoveVolumes(is_delete_volume).exec();

The container id deleted, but the volume still existed without error.

thanks

**Comment by KostyaSha** [comment]
Please show logs on docker daemon side, optionally please dump JSON request if you can.
