### ISSUE TITLE
remove image should return stream

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#398]
http://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#remove-an-image
and some `awaitCompletion()` will be required i think.

**Comment by KostyaSha** [comment]
Or not stream and just List...

@marcuslinke could you guide how implement it?
 I changed DockerCmd to AsyncCmd, replaced `Void`, to RemoveResponse... But should it return List<RemoveResponse> instead?

**Comment by marcuslinke** [comment]
@KostyaSha As the doc says it returns a complete JSON array this should'nt be stream. So this is a simple `DockerCmd` that returns some JSON mappable object like either `List<RemoveImageResponseItem>` where `List` type represents the JSON array or some `RemoveImageResponse` object that contains a member of `List<RemoveImageResponseItem>`. What to use is a design decision, but the latter demands to write a custom json serializer/deserializer. So I would prefer the list solution here. See `ListImagesCmd` implementation for a case that uses a `List` as response type.

**Comment by marcuslinke** [comment]
But maybe the docs are wrong here. I wonder because if I remember correctly removing of images from the docker CLI look like streaming behavior where each item is printed to console as far as it is processed by the deamon. But maybe I'm wrong with that. Needs to be evaluated.

**Comment by KostyaSha** [comment]
@marcuslinke could you look on it?

**Comment by KostyaSha** [comment]
Would be glad to see this in 3.0.0 :)
