### ISSUE TITLE
Can't ExecStartCmd execute some command?

### ISSUE THREAD

**Issue by lisicongIBM** [docker-java/docker-java#400]
For Example: 

ExecCreateCmd execCreateCmd = dockerClient.execCreateCmd(containerId);		

 **// I want to create a file in container and write some thing in it.**
**// For Example     cmd =["sed","-i","1a testtest","/opt/testfolder/testfile.txt"]**
**// For Example     cmd =["echo","this is test data",">","/opt/testfolder/testfile.txt"]**
execCreateCmd.withCmd(cmd);      
String  execCreateCmdId = execCreateCmd.exec().getId();
ExecStartCmd execStartCmd = dockerClient.execStartCmd(containerId);

**// but it doesn't work. I can't  write anything into testfile.txt**
InputStream is = execStartCmd.withExecId(execCreateCmdId).exec();   

Can't ExecStartCmd execute some command?

**Comment by KostyaSha** [comment]
Duplicates https://github.com/docker-java/docker-java/issues/253

**Comment by lisicongIBM** [comment]
Thanks! -----Kanstantsin Shautsou <notifications@github.com> wrote: -----To: docker-java/docker-java <docker-java@noreply.github.com>From: Kanstantsin Shautsou <notifications@github.com>Date: 12/14/2015 02:57AMCc: Si Cong VL Li/China/Contr/IBM@IBMCNSubject: Re: [docker-java] Can't ExecStartCmd execute some command? (#400)Duplicates #253

**Comment by zhaopengme** [comment]
hi .
I use the lastest code to test. but still can not  generate  file.and I found many test cases can not passed.

```
    @Test(groups = "ignoreInCircleCi")
    public void execCreateTest1() {
        String containerName = "generated_" + new SecureRandom().nextInt();

        CreateContainerResponse container = dockerClient.createContainerCmd("busybox").withCmd("top").withName(containerName).exec();
        dockerClient.startContainerCmd(container.getId()).exec();
        ExecCreateCmd execCreateCmd = dockerClient.execCreateCmd(container.getId());

        execCreateCmd.withCmd("echo", "\"this\"", ">", "/home/testfile.txt");
        String execCreateCmdId = execCreateCmd.exec().getId();
        ExecStartCmd execStartCmd = dockerClient.execStartCmd(container.getId());

    }
```
