### ISSUE TITLE
refactor serder tests

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#404]
- Create dir with docker kind/version/call  i.e. `src/test/resources/samples/docker-engine/1.21/execCmd/{sample1.json, sample2.json}`
- implement tests that picking such files for tests. 
- remove enums

Goal: have json samples from different docker version and our classes should produce expected results for them.  

@marcuslinke are you ok with this?

**Comment by marcuslinke** [comment]
:+1:

**Comment by KostyaSha** [comment]
i'm around, so after #445 and #444 can try resolve

**Comment by KostyaSha** [comment]
Started saving samples in #442 . Testng looks like junit3 :(

**Comment by KostyaSha** [comment]
- Storage created
- Some tests are written
- enums not touched...
