### ISSUE TITLE
Build images with one simple step throws an error

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#411]
Hi I am executing next code in version 2.1.2:

```
final String id = this.dockerClient.buildImageCmd(dockerFileLocationOrFile)
                .withNoCache(noCache)
                .withTag(getTag(image, tag)).exec(new BuildImageResultCallback()).awaitImageId();
```

And the Dockerfile looks like:

```
FROM busybox:latest
```

When I execute the code I get next exception:

```
com.github.dockerjava.api.DockerClientException: Could not build image: null
```

Basically what it is happening is that `com.github.dockerjava.api.model.BuildResponseItem#isBuildSuccessIndicated`  the `getStream` method returns the steps executed but not the word *Successful*. But if then I do a `docker images` the image is there, so it seems that the stream is closed before everything is written inside the String.

**Comment by KostyaSha** [comment]
Please provide full code, show what timeouts did you set for connection.

**Comment by KostyaSha** [comment]
Also, 2.1.3 is the latest version.

**Comment by lordofthejars** [comment]
aha, when you mention the timeouts thing I have tried to increased and it worked. Also I have updated the version to latest one. Thanks for the idea :)
