### ISSUE TITLE
Useless newline at the end of an exception-message

### ISSUE THREAD

**Issue by xFragger** [docker-java/docker-java#412]
```Unable to find a node fulfilling all dependencies: (....)```
this string comes out of e.getMessage() of a docker-exception, after a failed createContainerCmd

Problem is, that is has a useless newline at its end, is this expected?

I did something like the following in an Tomcat-Servet-Environment and the server didn't answer to the request, reason was that newline, after removing it, everything worked fine

```
resp.getOutputStream().print(e.getMessage()); //HttpServletResponse
```

**Comment by KostyaSha** [comment]
Sorry, don't understand what you are asking about.

**Comment by xFragger** [comment]
``` client.createContainerCmd(...).withSomeStuff().exec() ```
throws a DockerException, which is perfectly fine, but the message of that exception ends with a newline character. It isn't your fault, that tomcat or the outputStream behaves like i said, but i think it's just an useless character, which makes more problems, than benefits and i ask you to remove newlines at the end of exception messages

**Comment by KostyaSha** [comment]
Docker also returns new lines that printing during callback logging. I'm using StringUtils to replace end character.

**Comment by KostyaSha** [comment]
@xFragger could you propose PR?

**Comment by xFragger** [comment]
Didn't go that deep inside the client code. I workarounded the "problem" and the craziest fact is, that i wasn't able to reproduce that behavior again (the linebreak is there, but no problem with tomcat).

Another crazy thing is the "info" call to a swarm master (instead to a dockerdaemon) through the client.... there's an ArrayList returned for the driverExtensions, every value in that begins with a "backspace" character.... i simply regex-replaced all controlchars to make a simple string-comparison work.

So thanks for your work, but sorry for not having the time to help atm, i keep an eye on this and maybe i will propose one, in week 2/3 of january (eventually my next slacktime-project)

**Comment by KostyaSha** [comment]
Feel free propose PRs if you see something wrong in library :)
