### ISSUE TITLE
Is there any manual docs for setup development environment?

### ISSUE THREAD

**Issue by llqzwh** [docker-java/docker-java#413]
Hello, I want to setup development environment for docker-java, how to do it? Thanks!

**Comment by KostyaSha** [comment]
Hi, question sounds very generic, could you clarify what do you want achieve, where do you have problems atm?

**Comment by llqzwh** [comment]
I want to debug docker-java code, and I created an project in Eclipse, imported the code to my project, but it needs many external java jar files, I want to known if there is any easy way or any document to setup the development and debug environment?

**Comment by marcuslinke** [comment]
@llqzwh This is a maven project (https://maven.apache.org/). All dependencies are declared in pom.xml file so you can import it in eclipse and all needed jar are downloaded automatically. See https://books.sonatype.com/m2eclipse-book/reference/creating.html for details.

**Comment by llqzwh** [comment]
Thank you! @KostyaSha and @marcuslinke.
