### ISSUE TITLE
Master fails at runtime trying to resolve netty-transport-native-epoll

### ISSUE THREAD

**Issue by cdancy** [docker-java/docker-java#415]
FYI ... Not sure if you guys are aware but trying to resolve master out of sonatype fails due to the below stacktrace. I've sent in a PR with netty here: https://github.com/netty/netty/pull/4659.

Caused by: org.xml.sax.SAXParseException; systemId: <home-dir>/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-native-epoll/4.0.33.Final/308dd63c4026eb3b429738d596ce19c6c8eb2b1e/netty-transport-native-epoll-4.0.33.Final.pom; lineNumber: 1; columnNumber: 45; Invalid encoding name "ISO-8859-15".
	at weblogic.apache.xerces.parsers.DOMParser.parse(DOMParser.java:271)
	at weblogic.apache.xerces.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:201)
	at weblogic.xml.jaxp.RegistryDocumentBuilder.parse(RegistryDocumentBuilder.java:149)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.PomReader.parseToDom(PomReader.java:203)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.PomReader$1.transform(PomReader.java:98)

**Comment by marcuslinke** [comment]
Thanks for info. I wonder why this isn't a problem when building the docker-java project. Maybe this is gradle related?

**Comment by cdancy** [comment]
Could be @marcuslinke . Other tools, outside of ivy/gradle, may not care so much what the encoding is if they even check for it at all. Perhaps they're using another library to parse the xml. IDK. In either event my fix  https://github.com/netty/netty/pull/4659 has been merged and the project maintainer said they would back port to the 4.x release chain sometime this week. Any objections to me sending in a PR to update the netty dependencies here?

**Comment by marcuslinke** [comment]
Feel free to provide an appropriate PR if this change is released. Thanks.

**Comment by KostyaSha** [comment]
status?

**Comment by KostyaSha** [comment]
https://github.com/netty/netty/commit/e7af3ee9709a7b7ce5373601f571f94fc4aa5fc9
seems only rc1 available that has many unreleased fixes on top of it.

**Comment by cdancy** [comment]
They actually just released a few days ago. I was waiting for this to send in a PR.

https://github.com/netty/netty/releases/tag/netty-4.0.34.Final

**Comment by KostyaSha** [comment]
I think we will bump all deps before release. @marcuslinke wdyt?

**Comment by cdancy** [comment]
@KostyaSha @marcuslinke any idea on a new release? I'm a committer for gradle-docker-plugin and we'd love to rebase against a newer release in order to support docker-copy-archive-to-container functionality.

**Comment by KostyaSha** [comment]
@cdancy can't you define any version you need in your project?

**Comment by cdancy** [comment]
@KostyaSha the plugin itself is basically an abstraction of this library. We make it easier for those working with gradle to work with docker. We rebase only off of this projects releases. We have open requests to provide tasks (gradle speak if your unfamiliar) for copying files to a given container. As this functionality currently exists ONLY within master of docker-java we are stuck until you guys have a release that has this code.

**Comment by marcuslinke** [comment]
Fixed via https://github.com/docker-java/docker-java/pull/449
