### ISSUE TITLE
Add withFilter option when list images

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#416]
List images command allows three kind of parameters. https://docs.docker.com/engine/reference/api/docker_remote_api_v1.19/#list-images

* filters
* all
* filter

It seems that only the first two options are supported in list images command in the docker-java.

**Comment by KostyaSha** [comment]
What is the question?

**Comment by lordofthejars** [comment]
it is not a question it is a feature that it is not supported now.

**Comment by KostyaSha** [comment]
Feel free to provide PR, this library is missing many APIs.

**Comment by lordofthejars** [comment]
here it is the PR https://github.com/docker-java/docker-java/pull/297/files already done. Just accept it :)

**Comment by KostyaSha** [comment]
@lordofthejars so your issue duplicates PR?

**Comment by lordofthejars** [comment]
@KostyaSha yes, duplicates or it is resolved in.

**Comment by marcuslinke** [comment]
Resolved via https://github.com/docker-java/docker-java/pull/426
