### ISSUE TITLE
attach should include streaming stdin and stdout/stderr decoding

### ISSUE THREAD

**Issue by karchie** [docker-java/docker-java#42]
The existing attach operation doesn't allow interaction with the container through stdin/out/err. This should be implemented.

**Comment by robinst** [comment]
Any updates on this? I just wrote my own small method for decoding stdout/stderr from the stream. This looks like it could replace my hand-rolled method though.

**Comment by karchie** [comment]
I'm not using this (docker-java, docker) actively anymore. It seemed to be working when last I touched it and I've been vaguely meaning to submit a PR just to tie up that loose end but haven't gotten to it. Won't happen in the next few days but I'll try to get to it next week. Would be delighted to have someone beat me to it.

**Comment by marcuslinke** [comment]
Closing in favor of the new  ```FrameReader```. See #200
