### ISSUE TITLE
ExecStartCmd  failure

### ISSUE THREAD

**Issue by zhaopengme** [docker-java/docker-java#424]
hi .
I use the lastest code to test. but still can not  generate  file.and I found many test cases can not passed.

```
    @Test(groups = "ignoreInCircleCi")
    public void execCreateTest1() {
        String containerName = "generated_" + new SecureRandom().nextInt();

        CreateContainerResponse container = dockerClient.createContainerCmd("busybox").withCmd("top").withName(containerName).exec();
        dockerClient.startContainerCmd(container.getId()).exec();
        ExecCreateCmd execCreateCmd = dockerClient.execCreateCmd(container.getId());

        execCreateCmd.withCmd("echo", "\"this\"", ">", "/home/testfile.txt");
        String execCreateCmdId = execCreateCmd.exec().getId();
        ExecStartCmd execStartCmd = dockerClient.execStartCmd(container.getId());

    }
```

like this: #400 #253 #397

**Comment by marcuslinke** [comment]
You need to do `dockerClient.execStartCmd(container.getId()).exec()`.

**Comment by marcuslinke** [comment]
@KostyaSha Maybe we should rename `dockerClient.execCreateCmd()` to `dockerClient.createExecCmd()` ?

**Comment by KostyaSha** [comment]
@marcuslinke Deprecate old, add new. TODO remove 4.0 ? :)

**Comment by KostyaSha** [comment]
dunno... what is the real CMD - should be in the end of naming. If it doesn't match naming pattern, then rename.

**Comment by marcuslinke** [comment]
Command names must be renamed then also.

**Comment by KostyaSha** [comment]
@marcuslinke sorry, have no time :atm: but i'm +1 for consistency :)

**Comment by zhaopengme** [comment]
@marcuslinke thanks.   maybe i'm mistaken.I use the following code. still same result.could u give me a good code. thanks very very much.

```
        try {
            String containerName = "generated_" + new SecureRandom().nextInt();
            CreateContainerResponse container = dockerClient.createContainerCmd("busybox").withCmd("top").withName(containerName).exec();
            dockerClient.startContainerCmd(container.getId()).exec();
            String createCmdId = dockerClient.execCreateCmd(container.getId()).withAttachStderr(true).withAttachStdin(true).withAttachStdout(true).withTty(true).withCmd("touch", "/home/testfile.txt").exec().getId();
            System.out.println(createCmdId);
            dockerClient.execStartCmd(container.getId()).withExecId(createCmdId).withTty(true).withDetach(true).withStdIn(System.in).exec(new ExecStartResultCallback(System.out, System.err));
        } catch (NotFoundException e) {
            e.printStackTrace();
        } catch (ConflictException e) {
            e.printStackTrace();
        } catch (NotModifiedException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

```

**Comment by KostyaSha** [comment]
1) ensure that container is alive after your start with top
2) use bash for command execution.
3) AFAIR after you created `exec` you can only start it.

**Comment by marcuslinke** [comment]
@zhaopengme Whats the problem with the code above? What do you expect? I've created a testcase that runs fine. The file was touched/created successfully.

**Comment by zhaopengme** [comment]
@marcuslinke  I tested `ExecStartCmdImplTest.execStart.`  and can not write `/execStartTest.log`.

jdk 1.8.

![qq20160119-0](https://cloud.githubusercontent.com/assets/1415418/12410201/5065020e-bead-11e5-9f90-9f72da69ba28.png)

**Comment by zhaopengme** [comment]
I use spotify,it can generate file.
```
            DockerClient docker = DefaultDockerClient.builder()
                    .uri(URI.create("https://192.168.99.100:2376"))
                    .dockerCertificates(new DockerCertificates(Paths.get("/Users/zhaopeng/.docker/machine/machines/default")))
                    .build();
            String execId = docker.execCreate("117842de06b2", new String[]{"touch", "/home/aa.a"}, STDOUT, STDERR);
```
![image](https://cloud.githubusercontent.com/assets/1415418/12410487/a109052c-beb0-11e5-8d74-6d4ec2d9bc84.png)

**Comment by marcuslinke** [comment]
Please provide your complete test method code so I can verify here locally. Note that containers that are created within tests are removed after the test finished automatically.

**Comment by marcuslinke** [comment]
Hmmm. OK. There seems to be a problem with the jaxrx implementation at least when running from eclipse. All tests runs successfully when started from maven...

**Comment by marcuslinke** [comment]
@zhaopengme If you run the same test in `ExecStartCmdExecTest` it should work. Could your confirm?

**Comment by marcuslinke** [comment]
FYI: Currently there are two different implementations in docker-java. One uses jersey/jaxrs as foundation and the other uses netty framwork internally. `ExecStartCmdExecTest` uses the netty impl.

**Comment by zhaopengme** [comment]
@marcuslinke `ExecStartCmdExecTest ` is ok!   maybe I need use  the netty impl now .thanks!

**Comment by marcuslinke** [comment]
@zhaopengme Please note that netty impl will available in v3.0.0 of docker-java. Former releases do not contain it!

**Comment by zhaopengme** [comment]
@marcuslinke  ok!

**Comment by marcuslinke** [comment]
We should backport the fix to https://github.com/docker-java/docker-java/tree/2.x

**Comment by marcuslinke** [comment]
Fixed via https://github.com/docker-java/docker-java/pull/430 in master. Backported to 2.x line via 42f4670bd0a58e5bcc98f3f28f77766b61452788

**Comment by marcuslinke** [comment]
@zhaopengme You could give the current default (jaxrs/jersey) implementation a try now.
