### ISSUE TITLE
add support for new log drivers

### ISSUE THREAD

**Issue by patelrit** [docker-java/docker-java#428]
Docker now supports the following log drivers. 

gelf	- Graylog Extended Log Format (GELF)
fluentd -	Fluentd logging driver for Docker
awslogs - Amazon CloudWatch Logs logging driver for Docker

https://docs.docker.com/engine/reference/logging/overview/

Is there a generic way to add support for new drivers without requiring an update to docker-java library? Perhaps there is a better way to address docker plugin support so that we are not always playing catchup..

**Comment by KostyaSha** [comment]
It depends...

**Comment by marcuslinke** [comment]
@patelrit Please note that logging drivers aren't plugins in docker. They are build into a specific docker version and aren't pluggable...

**Comment by KostyaSha** [comment]
@marcuslinke maybe `3.1.0`? I feel hotfixes for 3.0.1 ;)

**Comment by cdancy** [comment]
I'll send in a PR to add the updated log drivers. We have a use-case for gelf and I can knock the others out while I'm here.

**Comment by cdancy** [comment]
@KostyaSha my apologies as I didn't see you assigned this to yourself. I've sent in PR's in this area previously so I don't mind adding the extra drivers. Let me know if you want me to hold off as you guys may have other ideas on where you want things to go.

**Comment by KostyaSha** [comment]
i assigned to keep the track, so marcus may process other issues

**Comment by KostyaSha** [comment]
Resolved via #463
