### ISSUE TITLE
unable to search image from private repository

### ISSUE THREAD

**Issue by pendyala** [docker-java/docker-java#429]
Unable to search image from private repository.

**Comment by KostyaSha** [comment]
Please provide logs and full description.

**Comment by pendyala** [comment]
I followed the code snippets provided on the README of the project. I am able to search images from the docker hub public repo, but when I try to the same with our private repository I am not getting any positive response. I am not seeing any error, but an empty list. Below is the source code. 

import com.github.dockerjava.api.DockerClient;
import com.github.dockerjava.api.exception.DockerException;
import com.github.dockerjava.api.model.*;
import com.github.dockerjava.core.DockerClientBuilder;
import com.github.dockerjava.core.DockerClientConfig;
import com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl;

import java.util.List;
import java.util.Properties;

public class App {

  //public static final Logger LOG = LoggerFactory.getLogger( App.class );

  private DockerClient dockerClient;

  public App( ) {
    init( );
  }

  public static void main( String[] args ) {
    App app = new App( );

    try {
      app.getDockerInfo( );
      app.getDockerVersion( );
      app.searchDockerRepository( );
      //app.createContainer( );
      //app.listImage( );
      //app.listContainers( );
    } catch ( DockerException de ) {
      System.out.println( "Error DockerException !!! " + de );
    } catch ( Exception e ) {
      System.out.println( "Error Exception !!! " + e );
    }

  }

  private void init( ) {

    Properties dockerConfigurationProperties = new Properties( );
    dockerConfigurationProperties.put( "docker.io.url", "http://192.168.0.107:4243" );
    dockerConfigurationProperties.put( "docker.io.serverAddress", "https://xxxx.xxxx.xxxx.xxxx/v1/" );
    dockerConfigurationProperties.put( "docker.io.username", "xxxxxx" );
    dockerConfigurationProperties.put( "docker.io.password", "xxxxxxx" );
    dockerConfigurationProperties.put( "docker.io.email", "xxxxx@xxxxx.com" );

    try {
      DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder( )
        //.withUri( "http://192.168.0.107:4243" )
        //.withServerAddress( "https://xxxxx.xxxx.xxxx.xxxx/v1/" )
        //.withUsername( "xxxxx" )
        // .withPassword( "xxxxxx" )
        // .withEmail( "xxxx@xxxx.com" )
        .withProperties( dockerConfigurationProperties )
        .build( );

      DockerCmdExecFactoryImpl dockerCmdExecFactory = new DockerCmdExecFactoryImpl( )
        .withReadTimeout( 100000 )
        .withConnectTimeout( 100000 )
        .withMaxTotalConnections( 100 )
        .withMaxPerRouteConnections( 10 );

      dockerClient = DockerClientBuilder.getInstance( config )
        .withDockerCmdExecFactory( dockerCmdExecFactory )
        .build( );

      System.out.println( "Registry Address = " + config.getServerAddress( ) );

    } catch ( Exception e ) {
      System.err.println( "Error in initializing dockerClient " + e.getMessage( ) );
      e.printStackTrace( );
    }

  }

  public void searchDockerRepository( ) throws DockerException {
    System.out.println( "\n\nSEARCHING DOCKER REPOSITORY" );
    List< SearchItem > dockerSearch = dockerClient.searchImagesCmd( "magento-ssh" ).exec( );
    System.out.println( "Search returned" );
    System.out.println("DockerSearch = " + dockerSearch);
    for ( SearchItem searchItem : dockerSearch ) {
      System.out.println( "Description: " + searchItem.getDescription( ) );
      System.out.println( "Name: " + searchItem.getName( ) );
      System.out.println( "Official: " + searchItem.isOfficial( ) + "\n\n" );
    }

  }

  public void getDockerInfo( ) throws DockerException {
    System.out.println( "\n\nGETTING DOCKER INFO" );
    Info info = dockerClient.infoCmd( ).exec( );
    System.out.print( info );
  }

  public void getDockerVersion( ) throws DockerException {
    System.out.println( "\n\nGETTING DOCKER VERSION" );
    Version version = dockerClient.versionCmd( ).exec( );
    System.out.println( version.toString( ) );
  }

  /*public void createContainer( ) throws DockerException {

    System.out.println( "\n\nCREATE CONTAINER" );

    ContainerConfig containerConfig = new ContainerConfig( );
    containerConfig.setImage( "busybox" );
    containerConfig.setCmd( new String[]{ "true" } );

    ContainerCreateResponse container = dockerClient.createContainer( containerConfig );
    System.out.println( "Created container " + container.toString( ) + "  id = " + container.getId( ) );

    dockerClient.startContainer( container.getId( ) );

    ContainerInspectResponse containerInspectResponse = dockerClient.inspectContainer( container.getId( ) );
    System.out.println( "Container Inspect: " + containerInspectResponse.toString( ) );
  }*/

  public void listImage( ) throws DockerException {

    System.out.println( "\n\nIMAGES" );

    List< Image > images = dockerClient.listImagesCmd( ).exec( );
    //LOG.info ( "Images List: " + images );

    int size = images.size( );

    System.out.println( "================> Images Count= " + size + " <==========================" );

    for ( Image img : images ) {
      System.out.println( "Created = " + img.getCreated( ) );
      System.out.println( "Size = " + img.getSize( ) );
      System.out.println( "Virtual Size = " + img.getVirtualSize( ) );
      System.out.println( "Id = " + img.getId( ) );
      System.out.println( "Tag = " + img.getRepoTags( ) );

      System.out.println( "\n\n\n" );
    }

  }

  public void listContainers( ) throws DockerException {

    System.out.println( "\n\nCONTAINERS" );

    List< Container > containers = dockerClient.listContainersCmd( ).exec( );
    System.out.println( "Container List: " + containers );

    int size = containers.size( );

    System.out.println( "Containers = " + size );

    for ( Container container : containers ) {
      //System.out.println ( "ID = " + container.getId () + " Image = " + container.getImage () );
      //dockerClient.startContainer ( container.getId ());
      System.out.println( "Container [ " + container.getId( ) + " ] => " + container.toString( ) );
    }
  }
}

**Comment by pendyala** [comment]
I am using docker-java 3.0.0-SNAPSHOT version.

**Comment by marcuslinke** [comment]
@pendyala What kind of private registry do you use?

**Comment by marcuslinke** [comment]
I see your url has a /v1 posfix so I guess you use docker-registry v1, right? If so you have to configure a seach index backend when starting the registry.

**Comment by pendyala** [comment]
Yes we are using docker registry version 1. We did configure the docker registry to use sqlalchemy as search backend. Below is the snippet from the startup script

env SEARCH_BACKEND=sqlalchemy
env SQLALCHEMY_INDEX_DATABASE=sqlite:////tmp/docker-registry.db

Also I am able to search an image using curl, below is the example

curl -X GET https://dreg1.staging.str5.net/v1/search?q=magento-ssh
{"num_results": 1, "query": "magento-ssh", "results": [{"description": null, "name": "stratus5/magento-ssh"}]}

**Comment by marcuslinke** [comment]
Could you provide appropriate logs from docker daemon please? Maybe there any hints when compare  logging for both ways (curl vs. docker-java)...

**Comment by pendyala** [comment]
Here the registry logs

for curl operation

==> /var/log/docker-registry/access.log <==
127.0.0.1 - - [21/Jan/2016:11:55:19] "GET /v1/search?q=magento-ssh HTTP/1.0" 200 110 "-" "curl/7.35.0"

==> /var/log/docker-registry/server.log <==
2016-01-21 11:55:19,711 INFO: 127.0.0.1 - - [21/Jan/2016:11:55:19] "GET /v1/search?q=magento-ssh HTTP/1.0" 200 110 "-" "curl/7.35.0"

Where as I don't see any logs written when I try to search image via docker-java client.

**Comment by marcuslinke** [comment]
Hmmm. Strange... So it seems the request doesn't arrive the registry? How is authentication implemented for your registry? If you have a proxy service as described here (https://docs.docker.com/v1.7/registry/authentication/) the problem may be there. Could you provide the relevant parts of your application log please? If the request is logged there then it should arrive the registry. Otherwise it is probably a network related issue (like http proxy, authentication proxy or something like this).

**Comment by pendyala** [comment]
We have disabled the authentication for the registry in our staging environment. We have nginx in front of the registry acting as reverse proxy. Unfortunately I don't see any request coming to nginx (as per nginx logs).

**Comment by marcuslinke** [comment]
Does your application log show the search request when you configure debug level? See https://github.com/docker-java/docker-java/blob/master/src/test/resources/logback.xml

**Comment by marcuslinke** [comment]
OK. I was totally wrong. docker-java doesn't send request to the registry directly. It requests the docker host. Now I found this: https://github.com/docker/docker/issues/15552. It explains how to search private registries. So the search term should contain the registry: `myregistry.com/ubuntu`

**Comment by pendyala** [comment]
Perfect. Thanks a million @marcuslinke. myregistry.com/ubuntu as search term works.

**Comment by KostyaSha** [comment]
Of course you need specify domain/name to get image. Or you can fill in docker server config registries, afaik they will be asked one by one during search.

**Comment by pendyala** [comment]
How can we define pool of registries, can you please guide me on that. Thanks.

**Comment by KostyaSha** [comment]
I say something related in `/etc/sysconfig/docker` on centos installation.

**Comment by marcuslinke** [comment]
@pendyala Yor are welcome. Didn't know how to search private registries until now... Thanks for questioning! :-)
