### ISSUE TITLE
Remote API image creation speed

### ISSUE THREAD

**Issue by igorspasic** [docker-java/docker-java#431]
Hi, when I build images in a folder using the library, i got significantly slower results. Please see details on stack-overflow:

http://stackoverflow.com/questions/34912931/building-docker-images-via-remote-api-takes-significantly-more-time-then-from-co

**Comment by KostyaSha** [comment]
Duplicates https://github.com/docker-java/docker-java/pull/402

**Comment by KostyaSha** [comment]
But feel free to provde more information, your code, your file, your folder listing, docker-java version and etc. So we will be able to reproduce this issue.
