### ISSUE TITLE
multi-module structure

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#432]
@marcuslinke could you prepare it before 3.0.0?
As soon as shade will be fixed it will be possible to provide 'pom' artifact with all information required for shading and people will be able to set their custom prefix property after inheriting this parent pom.

**Comment by KostyaSha** [comment]
Or i can do it as i have experience :) Just need green light in any moment

**Comment by marcuslinke** [comment]
I would suggest this for 3.1.0. Next docker version is release candidate already so we should hurry up with 3.0.0 release.

**Comment by bsideup** [comment]
Delivered in 3.2.0
