### ISSUE TITLE
way to specify http auth

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#446]
Working on https://github.com/KostyaSha/yet-another-docker-plugin/issues/14
It seems that some users setting their custom "proxy" auth instances (i.e. nginx). The only possible username/password in configBuild is username/password that used for push/pull registry calls. 
It would make sense provide the way of setting custom auth for docker-java calls.

PS for `docker client` i found only way to set auth with `-H tcp://login:password@url:port/`

**Comment by marcuslinke** [comment]
Do you know how docker CLI solves this?

**Comment by KostyaSha** [comment]
At least `-H` works. AFAIK there is no anything in docker other than tls keys, but technically it shouldn't be a problem to do such support in library.

**Comment by marcuslinke** [comment]
So it should work with docker-java and configured url `tcp://login:password@url:port` also. Have you tried this already?

**Comment by KostyaSha** [comment]
Tried, but didn't work. Will try again.
