### ISSUE TITLE
Authentication configurations need to be refactored

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#452]
Currently the `DockerClientConfig` allows configuration of one credential only whereas various commands (push/pull for example) allows to pass multiple `AuthConfigurations` directly. 

See discussion here: https://github.com/docker-java/docker-java/pull/447/files#r52124195

**Comment by KostyaSha** [comment]
refactored, or reviewed, or didn't get idea of docker API organisation again :)

**Comment by marcuslinke** [comment]
Related: #316

**Comment by marcuslinke** [comment]
As stated there: 
> docker-java should only provide programmatic API for passing AuthConfigurations object to the appropriate commands. Reading and writing from/to config files should be handled externally.

**Comment by marcuslinke** [comment]
The problem here is that for integrations tests at least it needs some declarative configuration of auth.

**Comment by KostyaSha** [comment]
WDYM?

**Comment by KostyaSha** [comment]
:atm: i'm simulating auths with https://github.com/KostyaSha/yet-another-docker-plugin/pull/17/files#diff-1992f33eb51765f75ec68bad9620776dR188

**Comment by marcuslinke** [comment]
Integration tests for push/pull commands needs authentication for docker hub. This can't be hard-coded in the tests but must be read from a config file.

**Comment by KostyaSha** [comment]
Well, i'm not using docker hub for test, only container registry https://github.com/KostyaSha/yet-another-docker-plugin/pull/17/files#diff-1992f33eb51765f75ec68bad9620776dR37

**Comment by marcuslinke** [comment]
Really interesting. Maybe we could do the same in docker-java. But it uses TestNG...

**Comment by KostyaSha** [comment]
:atm: tests are ugly as i still searching better design for them. Junit's ExternalResource looks better. When they will be good i plan move part of them to docker-java.
What kinds of auth for pull/push application should support at all?
- username+password(+email?)
- tls?
- tokens like in .docker/config.json (where get them without login?)

**Comment by marcuslinke** [comment]
What do you mean? docker-java should only support AuthConfig as described here: https://docs.docker.com/engine/reference/api/docker_remote_api/#authentication

**Comment by marcuslinke** [comment]
I think `DockerClientConfigBuilder` or `DockerClient` should have a method to pass a resolver for `AuthConfig`s. This way we can abstract from any configuration source.

**Comment by marcuslinke** [comment]
But then there is a problem with serialization. `DockerClientConfig` can't be serialized anymore if it contains a provider object.

**Comment by KostyaSha** [comment]
@marcuslinke where serveraddr field from AuthConfig is used at all?
```
X-Registry-Auth – base64-encoded AuthConfig object, containing either login information, or a token

Credential based login:

{
    "username": "jdoe",
    "password": "secret",
    "email": "jdoe@acme.com",
}
Token based login:

{
    "registrytoken": "9cbaf023786cd7..."
}
```

**Comment by KostyaSha** [comment]
And our AuthConfig is missing registrytoken field then, i will send PR!

**Comment by marcuslinke** [comment]
`serveraddr` is currently used by the build command where X-Registry-Config must be generated. 

I'm currently trying to understand the token based authentication. (https://docs.docker.com/registry/spec/auth/token/#example) but I don't know how this "registrytoken" field fits into the described workflow.

**Comment by KostyaSha** [comment]
token is base64 of (login:password), email seems should be set manually (in
json config it exists)...
As i see for registry config you need either token either plain
login+password.
server looks unneed because server is in repo name.

2016-02-10 23:02 GMT+03:00 marcuslinke <notifications@github.com>:

**Comment by KostyaSha** [comment]
```
2.3 Misc
Check auth configuration
POST /auth

Get the default username and email

Example request:

POST /auth HTTP/1.1
Content-Type: application/json

{
     "username":" hannibal",
     "password: "xxxx",
     "email": "hannibal@a-team.com",
     "serveraddress": "https://index.docker.io/v1/"
}
```

**Comment by KostyaSha** [comment]
So, `X-Registry-Auth` needs other object?

**Comment by marcuslinke** [comment]
Right, `X-Registry-Config` may contain multiple credentials as for building images the FROM clause in the Dockerfile might reference a private registry.

**Comment by KostyaSha** [comment]
Should we introduce two objects `XRegistryConfig` and `XRegistryAuth` and use them?

**Comment by marcuslinke** [comment]
We currently have `AuthConfig` which corresponds to `X-Registry-Auth` and `AuthConfigurations` which is used for `X-Registry-Config`.

I think the `DockerClientConfig` should be configurable with a provider object the returns something like `AuthConfigurations` that is basically a map with the registry address as key and an 'AuthConfig' like object as value. `AuthConfig` could be an interface then that abstracts from credential or token based authentication. Don't know if that really works...

**Comment by KostyaSha** [comment]
`AuthConfig` doesn't correspond to X-Registry-Auth because it has redundant field and has no token field.
`XRegistryConfig` may container `XRegistryConfigAuth`. My idea to get closer to API objects and names while we don't know ideal solution.
What is `effectiveAuthConfig`? Resolver for auth for some server?

**Comment by KostyaSha** [comment]
1.22 change
```
AuthConfig now supports a registrytoken for token based authentication
```

**Comment by KostyaSha** [comment]
FYI https://github.com/docker/docker/pull/20565

**Comment by KostyaSha** [comment]
Now i can't remember again what auth should look like...
