### ISSUE TITLE
Support docker update in 1.10

### ISSUE THREAD

**Issue by wouterhund** [docker-java/docker-java#455]
Command line docs: https://docs.docker.com/engine/reference/commandline/update/
API docs: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#update-a-container

This API lets you update a container's resource constraints while it is running, which is an addition in the recently released docker-engine 1.10.

**Comment by KostyaSha** [comment]
Thanks for reminder but we already know about release. Library is cares about docker API versions and not docker engine versions. atm we are syncing and releasing 1.21. 1.22 will be reviewed and released later in 3.1.0. 

Keeping in mind that we already have issues with 1.22 features updates. closing issue as duplicated.
