### ISSUE TITLE
DockerCmdExecFactoryImpl change uri inside DockerClientConfig during init ...

### ISSUE THREAD

**Issue by mbaechler** [docker-java/docker-java#456]
and this breaks support for unix socket.

The problem is that once you called `DockerCmdExecFactoryImpl.init()` once with a configuration containing uri : `unix:///var/run/docker.sock` , you can't reuse the configuration for a second `DockerCmdExecFactoryImpl` instance, because the new value set into `DockerClientConfig` is not supported but `init()` method.

The obvious fix is to prevent configuration from being modified.

I'll propose a PR soon.

**Comment by marcuslinke** [comment]
Closed via https://github.com/docker-java/docker-java/pull/457 and https://github.com/docker-java/docker-java/pull/465
