### ISSUE TITLE
Docker Swarm Inspect Container Info

### ISSUE THREAD

**Issue by gerdogdu** [docker-java/docker-java#458]
When using Docker Swarm Host, containers/{id}/json does not contain Node information and some other details. When using Swarm Remote API, the returned JSON is dfferent from docker-json response.
I looked at ﻿InspectContainerReponse and it does not include Node info.

**Comment by marcuslinke** [comment]
Duplicates https://github.com/docker-java/docker-java/pull/383 as well as https://github.com/docker-java/docker-java/issues/395
