### ISSUE TITLE
Release alpha version from master

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#460]
@marcuslinke could you release 3.0.0-alpha1 from master? That should allow people switch to tagged version and produce some test results. 
PS can i do somehow releases?

**Comment by marcuslinke** [comment]
I thought about this also some days ago as the 3.0.0 milestone due date is 15th of february...  So we should branch to `3.0.0-alpha1` after release it, right?

For making releases you must have some credentials/gpg keys. If you want I can give it to you.

**Comment by KostyaSha** [comment]
for alpha releases you don't need branches. You just do release processes as
3.0.0-SNAPSHOT -> 3.0.0-alpha1
next dev version, back -> 3.0.0-SNAPSHOT
(note, not 3.0.0-alpha2-SNAPSHOT that may propose maven-release-plugin)

**Comment by marcuslinke** [comment]
Wouldn't it be better to have a named commit for easier access to the sources? The branch could be removed after final release then.

**Comment by KostyaSha** [comment]
maven-release-plugin do tags automatically.

**Comment by KostyaSha** [comment]
@marcuslinke do you have docker container for building release?

**Comment by KostyaSha** [comment]
@marcuslinke could you point on some documentation on how releasing? Is it done with maven central or bintray?

**Comment by KostyaSha** [comment]
@marcuslinke i updated instructions.

**Comment by KostyaSha** [comment]
As soon as alpha will be released you may call for testing (i.e. i will migrate to it my plugin and start testing). Then wait for some time to get feedback and later finally release 3.0.0. WDYT?

**Comment by KostyaSha** [comment]
CC @cdancy am i right remember that you also producing some plugins for end users? Would you like join such testing?

**Comment by cdancy** [comment]
@KostyaSha that is correct. I'm a contributor for https://github.com/bmuschko/gradle-docker-plugin. Sure I can run through your guys test suite whenever you think things are ready. We are actually waiting on this next release so plugging that into our plugin, and running our test suite, will be a good indication of things as well. Let me know.

**Comment by marcuslinke** [comment]
@KostyaSha No container right now. I'm on MacOS so it's a bit difficult as docker doesn't run natively here. Beside this lets call it 3.0.0.RC1. I will prepare release tomorrow.

**Comment by KostyaSha** [comment]
@marcuslinke https://www.docker.com/products/docker-toolbox ;-) Should be TODO for having container to get reproducible builds (creds can be mounted with volume i think). Plus publishing build logs somewhere would be good...

**Comment by marcuslinke** [comment]
3.0.0-RC1 should arrive maven central in a few hours. I've also releases v2.2.0 today.

**Comment by cdancy** [comment]
@marcuslinke difference between 2.2.0 and 3.0.0?

**Comment by KostyaSha** [comment]
2.2.0 has only bugfixes, 3.0.0 new features and refactorings

**Comment by KostyaSha** [comment]
@marcuslinke btw, did you get my messages about bintray?
