### ISSUE TITLE
Exec start command: end of STDIN stream not detected

### ISSUE THREAD

**Issue by rtimush** [docker-java/docker-java#471]
When `docker exec` is invoked from command line like this the end of input stream is properly detected and `cat` process finishes:
```
$ echo OK | docker exec -i some_busybox_container cat
OK
$
```
When I try to do the same with docker-java, the end of stream is not detected and `cat` process waits forever. This problem is not caught by com.github.dockerjava.netty.exec.ExecStartCmdExecTest#execStartAttachStdin test because `.awaitCompletion(5, TimeUnit.SECONDS)` doesn't fail if the process is not completed.

**Comment by marcuslinke** [comment]
@rtimush Thanks for reporting. Simply don't know how this could be implemented yet.

**Comment by marcuslinke** [comment]
Hmmm. Maybe we have to pass `CTRL-D` (EOF) character downstream?

**Comment by rtimush** [comment]
I tried "\u0004" (EOF), "\n\n", "\r\r", "\u0000" but without luck — they are copied by `cat` to stdout as ordinary characters and the process doesn't end.

**Comment by rtimush** [comment]
If I read docker sources correctly, it invokes "CloseWrite" on socket when stream ends. This moves tcp connection to a half-closed mode with write side closed but read side open to transfer stdout/stderr.

**Comment by rtimush** [comment]
It seems that the following code works:
```java
((NioSocketChannel)channel).shutdownOutput();
```

**Comment by marcuslinke** [comment]
Great! So we have to detect end of stdin `InputStream` and trigger that method then. Could you provide a PR for this please?

**Comment by rtimush** [comment]
Yes, will do.

**Comment by marcuslinke** [comment]
Thanks. Besdide this, could you provide a link for the appropriate docker sources here please?

**Comment by rtimush** [comment]
Somewhere over there: https://github.com/docker/docker/blob/v1.10.1/api/client/hijack.go#L34

**Comment by gerdogdu** [comment]
This is also problem in JAXRS versiob of ExecStart. awaitCompletion never returns

**Comment by marcuslinke** [comment]
@gerdogdu JAX-RS version of ExecStart doesn't support STDIN redirection to container. This is the main reason for introducing the whole netty implementation.
I would suggest to switch to netty impl as this will supersede the JAX-RS based one with one of the next releases. Therefore I don't want invest too much in fixing JAX-RS impl. Is this an option for you?
