### ISSUE TITLE
BuildImage call returns 500 error 

### ISSUE THREAD

**Issue by randomnumber12345** [docker-java/docker-java#489]
Hi,
I use latest API 3.0.0RC2 (also tried 2.2.1) to build image such as:

    	         File baseDir = new File(dockerfilePath);
		String imageId = client.buildImageCmd(baseDir).withNoCache(true)
				 .exec(new BuildImageResultCallback()).awaitImageId();

I am sure the file path is valid. I put debugging print there and I verified it. 
Also I know the client is instantiated properly. Since I can call startContainerCmd() command to succesfully start container.

But WHY do I get error for building image?
Below is the error message. I notice the POST command missed the image name. WHY is that?
thanks.

INFO[1601] POST /v1.19/build?nocache=true&rm=true
ERRO[1601] Handler for POST /build returned error: EOF
ERRO[1601] HTTP Error                                    err=EOF statusCode=500

**Comment by marcuslinke** [comment]
@randomnumber12345 What docker version do you use? What is the content of the basedir?

For reference: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.19/#build-image-from-a-dockerfile

**Comment by randomnumber12345** [comment]
@marcuslinke 
I use docker 1.7
basedir is a directory, which I put  /home/userxxx/ for now.
inside, there is a Dockerfile which has only one simple line "FROM busybox"

I read the link you posted. Seems from error 500, it could not tell much info...

**Comment by KostyaSha** [comment]
1.7 unreally ancient and i would say that we doesn't support it.

**Comment by randomnumber12345** [comment]
1.7.1  is released (2015-07-14) ... you call it ancient????.....

**Comment by KostyaSha** [comment]
Date doesn't matter 1.8, 1.9 and 1.10 are available today with 3 different API versions and features.

**Comment by randomnumber12345** [comment]
@KostyaSha 
Put docker version aside, do you think this call generated by docker-java is right?

POST /v1.19/build?nocache=true&rm=true
Where is the Dockerfile information?? I think that parameter is missed. And that has nothing to do with Docker server.

**Comment by KostyaSha** [comment]
@randomnumber12345 please read upstream docs https://docs.docker.com/engine/reference/api/docker_remote_api_v1.19/#build-image-from-a-dockerfile call is right and works on 1.20, 1.21 API  If if complains about EOF, then you specified something wrong for baseDir. Please attach directory listing and debugger screenshot. Are you sure that `baseDir` points to base dir where Dockerfile is placed?

**Comment by randomnumber12345** [comment]
I got this error from this client :

Cached exceptioncom.github.dockerjava.api.exception.DockerClientException: Error occurred while preparing Docker context folder.

When I do "ls" , I do see my Dockerfile with content "FROM busybox"
 % ls
Dockerfile

**Comment by marcuslinke** [comment]
Maybe this is a file permission issue then?

**Comment by randomnumber12345** [comment]
@marcuslinke  file permission is checked, no issue.

from this docker doc:  dockerfile - Path within the build context to the Dockerfile. 
Seems dockerfile parameter is required. 

Actually, If I use docker cli to do same thing, I am able to create image. And from docker daemon debugging info I can see this:

POST /v1.19/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=noname

you can see, the correct one contains dockerfile parameter....

**Comment by KostyaSha** [comment]
```
The archive must include a build instructions file, typically called Dockerfile at the archive’s root. The dockerfile parameter may be used to specify a different build instructions file. To do this, its value must be the path to the alternate build instructions file to use.
```

**Comment by randomnumber12345** [comment]
okay. so you guys are saying this library does not support docker 1.7.1 right?

**Comment by randomnumber12345** [comment]
this error comes from this client code "Error occurred while preparing Docker context folder."
can you share some insights what does it really mean? What error occurred while preparing context folder?

**Comment by KostyaSha** [comment]
that's your `baseDir` please provide screenshots of your debugger under breakpoint.

**Comment by randomnumber12345** [comment]
@KostyaSha  thank you for your info. Though, we don't use any debugger for testing. And I have provided that error message I saw from our log. And I even give that baseDir 777 access level. And I did verify Dockerfile was there. Still a mystery to me... Thank you for help.

**Comment by KostyaSha** [comment]
We are trying to make compatible tests and code, so in future (i hope) we will have longer backward compatible tests...

**Comment by randomnumber12345** [comment]
surprised  to see you said that. coz  from your README , you guys said  
"Supports a subset of the Docker Remote API v1.19, Docker Server version 1.7.x"
in second line.

**Comment by KostyaSha** [comment]
README is from master and master is in progress of rework. As soon as you found issue we will deprecate old version and merge new staff. We are working at evenings so it bit slow :(
