### ISSUE TITLE
Update jersey with the fix 

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#491]
@marcuslinke code mentions workaround for https://java.net/jira/browse/JERSEY-2852
https://github.com/jersey/jersey/pull/164 that was already resolved in released versions https://github.com/jersey/jersey/releases/tag/2.22.2 .

@marcuslinke could you review and update it? Maybe it will help with my TTY/hijack issues...

**Comment by KostyaSha** [comment]
Or would you wait just to remove jersey from library at all?

**Comment by marcuslinke** [comment]
Right. I don't think its worth to switch to new jersey version.

**Comment by KostyaSha** [comment]
They removed https://github.com/jersey/jersey/commit/10800f621b92e23bfe23b62013a6771ed5953c00#diff-b74fc7ce04e2f68cc60f86b10c2697f0
`ApacheClientProperties.SSL_CONFIG`

**Comment by KostyaSha** [comment]
updated in master!
