### ISSUE TITLE
Expose RepoTags from inspect image command

### ISSUE THREAD

**Issue by davidtnorth** [docker-java/docker-java#493]
docker inspect <image> includes a field like so:

        "RepoTags": [
            "my-registry.example.com:5000/imageName:tag"
        ],

It would be very useful if the inspect image command exposed this - I think it just needs adding to InspectImageResponse.

**Comment by KostyaSha** [comment]
What library version do you use?

**Comment by davidtnorth** [comment]
3.0.0-RC1
