### ISSUE TITLE
InputStream returned on execution of copy file/archive command skips 0xFF bytes

### ISSUE THREAD

**Issue by tejksat** [docker-java/docker-java#496]
For Netty implementation `DockerClient.copyFileFromContainerCmd().exec()` and `DockerClient.copyArchiveFromContainerCmd().exec()` returns `InputStream` that skips all 0xFF bytes. This results in malformed downloaded tar archives.

Check [HttpResponseStreamHandler.java:84](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/netty/handler/HttpResponseStreamHandler.java#L84) where `current.readByte()` may return `-1` which for `InputStream.read()` means _there is no more data because the end of the stream has been reached_. Could be fixed with returning `current.readByte() & 0xFF`.

**Comment by KostyaSha** [comment]
Could you provide a test case and fix?

**Comment by tejksat** [comment]
@KostyaSha sure, within a day.

**Comment by marcuslinke** [comment]
Fixed by merging https://github.com/docker-java/docker-java/pull/501
