### ISSUE TITLE
Docker-Java does not publish ports when run against docker swarm

### ISSUE THREAD

**Issue by nfoonf** [docker-java/docker-java#497]
Docker-Build-Step, a jenkins-plugin using docker-java is unable to publish ports of a started container when run against the swarm-API. As it is totally capable of this when run against normal docker-API this seems to be a problem related to docker-java and it's swarm support, as the plugin is not aware of the difference and uses the same codepaths.

Running: 
Docker-engine 1.10.2
Docker-Swarm 1.1.3
Jenkins ver. 1.642.2 inside Docker Container with all default config
org.jenkins-ci.plugins:docker-build-step:1.34 Plugin

**Comment by KostyaSha** [comment]
Sorry, this project is not about jenkins plugins. Please try reproduce your issue with plain docker-java.
