### ISSUE TITLE
docker-java doesn't work 'out of the box' with v2 registries

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#506]
There's some hacky looking code in AbstrDockerCmdExec.registryConfigs() that uses the dockerClientConfig version to decide whether or not to wrap the X-Registry-Config header base64 encoded json in a 'configs' subobject or not.  If the version is greater or equal to v1.19, it doesn't wrap, otherwise, it does.  Apparently, the v1.19 remote api is being used as a proxy for whether or not the registry api is v2 or v1, and the v2 api doesn't want the 'configs' wrapper.

However, the default remote api version for the library is UNKNOWN_VERSION, and so this fails 'out of the box' when you have a v2 registry.  You have to explicitly set the remote api version to some v1.19+ value for things to work.  If docker-java is several layers down the software stack from you, this is a royal pain.

**Comment by KostyaSha** [comment]
I think i fixed it as part of #488 please try `3.0.0-RC3` version.

**Comment by llamahunter** [comment]
Unfortunately, there have been a number of breaking API changes in 3.0.0, and the intervening library between myself and docker-java (gradle-docker-plugin) has not yet been adapted to support them.

**Comment by KostyaSha** [comment]
@llamahunter would you able to create some branch in your plugin and try migrate to 3.0.0. Also i would suggest to try netty implementation because it provides new features. We would be glad to here 3.0.0-rc* feedbacks before releasing final 3.0.0

**Comment by llamahunter** [comment]
I'm not the owner of the gradle-docker-plugin.  Unfortunately, they dynamically bind to the docker-java api using reflection, so porting to 3.0.0 is not exactly straightforward, as the compiler is no help in determining what APIs have changed.  See https://github.com/bmuschko/gradle-docker-plugin/issues/180

**Comment by KostyaSha** [comment]
Feel free to ask if you have any issues, most things should be intuitive. We following naming like in api and some setters changed to with* fluent builders. That shouldn't be so hard to do migration.
