### ISSUE TITLE
CertificateUtils.verifyCertificatesExist() is not working correctly

### ISSUE THREAD

**Issue by Hendrik-H** [docker-java/docker-java#508]
[CertificateUtils.verifyCertificatesExist()](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/util/CertificateUtils.java) should check for the existence of three pem files but actually only tests for the first one. When you cert directory only contains the `ca.pem` file the code consequently crashes later on as `createKeyStore` first reads in the `key.pem` file.

A fix could look like this:

```
public static boolean verifyCertificatesExist(String dockerCertPath) {
    String[] files = {"ca.pem", "cert.pem", "key.pem"};
    boolean result = true;
    for (String file : files) {
        File path = new File(dockerCertPath, file);
        result &= path.exists();
    }

    return result;
}
```

**Comment by KostyaSha** [comment]
Could you PR fix?

**Comment by Hendrik-H** [comment]
The above code change fixed the issue for me. I have to first ask to for approval before I get contribute a fix, same as for the other issue. Once I have that I can create a fork and fix it unless you don't just want a diff.

**Comment by KostyaSha** [comment]
Please pull request changes + create some test case to not have this issue in future again.
