### ISSUE TITLE
container shell command and set static ip for container

### ISSUE THREAD

**Issue by luoyunpeng** [docker-java/docker-java#524]
how to execute container shell command for running container with docker-java?
how to set static ip for container?

**Comment by marcuslinke** [comment]
See https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/netty/exec/ExecStartCmdExecTest.java#L126 how to execute command in running container. To make it work you have to configure netty implementation of 'DockerCmdExecFactory' like described here https://github.com/docker-java/docker-java/wiki#intialize-docker-client-advanced

What do you mean with static container ip? The container simply exposes its services to the outside through the ip of the docker host its running on.

**Comment by luoyunpeng** [comment]
I want to get a static ip for a container with Docke-java .like Docker Engine command  -ip=....,when we use docker run command，

**Comment by KostyaSha** [comment]
If it run, then configure in create command.

**Comment by luoyunpeng** [comment]
But i do not find it in create command，just like docker.createContainerCmd("centos").withIPaddress(".........").exec;

**Comment by marcuslinke** [comment]
I think this is realized via https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#connect-a-container-to-a-network in the docker CLI somehow but that is just a guess. Why do you need assign such a static ip? What is it useful for?

**Comment by KostyaSha** [comment]
Why `connect to container`? He just need configure HostConfig AFAIR in create to have static ip.

**Comment by luoyunpeng** [comment]
Ｉwant the static ip with container for building my DB cluster easier with docker, and it is ok for bind static ip for Docker Engine 1.10.x

**Comment by marcuslinke** [comment]
@KostyaSha Can't find appropriate field in `HostConfig`

**Comment by KostyaSha** [comment]
Then i would guess it moved to network configuration in 1.22 API.

**Comment by KostyaSha** [comment]
In any case it should be possible to run wireshark and dump `follow->tcp stream` executed docker cli command targeted to unsecured daemon connection (`-H`). 

Sound like i need document such things...
