### ISSUE TITLE
Fail to use docker-java3.0.0-RC3

### ISSUE THREAD

**Issue by luoyunpeng** [docker-java/docker-java#530]
It is ok to run with this,
@Test
	public void buildDockerClientWithSocker() {
		docker = DockerClientBuilder.getInstance("unix:///var/run/docker.sock")
				.build();
	}
But when  i run 
@Test
	public void buildDockerClientWithSocker() {
		docker = DockerClientBuilder.getInstance("unix:///var/run/docker.sock")
				.build();
		docker.stopContainerCmd("coord").exec();

	}
It failed ,
(Permission denied (socket: /run/docker.sock) )

**Comment by KostyaSha** [comment]
> Permission denied (socket: /run/docker.sock) )

It's not a library issue. Ensure that you have right permissions on socket.

**Comment by luoyunpeng** [comment]
Yes i did it ,but i still failed to run the test demo
![image](https://cloud.githubusercontent.com/assets/17898126/14075003/f7fbebe6-f507-11e5-8fff-23118a1737e7.png)
the Docker Engine is on centos 7 and the kernel version is 3.10 ,and should i update to 3.18?
