### ISSUE TITLE
Thread-safety and pooling

### ISSUE THREAD

**Issue by bsideup** [docker-java/docker-java#536]
Hi!

I saw some work on Netty, so I want to update the status of my questions:

- [ ] Is it safe to re-use DockerClient now?
- [ ] If not, is there any pooling or something?

Thanks!

**Comment by KostyaSha** [comment]
https://github.com/docker-java/docker-java/pull/488#issuecomment-192381580 and  https://github.com/spotify/docker-client/issues/258#issuecomment-164514078 threads need to be checked again. Hope some fix appeared.

**Comment by marcuslinke** [comment]
@KostyaSha I don't see any relation to threading. Could you explain please?
@bsideup At least when using the netty impl, `DockerClient` SHOULD be thread safe as long as command objects aren't shared between threads. Netty itself manages it own thread pool for processing and guarantuees that handlers are not called concurrently. Currently there is no connection pooling/reuse implemented, so chances are high that it is thread safe.

**Comment by bsideup** [comment]
@marcuslinke oh, cool :) Any ETA of Netty-based implementation?

**Comment by KostyaSha** [comment]
@marcuslinke ` Is it safe to re-use DockerClient now` if connection problem isn't fixed, then no.

**Comment by marcuslinke** [comment]
@bsideup It's already there in 3.0.0-RC4 but must be configured manually. See https://github.com/docker-java/docker-java/wiki#intialize-docker-client-advanced to get an idea how to configure the netty impl of `DockerCmdExecFactory` into the client instance. It will replace the jersey impl sometimes.

**Comment by marcuslinke** [comment]
@KostyaSha I probably don't understand the problem as you already did. As I understand netty impl is not reusing connections currently so how the error should occur then. Or is it a problem of server side connection pooling only?

**Comment by KostyaSha** [comment]
As i see all clients made workaround fixes. Fine if it works with netty without issues.
