### ISSUE TITLE
Conflicting getter definitions for property "OomKillDisable"

### ISSUE THREAD

**Issue by mradamczyk** [docker-java/docker-java#539]
I'm trying to create docker using docker-java api 3.0.0-RC4. Unfortunately I'm getting such error:

```
[ForkJoinPool-1-worker-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (com.fasterxml.jackson.databind.JsonMappingException) caught when processing request to {s}->__IP__: Conflicting getter definitions for property "OomKillDisable": com.github.dockerjava.api.model.HostConfig#getOomKillDisable(0 params) vs com.github.dockerjava.api.model.HostConfig#isOomKillDisable(0 params) (through reference chain: com.github.dockerjava.core.command.CreateContainerCmdImpl["HostConfig"])'`
```
I'm not sure if I'm doing sth wrong or it's a problem with dockerjava implementation.

Here is what Docker daemon writes to console:
```
Apr  8 16:17:35 b-worker docker[21567]: time="2016-04-08T16:17:35.533645803Z" level=error msg="Handler for POST /v1.22/containers/create returned error: unexpected EOF"
```

https://groups.google.com/d/msg/docker-java-dev/gfzC2AcsIso/GAIgJBjGAAAJ

**Comment by KostyaSha** [comment]
@marcuslinke Why mapper complain about getters while annotation defined only on field?

**Comment by KostyaSha** [comment]
So the hostconfig is part of create cmd that i can't test serialisation-deserilization. Making PR with the fix.

**Comment by KostyaSha** [comment]
#540 should be the fix

**Comment by mradamczyk** [comment]
Thanks! #540 fix my problem.
