### ISSUE TITLE
GrailsContextLoaderListener  - Error initializing the application

### ISSUE THREAD

**Issue by AneesUrRehman** [docker-java/docker-java#543]
I appliied Docker-Java in my project , but when i add 
class DockerService {
DockerClient dockerClient = DockerClientBuilder.getInstance("http://localhost:2375").build();

Then its shows the error.............
..............................................................................................................................................................

| Running Grails application
| Error 2016-04-11 10:36:52,230 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'docker.DockerController': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dockerService': Cannot create inner bean '(inner bean)#50b18630' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#50b18630': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
Message: Error creating bean with name 'docker.DockerController': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dockerService': Cannot create inner bean '(inner bean)#50b18630' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#50b18630': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
    Line | Method
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanCreationException: Error creating bean with name 'dockerService': Cannot create inner bean '(inner bean)#50b18630' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#50b18630': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanCreationException: Error creating bean with name '(inner bean)#50b18630': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by NoClassDefFoundError: com/google/common/base/Preconditions
->>  373 | withDockerHost in com.github.dockerjava.core.DockerClientConfig$DockerClientConfigBuilder
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    362 | withProperties in     ''
|    228 | createDefaultConfigBuilder in com.github.dockerjava.core.DockerClientConfig
|    217 | createDefaultConfigBuilder in     ''
|    141 | configWithServerUrl in com.github.dockerjava.core.DockerClientImpl
|    132 | <init>    in     ''
|    153 | getInstance in     ''
|     31 | getInstance in com.github.dockerjava.core.DockerClientBuilder
|      6 | <init> .  in docker.DockerService
|    262 | run       in java.util.concurrent.FutureTask
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
Caused by ClassNotFoundException: com.google.common.base.Preconditions
->>  366 | run       in java.net.URLClassLoader$1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    355 | run       in     ''
|    354 | findClass in java.net.URLClassLoader
|    425 | loadClass in java.lang.ClassLoader
|    373 | withDockerHost in com.github.dockerjava.core.DockerClientConfig$DockerClientConfigBuilder
|    362 | withProperties in     ''
|    228 | createDefaultConfigBuilder in com.github.dockerjava.core.DockerClientConfig
|    217 | createDefaultConfigBuilder in     ''
|    141 | configWithServerUrl in com.github.dockerjava.core.DockerClientImpl
|    132 | <init>    in     ''
|    153 | getInstance in     ''
|     31 | getInstance in com.github.dockerjava.core.DockerClientBuilder
|      6 | <init> .  in docker.DockerService
|    262 | run       in java.util.concurrent.FutureTask
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
| Error Forked Grails VM exited with error
| Server running. Browse to http://localhost:8080/DOCKER
root@Lenovo-B570e:~/Documents/DOCKER# ^C
| Downloading: org/hibernate/hibernate-ehcache/3.6.10.Final/hibernate-ehcache-3.| Downloading: org/hibernate/hibernate-parent/3.6.10.Final/hibernate-parent-3.6.| Downloading: org/hibernate/hibernate-core/3.6.10.Final/hibernate-core-3.6.10.F| Downloading: org/hibernate/hibernate-commons-annotations/3.2.0.Final/hibernate| Downloading: org/hibernate/javax/persistence/hibernate-jpa-2.0-api/1.0.1.Final| Downloading: org/grails/grails-datastore-gorm-hibernate/3.1.2.RELEASE/grails-d| Downloading: javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.| Downloading: org/hibernate/hibernate-validator/4.1.0.Final/hibernate-validator| Downloading: org/hibernate/hibernate-validator-parent/4.1.0.Final/hibernate-va| Downloading: org/hibernate/hibernate-entitymanager/3.6.10.Final/hibernate-enti| Downloading: org/hibernate/hibernate-ehcache/3.6.10.Final/hibernate-ehcache-3.| Downloading: javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.| Downloading: org/hibernate/hibernate-validator/4.1.0.Final/hibernate-validator| Downloading: org/hibernate/hibernate-core/3.6.10.Final/hibernate-core-3.6.10.F| Downloading: org/grails/grails-datastore-gorm-hibernate/3.1.2.RELEASE/grails-d| Downloading: org/hibernate/hibernate-entitymanager/3.6.10.Final/hibernate-enti| Downloading: org/hibernate/hibernate-commons-annotations/3.2.0.Final/hibernate| Uninstalled plugin [hibernate4]
| Compiling 121 source files

| Running Grails application
| Error 2016-04-11 11:04:10,519 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'docker.DockerController': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dockerService': Cannot create inner bean '(inner bean)#48e4d3df' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#48e4d3df': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
Message: Error creating bean with name 'docker.DockerController': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dockerService': Cannot create inner bean '(inner bean)#48e4d3df' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#48e4d3df': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
    Line | Method
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanCreationException: Error creating bean with name 'dockerService': Cannot create inner bean '(inner bean)#48e4d3df' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#48e4d3df': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanCreationException: Error creating bean with name '(inner bean)#48e4d3df': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanDefinitionStoreException: Factory method [public java.lang.Object org.codehaus.groovy.grails.commons.AbstractGrailsClass.newInstance()] threw exception; nested exception is org.codehaus.groovy.grails.exceptions.NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by NewInstanceCreationException: Could not create a new instance of class [docker.DockerService]!
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by NoClassDefFoundError: com/google/common/base/Preconditions
->>  373 | withDockerHost in com.github.dockerjava.core.DockerClientConfig$DockerClientConfigBuilder
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    362 | withProperties in     ''
|    228 | createDefaultConfigBuilder in com.github.dockerjava.core.DockerClientConfig
|    217 | createDefaultConfigBuilder in     ''
|    141 | configWithServerUrl in com.github.dockerjava.core.DockerClientImpl
|    132 | <init>    in     ''
|    153 | getInstance in     ''
|     31 | getInstance in com.github.dockerjava.core.DockerClientBuilder
|      6 | <init> .  in docker.DockerService
|    262 | run       in java.util.concurrent.FutureTask
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
Caused by ClassNotFoundException: com.google.common.base.Preconditions
->>  366 | run       in java.net.URLClassLoader$1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    355 | run       in     ''
|    354 | findClass in java.net.URLClassLoader
|    425 | loadClass in java.lang.ClassLoader
|    373 | withDockerHost in com.github.dockerjava.core.DockerClientConfig$DockerClientConfigBuilder
|    362 | withProperties in     ''
|    228 | createDefaultConfigBuilder in com.github.dockerjava.core.DockerClientConfig
|    217 | createDefaultConfigBuilder in     ''
|    141 | configWithServerUrl in com.github.dockerjava.core.DockerClientImpl
|    132 | <init>    in     ''
|    153 | getInstance in     ''
|     31 | getInstance in com.github.dockerjava.core.DockerClientBuilder
|      6 | <init> .  in docker.DockerService
|    262 | run       in java.util.concurrent.FutureTask
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
| Error Forked Grails VM exited with error

**Comment by marcuslinke** [comment]
According to `Caused by ClassNotFoundException: com.google.common.base.Preconditions` you probably have the wrong google guice library in your classpath. Or it is missing at all. You have to ensure that all docker-java runtime dependencies are in the classpath.
