### ISSUE TITLE
Question: If Docker API returns an error, what happens?

### ISSUE THREAD

**Issue by AndrewGuenther** [docker-java/docker-java#544]
I've been trying to tear through the 30 layers of abstraction, but it is proving near impossible to decipher what is going on.

All I want to know is what happens if the remote API returns an error.

**Comment by marcuslinke** [comment]
If the remote API returns with an http error state a `DockerException` is thrown. There are some specialized subclasses of `DockerException` like `InternalServerErrorException` for example (see https://github.com/docker-java/docker-java/tree/master/src/main/java/com/github/dockerjava/api/exception for details)

**Comment by marcuslinke** [comment]
You could also enable debug logging of docker-java by putting this [file](https://github.com/docker-java/docker-java/blob/master/src/test/resources/logback.xml) in your classpath.
