### ISSUE TITLE
Start container by swarm report error: memory.swappiness: invalid argument

### ISSUE THREAD

**Issue by c2j** [docker-java/docker-java#545]
Cannot start container 158a4580766e384afa64e2bf5f19cf6ec4e345cb3d54b27dd7aa5de08c582958: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker/158a4580766e384afa64e2bf5f19cf6ec4e345cb3d54b27dd7aa5de08c582958/memory.swappiness: invalid argument

Direct start container by docker engine without this issue.

May related with swarm?

**Comment by marcuslinke** [comment]
I think this is related: https://github.com/docker/swarm/issues/1411

**Comment by KostyaSha** [comment]
@c2j is it still actual?

**Comment by KostyaSha** [comment]
no reply
