### ISSUE TITLE
inspectContainerCmd compatible with docker-swarm

### ISSUE THREAD

**Issue by qingmo** [docker-java/docker-java#546]
after compare restful api of docker and swarm. the only difference is in
{
...
  "Node": {
    "ID": "ZN3S:DPLW:2PXV:KIL7:2ARF:IH4P:T4SD:CI3D:XW2Z:3BPH:SB6I:3XMC",
    "IP": "10.5.5.54",
    "Addr": "10.5.5.54:2375",
    "Name": "lab54",
    "Cpus": 4,
    "Memory": 8083677184,
    "Labels": {
      "executiondriver": "native-0.2",
      "kernelversion": "3.10.0-327.10.1.el7.x86_64",
      "operatingsystem": "CentOS Linux 7 (Core)",
      "storagedriver": "devicemapper"
    }
  },
...
}

can i implement those json property by myself in com.github.dockerjava.api.command.InspectContainerResponse just like inner class Mount. then make a pull request?

**Comment by KostyaSha** [comment]
Hi we would really want to end 3.0.0 and we have only network api unimplemented. We planned swarm for the next version. So i not sure. You could also point docker-java on previous API version and get mounts in old format and this way should work.

**Comment by igorspasic** [comment]
Hey @KostyaSha I do understand, but can you at least map this Node field from JSON to something that is readable in Java? I mean, this one is really kind of important, and for the first time it can be just matter of mapping?

**Comment by crazyproger** [comment]
@KostyaSha please create 3.1.0-RC version as fork of current 3.0.0-RC with `Node` field in it.

**Comment by KostyaSha** [comment]
Duplicates #383
