### ISSUE TITLE
docker api v1.23 support

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#552]
Fun times... docker released a new API version with docker machine v1.11.  I realize that docker-java is still working towards the 3.0.0 release for api v1.22, but is there a general timeline for new api support?

In the meantime, holding off my developers from rushing forward to the latest and greatest.

**Comment by KostyaSha** [comment]
Please remember that you can target docker-java to specific API version by setting it explicitly in client. That shouldn't block you from updating daemons!

**Comment by llamahunter** [comment]
hmm... yes, now that I added such support in gradle-docker-plugin, to work around the problems in docker-java 2.2.3 described in #506, I suppose it's a non issue as far as developer upgrades go.  Still, it would be good to add v1.23 support someday.

fyi... gradle-docker-plugin is waiting for the release of 3.0.0 before they can pull the likely fix for #506

**Comment by KostyaSha** [comment]
I can suggest start using RCs, in fact we are missing only network API (too difficult to implement tests) and netty seems wouldn't work for all cases (i.e. missing macos socket based connection for docker beta).

**Comment by bsideup** [comment]
Supported
