### ISSUE TITLE
Support volumes propagation flags

### ISSUE THREAD

**Issue by jbonjean** [docker-java/docker-java#554]
Hi,
It would be nice to support the new volumes :[r]shared, :[r]slave and :[r]private propagation flags.
Thanks!

**Comment by KostyaSha** [comment]
please link to API docs

**Comment by jbonjean** [comment]
I couldn't find the corresponding doc. All I can tell you is that the feature has been available in the docker client since 1.10, here is the pull request: https://github.com/docker/docker/pull/17034

**Comment by jbonjean** [comment]
And it seems the missing documentation is a know issue :) https://github.com/docker/docker/issues/20656
