### ISSUE TITLE
docker java generate empty filter instead of no filter

### ISSUE THREAD

**Issue by ylorenza** [docker-java/docker-java#557]
When i use ListContainersCmd with no filter, i expext to generate a request like that : /v1.23/containers/json

but with docker java i have that : /containers/json?filters=%7B%7D

That's because in ListContainersCmdExec 
```
if (command.getFilters() != null) {
            webTarget = webTarget
                    .queryParam("filters", urlPathSegmentEscaper().escape(FiltersEncoder.jsonEncode(command.getFilters())));
        }
```

but command.getFilters() is never null, it's a Builder and it return an empty but not null map.

If you are ok i do a PR

**Comment by marcuslinke** [comment]
Nice finding! Awaiting your PR. Thanks!

**Comment by ylorenza** [comment]
already done

**Comment by marcuslinke** [comment]
Closed via https://github.com/docker-java/docker-java/pull/558

**Comment by marcuslinke** [comment]
@ylorenza Thanks!
