### ISSUE TITLE
Create new Docker container, start and stop it:  ERROR

### ISSUE THREAD

**Issue by AneesUrRehman** [docker-java/docker-java#559]
i am going to add examples from docker-java wiki and not succed to create cxontainer example. i am on grails 2.4
my issue is
![screenshot from 2016-05-01 13 02 46](https://cloud.githubusercontent.com/assets/12816566/14940773/12c13ada-0f9d-11e6-8657-6fd9f166eb46.png)

**Comment by marcuslinke** [comment]
As stated in the error message the image `busybox:latest` can't be found locally. You need to pull it before you can create a container. Please note that docker-java doesn't implement docker CLI behavior. It's just a wrapper around docker remote API (https://docs.docker.com/engine/reference/api/docker_remote_api/).
