### ISSUE TITLE
container run with daemon

### ISSUE THREAD

**Issue by langziming** [docker-java/docker-java#564]
I have a trouble, can you help me?  the issue as follows
Affter I create a container with the remote api “container/{id}/create” , 
when I start container with remote api "container/{id}/start"    
it is not run with daemon, 
（AS the command "docker run -d xxx:xxxx"   , Arguments "-d"  ) 。

**Comment by marcuslinke** [comment]
Post docker-java code example please!

**Comment by langziming** [comment]
my code as fllows

ListImagesCmd list = docker.listImagesCmd();
			CreateContainerResponse container = docker.createContainerCmd("ubuntu:latest").exec();
			docker.startContainerCmd(container.getId()).exec();

**Comment by langziming** [comment]
thank you 
when i create and start as another image, it is work

**Comment by marcuslinke** [comment]
You have not passed any CMD while container creation (via `createContainerCmd.withCmd(...)`). See https://github.com/docker-java/docker-java/wiki#create-new-docker-container-start-and-stop-it

Starting a container without a CMD doesn't make sense. A container exists as long as the process with PID 1 is running. The command for this process is referred as CMD in the Dockerfile or is passed while creation of the container.

**Comment by marcuslinke** [comment]
Forget my latest comment. Dockerfile for `ubuntu:latest` has CMD set so your code should just start a `bash` shell and terminate right after that.

**Comment by KostyaSha** [comment]
Reply from train…
Probably he need attach stdin and keep it open either bash will exist asap.

**Comment by xautjzd** [comment]
If I want to start a container without specifying CMD eg: `/bin/bash` in daemon mode,  as `docker run -d image`, what should I do?

**Comment by y9y2x8sz** [comment]
> 如果要在不指定CMD的情况下启动容器，例如：`/bin/bash`在守护程序模式下，如`docker run -d image`，我该怎么办？

use `.withTty(true)` ,keep it open。

**Comment by Detail-analy** [comment]
How is it that the container disappears immediately after it is created
