### ISSUE TITLE
IPAM config is not setable

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#567]
IPAM config is not setable https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/Network.java#L130 so how can it be created a Config object for setting in `withIpamConfig` method?

**Comment by KostyaSha** [comment]
Seems it used only in response, so try use where request object is, either it unsupported.

**Comment by lordofthejars** [comment]
Well it seems it should be valid as input as well according to docker remote api

**Comment by vuminhkh** [comment]
I think it's related to my pull request https://github.com/docker-java/docker-java/pull/550

**Comment by marcuslinke** [comment]
Closed via #550
