### ISSUE TITLE
Inconsistent interpretation of DOCKER_TLS_VERIFY

### ISSUE THREAD

**Issue by dlouwers** [docker-java/docker-java#576]
The Docker CLI client will use TLS (and look for a certificate file) when DOCKER_TLS_VERIFY is set to ANY value. The docker-java library will always try to use TLS unless DOCKER_TLS_VERIFY=0. This is inconsistent and causes settings that work with docker-java to break usage of the Docker CLI client.

**Comment by marcuslinke** [comment]
For this we have to change default [docker-java.properties](https://github.com/docker-java/docker-java/blob/master/src/main/resources/docker-java.properties) that prefers tls connections currently. Maybe we should preconfigure local unix domain socket connection there...

**Comment by dlouwers** [comment]
I think just DOCKER_HOST=unix:///var/run/docker.sock would make sense since that is the default for Docker CLI as well. AFAIK other settings aren't assumed next to this.

**Comment by marcuslinke** [comment]
Closed via #590
