### ISSUE TITLE
Lets get an IntelliJ OpenSource Ultimate Licence for Docker Java developers

### ISSUE THREAD

**Issue by alexec** [docker-java/docker-java#577]
Hi @marcuslinke, @KostyaSha , @kpelykh,

Are you IDEA users, if so I think we could get a free open source licence for the ultimate edition.

https://www.jetbrains.com/shop/eform/opensource?product=II

I'm quite happy to do the paperwork myself.

**Comment by KostyaSha** [comment]
Hi, i own license for docker-java from JetBrainz. Can share it to you via email if you fit into their license requirements.

**Comment by KostyaSha** [comment]
I was unable to find your email. Please send it me personally to my email.

**Comment by alexec** [comment]
No need to share. The open sourc license will be really good!

**Comment by KostyaSha** [comment]
Sorry, what do you mean? If you need ultimate license for docker-java, please write me your email. 
```
...
Please feel free to invite your team members to free Open Source access (via secure channels only: please do not use public forums or mailing lists to share license keys).
...
```
If you want to you open source IDEA version, then you don't need ask us to do it.

**Comment by alexec** [comment]
@marcuslinke, @KostyaSha , @kpelykh, -- I have 4 keys (3 left) for the Ultimate edition. If you want one, let me know your email, and I'll send you link to get it.

> Dear Alex,
> We are writing to you regarding your Open Source license request for JetBrains product(s).
> 
> We have approved your request and you will be able to use free Open Source access to the selected products shortly. To claim your licenses, click the link below: 
> Take me to my license(s)
> 
> Please find the license certificate for order D368028835 attached.
> 
> Please feel free to invite your team members to free Open Source access (via secure channels only: please do not use public forums or mailing lists to share licenses).
> 
> Your team’s access to the license will be valid for one year, qualifying you for all upgrades (including major ones) during this time. You may apply for a renewal shortly before the expiration date, by completing an online form at https://www.jetbrains.com/shop/eform/opensource
> 
> We hope our software will be useful for your project’s development. Should you have any further questions, please contact us directly at opensource@jetbrains.com. We'd be happy to help.
> 
> Best regards,
> 
> Elena Prohaskova 
> Regional Sales Representative - Russia & CIS
> 
> JetBrains s.r.o. 
> Na Hřebenech II 1718/10 
> Prague I 147 00 I Czech Republic 
> Phone (RU): +7(812) 331-15-74 
> Phone: +420 241 722 501 (ext. 77906) 
> Fax: +420 241 722 540 
> http://www.jetbrains.com 
> The Drive to Develop

**Comment by KostyaSha** [comment]
@alexec sorry, but i don't understand why do you need request personally them while i'm the contact person for docker-java licenses. I already informed @marcuslinke that he can get license if he needs it like any other developer. I said that you should send me your email if you want license, now you posting the same information.

**Comment by KostyaSha** [comment]
Yes, i see, you got access to the same organisation (but seems i only administrator for it). You created additional team and  got `All Products Pack` for it, no idea why you need all JB products instead of just IDEA Ultimate that i offered initially.
