### ISSUE TITLE
Error IncompatibleClassChange

### ISSUE THREAD

**Issue by Mouflin-Guillaume** [docker-java/docker-java#582]
Hello,

I have this error :  java.lang.IncompatibleClassChangeError: Implementing class
when I launch my command :
 $ java -cp .:commons-lang3-3.0.jar:commons-io-1.2.jar:commons-cli-1.1.jar:rabbitmq-client.jar:java-json.jar:ffmpeg.jar:slf4j-api-1.6.1.jar:guava.jar:commons-io-2.4.r:gson-2.2.2.jar:docker-java-3.0.0-SNAPSHOT.jar:apache-commons-lang.jar:jackson-annotations-2.1.2.jar:AllPackage/*  Core. 

I use Tomcat and RabbitMQServer and I use docker-java.

My code is following : 

        	DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder()
        			.withApiVersion("1.16")
        			.withDockerHost("unix://192.168.99.102:2376")
        			.withDockerTlsVerify(false)
        			.build();
        	
               DockerClient docker = DockerClientBuilder.getInstance(config).build();

I try to create several container for multiple instance. 

Thank.

**Comment by KostyaSha** [comment]
Why not use maven or gradle to get all deps automatically? Have you downloaded all transitive deps as well?

**Comment by Mouflin-Guillaume** [comment]
I used maven but when I launch command Java -cp , I have java.lang.ClassNotFoundException

**Comment by KostyaSha** [comment]
Well, you should create fat jar or application packaging, use maven-shade-plugin and not handle dependencies manually.
