### ISSUE TITLE
API Model classes not Serializable

### ISSUE THREAD

**Issue by stockiNail** [docker-java/docker-java#594]
I see Java classes into "model" package are not Serializable.
Being the model classes, I think they should be. This enables the usage of these classes with other frameworks where the JAVA (or other) serialization is required (without invoking Jackson everytime).

**Comment by KostyaSha** [comment]
Could you share some use case?

**Comment by KostyaSha** [comment]
#667 would be enough?

**Comment by stockiNail** [comment]
Decoupling the listening of events and possible actions to take related to events, you need to serialize object in a queue. If the objects are Serializable, you dont' to create similar classes to copy the content of docker-java result

**Comment by KostyaSha** [comment]
@stockiNail some classes seems not real models and contains streams, could be fixed later...

**Comment by stockiNail** [comment]
Sounds very good!! Thank you very much.!!

**Comment by KostyaSha** [comment]
Issue will be closed automatically after merge
