### ISSUE TITLE
API for pulling with content trust enabled

### ISSUE THREAD

**Issue by sburnwal** [docker-java/docker-java#597]
Do we have any API with which I can do docker pull from a registry server with docker content trust enabled ? I know this is possible with the command line 'docker pull ...' but I am looking for programmatic way.

Or, is there any way to pull the docker image from a registry server to some temporary location and then do some md5 or sha1 signature validation check before loading the image into local image repository ?

Appreciate the response, thanks!

**Comment by KostyaSha** [comment]
docker-java is using docker API if docker daemon supports it - then yes. Please check docker api for your feature.
