### ISSUE TITLE
Dockercon 2016?

### ISSUE THREAD

**Issue by cdancy** [docker-java/docker-java#600]
@KostyaSha @marcuslinke you guys going this year? Thought I'd come say hello and thanks as we ([gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin)) have used your library as our backend from the beginning.

**Comment by KostyaSha** [comment]
@cdancy Would be very happy to participate, but US trip is expensive. Will wait for some Europe events :)

**Comment by marcuslinke** [comment]
@cdancy Same here. However, thanks for using and contributing.
