### ISSUE TITLE
can not start a container with just a custom network

### ISSUE THREAD

**Issue by Hendrik-H** [docker-java/docker-java#601]
Hi,

when I use the docker CLI I can start a container using `docker run -d --net=<network-name> <image-name>`. Doing the same using `docker-java` seems to be impossible. I can use `docker.connectToNetworkCmd()` to add a connection to my custom network but then my container ends up with two network interfaces.

I tried using the `withNetworkMode` and `withNetworkDisabled` methods of the `createContainerCmd` to get a container without the additional network but nothing worked so far.

**Comment by KostyaSha** [comment]
Please check docker API whether they have methods that you want. docker-java is only library layer to their API.

**Comment by Hendrik-H** [comment]
Ok, I checked the message that goes over the wire using the docker cli and noticed that `HostConfig / NetworkMode" is set to the ID of the custom network. Doing the same using the docker-java actually works the same. So if you want to your new container to connect to a custom network you can use `docker.createContainerCmd(imageName).cmd.withNetworkMode("<custom netowrk id>");` Maybe that is something you want to add to the JavaDoc of com.github.dockerjava.api.command.CreateContainerCmd.withNetworkMode(String). Like
```
<li>'network-id': connect the container to the specified network</li>
```
