### ISSUE TITLE
Thoughts on setting `tlsVerify` to true if client sets `certPath`

### ISSUE THREAD

**Issue by cdancy** [docker-java/docker-java#607]
Is there any reason to not set `tlsVerify = true`, within the DockerClientConfig, when the user passes in the `certPath`?

**Comment by KostyaSha** [comment]
I had the same thoughts, but what is the docker cli behaviour?

**Comment by cdancy** [comment]
Looks to be you need both which is why, I have to imagine, you guys adopted this route. I'll ask around on docker IRC to see what the devs have to say. Seems setting the `certPath` implies tlsverify?

Even if they do both would it be better to copy them or make it easier on our users?

**Comment by KostyaSha** [comment]
We can change to any behaviour in dockerbuiler. Maybe check docker cli sources?

**Comment by marcuslinke** [comment]
Docker CLI disables TLS when DOCKER_TLS_VERIFY is unset or equal 0 regardless any DOCKER_CERT_PATH settings. As we evaluate the environment variables we should be compatible to docker CLI here.

**Comment by KostyaSha** [comment]
it more crazy https://github.com/docker/docker/issues/22411
docker assume 0 - is enabled!

**Comment by marcuslinke** [comment]
Acknowledged... Strange logic. However, I think we have to follow this.

**Comment by marcuslinke** [comment]
Created issue: https://github.com/docker-java/docker-java/issues/608
