### ISSUE TITLE
DOCKER_TLS_VERIFY set to any value should enable TLS

### ISSUE THREAD

**Issue by marcuslinke** [docker-java/docker-java#608]
All of:

DOCKER_TLS_VERIFY=1
DOCKER_TLS_VERIFY=0
DOCKER_TLS_VERIFY=foo

enables TLS with docker CLI. Only missing or empty variable disables it. We should follow this (strange) logic to be fully compatible.

**Comment by KostyaSha** [comment]
> (strange)

stupid logic!
