### ISSUE TITLE
Second execution of a docker command in Netty implementation always fails

### ISSUE THREAD

**Issue by tejksat** [docker-java/docker-java#625]
Second and consequent executions of a docker command fails with _404 page not found_ error because `baseResource` in `AbstrDockerCmdExec` is modified every execution by an invocation of `getBaseResource().path(...)` method, which mutates `WebTarget` state. F.e. in `CreateContainerCmdExec`:

```
        WebTarget webResource = getBaseResource().path("/containers/create");
```

**Comment by KostyaSha** [comment]
Could you propose PR?

**Comment by tejksat** [comment]
PR #630

**Comment by KostyaSha** [comment]
Thanks!

**Comment by KostyaSha** [comment]
Was merged and released.
