### ISSUE TITLE
create comtainer which property is replace the command args “-P”

### ISSUE THREAD

**Issue by langziming** [docker-java/docker-java#628]
when i run a container as command  “docker run -d -P tomcat:5.0” the container is run and the port info as flow 
     "Ports": {
            "8080/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "32770"
                }
            ]
        }

but when i create container as java api which args is same as command args -P

**Comment by KostyaSha** [comment]
what is the question?

**Comment by rnorth** [comment]
I think @langziming is after the method on `CreateContainerCmd` that is the equivalent of using `-P` in the docker CLI. If that's the case `.withPublishAllPorts(true)` should do the trick.

**Comment by KostyaSha** [comment]
There are 3 places that you need/may configure to get ports. PortBindings, publish, ... 
Because you image may already has `Expose` and you only need to publish or portbind it.

**Comment by langziming** [comment]
@KostyaSha my issue like  rnorth say

**Comment by KostyaSha** [comment]
Thanks, closing then.
