### ISSUE TITLE
netty freezes when sslconfig is null

### ISSUE THREAD

**Issue by KostyaSha** [docker-java/docker-java#635]
It seems to me that jersey throws exception while netty doesn't. Probably test case would be to build connection using Builder with null sslconfig.
One of possible stacktraces (based on shaded version) https://gist.github.com/KostyaSha/c19500f620ae588444f53aeca0fb7446#file-java-L223

**Comment by khayamgondal** [comment]
@KostyaSha is this issue still open? I can work on it.
