### ISSUE TITLE
Should at least document the Jersey 2.x requirement

### ISSUE THREAD

**Issue by sfitts** [docker-java/docker-java#64]
For a variety of reasons the DropWizard framework (which gets fairly wide use) is still on Jersey 1.18.  The fact that this library has moved on to Jersey 2.x means that it can't be used as part of a DW application (which unfortunately is my use case).

I'll be forking this to take it back to 1.18 for those of us who cannot switch.  In the meantime you probably want to document this requirement.  You may also want to consider whether you really need to be using Jersey 2.x (since I think you can use 1.18 client code in a 2.x application, but you can't go the other way due to the use of methods that don't exist in 1.18).

**Comment by marcuslinke** [comment]
After some thinking a decided to not breaking up API and different implementations. It would be to expensive to maintain two separate implementations for me. There would be also a risk that one implementation stays behind the other as the API develops forward.
