### ISSUE TITLE
Documentation is missing on the getEnvs/withEnvs method 

### ISSUE THREAD

**Issue by monksy** [docker-java/docker-java#656]
I'm not sure what format that the withEnvs setting is expecting. Is it expecting single strings with "key=value",... Or is it expecting ["key", "value", ....]

https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java#L303-L305

Suggestion: make this a map.

**Comment by KostyaSha** [comment]
Should be the same as https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/

**Comment by monksy** [comment]
That doesn't really help with the person using your software
