### ISSUE TITLE
build docker-java use gradle get a wrong dependencies

### ISSUE THREAD

**Issue by zizhongwei** [docker-java/docker-java#658]
hi~
when I build docker-java use gradle,  get a wrong dependencies:
com.google.collections:google-collections:1.0
![image](https://cloud.githubusercontent.com/assets/12456254/17389154/2ecc0eee-5a34-11e6-86cc-176677e26ef4.png)
so need to add:  all*.exclude group: 'com.google.collections', module: 'google-collections' in the build.gradle

**Comment by KostyaSha** [comment]
What is wrong?

**Comment by Loki-Afro** [comment]
@zizhongwei this dependency does only occur at test time.

@KostyaSha if it would be a compile time dependency you'll end up having the same classes in 2 dependencies: guava and google-collections

**Comment by KostyaSha** [comment]
Hamcrest is test scoped, i see no problems.
