### ISSUE TITLE
Duplicated Code for Jaxrs and netty implementations

### ISSUE THREAD

**Issue by Yogu** [docker-java/docker-java#671]
We're currently implementing missing features from Docker 1.12 into this library (Services, Nodes, Tasks, ...), see #617. While at this, I wonder if it is really necessary to have duplicate command exec implementations as well as tests for jaxrs and netty? The `WebTarget` is already a good abstraction between both worlds - couldn't we just use the jaxrs `WebTarget` interface?

**Comment by bsideup** [comment]
`DockerHttpClient` is the only abstraction that needs to be implemented for custom transports nowadays. Closing as outdated.
