### ISSUE TITLE
Label image during build

### ISSUE THREAD

**Issue by cirocosta** [docker-java/docker-java#681]
Hey,

just noticed that there's no way of adding labels to images that are build built with `buildImageCmd` (or am i missing something?) .

From https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/build-image-from-a-dockerfile we can pass `labels` so that at the end the labels are added to it. 

Maybe that could be a `.withLabels` or something like that. Wdyt?

Thx!

**Comment by cberes** [comment]
Hi, sorry for working on this before chatting with you. I'd like to help contribute to this project. This seemed like an easy ticket to start with. Please let me know if there's anything I should know about contributing. I'll open a pull request for this.
