### ISSUE TITLE
Support multiple access options on binds

### ISSUE THREAD

**Issue by dmandalidis** [docker-java/docker-java#688]
In general, access options (rw,ro etc.) is a comma-separated list instead of a single value, could it be possible to support multiple options as well like nocopy ?

**Comment by KostyaSha** [comment]
don't understand, please show examples.

**Comment by dmandalidis** [comment]
I 'm talking about the [-v|--volume[=[[HOST-DIR:]CONTAINER-DIR[:OPTIONS]]]] option of docker create; my impression is that docker-java supports supplying only one option, backed by the AccessMode enum (rw,ro) although from the API it's is possible to supply multiple e.g. "rw,shared,nocopy"

**Comment by KostyaSha** [comment]
So additional modes should be added in enum? Feel free to PR

**Comment by dmandalidis** [comment]
Well on second thought, "nocopy" is an additional option rather that an access option....

https://github.com/docker-java/docker-java/pull/696
