### ISSUE TITLE
How is API version selected when none is passed?

### ISSUE THREAD

**Issue by cdancy** [docker-java/docker-java#695]
Say I'm using the latest release but running against docker 1.9 or really anything older. When I make a request say to build an image how does docker-java figure out which api version to use? Do you guys make a query ahead-of-time to figure it out if none is passed in?

**Comment by KostyaSha** [comment]
It doesn't figure, it sends to root endpoint or to versioned endpoint if you specified version. 
Only auth call has version specific logic, but then fallback and adds both level of auth fields in JSON request.

**Comment by cdancy** [comment]
Where root endpoint is the latest supported by that docker engine. @KostyaSha Ok got it and thanks. I assume then there is no _benefit_ per se to querying the daemon first for the version and then passing that along to docker-java? The only reason I could see doing so is if one wanted to work against an older version though their docker-engine supports the latest.

**Comment by KostyaSha** [comment]
World is not ideal and docker-java can't support all docker API endpoint changes. While docker has versioned API endpoints. So it may happen that latest docker-java wouldn't work correctly on some API targets (so i'm limited tests to 1.12-1.0 as using 1.9 has no sense now). If you will have some issues it would make sense to make conditional logic, but it may fail with probably as engines will be behind it?

**Comment by cdancy** [comment]
Makes sense and thanks.
