### ISSUE TITLE
difference between awaitCompletion() & awaitCompletion(long,TimeUnit) in ResultCallbackTemplate

### ISSUE THREAD

**Issue by iGabon** [docker-java/docker-java#699]
Firstly, thanks for the work on this project.
I got a question when I use this sdk on my project.
the frist method :
```
    public RC_T awaitCompletion() throws InterruptedException {
        completed.await();
        // eventually (re)throws RuntimeException
        getFirstError();
        return (RC_T) this;
    }
```
and the second one :
```
    public boolean awaitCompletion(long timeout, TimeUnit timeUnit) throws InterruptedException {
        return completed.await(timeout, timeUnit);
    }
```
I readly donot understand why the second one donot call getFirstError() after call completed.await(timeout, timeUnit);

**Comment by marcuslinke** [comment]
This seems to be a bug to me. Feel free to provide a PR.

**Comment by KostyaSha** [comment]
https://github.com/docker-java/docker-java/pull/700
