### ISSUE TITLE
startContainerCmd().(CONTAINER_ID).exec() is not able to start a container

### ISSUE THREAD

**Issue by Sakib37** [docker-java/docker-java#701]
Tried the following code from the wiki-
------------------------------------------------------------------------------------------
CreateContainerResponse container = dockerClient.createContainerCmd("busybox")
   .withCmd("touch", "/test")
   .exec();

dockerClient.startContainerCmd(container.getId()).exec();
------------------------------------------------------------------------------------------

createContainerCmd() always create a container with a command which makes the container stopped immediately after running the command task. 

startContainerCmd() never starts a container. Containers are always stop. Is it possible to create container in detached mode for further use?

**Comment by KostyaSha** [comment]
Please check docker daemon logs.

**Comment by KostyaSha** [comment]
> Is it possible to create container in detached mode for further use?

Check available options in createCmd or follow examples in tests.

**Comment by Sakib37** [comment]
From the test cases I found the following code to start a container in UP state.
CreateContainerResponse container = dockerClient.createContainerCmd("ubuntu")
                .withCmd("sleep", "99999")
                .withTty(true)
                .exec();
My question is if the container is sleeping for 99999, is it possible to run any application inside the container while it is up. Can you please tell me how do you use the container when it is 'UP'?

**Comment by marcuslinke** [comment]
The container is up as long the CMD you have specified is running. So if you want to execute an application within the container just pass it via CMD. If you want the execute an application within a running container you have to create and start an exec. See docker remote API for details and/or look at the test cases.
