### ISSUE TITLE
'removeContainerCmd' does not delete a container

### ISSUE THREAD

**Issue by Sakib37** [docker-java/docker-java#702]
Used the following code to delete a container- 

```
CreateContainerResponse container = dockerClient.createContainerCmd("ubuntu")
                .withCmd("true")
                .withTty(true)
                .exec();
        System.out.println("Created container ID: " + container.getId());
        dockerClient.startContainerCmd(container.getId()).exec();
        dockerClient.waitContainerCmd(container.getId()).exec(new WaitContainerResultCallback()).awaitStatusCode();
        dockerClient.removeContainerCmd(container.getId());
```
The code is taken from [this](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/RemoveContainerCmdImplTest.java) test case. 

Tried with force also  -

`dockerClient.removeContainerCmd(container.getId()).withForce(true);`

When I check from the terminal the container is there. But I expected the container to be deleted already

[log](http://pastebin.com/Gp37BKdK)

In the log I do not see the DELETE method is called. Its may be a bug. Can you please check.

**Comment by marcuslinke** [comment]
You forgot to call `exec()`...
