### ISSUE TITLE
Run images on a docker swarm using the docker-java

### ISSUE THREAD

**Issue by neddogg** [docker-java/docker-java#709]
Hi Everybody,

I'm a newbie on docker. I was able to install docker and run an images on the single docker. Now I want to go ahead and run that images on the swarm of docker machines that I have setup. So, I was asking myself if this java client integrate api for the swarm.

Any clues please?
Thanks

**Comment by KostyaSha** [comment]
https://docs.docker.com/swarm/swarm-api/
current docker-java version would work with standard engine features.
Other swarm stuff and swarm-mode will come later.

**Comment by just1689** [comment]
Any news on this?
