### ISSUE TITLE
Start a container with flags using docker-java

### ISSUE THREAD

**Issue by neddogg** [docker-java/docker-java#713]
Hi Everybody,

I was able to start a container using the code.

    public class App {
	public static void main(String[] args) {
		DockerClient dockerClient = DockerClientBuilder.getInstance().build();

		dockerClient.startContainerCmd(containerId).exec();
        }
    }
And this works very well. Now I want to start the same container with flags. That is do something similar to 

docker run -it --rm my-container-tag

Any clue please?
Thanks.

**Comment by KostyaSha** [comment]
Please follow test cases and Docker API.
