### ISSUE TITLE
Docker build with multiple tags

### ISSUE THREAD

**Issue by MarkRx** [docker-java/docker-java#720]
Docker 1.10 added the ability to use multiple tags when doing a docker build. Would be nice to have this ability here. If a client is <1.10 then it could either (1) fail, (2) only use the first tag, or (3) run tag steps behind the scenes.

**Comment by MarkRx** [comment]
Request for https://github.com/bmuschko/gradle-docker-plugin/issues/286

**Comment by ben-gineer** [comment]
This would be a useful feature to reduce the number of tasks needed in the gradle-docker-plugin.

**Comment by matthiasbalke** [comment]
@orzeh did you merge your commit https://github.com/orzeh/docker-java/commit/81a33c697538ae46c707bbbefd2afa8c19c641a9 to the official docker-java repo? I can't find the changes regarding multiple tags.

**Comment by orzeh** [comment]
@matthiasbalke  My PR #739 is still waiting. @KostyaSha can you look at this?

**Comment by KostyaSha** [comment]
PR in process of review
