### ISSUE TITLE
Docker Ignore File isn't completely through

### ISSUE THREAD

**Issue by monksy** [docker-java/docker-java#721]
A docker ignore entry of .git is ignored.

Docker ignore line:

`.git 
`
File 

 `.git/config`

The file is added in the list of files to go into the tar.

The following regex is produced: 

`^\.git(\\.*)?`

**Comment by KostyaSha** [comment]
What docker-java do you use?

**Comment by monksy** [comment]
3.0.6.

**Comment by monksy** [comment]
This is on windows. Your regex should be:

`^\.git([\\|/].*)?`

**Comment by KostyaSha** [comment]
Filtering logic is bit crazy, please check test cases and code.

**Comment by monksy** [comment]
https://github.com/docker-java/docker-java/pull/722

I did a pull request.. 

To verify this you may want a unit test arround GoLangFileMatch::match(".git", ".git/config") == true. 

I can't really make that change at work. But that is what you need for the test. Also, you'll have to change the file seperator char. I'm not sure how to do that.

**Comment by monksy** [comment]
When running the same code in linux with the docker ignore file.. the taring is much much faster, which idicates to me that this is the issue. (The difference in the File seperator).
