### ISSUE TITLE
Calling onComplete Event on Resultcallback to abort process going in infinite loop.

### ISSUE THREAD

**Issue by dipak-pawar** [docker-java/docker-java#730]
Implement ResultCallback for StatsCmd -> dockerClient.statsCmd(id);

Currently I am trying to gather first stream only from stats command, instead of continuous stream.

Below is the code:
    private Statistics statistics = null;

    public StatsLogsResultCallback() {
    }

    @Override
    public void onNext(Statistics statistics) {
        if (statistics != null) {
            this.statistics = statistics;
            this.onComplete();
        }
    }

    public Statistics getStatistics() {
        return this.statistics;
    }

I am calling onComplete() event to abort the process as we are interesting in only first stream.

for some examples it's going in infinite loop.

Am I doing something wrong or missing something?

**Comment by dipak-pawar** [comment]
StatsCommandImplementation
```java
StatsCmd statsCmd = this.dockerClient.statsCmd(id);
            StatsLogsResultCallback statslogs = new StatsLogsResultCallback();
            try {
                statsCmd.exec(statslogs).awaitCompletion();
            } catch (InterruptedException e) {
                throw new IOException(e);
            }
            return statslogs.getStatistics();
```

**Comment by marcuslinke** [comment]
You should call close() if you want to abort the connection.

**Comment by dipak-pawar** [comment]
Oncomplete is using close inside it. So what's wrong with it.

**Comment by marcuslinke** [comment]
Please check jersey runtime dependency then. It must be the same version as declared in docker-java's pom.xml.
