### ISSUE TITLE
Monitoring of docker container

### ISSUE THREAD

**Issue by mehdiAhmed** [docker-java/docker-java#731]
I'm stating with docker-java API. I read some example from the test repositories.
I have generated a container from java api. afterwards, I want to monitor this container. In other words, translate  `docker stats myContainer`  in Java API.

When I make: docker stats container1  from shell I got this result:

```
> CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
> container1          0.00%               92 KiB / 995.9 MiB   0.01%               648 B / 648 B       0 B / 0 B           1
```

However, when I try to retrieve these results from Java API like this:

        List<Container> containers = dockerClient.listContainersCmd().exec();
        for(Container container: containers){
            InspectContainerResponse response= dockerClient.inspectContainerCmd(container.getId()).exec();
            System.out.println(response.getHostConfig());
        }

I Obtain:

`com.github.dockerjava.api.model.HostConfig@1992eaf4[binds=<null>,blkioWeight=0,blkioWeightDevice=<null>,blkioDeviceReadBps=<null>,blkioDeviceReadIOps=<null>,blkioDeviceWriteBps=<null>,blkioDeviceWriteIOps=<null>,memorySwappiness=-1,capAdd=<null>,capDrop=<null>,containerIDFile=,**cpuPeriod**=0,**cpuShares**=0,**cpuQuota**=0,cpusetCpus=,cpusetMems=,devices={},dns={},dnsSearch={},extraHosts=<null>,links=<null>,logConfig=com.github.dockerjava.api.model.LogConfig@f74e835,lxcConf=<null>,**memory**=0,**memorySwap**=0,**memoryReservation**=0,**kernelMemory**=0,networkMode=default,oomKillDisable=false,oomScoreAdj=false,portBindings={80/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@21d8bcbe},privileged=false,publishAllPorts=false,readonlyRootfs=false,restartPolicy=no,ulimits=<null>,volumesFrom=<null>,pidMode=,securityOpts=<null>,cgroupParent=,volumeDriver=,shmSize=67108864]`

All attributes are 0 !!! some one can explain for me how can I retrieve the same result as `docker stats myContainer` ?

**Comment by marcuslinke** [comment]
Why do you use InspectContainerCmd when you want the stats of the container? Please use StatsCmd.
