### ISSUE TITLE
How to use the 'docker exec' command? 

### ISSUE THREAD

**Issue by Sakib37** [docker-java/docker-java#736]
I want to do something like the terminal command -

docker exec -it CONTAINER_ID COMMAND

I checked the following test cases -
[ExecCreateCmdImplTest.java](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/ExecCreateCmdImplTest.java)

[ExecStartCmdImplTest.java](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/ExecStartCmdImplTest.java)

After running the test cases I do not see the command in the log(docker logs CONT_ID) and also no change after running the command.

My test-
1. created a container(CONT_ID) from terminal.
2. ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(CONT_ID)
                .withCmd('touch', 'test').exec();
        System.out.println(execCreateCmdResponse);

I do not see the file 'test' inside the container and also docker logs does not show 'touch test' in the log. 

Is this "ExecCreateCmdImplTest" or "ExecStartCmdImplTest" method are actually for this purpose?
If it is, can you please tell me how to run a custom command in a running container?

Thanks

**Comment by marcuslinke** [comment]
After ExecCreate you have to call ExecStart just as its done in one of the tests in `ExecStartCmdImplTest`.
