### ISSUE TITLE
Docker-Java does not support Windows Server 2016 Bind spec

### ISSUE THREAD

**Issue by gamma** [docker-java/docker-java#745]
It seems that I cannot use the bind spec for a windows containers to connect volumes to a container.

e.g.:

    docker run -it -v "C:/Windows:C:/temporary" --rm microsoft/nanoserver cmd

works as expected either from the Windows Server 2016 host itself or by remote access. Docker-Java will exit with an exception in the `Bind`-Class

**Comment by KostyaSha** [comment]
I have no windows :/

**Comment by KostyaSha** [comment]
Or if it only Bind.parse, then please PR
