### ISSUE TITLE
Possibility to ignore host SSL verification?

### ISSUE THREAD

**Issue by samized** [docker-java/docker-java#752]
Hi

Is it possible with this API client to connect to a docker host using TLS without validating the certificate of the docker host?

Using the IP Address instead of the domain name leads to this error:
`javax.net.ssl.SSLPeerUnverifiedException: Host name '10.0.0.74' does not match the certificate subject provided by the peer (CN=*.xyz.ch)`

Using docker from CLI it is possible to ignore the server certificate verification:
`$ docker --tls ps`

I had already opened an issue on a project which uses this java api client:
https://github.com/bmuschko/gradle-docker-plugin/issues/301

**Comment by orzeh** [comment]
You can provide your own [SSLConfig]() which uses custom [TrustManager implementation](http://www.programcreek.com/java-api-examples/javax.net.ssl.TrustManager) that trust your cert and use it during client configuration:
````java
SSLConfig sslConfig = new MyCustomSSLConfigImpl();
DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
    .withDockerHost("tcp://my-docker-host.tld:2376")
    .withDockerTlsVerify(true)
    .withDockerCertPath("/home/user/.docker/certs")
    .withCustomSslConfig(sslConfig)
    .build();
DockerClient docker = DockerClientBuilder.getInstance(config).build();
````
