### ISSUE TITLE
NetworkSettings#ports empty when using --net=host

### ISSUE THREAD

**Issue by alecharp** [docker-java/docker-java#753]
When we start a container with `--net=host` (which is possible in the latest `docker-plugin` of Jenkins), then the port bindings is empty. 

When the container is created, the `Ports` is correctly deserialize with the binding. However, when trying to access the container details, the `NetworkMode` is correct, but the library doesn't deserialize the binding correctly.

**Comment by KostyaSha** [comment]
Feel free to provide PR.

**Comment by lukelast** [comment]
I think this is expected. When using host networking there is no longer a concept of port bindings.
