### ISSUE TITLE
Authentication with private docker registry does not work

### ISSUE THREAD

**Issue by norman-knott** [docker-java/docker-java#754]
I'm trying to deploy a container with an image from our own Docker registry, and authentication configured in the user config.json:
```
{"auths": {"docker.my.domain": {"auth": "abcdasdfasdfd="}}}
```
, by this code
```
DockerClientConfig config = DefaultDockerClientConfig
                .createDefaultConfigBuilder()
                .withDockerHost("unix:///var/run/docker.sock")
                .withDockerConfig("/home/user/.docker")
                .withRegistryUrl("https://docker.my.domain")
                .build();
```
, but
```
List<SearchItem> dockerSearch = dockerClient.searchImagesCmd("docker.my.domain/image").exec();
```
, always gets an exception:
```
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Unexpected status code 401"}
```

The Docker cli works with this credentials.

**Comment by norman-knott** [comment]
Sorry for the wrong title.

**Comment by KostyaSha** [comment]
Don't set auth in client config there is auth config argument that allows
set multiple cards

**Comment by norman-knott** [comment]
Hi thanks for your answer. Can you point me to an example?

**Comment by KostyaSha** [comment]
didn't read well from mobile. Never used search, dunno.

**Comment by norman-knott** [comment]
Ok, for pullImageCmd() there is a withAuthConfig(), but for searchImagesCmd() it is missing.

**Comment by marcuslinke** [comment]
Seems auth for search is not documented. (https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/search-images)

**Comment by marcuslinke** [comment]
Please try to dump http requests from docker CLI for analysis.

**Comment by norman-knott** [comment]
It's a SSL connection. Do you know a way, to let docker CLI dump it out?

**Comment by KostyaSha** [comment]
switch daemon to unsecured connection + tcpdump/wireshark

**Comment by norman-knott** [comment]
I do not have any access rights to the registry server. So I have to install my own for tests. This will take a while.

**Comment by KostyaSha** [comment]
docker in docker should help you :)

**Comment by norman-knott** [comment]
:-) I am a noob. I just started with docker. :-/

**Comment by marcuslinke** [comment]
AFAIK dockers own registry doesn't provide search capability. But I'm not sure about this.

**Comment by marcuslinke** [comment]
Related: https://github.com/docker/distribution/issues/206

**Comment by norman-knott** [comment]
But how should `docker search java8` then?

**Comment by marcuslinke** [comment]
I guess they use an external solution with docker hub thats not part of the opensource version of the registry.

**Comment by norman-knott** [comment]
Hmm, so I have to use the catalog API directly on the registry server in application.

**Comment by norman-knott** [comment]
It's confusing the doc: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/search-images
, says it is to search at Docker Hub. But the result also delivers images from our private repo.
Outdated doc? :D

**Comment by marcuslinke** [comment]
Not sure how this works. What registry server do you use? Maybe you could ask the admin team? Would be interesting.

**Comment by norman-knott** [comment]
We use Nexus as repository server.
I have installed a Docker image of Nexus to proxy our repository :D
Thus I was able to get docker cli to repository request:
```
GET /v1/search?q=java8&n=25 HTTP/1.1
Host: localhost:9090
User-Agent: docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.4.0-53-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \(linux\))
Authorization: Basic dGVzdGVyOnRlc3Q=
X-Docker-Token: true
Accept-Encoding: gzip
Connection: close
```

**Comment by tourea** [comment]
I ran into a similar issue. I've created a "Pull Request" that solves the issue:
https://github.com/docker-java/docker-java/pull/756

**Comment by norman-knott** [comment]
@KostyaSha @marcuslinke is there someone who can check @tourea 's PR
