### ISSUE TITLE
Enable monitoring of multiple running containers

### ISSUE THREAD

**Issue by kpnarayanan** [docker-java/docker-java#757]
Hi,
I have a *requirement* where I have to gather data of all running containers.

Using the example code in the *Test* package (https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StatsCmdImplTest.java), I am able to *monitor* a single container. 

To gather data of multiple containers, I use a parallel.ForEach() as shown in the implementation below. 
However, I notice that only a subset from the overall list of containers is monitored.

The *example source code* is attached below:
`containerSet.parallelStream().forEach((containerObj)` -> {
				`ContainerStatistics cont = new ContainerStatistics(containerObj.getId(), containerObj.getNames()[0]);`
				`try{`
					`System.out.println("Container Id for stat collection = " + containerObj.getId());`
					`cont = dockerClient.dockerConn.statsCmd(containerObj.getId()).exec(cont);`
					`cont.awaitCompletion();`
				`}catch(Exception ex){`
				`}`
			`});`
where *containerSet* is a *Set* of Container objects. ContainerObj refers to each *container*.

*Output*: If I have *three* running containers, this code gathers data of any *two* containers.

Can somebody suggest what could be the problem and any pointers to resolve this issue? If there are examples (Test code) that exists in this repository that has a similar implementation, please re-direct me to them.

Thanks,
Krishnaprasad

**Comment by lukelast** [comment]
Parallel streams by default use a fixed size thread pool matching the number of cpu cores. Also it is strongly recommended not to use parallel streams for any blocking IO because by default the thread pool it uses is global.
Try an Executor
