### ISSUE TITLE
Container exits immediately with Ubuntu image

### ISSUE THREAD

**Issue by Sakib37** [docker-java/docker-java#758]
I tried to create a container as below-

```
CreateContainerResponse container =
        dockerClient.createContainerCmd(imageName)
                .withUser("root")
                .withHostName(containerHostname)
                .withName(containerName)
                .withCmd(cmd)
                .exec();
```
Then start the container 
`dockerClient.startContainerCmd(container.getId()).exec();`

This starts the container when I use "busybox" as image. But it fails for ubuntu:latest and ubuntu:14.04. When I use 'ubuntu:14.04' as the image, startContainerCmd does not give any error but the container "STATUS" shows that it exited immediately after start. 

I am not sure why it works fine with 'busybox' but fails with 'ubuntu:14.04'. Any clue?

**Comment by marcuslinke** [comment]
This is probably not related to docker-java. Take a look into the docker daemons log file. Maybe there is any hint.

**Comment by Sakib37** [comment]
The two provided test cases "ExecCreateCmdImplTest" and "ExecStartCmdImplTest" also fails with ubuntu:14.04 image. 
If I run "ExecCreateCmdImplTest" it passes but if set a breakpoint at 
`dockerClient.startContainerCmd(container.getId()).exec();`
and then you continue to debug line by line, it fails. I think when I run "ExecCreateCmdImplTest" the following line cannot detect the 'exit' status of the container so it passes the test case.
```
ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(container.getId())
                .withCmd("touch", "file.log").exec();
```
But if try to debug line by line it fails. 

However execStart() method in "ExecStartCmdImplTest" always fails with ubuntu:14.04. I believe it is the same case with other image also except 'busybox'.

But no problem occurs when I use docker client from terminal with ubuntu:14.04 or ubuntu:latest. Can you please reconsider this issue?

**Comment by marcuslinke** [comment]
The following runs successfully with latest master. Please note that I've changed the CMD to be "sleep 9999". I guess the former "top" terminates as soon as it gets started because there is no terminal. So in this case its a timing issue whether the container is running or not.

```java
    public void execStart() throws Exception {
        String containerName = "generated_" + new SecureRandom().nextInt();
        
        dockerClient.pullImageCmd("ubuntu:14.04").exec(new PullImageResultCallback()).awaitCompletion();

        CreateContainerResponse container = dockerClient.createContainerCmd("ubuntu:14.04").withCmd("sleep", "9999")
                .withName(containerName).exec();
        LOG.info("Created container {}", container.toString());
        assertThat(container.getId(), not(isEmptyString()));

        dockerClient.startContainerCmd(container.getId()).exec();

        ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd(container.getId())
                .withAttachStdout(true).withCmd("touch", "/execStartTest.log").withUser("root").exec();
        dockerClient.execStartCmd(execCreateCmdResponse.getId()).exec(
                new ExecStartResultCallback(System.out, System.err)).awaitCompletion();

        InputStream response = dockerClient.copyArchiveFromContainerCmd(container.getId(), "/execStartTest.log").exec();
        Boolean bytesAvailable = response.available() > 0;
        assertTrue(bytesAvailable, "The file was not copied from the container.");

        // read the stream fully. Otherwise, the underlying stream will not be closed.
        String responseAsString = asString(response);
        assertNotNull(responseAsString);
        assertTrue(responseAsString.length() > 0);
    }


```
