### ISSUE TITLE
Disk IO stats of containers

### ISSUE THREAD

**Issue by kpnarayanan** [docker-java/docker-java#759]
Hi,

I am using the StatsCmd to retrieve the block IO stats of containers. The following are the attributes returned as output from the blockIOStats API
-  io_service_bytes_recursive=[]
-  io_serviced_recursive=[]
-  io_queue_recursive=[]
-  io_service_time_recursive=[]
-  io_wait_time_recursive=[], 
-  io_merged_recursive=[]
- io_time_recursive=[]
-  sectors_recursive=[]

May I know how the above attributes are mapped to disk read bytes (KB / sec) and write bytes (KB / sec) or disk read / write time?

Thanks,
Krishnaprasad

**Comment by lukelast** [comment]
I was hoping [this](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/get-container-stats-based-on-resource-usage) would help but the block IO section is empty ha.
Most of the attributes you list have the units in the name though.
