### ISSUE TITLE
On Windows npipe protocol support

### ISSUE THREAD

**Issue by cdancy** [docker-java/docker-java#765]
I suspect I know the answer to this but just wanted to confirm with you guys one way or the other. [Trying to use `npipe` URL on windows 10 with docker ](https://github.com/bmuschko/gradle-docker-plugin/pull/313)throws the below exception. Is it possible to add support for this or is this currently being worked on by @marcuslinke and his work with unixsockets/jnr/etc.?

```
Caused by: com.github.dockerjava.api.exception.DockerClientException: Unsupported protocol scheme found: 'npipe:////./pipe/docker_engine'. Only 'tcp://' or 'unix://' supported.
        at com.github.dockerjava.core.DefaultDockerClientConfig.checkDockerHostScheme(DefaultDockerClientConfig.java:96)
        at com.github.dockerjava.core.DefaultDockerClientConfig.<init>(DefaultDockerClientConfig.java:82)
        at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.build(DefaultDockerClientConfig.java:431)
        at com.github.dockerjava.core.DefaultDockerClientConfig$Builder$build$1.call(Unknown Source)
```

**Comment by cdancy** [comment]
Maybe ammending this [snippet](https://github.com/docker-java/docker-java/blob/15aa30eaa6ed5c40dbbe1ef4dc3e4a4caeb867ec/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L93) to allow for `npipe` would suffice?

**Comment by marcuslinke** [comment]
AFAIK there is currently no out-of-the-box named pipe support for java. For netty at least it would need a `java.nio.channels.SocketChannel` implementation. Not sure what kind of interface is needed for jersey. However, I doubt that anyone is working on this.

**Comment by gesellix** [comment]
... and in case you're in need for some integration test, I wrote a simple "echo over named pipe helper" - usage can be found there: https://github.com/gesellix/docker-client/blob/c6c4680a2b4fc2178a85f6b37bb00b455eab6c31/client/src/integrationTest/groovy/de/gesellix/docker/client/filesocket/HttpOverNamedPipeIntegrationTest.groovy

**Comment by cdancy** [comment]
@marcuslinke @KostyaSha any updates here? Thought you guys were doing some work around this but can't seem to find it at the moment. 

We've got a lot of devs starting to upgrade to windows 10 with native docker and I'd love to have them be able to use our `gradle-docker-plugin` with no issues if at all possible.

**Comment by KostyaSha** [comment]
I personally wouldn't waste my life on windows and socket/pipe connections. Rest api is for http.

**Comment by cdancy** [comment]
@KostyaSha fair enough but that then requires users to then configure there docker instance to open up to the world. A good number of our devs our on mac and use the OOTB docker setup without having to open it up to the world. We'd like to be able to do the same for windows devs as we've found, specifically for windows developers, that they are not as technically inclined and further break things when they attempt to start configuring/playing/etc.

**Comment by KostyaSha** [comment]
Nobody requires open it to the world. Nobody forbid to use SSL certs or anything else.

**Comment by cdancy** [comment]
@KostyaSha yeah but by default docker does not listen over tcp/http: it's meant to be used natively and always has been. Enabling that requires further configuration that most windows devs, at least in my experience, are not too comfortable with. They just want to use docker and not have to think about anything else which I can appreciate it.

**Comment by gesellix** [comment]
Named Pipes might become even more popular: https://blogs.technet.microsoft.com/hybridcloud/2017/05/10/windows-server-for-developers-news-from-microsoft-build-2017/#Container%20Orchestration

**Comment by cdancy** [comment]
@gesellix yeah we're currently evaluating our corporate policy surrounding windows and what version and if we should pushing folks to use win10 with native docker support or something else. As most of our devs are windows based we kind of need native support to work.

**Comment by gesellix** [comment]
I'm aware that a Netty implementation will look different. Yet, there are at least two different Docker/Npipe client implementations to get some inspiration:

- for Apache HttpClient: https://github.com/fabric8io/docker-maven-plugin/tree/f766cdbdd3d2ef353604dc3bd0a38c51f5e88c45/src/main/java/io/fabric8/maven/docker/access/hc/win
- for Square's OkHttp: https://github.com/docker-client/docker-filesocket/tree/9cc1ad1a0bce51ceb6b561ddef4a3664ac3c629a/src/main/groovy/de/gesellix/docker/client/filesocket (yep, the same self plug as already mentioned above.)

Though I personally wouldn't prefer Windows as dev platform, the necessary code to ease Windows devs working without additional setup is more or less the same like for Unix domain sockets. Maybe the recent changes on the Netty side for Unix sockets will help with the Named pipe, too?

**Comment by KostyaSha** [comment]
Feel free to check netty for updates, i will spent nearest time on getting damn swarm tests and 3.1

**Comment by cdancy** [comment]
I thought at one point @marcuslinke was working with the netty guys to get this going but not sure where that ended up.

**Comment by KostyaSha** [comment]
I did some updates some time ago, but found that even minor updates in netty and httpclient were breaking tests. Now @marcuslinke added some overlapping classes that maven compiler blame and would be cool to change when dependency become better.

**Comment by kadwanev** [comment]
This is currently a requirement to be able to use docker-java on Azure as a managed app service.
+1

**Comment by cowwoc** [comment]
I'm also in favor of adding Windows pipe support, but see https://github.com/docker/for-win/issues/225#issuecomment-301254239 for a workaround.

**Comment by cdancy** [comment]
@cowwoc yeah that's what we've been advising developers here to do. It works of course but would like true native support at some point.

**Comment by kiview** [comment]
Microsoft recently published a [blog post](https://blogs.technet.microsoft.com/virtualization/2017/12/08/wsl-interoperability-with-docker/) about integrating Docker for Windows with WSL. They are using a Go binary to setup a named pipe releay: https://github.com/jstarks/npiperelay

Maybe a solution along these lines would be a possible workaround, since it seems Netty won't get named pipe support?

**Comment by cdancy** [comment]
That would be awesome!!! Here's hoping it works as expected ;)

**Comment by AndyGee** [comment]
Is there a workaround for this - Any command line option etc?

**Comment by kiview** [comment]
@AndyGee 
There is a way to get NPIPE support with docker-java, we are using in the [Testcontainers ](https://github.com/testcontainers/testcontainers-java)project as well.

You can see our OkHttp implementation of NPIPE here:
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/transport/okhttp/NamedPipeSocketFactory.java

This works by providing our own `AbstractDockerCmdExecFactory `:
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/transport/okhttp/OkHttpDockerCmdExecFactory.java

The ability to provide a custom  `AbstractDockerCmdExecFactory ` (and thereby circumventing Netty) has been implemented in #980.

@KostyaSha 
Would the ability to switch between Netty and OkHttp for transport (and thereby allowing NPIPE support) be something, that could be considered for docker-java?

**Comment by kohlschuetter** [comment]
junixsocket 2.2 now supports Unix Domain Sockets on Windows 10.

**Comment by cdancy** [comment]
@KostyaSha ^^^ that would be awesome to get in.

**Comment by KostyaSha** [comment]
https://github.com/docker-java/docker-java/pull/1159/files

**Comment by KostyaSha** [comment]
for okhttp i had talks with @bsideup in the next versions we can split docker-java to modules

**Comment by malejpavouk** [comment]
this would be really useful, because the exposure of 2375 is not really stable on windows (sometimes it works, sometimes it does not - and no port is exposed)

**Comment by casz** [comment]
Adding support for WSL 2 pipe as well would be awesome: `npipe:////./pipe/docker_wsl`

**Comment by berntie** [comment]
Any decision on whether this will be implemented someday or not?

**Comment by bsideup** [comment]
In #1284, we added a new, OkHttp based transport, that supports all existing communication models (tcp, unix socket, npipe)

There is an RC with it, `3.2.0-rc3`.

**Comment by berntie** [comment]
I built a version of the [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) using 3.2.0-rc4 but I still get

`com.github.dockerjava.api.exception.DockerClientException: Unsupported protocol scheme found: 'npipe:////./pipe/docker_engine'. Only 'tcp://' or 'unix://' supported.
        at com.github.dockerjava.core.DefaultDockerClientConfig.checkDockerHostScheme(DefaultDockerClientConfig.java:104)`

which is consistent with the check that's still present in the current master in https://github.com/docker-java/docker-java/blob/b4ce5ae0145d1b0143eabfb7e3c0abc07fccfc64/docker-java-core/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L100

I'm confused. How is this is supposed to work? Are you sure `npipe`is supported in RC3/4?

**Comment by bsideup** [comment]
@berntie thanks for trying! I will fix it ASAP!

We backported the OkHttp transport from Testcontainers but forgot to fix the check. It worked there because we applied a hack:
https://github.com/testcontainers/testcontainers-java/blob/6f7b17a9717bb600eccd839b2d84566392e7d999/core/src/main/java/org/testcontainers/dockerclient/NpipeSocketClientProviderStrategy.java#L45

**Comment by bsideup** [comment]
@berntie I just submitted #1325, it should solve the issue

**Comment by berntie** [comment]
@bsideup when will RC5 be available on jcenter? that will make experimenting easier.

**Comment by bsideup** [comment]
@berntie released yesterday :)

**Comment by berntie** [comment]
@bsideup yeah, but I'd like to have it available [here](https://bintray.com/search?query=docker-java). Using the self-built version of the gradle-docker-plugin already is cumbersome. Building the self-built gradle-docker-plugin with a self-built docker-java is twice as cumbersome.

**Comment by bsideup** [comment]
RC5 is on Maven Central. Bintray's JCenter is a superset of the Maven Central, and you can get MC dependencies thought JCenter.

**Comment by berntie** [comment]
Ah, I did not know that, thanks.

**Comment by berntie** [comment]
@bsideup With RC5 I get 

`java.lang.IllegalArgumentException: Unsupported protocol scheme: npipe:////./pipe/docker_engine
        at com.github.dockerjava.jaxrs.JerseyDockerCmdExecFactory.init(JerseyDockerCmdExecFactory.java:155)`

cf. https://github.com/docker-java/docker-java/blob/49d8e297d2be3afb798f2906f18b42638b5de44e/docker-java-transport-jersey/src/main/java/com/github/dockerjava/jaxrs/JerseyDockerCmdExecFactory.java#L142

since there might be more of those leftovers remaining: can't you get hold on a Windows copy somewhere to try this out yourself? I don't mind helping you out, but the feedback cycle via github certainly takes a lot of time...

**Comment by bsideup** [comment]
@berntie the result you get is correct, npipe support is only implemented in OkHttp and we have no plans (yet) to add it to other transports.
Consider using it instead of Jersey, we were using it in Testcontainers for years and it works *very* well (plus, like Netty, supports streaming and stdin attachment, but does not require Netty and can easily be shaded)

P.S. thanks for trying and reporting issues! 👍

**Comment by berntie** [comment]
Hmm, I'll see what I can do. Thanks for your fast responses!
