### ISSUE TITLE
Returning docker host mount point and rest of the value 

### ISSUE THREAD

**Issue by vinnu5064** [docker-java/docker-java#767]
Hi,

I think there is a bug at line 103 in https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/Bind.java
Where it is returning the docker host path and rest of the path.
This snippet is from your Bind.java code
public static Bind parse(String serialized) {
        try {
            String[] parts = serialized.split(":");
            switch (parts.length) {
            case 2: {
                return new Bind(parts[0], new Volume(parts[1]));
}
In above code you are returning entire parts[1] I think it should not.

please have a look at the example below made from your code
public class Bind
{
    public static void main(String []args)
    {
        String s="/root/Tomcat/webapps:/usr/local/tomcat6/webapps,/root/Tomcat/logs:/usr/local/tomcat6/logs";
        String[] parts = s.split(":");
        System.out.println (parts[0]);
        System.out.println (parts[1]);
    }
}

**Comment by KostyaSha** [comment]
Feel free provide test case and change

**Comment by vinnu5064** [comment]
please have a look at the example below made from your code
public class Bind
{
public static void main(String []args)
{
String s="/root/Tomcat/webapps:/usr/local/tomcat6/webapps,/root/Tomcat/logs:/usr/local/tomcat6/logs";
String[] parts = s.split(":");
System.out.println (parts[0]);
System.out.println (parts[1]);
}
}

**Comment by vinnu5064** [comment]
Yeah, if the input is /root/Tomcat/webapps:/usr/local/tomcat6/webapps,rw /root/Tomcat/logs:/usr/local/tomcat6/logs,rw
then, it is not working

it is working only for two inputs those are 
/root/Tomcat/webapps:/usr/local/tomcat6/webapps,rw
or
/root/Tomcat/webapps:/usr/local/tomcat6/webapps

**Comment by marcuslinke** [comment]
Sorry, I don't understand the problem. Bind.parse() is intended to parse a single bind only as a Bind object represents a single bind.

**Comment by vinnu5064** [comment]
![screenshot from 2016-12-20 20 31 19](https://cloud.githubusercontent.com/assets/9989383/21355286/65672d4a-c6f3-11e6-847a-1835c16605bd.png)

Actually I was trying to mount multiple volumes while launching container. Please have a look at the screenhot.

**Comment by KostyaSha** [comment]
That's library and not some jenkins plugin. Ask questions in right places.

**Comment by vinnu5064** [comment]
![screenshot from 2016-12-20 20 50 57](https://cloud.githubusercontent.com/assets/9989383/21356015/356bc814-c6f6-11e6-975f-46735b1fc0e3.png)


please have a look at this screenshot giving java.lang.IllegalArgumentException 
at com.github.dockerjava.api.model.Bind.parse(Bind.java:92)

**Comment by KostyaSha** [comment]
> Bind.parse() is intended to parse a single bind only as a Bind object represents a single bind.

Question closed.
