### ISSUE TITLE
Host and container port mapping enabled with 0.0.0.0

### ISSUE THREAD

**Issue by kpnarayanan** [docker-java/docker-java#769]
Hi,

I was searching for the issue in the github but was not able to successfully find one. 

Using the *docker java client*, while creating the container I want to enable the host to container port mapping to be of the following type *0.0.0.0:host port -> container port / tcp*.

If I use only the *exposed port* and the corresponding *host port binding*, I notice that the host ip and port are either null or empty.

I referred to the example in this link https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L229 for setting the exposed ports and port bindings.

May I kindly know how should I generate the *above setting* using the docker java client APIs. Any quick suggestions will be of great help.

Thanks,
Krishnaprasad

**Comment by marcuslinke** [comment]
Not sure what you want to achieve. For me it seems to be a simple port binding, so mapping host 0.0.0.0:80 -> container 8080/tcp for example. See https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L187 how to do it.

**Comment by kpnarayanan** [comment]
Thanks for your response. I used the same line of code for creating the container.

`ExposedPort tcp23 = ExposedPort.tcp(23);`
`Ports portBindings = new Ports();`
`portBindings.bind(tcp23, Binding.bindPort(11022));`

The output ontained is shown below:

CONTAINER ID    IMAGE   COMMAND  CREATED   STATUS  PORTS  NAMES
2b7a7c2972f4        test:latest   "/home/test/"   7 seconds ago       Up 6 seconds 23/tcp   testcontainer

The question that I have is only the 22/tcp is created / displayed while the 0.0.0.0:11022 is missing. 

I am using docker-java version 3.0.6. May I know how should I enable / obtain 0.0.0.0:hostport:containerPort

**Comment by kpnarayanan** [comment]
In continuation from my above email, I have the following setup :

A Web application is hosted on a container on *port X*. When I start the web server on the container, I want the container port to me mapped to the host running docker on port Y. May I kindly know how should I implement this?

**Comment by marcuslinke** [comment]
It should work as described by the test case I've linked above. Could you post your (almost) complete docker-java client code here please? What docker daemon / remote API version do you use?

**Comment by kpnarayanan** [comment]
My *docker client* and *server* version is *1.12.0* and the *API* version is 1.24.

*Docker java client code*

`ExposedPort tcp23 = ExposedPort.tcp(23);`
`Ports portBindings = new Ports();`
`portBindings.bind(tcp23, Binding.bindPort(11022));`

`CreateContainerResponse container = dockerConn.createContainerCmd("ubuntu").withExposedPorts(tcp23).withPortBindings(portBindings).withName("testContainer").exec();`

`dockerConn.startContainerCmd(container.getId()).exec();`
where the *dockerConn* object is generated as follows:  
`DockerClientBuilder.getInstance("docker connection URL").build();`

On the remote server, the *docker* is started as shown here: 
` dockerd -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375`

Let me know if I have to make any changes to the source code that I have posted above?
