### ISSUE TITLE
Network IO stats description

### ISSUE THREAD

**Issue by kpnarayanan** [docker-java/docker-java#775]
Hi,
I am getting the following values of the network rx and tx using the statscmd API of docker java client that is logged for the first ten time interval (in secs).

The question that I have are the following:
a) Are these the absolute values. If yes, can I know the unit of these values
b) If they are in the incremental order, do I have to compute the difference between the values at the consecutive  time periods

  net. rx                net. tx
60295498	20693903
64801513	22245223
69502248	23867921
74155404	25473919
79119776	27184243
83725509	28732507
88427315	30374611
93294078	32068615
97875477	33649317
102672543	35307821
107564711	36998191
112050764	38549649

Thanks,
Krishnaprasad

**Comment by lukelast** [comment]
They look like total bytes

**Comment by kpnarayanan** [comment]
Do this mean they are absolute values and there is no need for computing the difference between the values at timestamp t2 and t1?
