### ISSUE TITLE
Add pidsLimit option when creating containers

### ISSUE THREAD

**Issue by menarguez** [docker-java/docker-java#779]
Enable pid limitation is a cgroups configuration that is able to limit the number of processes that a container can create. This setting is extremely useful as it can prevent fork bombs. 

For more details see pids.max https://www.kernel.org/doc/Documentation/cgroup-v1/pids.txt

I have created a fix for this and will soon submit a pull request to HostConfig.java with Testing done.

**Comment by menarguez** [comment]
I have submitted a pull request with the feature. I built the library and tested with the .jar file a sample app  that runs a container with pidsLimit=512, then inspected the container and got the following:

```
$ docker inspect eee5a13cc375 | grep Pids
            "PidsLimit": 512,
```

**Comment by loganbruns** [comment]
@menarguez, given another PR was merged that fixed this should we close this now?
