### ISSUE TITLE
Intialize docker client (simple) example is outdated

### ISSUE THREAD

**Issue by Legend-Dale** [docker-java/docker-java#782]
Where?
First example on the docker-java wiki page:
https://github.com/docker-java/docker-java/wiki

Intialize docker client (simple):
DockerClient dockerClient = DefaultDockerClientConfig.getInstance("tcp://localhost:2375").build();

What?
"DefaultDockerClientConfig" has no "getInstance" method.

**Comment by MarkVee87** [comment]
Hey, I ran into the same issue, I solved it using the below, hope this helps! :)

        DockerClient dc = DockerClientBuilder.getInstance().build();
        Info info = dc.infoCmd().exec();
        System.out.print(info);

**Comment by GTP95** [comment]
Same problem here, wiki should be updated

**Comment by bsideup** [comment]
Wiki is no longer used. Please see https://github.com/docker-java/docker-java/tree/master/docs
