### ISSUE TITLE
How to specify non-standard CLI options via Java API?

### ISSUE THREAD

**Issue by greenechri** [docker-java/docker-java#784]
How do I use non standard options, like --shm-size for docker run or new --network option for docker build? The API seems very typed with no generic array of strings for CLI options that are not yet officially added the docker-java wrapper. Unless I've overlooked?

**Comment by loicmathieu** [comment]
+1 the docker API is so rich and evolving that passing generic commands (at least for the run docker command) will be very usefull.

**Comment by alxeg** [comment]
+1 at least we need to specify --oom-score-adj

**Comment by RoopeHakulinen** [comment]
Setting shm and other similar options has been supported since 3.0.2 with host config:
```
.withHostConfig(HostConfig.newHostConfig().withShmSize(1000000)) // 1GB of shm
```
