### ISSUE TITLE
Socket Timeout Exception: Read Timeout at Command exec()

### ISSUE THREAD

**Issue by harloveleenKaur** [docker-java/docker-java#788]
On executing the commands to start, stop and restart the containers  as : dockerClient.restartContainerCmd(containerId).exec(); gives 

**java.net.SocketTimeoutException: Read timed out**

Though the Command gets executed i.e. the container gets restarted, But an exception occurs on the console
My DockerClient Configuration looks like this : 
config = DefaultDockerClientConfig.createDefaultConfigBuilder()
				.withDockerHost("DOCKER_HOST")
			    .withDockerTlsVerify("DOCKER_TLS_VERIFY")
				.withDockerCertPath("DOCKER_CERT_PATH")
				.build(); 
		@SuppressWarnings("resource")
		DockerCmdExecFactory dockerCmdExecFactory = new JerseyDockerCmdExecFactory()
		  .withReadTimeout(1000)
		  .withConnectTimeout(1000)
		  .withMaxTotalConnections(100)
		  .withMaxPerRouteConnections(10);
		DockerClient dockerClient = DockerClientBuilder.getInstance(config)
				  .withDockerCmdExecFactory(dockerCmdExecFactory)
				  .build();

**Comment by marcuslinke** [comment]
You probably have to increment `withReadTimeout(1000)`. A read timeout of 1 second is not suitable for long running commands such as building images or container restarts. I don't recommend to set the read timeout value as it is a global param but when you have to set it it should be set to something above a minute.

**Comment by harloveleenKaur** [comment]
:+1:  Removing the Timeout works for me
