### ISSUE TITLE
Does not work in OSGi enviroionment

### ISSUE THREAD

**Issue by PhilAndrew** [docker-java/docker-java#789]
It would be nice if it worked in OSGi, if the JAR had the right manifest etc.

For example in your jar, your META-INF/MANIFEST.MF looks like the following which is not enough for OSGi:

```
Manifest-Version: 1.0
Built-By: integer
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_112

```

This has the consequence that I cannot use camel-docker component in Apache Karaf.

**Comment by KostyaSha** [comment]
I have no ideas how OSGI works, maven packaging is jar and it ok for maven.

**Comment by orzeh** [comment]
@PhilAndrew you can use [Bundlor](http://www.eclipse.org/virgo/documentation/bundlor-documentation-1.1.1.RELEASE/docs/user-guide/htmlsingle/user-guide.html#quickstart.command.line) tool to create valid OSGi manifest for existing JAR file. The obvious drawback is that you have to host the final JAR in custom Maven repository.

@KostyaSha I can submit PR which enables Bundlor in this project if you are interested.

**Comment by orzeh** [comment]
@PhilAndrew I've made PR that generates OSGi compliant manifest. I've tried `docker-java` bundle in [Eclipse Virgo](http://www.eclipse.org/virgo/) because I'm familiar with it. Please check if it works on Apache Karaf.

**Comment by PhilAndrew** [comment]
@orzeh How do I create the OSGi jar file from your code at https://github.com/orzeh/docker-java/tree/osgi ? 
mvn clean install -DskipITs
That made a jar in target docker-java-3.0.7-SNAPSHOT.jar but in that jar the MANIFEST.MF is not OSGi.

**Comment by PhilAndrew** [comment]
Hi @orzeh , why do you exclude the package com.github.dockerjava.core in the template.mf? as DefaultDockerClientConfig exists in com.github.dockerjava.core.DefaultDockerClientConfig as per the example code on the homepage of docker-java.

**Comment by PhilAndrew** [comment]
It works in Felix and Karaf as long as com.github.dockerjava.core is not excluded, and when I say works I mean, its working but not "tested", not running any specific tests, but that's really sufficient to say it works I believe.

**Comment by orzeh** [comment]
@PhilAndrew you are right, I've changed my PR and now it exports `com.github.dockerjava.core` and subpackages.

Thanks for testing on Karaf and Felix!

**Comment by PhilAndrew** [comment]
Thanks, hope this goes to a snapshot or release soon.

**Comment by PhilAndrew** [comment]
Reference this Apache Camel Docker component wants this https://issues.apache.org/jira/browse/CAMEL-10307

**Comment by KostyaSha** [comment]
So is this PR correct and everuthing is ok https://github.com/docker-java/docker-java/pull/797 ?
