### ISSUE TITLE
Move --rm to daemon side

### ISSUE THREAD

**Issue by destebanm** [docker-java/docker-java#792]
Hi!

In Docker daemon 1.13, --rm option has been moved to daemon side.

Is there any option to use it (or AutoRemove HostConfig option) with this docker java library, in order to  remove container after it terminates?

Thanks in advance!

**Comment by KostyaSha** [comment]
Such options set during container create API call, check it in Docker API docs and compare with available methods in docker-java create cmd.

**Comment by destebanm** [comment]
[v1.25 API changes](https://docs.docker.com/engine/api/version-history/#v125-api-changes)
_POST /containers/create now takes AutoRemove in HostConfig, to enable auto-removal of the container on daemon side when the container’s process exits._

docker-java create cmd does not allow to specify this param, and I think it would be really interesting

Could it be added in next versions?

Thanks
