### ISSUE TITLE
Library resets host TLS to version 1.0 only

### ISSUE THREAD

**Issue by meredydd** [docker-java/docker-java#798]
Line 50 of `com/github/dockerjava/core/LocalDirectorySSLConfig.java` does this:

```java
System.setProperty("https.protocols", "TLSv1");
```

This is exactly as horrible as it looks - it forces everything else in this VM down to TLSv1.0. This silently degrates TLS security, and/or loudly causes requests (to TLS-v1.1+-only endpoints) to fail.

If (and only if) `https.protocols` has been explicitly set to something non-default, this code restores the original values after creating an `SslConfigurator`. But even this is not acceptable in any multi-threaded application, as it creates a race condition that affects any TLS requests during this time.

**Comment by orzeh** [comment]
@meredydd this is obvious security bug. The comment in `LocalDirectorySSLConfig.java` says that it is needed for Java 1.6, but since this library is compiled against Java 7 is seems this code can be remove.

I've made PR #800 that should fix this.

**Comment by meredydd** [comment]
Bravo, thank you!
