### ISSUE TITLE
unix protocol is not supported when using unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by ssbarnea** [docker-java/docker-java#802]
It seems that the docker plugin is not able to connect to docker even when docker is configured on the same machine as the jenkins master and if you try to configure `unix:///var/run/docker.sock` you will get an exception:
```
org.apache.http.conn.UnsupportedSchemeException: unix protocol is not supported
javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: unix protocol is not supported
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
```

info: 
* running docker commands works from both root and jenkins user on that machine (jenkins used being added to the docker group
* machine: fedora 25 using docker-engine (but also tested with fedora 23 running docker.io and got same results).
* The info-tips of the plugin suggest using `unix:///var/run/docker.sock` so it doesn't make any sense to get such an error. The sock file exists.
* jenkins stable: 2.32.2

**Comment by KostyaSha** [comment]
Please report issues to jenkins firstly. If maintainer identify it as docker-java, then he will fill with describption.

**Comment by ssbarnea** [comment]
I added this at https://issues.jenkins-ci.org/browse/JENKINS-42157 and assigned it to `docker-plugin` component, as think that's the correct plugin that is supposed to provide docker cloud type.
