### ISSUE TITLE
Missing  "Node" info from inspecting container deployed on a  Swarm cluster

### ISSUE THREAD

**Issue by bklau** [docker-java/docker-java#804]
There is an optional "Node" info available when  API is inspecting a container deployed on a Swarm cluster. I pasted a small segment here:

"Image": "sha256:4fbf0283134c97fefc7080a7871a8219596c13ad54ebd3dc6c9236f39fa9b3c4",
        "ResolvConfPath": "/var/lib/docker/containers/fd8014f15337a62ef81bf33463f313555c924fdf08fc7d12054bde6da1f4cc0f/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/fd8014f15337a62ef81bf33463f313555c924fdf08fc7d12054bde6da1f4cc0f/hostname",
        "HostsPath": "/var/lib/docker/containers/fd8014f15337a62ef81bf33463f313555c924fdf08fc7d12054bde6da1f4cc0f/hosts",
        "LogPath": "",
        **"Node": {
            "ID": "OGBM:VIK7:WTEK:FREG:EJ7G:DSBS:7SGG:6AXT:XXRC:BAJG:RCJO:XYWI",
            "IP": "10.245.1.25",
            "Addr": "10.245.1.25:2375",
            "Name": "tciapps5",
            "Cpus": 1,
            "Memory": 1040920576,
            "Labels": {
                "availability-zone": "az-3",
                "kernelversion": "4.8.6-201.fc24.x86_64",
                "node-set": "tciapps",
                "operatingsystem": "Fedora 24 (Twenty Four)",
                "storagedriver": "btrfs"
            },
            "Version": "1.12.2",
            "DeltaDuration": 0
        }**,

**Comment by orzeh** [comment]
@bklau this duplicates #761 
Please keep an eye on #762
