### ISSUE TITLE
NettyDockerCmdExecFactory ignores API version configuration 

### ISSUE THREAD

**Issue by jamesnetherton** [docker-java/docker-java#807]
Seems `NettyDockerCmdExecFactory` does not respect the API version that was provided to the `DockerClientConfig`.

If I look at the `DEBUG` log output, the client appears to be hitting all of the unversioned REST endpoints.

I guess [getBaseResource()](https://github.com/docker-java/docker-java/blob/75e9a2cd3d1bf1489f7a94fd9dc8d624359fa430/src/main/java/com/github/dockerjava/netty/NettyDockerCmdExecFactory.java#L622) should add the version to the `WebTarget` path.

**Comment by KostyaSha** [comment]
Please PR!
