### ISSUE TITLE
[Question] Does docker-java works with Docker 1.13?

### ISSUE THREAD

**Issue by lordofthejars** [docker-java/docker-java#814]
Does docker-java works with Docker 1.13? I ask this because I have seen you removed from your CI descriptors.

Thank you so much.

**Comment by bklau** [comment]
I'm looking forward to Swarm mode support also.

**Comment by KostyaSha** [comment]
@lordofthejars first of all you can always target on previous API versions.
Secondary i tried enable it but some tests failed, so i disabled it. If somebody wants fix tests, then PR travis change with fixes.
