### ISSUE TITLE
What is the equivalent of the --userns=host flag on 'docker run'?

### ISSUE THREAD

**Issue by EarthCitizen** [docker-java/docker-java#815]
We have our docker daemon set up so that root inside the container is mapped to the user that is running the CI server. This is so that files created in a volume inside the container are not owned by root when the container exits. For a few containers in which we use `--privileged`, we need to disable this. The way to do this is to use the `--userns=host` flag. How is this flag set with `docker-java`?

**Comment by KostyaSha** [comment]
Please check Docker API docs and search for corresponding option in corresponding Cmd. If it missing feel free to PR addition.
