### ISSUE TITLE
Building an image based on another one from a private registry?

### ISSUE THREAD

**Issue by dornatsky** [docker-java/docker-java#817]
Judging by the look of BuildImageCmd, there's currently no way to provide an AuthConfig instance. Is there a way to build an image based on another image that is stored in a private registry?

**Comment by dornatsky** [comment]
Should I just pull before building?

**Comment by marcuslinke** [comment]
What about https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/BuildImageCmd.java#L145?

**Comment by dornatsky** [comment]
Yes, my bad, thank you.
