### ISSUE TITLE
Support tmpfs

### ISSUE THREAD

**Issue by RobeEW** [docker-java/docker-java#818]
My primary use case (via testcontainers) is running a postgres container for testing purposes - I'm assuming this would be much faster with a ram disk. As such it would be nice to support HostConfig.Tmpfs:
https://docs.docker.com/engine/api/v1.26/#operation/ContainerCreate
This was available as early as v1.22:
https://docs.docker.com/engine/api/v1.22/#endpoints

**Comment by KostyaSha** [comment]
So it appeared since 1.22?

**Comment by rnorth** [comment]
I've prepared a fork of tmpfs support and will contribute a PR for `docker-java`.

**Comment by slnowak** [comment]
Any updates on that? We're using testcontainers with postgres heavily, I assume this would speedup our CI significantly.

**Comment by hanswesterbeek** [comment]
+1, am after exactly the same thing...

**Comment by mbaechler** [comment]
see https://github.com/docker-java/docker-java/pull/873

**Comment by ChristianCiach** [comment]
Bump. We need this as well.

**Comment by DamirCiganovic-Jankovic** [comment]
No love for this?

**Comment by taizel** [comment]
For the ones looking for it on testcontainers, I believe this is already available: https://github.com/testcontainers/testcontainers-java/issues/673
@slnowak 
@RobeEW Isn't that a duplicate of #1022 
Duplicate of #1022

**Comment by rnorth** [comment]
Yeah, I believe this ticket can be closed!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mbaechler** [comment]
Yes it looks like it has been merged already.
