### ISSUE TITLE
Can't publish ports

### ISSUE THREAD

**Issue by Niro** [docker-java/docker-java#819]
Hello. Excuse me for the stupid question, but I've faced next problem. 

I used example from [test](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L189-L198) and have no published ports. I've read and tried almost all solutions from this repo.

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
docker-java version: 3.0.6

Output from `docker ps`
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
303836dd660e        busybox             "true"              4 seconds ago       Created                                 wizardly_heisenberg

```

**Comment by orzeh** [comment]
@Niro you won't see exposed ports unless you start a container.
