### ISSUE TITLE
how stop inputStream

### ISSUE THREAD

**Issue by 329706598** [docker-java/docker-java#829]
1、I use the "/ bin / bash" command to connect to the docker container, StdIn is System.in Stdout is System.out. 
2、Then enter some linux commands in the console window such as "tail -f my.log".
3、Now how do i exit the "tail" command and return "/ bin / bash"?

**My code is as follows:**
```
ExecCreateCmdResponse execCreateCmdResponse = dockerClient.execCreateCmd("a93228b610e2")
	                .withAttachStdout(true)
	                .withAttachStdin(true)
	                .withTty(true)
	                .withCmd("/bin/bash").withUser("root")
	                .exec();

 dockerClient.execStartCmd(execCreateCmdResponse.getId())
			 			.withTty(true)
			 			.withStdIn(System.in)
			 			.exec(new ExecStartResultCallback(System.out, System.err))
			 			.awaitCompletion();
```

**Comment by KostyaSha** [comment]
Docker container should get error signal, but because it wrapped with java you should somehow catch interrupt signal and forward it to TTY.
