### ISSUE TITLE
Support for --cache-from arg in > docker 17.03, Docker engine API 1.26 

### ISSUE THREAD

**Issue by kish3007** [docker-java/docker-java#833]
The latest docker engine API 1.26 supports the new build argument --cache-from to make use of caching, Looking at the docker-java support it works till 1.24 docker-engine API.  For this new functionality --cache-from to work, this project has to be updated to use the Docker-engine API 1.26

**Comment by KostyaSha** [comment]
Feel free to PR with tests.

**Comment by kish3007** [comment]
Sure @KostyaSha , i have written the code. Have trouble pushing it to the repo, Can you give me push access to this repo?

**Comment by KostyaSha** [comment]
Open Pull Request

**Comment by kish3007** [comment]
I should have my branch pushed first right? I am facing 403 error when I try to push. Am I missing anything?

**Comment by KostyaSha** [comment]
https://help.github.com/articles/fork-a-repo/

**Comment by kish3007** [comment]
Thanks for the link, will open a pull request soon.
