### ISSUE TITLE
Incorrectly handled InterruptedException

### ISSUE THREAD

**Issue by JLLeitschuh** [docker-java/docker-java#840]
This hasn't directly caused any problems for me but it could for other developers.

If you have code that catches the `InterruptedException` it needs to reset the thread's interrupt flag.

Eg, this is wrong, because if someone catches the `DockerClientException` then the interrupt flag will have been unset and the another thread could get stuck on a `thread.join()` call.
```java
    public String awaitImageId() {
        try {
            awaitCompletion();
        } catch (InterruptedException e) {
            throw new DockerClientException("", e);
        }
        return getImageId();
    }
```

The correct way to handle the InterruptedException is this:
```java
public String awaitImageId() {
        try {
            awaitCompletion();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new DockerClientException("", e);
        }

        return getImageId();
    }
```

http://www.yegor256.com/2015/10/20/interrupted-exception.html

**Comment by KostyaSha** [comment]
Could you PR?

**Comment by JLLeitschuh** [comment]
Probably not. I've got a bunch of things in flux right now, I don't really have the time right now.
