### ISSUE TITLE
Multiple serious bugs

### ISSUE THREAD

**Issue by peterdnight** [docker-java/docker-java#841]
- bug 1:  dockerClient.loadImageCmd() holds connection and never releases
- bug 2: dockerClient blocks forever if connection pool has no remaining connections. More serious due to bug 1
- bug 3: http pooling does NOT pool/reuse connections, a new http connection is established and released on every api request. Run list command 5 times - 5 separate connections to docker engine are created/released.  This is very inefficient management with lots of connections in time-wait (every command spins up new connection, rather then reusing). Use linux socket stat, or similar to watch port activity when using api( eg. run list command in a for loop - and watch connections). Refer to: http://www.baeldung.com/httpclient-connection-management 

Easy workaround for bug #3 - enhance the api to allow API users to inject their own correctly managed pool. It is very probable however - most would find it convenient if 
- JerseyDockerCmdExecFactory().withPoolTimeout(3, TimeUnit.Seconds)   // bug 2
- JerseyDockerCmdExecFactory().withPoolReuse(3, TimeUnit.Seconds)      // use existing connection if available

To reproduce:

````
        public final int dockerPoolSize = 1;
	private JerseyDockerCmdExecFactory buildDockerJerseyCommandFactory() {
		return new JerseyDockerCmdExecFactory()
				.withReadTimeout( 10000 )
				.withConnectTimeout( 10000 )
				.withMaxTotalConnections( dockerPoolSize )
				.withMaxPerRouteConnections( dockerPoolSize );
	}
````

then simply do a load - then list. Request hangs forever waiting for connection

````

		try (
			InputStream uploadStream = Files.newInputStream( targetFile.toPath() )) {
			dockerClient.loadImageCmd( uploadStream ).exec();
		}

		logger.info( "loaded image targetFile: {}", targetFile.getCanonicalPath() );

		logger.info( "\n\n - loaded image" );

//		lastFactory.close();
//		dockerClient = buildDockerClientWithShutdown() ;
		
		/**
		 * Image list
		 */
		verify_images_list();
		

		logger.info( "\n\n - listed image" );
		Thread.sleep( 60000 );
````

**Comment by KostyaSha** [comment]
> bug 3: http pooling does NOT pool/reuse connections, a new http connection is established and released on every api request. Run list command 5 times - 5 separate connections to docker engine are created/released. This is very inefficient management with lots of connections in time-wait (every command spins up new connection, rather then reusing)

You are not taking into account that docker itself doesn't work right with connections. People at all creating dockerClient for every call. Can't remind keyword for search. Please PR changes, we can revert them in any time.

**Comment by peterdnight** [comment]
Ya - i had wondered about that - thanks for confirming.

**Comment by KostyaSha** [comment]
cc @fengxx

**Comment by fengxx** [comment]
for item 3, httpclient does pool connection, but will not reuse until it reaches MaxPerRouteConnections

**Comment by blackr1234** [comment]
The reported issue still exists in docker-java version 3.0.14.


    public class Main {

        public static void main(String[] args) throws Exception {

            final DockerClient dockerClient = DockerClientBuilder.getInstance().build();
            final String image = "alpine:latest";

            try {
                dockerClient.pullImageCmd(image);
                System.out.println("Pulled");
            } catch (Exception e) {
            }

            dockerClient.removeImageCmd(image).exec();
            System.out.println("Removed");
            try (InputStream is = new FileInputStream("/Users/michael.chung/Desktop/alpine - latest.tar")) {
                dockerClient.loadImageCmd(is).exec();
            }
            System.out.println("Loaded");

            dockerClient.listImagesCmd().exec().forEach(System.out::println);

            dockerClient.removeImageCmd(image).exec();
            System.out.println("Removed");
            try (InputStream is = new FileInputStream("/Users/michael.chung/Desktop/alpine - latest.tar")) {
                dockerClient.loadImageCmd(is).exec();
            }
            System.out.println("Loaded");

            // the below line blocks
            dockerClient.listImagesCmd().exec().forEach(System.out::println);
        }
    }
