### ISSUE TITLE
Pull images broken on RHEL with Docker 1.12.6

### ISSUE THREAD

**Issue by berndv** [docker-java/docker-java#845]
Problem
On **Red Hat Enterprise Linux Server release 7.3** (Maipo) with **Docker 1.12.6 (Git commit: 3a094bd/1.12.6)** installed from yum repo **rhel-x86_64-server-extras-7** pulling images always fails. Stee stack trace below.

docker-java version 3.0.0

Reason
`com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess()` expects the last `com.github.dockerjava.api.model.PullResponseItem` to contain sth like _"Status: Image is up to date"_ in its status message. But this last item is not send by the docker deamen. On the setup descriped above, the last item is always the _"Digest: sha256:3a.."_ message.

Docker 1.12.6 (Git commit: 3a094bd/1.12.6)
```
bash-4.2$ docker pull rb-dtr.de.bosch.com/spade/foo:2.0.0-SNAPSHOT
Trying to pull repository rb-dtr.de.bosch.com/spade/foo...
2.0.0-SNAPSHOT: Pulling from rb-dtr.de.bosch.com/spade/foo

Digest: sha256:3ad08401d321e1b4004b5d876c63f7130e9b7cb25abef718976316fc1880b2be
bash-4.2$ 
```

Docker 1.12.6 (Git commit: d5236f0)
```
core@spade ~ $ docker pull rb-dtr.de.bosch.com/spade/foo:2.0.0-SNAPSHOT
2.0.0-SNAPSHOT: Pulling from spade/foo

Digest: sha256:3ad08401d321e1b4004b5d876c63f7130e9b7cb25abef718976316fc1880b2be
Status: Image is up to date for rb-dtr.de.bosch.com/spade/foo:2.0.0-SNAPSHOT
core@spade ~ $
```

Stack trace with Docker 1.12.6 (Git commit: 3a094bd/1.12.6)
```
PullResponseItem[stream=<null>,status=Pulling from rb-dtr.de.bosch.com/spade/mysql,progressDetail=<null>,progress=<null>,id=2.0.0-SNAPSHOT,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
PullResponseItem[stream=<null>,status=Digest: sha256:3ad08401d321e1b4004b5d876c63f7130e9b7cb25abef718976316fc1880b2be,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 142.479 sec <<< FAILURE! - in com.bosch.spade.im_backend.VerifyIT
com.bosch.spade.im_backend.VerifyIT  Time elapsed: 142.478 sec  <<< ERROR!
com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Digest: sha256:3ad08401d321e1b4004b5d876c63f7130e9b7cb25abef718976316fc1880b2be
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at com.bosch.docker.api.impl.CloseableDockerImpl.execPull(CloseableDockerImpl.java:163)
	at com.bosch.docker.api.impl.CloseableDockerImpl.pull(CloseableDockerImpl.java:121)
	at com.bosch.spade.SpadeUtils.pullSpadeImage(SpadeUtils.java:38)
	at com.bosch.spade.mysql.Mysql.run(Mysql.java:25)
	at com.bosch.spade.im_backend.VerifyIT.setUpClass(VerifyIT.java:22)
```

**Comment by KostyaSha** [comment]
`docker-java version 3.0.0` seriously? :)

**Comment by KostyaSha** [comment]
We have integration tests and they work fine against 1.12, first of all you should try the latest available release. If it still exists, then please try disable trusted something blabla about images. If it trusted images issue, then please open issue.

**Comment by JeffAtCisco** [comment]
So we started seeing this after updating to yad 0.1.0-rc48 the other day. Still following the other related threads and debugging, but I see this was reopened over a year ago... any progress? Or more info?
