### ISSUE TITLE
Unrecognized field "IdentityToken" when using AuthCmd

### ISSUE THREAD

**Issue by tjakoen** [docker-java/docker-java#846]
Hello, So I'm having a problem on using AuthCmd. 
I'm using Docker on Mac with boot2docker.

The request seems to work. But AuthResponse is missing IdentityToken causing jackson to throw an exception rendering AuthResponse null.

```
"{"IdentityToken":"","Status":"Login Succeeded"}[\n]"
```
```
javax.ws.rs.ProcessingException: Error reading entity from input stream

Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "IdentityToken" (class com.github.dockerjava.api.model.AuthResponse), not marked as ignorable (one known property: "Status"])
```

I've googled around and  using

```
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
@JsonIgnoreProperties(ignoreUnknown = true)
```

doesn't seem to do the trick.

Another thing I wanted to try is just manually create a request class and a model for AuthCmd
but I can't access the endpoint using curl or postman. And I can't see what the request looks like even if I use Wireshark. And I can't find any simple REST examples online.

Anyways, I'm new to all this and I'm doing my best
Is there anything I could do?
Thanks 😄

**Comment by orzeh** [comment]
@tjakoen see [this issue](https://github.com/docker-java/docker-java/issues/810)

**Comment by tjakoen** [comment]
I updated my docker-java version to 3.0.10 and my problem was immediately fixed.
I was using version 3.0.6 which was the one stated in Latest Release version in the README.

Thank you very much @orzeh! 😄
