### ISSUE TITLE
Unable to gently close() stream in ResultCallbackTemplate

### ISSUE THREAD

**Issue by wstrzalka** [docker-java/docker-java#850]
I do have an issue with LogContainerCmd - once I execute it it seems impossible to stop receiving the data in the ResultCallbackTemplate in gentle way. 
The problem is that if the ResultCallbackTemplate.close() method gets exception when closing underlying stream it leaves the callback in inconsistent state - it sets the closed flag but doesn't release the latch. That means none of the waiting threads can proceed :( 
It seems to be safe to move latch operation above the underlying steam closing what shall solve the issue.

**Comment by KostyaSha** [comment]
Could you try the latest version? Do you use netty or jersey?
