### ISSUE TITLE
Error while using docker-java in zlinux(s390x-Linux) machine

### ISSUE THREAD

**Issue by praveenjala** [docker-java/docker-java#855]
Hi,

I am using docker-java(3.0.6) client to connect to Docker. When i am trying to connect in zlinux machine(s390x-Linux) i am getting error with following:
Caused by: java.lang.RuntimeException: Unhandled architecture/OS: s390x-Linux
mtcac_1 | at org.newsclub.net.unix.NarSystem.getAOLs(NarSystem.java:110)
mtcac_1 | at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:30)

Please find the complete log in the attached log file.

Can you please help me in resolving this as early as possible?

Thanks,
Praveen.

[unixsockerror.txt](https://github.com/docker-java/docker-java/files/1050804/unixsockerror.txt)

**Comment by KostyaSha** [comment]
docker-java is using jersey and netty connection libraries, one of them using org.newsclub... so any platform connection issue will mostly relate to libraries (beside we missing additional library). 

All this native connections is hell, i suggest expose rest API and work via it.

**Comment by praveenjala** [comment]
Thanks for replying. 
You mean to say instead of using unix socket, expose a TCP port and use that for accessing docker.
Am i correct

**Comment by duanedsouza** [comment]
Hi Praveen. Are you looking to use docker on linux s390x ? I guess docker is available in the repos for Ubuntu and SLES12. If you are looking to use it on RedHat i guess you can download the binaries and get docker running.
Using docker daemon u can start docker on a specific port or get docker to listen on the default /var/run/docker.sock
Or like u mentioned expose a port using -H tcp://0.0.0.0:2375
