### ISSUE TITLE
Double encoding of filter query

### ISSUE THREAD

**Issue by igr** [docker-java/docker-java#857]
This:

https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/jaxrs/ListContainersCmdExec.java#L42

Later query params in `WebTarget` are going to be encoded again.

**Comment by KostyaSha** [comment]
And?

**Comment by igr** [comment]
so if you e.g. use filter to filter containers, docker expects json map in query parameter: `filter={"foo"`. So special chars like `{` will be encoded twice. And there will be exception.
