### ISSUE TITLE
Port Binding Example in Wiki is Stale

### ISSUE THREAD

**Issue by ywalterh** [docker-java/docker-java#858]
https://github.com/docker-java/docker-java/wiki shows example of 

`portBindings.bind(tcp22, Ports.Binding(11022));`

The new api is `Binding.bindPort()` instead of `Ports.Binding`.

**Comment by karlhenselin** [comment]
There are also issues with:
withBinds
withPortBindings

I can't seem to create a pull request for the wiki, but maybe I am doing something wrong.
Perhaps you could follow the guide here:
https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by KostyaSha** [comment]
Setting are in HostConfig like it is in docker API model, may be they will be restored, but only with Deprecated annotation.

**Comment by karlhenselin** [comment]
I am not suggesting that they be restored, but rather that the wiki be updated to have them in the right spot.

**Comment by bsideup** [comment]
Wiki is no longer used. Please see https://github.com/docker-java/docker-java/tree/master/docs
