### ISSUE TITLE
DockerClientException: Could not build image: null when tagging an image

### ISSUE THREAD

**Issue by DeepSnowNeeL** [docker-java/docker-java#860]
It looks like the `BuildResponseItem` in `isBuildSuccessIndicated()` looks for `BUILD_SUCCESS = "Successfully built";` but since I tag my image, my last getStream() value is "Successfully tagged test:latest".

Code : `String imageId = docker.buildImageCmd(pathServ.toFile()).withTag("test").exec(callback).awaitImageId();`

Log : 

```
08/06-14:25:59[VERBOSE]DockerBuildPhase$1#onNext:57// BuildResponseItem[stream= ---> 8cfc9e9191ff
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]

08/06-14:25:59[VERBOSE]DockerBuildPhase$1#onNext:57// BuildResponseItem[stream=Successfully built 8cfc9e9191ff
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]

08/06-14:25:59[VERBOSE]DockerBuildPhase$1#onNext:57// BuildResponseItem[stream=Successfully tagged test:latest
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]

08/06-14:25:59[ ERROR ]Error uncaught// com.github.dockerjava.api.exception.DockerClientException: Could not build image: null
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:71)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
	at com.ic2.builder.phases.docker.DockerBuildPhase.go(DockerBuildPhase.java:61)
	at com.ic2.builder.PhasedBuilder.go(PhasedBuilder.java:133)
	at com.ic2.builder.EntryPoint.main(EntryPoint.java:17)
```

**Comment by eshengit** [comment]
I confirm this issue: 
its related to latest docker version 
17.05 
17.03 and 1.12.3 all works fine. 
docker-java version I am using is 3.0.6 tried 3.0.7 but not working as well.

**Comment by KostyaSha** [comment]
Try latest version

**Comment by DeepSnowNeeL** [comment]
I tried the latest stable version specified in your readme.md so the 3.0.6 so not my fault if it's not updated,

I saw that the 3.0.7 is released but the same issue exists, Should I try the 3.0.7-SNAPSHOT now ?

**Comment by DeepSnowNeeL** [comment]
allright please update the readme :)

**Comment by KostyaSha** [comment]
Already done https://github.com/docker-java/docker-java/commit/f9a8c46e8494743820c9f0e9c8a406ca98ee80a9 ;)
