### ISSUE TITLE
Expose --cpus parameter during container creation.

### ISSUE THREAD

**Issue by dlachica** [docker-java/docker-java#863]
We need to manage the CPU load taken by a container. This can be done by setting the --cpus=<value> parameter, or a combination of --cpu-period=<value> and --cpu-quota=<value> as seen on https://docs.docker.com/engine/admin/resource_constraints/#cpu . However, CreateContainerCmdImpl does not expose an equivalent for --cpus. It would greatly help us in managing CPU utilization if this will be implemented. Thanks!

**Comment by cirocosta** [comment]
i.e, we're missing just `quota`, right? As `--cpus` becomes the `NanoCPUs` in the API (https://docs.docker.com/engine/api/v1.29/#operation/ContainerUpdate) which is used in the internal transformation to {cpuPeriod, cpuQuota} 🤔  (https://github.com/moby/moby/blob/5b1cae227171a299e41835a4806cd939b984c596/daemon/update_linux.go)
