### ISSUE TITLE
Can we specify insecure registries ?

### ISSUE THREAD

**Issue by RajAsapu** [docker-java/docker-java#865]
hi ,

I have a scenario where i need to specify my private registry as insecure to pull images.Do we have an option to specify registry as insecure using docker-java?

**Comment by orzeh** [comment]
@RajAsapu see [this](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/PullImageCmdImplTest.java#L54) test. Instead of `null` in `pullImageCmd.withAuthConfig(null);` use your own auth configuration.

**Comment by Shanky2304** [comment]
Hi, I have a similar question, do I need to pass some special AuthConfig if I'm to access an insecure registry?
Only specifying RegistryUrl, RegistryUsername, RegistryPassword doesn't work for me.

**Comment by KostyaSha** [comment]
If you don't understand how to use docker-java, then firstly do it with plain docker-daemon rest-api and then you will understand everything.
