### ISSUE TITLE
Swarm mode support release date

### ISSUE THREAD

**Issue by destebanm** [docker-java/docker-java#869]
hey guys!

Do you have an estimated date (aprox which month/year) for releasing 3.1.0 with swarm support?

Thank you! You do a great job!

**Comment by KostyaSha** [comment]
> Do you have an estimated date

Nom still fighting with tests and weird errors.

**Comment by destebanm** [comment]
Anyway thanks!

**Comment by KostyaSha** [comment]
You can `watch` PR for swarm branch, i still trying to get tests passing.
