### ISSUE TITLE
pullImageCmd with registry config in DefaultDockerClientConfig

### ISSUE THREAD

**Issue by destebanm** [docker-java/docker-java#870]
Hi!

I am trying to pull an image from a private repository.

If I run the pullImageCmd  providing an AuthConfig It works successfully :
```
AuthConfig authConfig = new AuthConfig().withUsername(username).withPassword(password)
.withRegistryAddress("https://xxxx.dkr.ecr.us-west-2.amazonaws.com");

dockerClient.pullImageCmd("xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx/xxxx")
.withTag("1.1").**withAuthConfig(authConfig)**
.exec(new PullImageResultCallback()).awaitCompletion();
```

But if I set the registry configuration when creating the DockerClient it doesn´t work

```
DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().withRegistryPassword(password)
.withRegistryUsername(username)
.withRegistryUrl("https://xxxx.dkr.ecr.us-west-2.amazonaws.com")
.withDockerHost(environmentConfig.getDockerAgentAddress()).build();
```

```
dockerClient.pullImageCmd("xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx/xxxx")
.withTag("1.1").
.exec(new PullImageResultCallback()).awaitCompletion();
```

Why pullImageCmd is not using the DockerClientConfig when AuthConfig is not provided?

Thanks!

**Comment by KostyaSha** [comment]
> Why pullImageCmd is not using the DockerClientConfig when AuthConfig is not provided?

Feel free to debug code.

**Comment by destebanm** [comment]
OK, but It supposed to work as I explained? Or I did something wrong?

**Comment by destebanm** [comment]
Problem was related with method getAuthConfig() in DefaultDockerClientConfig

```
  private AuthConfig getAuthConfig() {
        AuthConfig authConfig = null;
        if (getRegistryUsername() != null && getRegistryPassword() != null && getRegistryEmail() != null
                && getRegistryUrl() != null) {
            authConfig = new AuthConfig()
                    .withUsername(getRegistryUsername())
                    .withPassword(getRegistryPassword())
                    .withEmail(getRegistryEmail())
                    .withRegistryAddress(getRegistryUrl());
        }
        return authConfig;
    }
```

It is being checked that every registry field is not null. In ECR for example, you have not email. If email is setted to "" when creating DockerClientConfig then works, but I don´t think that is the clearest way. Maybe, in the function above is not necessary to check that every field is not null

**Comment by KostyaSha** [comment]
I got error locally and this PR helped https://github.com/docker-java/docker-java/pull/868/commits/e640aff1c72a143d260b73db81fe38df0322703d, i cherry-picked it and found null auth issue, then added fixup and updated test json. 

If you have some additional configs you can create test case (or check already existing PRs).
