### ISSUE TITLE
Container name start with '/' from ListContainerCmd

### ISSUE THREAD

**Issue by xuchenCN** [docker-java/docker-java#875]
Docker : Server Version: 17.03.1-ce
System : OSX

All container names are start with '/' using ListConainerCmd like : 
/reverent_kare
/naughty_bhabha
/hopeful_lumiere
/distracted_brattain

When I run python client without this issue

**Comment by xuchenCN** [comment]
I review the docker-py it stripped the '/' from json response of attribute **Name**
https://github.com/docker/docker-py/blob/master/docker/models/containers.py#L19
Could resolve this issue as docker-py ?

**Comment by KostyaSha** [comment]
I don't see issues, library return as is API answer, who knows what docker will implement and you can easily strip prefix in your code.
