### ISSUE TITLE
 logContainerCmd method timed out

### ISSUE THREAD

**Issue by dhmah1** [docker-java/docker-java#877]
I am using the latest docker version 1.30, my host machine is windows 7, and I am running docker in Oracle VM Virtual box.

```
Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I am trying to read docker logs using this API:
`logContainerCmd(@Nonnull String containerId).withStdOut(true).withFollowStream(true);`
This API used to work just fine with the older version of docker, but now with docker 1.30 I am getting this error:
`java.net.SocketTimeoutException: Read timed out`
In this method:
`void onError(Throwable throwable);`

I never been able to step inside the:
`void onNext(A_RES_T object);` method.

**Comment by nsidhaye** [comment]
@dhmah1 : By using `LogContainerResultCallback` I able to get rid of exception.

**Comment by KostyaSha** [comment]
Right callback type should be used with corresponding command.
