### ISSUE TITLE
Give more info on "the command ... returned a non-zero code" 

### ISSUE THREAD

**Issue by sscarduzio** [docker-java/docker-java#879]
Docker-java does not collect crucial error messages from the shell. This example from SO is very clear:

![image](https://user-images.githubusercontent.com/1327189/28410974-972f3d48-6d3f-11e7-9787-10f7ba2259cc.png)

https://stackoverflow.com/questions/31876031/the-command-bin-sh-c-returned-a-non-zero-code-127

Basically this guy forgets to install wget, and docker says:

```
The command '/bin/sh -c "wget",  "http://www.us.apache.org/dist/tomcat/tomcat-6/v6.0.44/bin/apache-tomcat-6.0.44.tar.gz"'  returned a non-zero code: 127
```

But the actual ONLY USEFUL error message is printed in the stderr right above:

```
/bin/sh: wget,: command not found
```
When using docker-java, we only can see the first message, but not the second. Is it possible to log that too?

Thanks,

_S

**Comment by KostyaSha** [comment]
Please provide code that you are running and ensure that stderr is attached.
