### ISSUE TITLE
Attach container to send shell

### ISSUE THREAD

**Issue by aTan20170106** [docker-java/docker-java#905]
In the dockerClient.startContainerCmd () after the use of attach method attached to the container, to the container to send shell instructions operation example. Studied for half a day without getting an answer.

**Comment by xuchenCN** [comment]
Hi @aTan20170106 you want send shell instructions to started container 
1.Create container has **tty** and **attach std**(in,out,err) = true, **cmd** set to **/bin/bash** or **/bin/sh**
2.Hold the container's **OutputStream**
3.Send instructions to OutputStream (you may use **PipedInputOutputStream** to send data to the Container's OutputStream)
4.Don't forget the end of the instruction with a ENTER (\n)

**Comment by KostyaSha** [comment]
@xuchenCN thanks.
@aTan20170106  that's all available in our tests, please check them as examples.
