### ISSUE TITLE
Unsupported JSON request parameter HostConfig.GroupAdd for CreateImageCmd

### ISSUE THREAD

**Issue by mgtsai** [docker-java/docker-java#907]
Since Docker Engine API v1.20, the request parameter HostConfig.GroupAdd has been officially supported, which reflects the "--group-add" argument of "docker create" and "docker run" CLI commands.

But I cannot find any implementation in docker-java project. Maybe an additional method "withGroupAdd()" should be supported in "com.github.dockerjava.api.command.CreateImageCmd"

**Comment by KostyaSha** [comment]
> argument of "docker create" and "docker run" CLI commands.

That's about container


> "com.github.dockerjava.api.command.CreateImageCmd"

That is for creating image from tar file, not a container.
