### ISSUE TITLE
jar package code is old, please update maven repository

### ISSUE THREAD

**Issue by gzvincen** [docker-java/docker-java#908]
3.0.13 version of the jar package inside the code is old, and from github grasp the code is not the same, you are not automatically packing process problems? From [http://mvnrepository.com/artifact/com.github.docker-java/docker-java] download down the jar package code are old, as soon as possible update the maven repository.  My English is very bad, sorry。I wish you could understand what I meant

**Comment by KostyaSha** [comment]
Why do you think that it old? Please provide any valuable information.

**Comment by gzvincen** [comment]
You can download the 3.0.13 version of the jar package or source package via maven and compare it to the code on github. Just compare the DockerClientImpl.java class, you will find that there are a lot of missing jar packages. This is the contrast image address https://github.com/gzvincen/test/blob/master/DockerClientImpl-class-bc.png
The left side of the picture is the 3.0.13 version of the source code, the right is github on the code

**Comment by orzeh** [comment]
@gzvincen 3.0.13 does not contain classes for Docker Swarm management. Compare it with the head of  [3.0.x](https://github.com/docker-java/docker-java/tree/3.0.x) branch.

**Comment by gzvincen** [comment]
My mistakes, thank you. @orzeh 
The next version of the docker-java will contain classes for Docker Swarm management？？？ @KostyaSha
