### ISSUE TITLE
Pull status is not complete when pulling image.

### ISSUE THREAD

**Issue by lord-i-will** [docker-java/docker-java#910]
Steps to reproduce the problems:
1. install docker jenkins plugin.
2. add "Execute Docker command" in job config as followings:
![image](https://user-images.githubusercontent.com/14847104/30147741-917831e8-93d2-11e7-808c-458d7cec6715.png)
3.run the job, and the console outputs as followings:
![image](https://user-images.githubusercontent.com/14847104/30147800-d01999a0-93d2-11e7-87ff-11de9bbabee7.png)
4.go back to jenkins node, the image is already pulled....So **it should not fail but succeed.**

In the above picture we can see the status change, but in https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/PullResponseItem.java#L35 the status is not complete....

please fix it.

**Comment by KostyaSha** [comment]
JFYI There is workaround https://github.com/KostyaSha/yet-another-docker-plugin/issues/161

**Comment by lord-i-will** [comment]
okay~
