### ISSUE TITLE
how to delete images from private v2 registry?

### ISSUE THREAD

**Issue by alexandnpu** [docker-java/docker-java#914]
I did a simple search, and cannot find some documents on this topic.

Could you show me some examples, please?

Thanks.

**Comment by KostyaSha** [comment]
How do you delete it using docker cli?

**Comment by alexandnpu** [comment]
@KostyaSha , I donot know how to delete it through docker cli. You mean that docker-java can do what docker cli can do? If docker cli cannot, then docker-java cannot.

I read from the registry api from docker document that the image seems to be deleted from [RESTful API](https://docs.docker.com/registry/spec/api/#deleting-an-image).

Am I right?

**Comment by KostyaSha** [comment]
docker daemon API != docker registry API

**Comment by alexandnpu** [comment]
Yep, I got your point now. Thanks.
