### ISSUE TITLE
Container exiting immediately after starting

### ISSUE THREAD

**Issue by deepu-appfabs** [docker-java/docker-java#915]
I am trying to remotely run a docker image using the following code. But the container is exiting immediately after starting. 

```
		DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
				.withDockerHost(dockerHostName)
				.build();
				
		String[] commands = new String[] {
		                "true",
		                "/bin/sh -c while true; do sleep 1000; done"
        	};
        	
        	ExposedPort tcp80 = ExposedPort.tcp(80);
		DockerClient docker = DockerClientBuilder.getInstance(config).build();
		CreateContainerResponse response = docker.createContainerCmd(dockerImage)
				.withCmd(commands)
				.withExposedPorts(tcp80)
				.exec();
				
		docker.startContainerCmd(response.getId());
		logger.info("container started, id - " + response.getId());
```	
As suggested from various articles I have included a shell command to keep the container live and running. But still the container exits immediately. Could anybody help me to understand the how to keep  the container up and running?

**Comment by KostyaSha** [comment]
Try run with open stdin or stdout. Also please check a lot of examples in our test sources.

**Comment by xzy256** [comment]
@deepu-appfabs how to run container detach,  at last for you?
i createContainerCmd able to stdout and stdin， like `createContainerCmd.withTty(true).withAttachStdout(true).withStdinOpen(true).withAttachStdout(true).withAttachStderr(true).withAttachStdin(true)`. Then start it, but useless.
