### ISSUE TITLE
Build Images with remote dockerfile.

### ISSUE THREAD

**Issue by Shanky2304** [docker-java/docker-java#923]
I'm using a remote Docker daemon(running Docker version 17.06.2-ce), is there a way to specify the Dockerfile path which is not local?
I feel it shouldn't be restricted to the local system.

**Comment by KostyaSha** [comment]
Sorry, i don't understand the question. Please read Docker API logs, docker-java is just 1:1 api client.

**Comment by Shanky2304** [comment]
My bad..I guess I wasn't clear enough. AFAIK, right now the Dockerfile which is passed to the docker daemon needs to be a local file path, is there a way to pass a remote Dockerfile to docker-java..?
