### ISSUE TITLE
Not know image.created means.

### ISSUE THREAD

**Issue by wanxinGit** [docker-java/docker-java#925]
it is a long type.
but convert to Date is not right. what does it means.

**Comment by KostyaSha** [comment]
Sorry, i don't understand your question.

**Comment by KostyaSha** [comment]
https://docs.docker.com/engine/api/v1.30/#operation/ImageInspect 
"Created": "2015-09-10T08:30:53.26995814Z",
if something wrong please reply

**Comment by KostyaSha** [comment]
https://github.com/moby/moby/blob/131e2bf12b2e1b3ee31b628a501f96bbb901f479/image/image.go#L28-L29
Maybe we can change to Date
