### ISSUE TITLE
Could not push image: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by Shanky2304** [docker-java/docker-java#926]
I'm using docker-java to create an image on a docker host(Docker version 17.09.0-ce build afdb6d4) which is running on a Ubuntu 16.04 VM. The image creation works just fine and I can list the image created via docker-java. But when I try to push the image to a private v2 registry(Harbor) 

`com.github.dockerjava.api.exception.DockerClientException: Could not push image: denied: requested access to the resource is denied
`

I have added my current user to the usergroup docker and can manually push the image with the following command from the terminal(note no sudo).

`docker login docker push some_ip/app/test:testapp` 

But when I make the following call from my java code I get the above mentioned error.

`dockerClient.pushImageCmd("some_ip/app/test:testapp")                                       .exec(pushImageResultCallback).awaitSuccess();`

I have manually verified that the mentioned image exists.

**Comment by KostyaSha** [comment]
> Could not push image: denied: requested access to the resource is denied\

> dockerClient.pushImageCmd("some_ip/app/test:testapp") .exec(pushImageResultCallback).awaitSuccess();

You didn't specified authConfig.

**Comment by Shanky2304** [comment]
But I did specify it in the DefaultClientConfig which is passed to my DockerClient object.
