### ISSUE TITLE
Netty test is broken for URI double encoding in master branch

### ISSUE THREAD

**Issue by fengxx** [docker-java/docker-java#927]
Netty
```
GET /tasks?filters=%257B%2522service%2522%3A%255B%25227mgu0x63rgpeeu61c4fsgo5e1%2522%255D%257D HTTP/1.1
```

Jersey is fine
```
GET http://localhost:2375/tasks?filters=%7B%22id%22%3A%5B%22f6jjdjk1hcfufqm2yibftl2x3%22%5D%7D
```

**Comment by KostyaSha** [comment]
in master or in 3.0.x?

**Comment by KostyaSha** [comment]
i think 3.0.x is not merged yet into master

**Comment by KostyaSha** [comment]
hm... https://github.com/docker-java/docker-java/pull/932 
How test is broken?

**Comment by fengxx** [comment]
master branch, I think it is caused by #909

**Comment by KostyaSha** [comment]
when i deduplicated tests i used tests only from one of implementations. Maybe i missed something? Could you check/pr?
