### ISSUE TITLE
How do you set environment variables?

### ISSUE THREAD

**Issue by Shanky2304** [docker-java/docker-java#933]
I tried something like:
```
CreateContainerResponse containerResponse = dockerClient.createContainerCmd("testApp")
            .withEnv("DISPLAY=$DISPLAY")
            .exec();
```
but this doesn't seem to work. The $DISPLAY mentioned is supposed to be the value of the environment variable on the Ubuntu system where the docker daemon is running. I verified that it's properly defined.

**Comment by KostyaSha** [comment]
Sorry, that's a question docker API, not about client library. Also you can look at our tests that has a lot of examples of API usage.

**Comment by Shanky2304** [comment]
@KostyaSha I tried finding similar examples, could you point me to one?

**Comment by orzeh** [comment]
@Shanky2304 your code snippet is correct - that is how you set environment variables **inside** container. However, you don't have access to Docker daemon environment, so your particular example won't work anyway.

**Comment by Shanky2304** [comment]
@orzeh I'm sorry, I don't understand. What do you mean I don't have access? What should have I done differently?

**Comment by orzeh** [comment]
@Shanky2304 In https://docs.docker.com/engine/reference/run/#env-environment-variables :
> If the operator names an environment variable without specifying a value, then the current value of the named variable is propagated into the container’s environment

In that case AFAIK the value is read from **client environment**.

Back to your example, you can read `DISPLAY` env variable and pass it to Java code:
````java
String dispayVarValue = System.getEnv(...);
CreateContainerResponse containerResponse = dockerClient.createContainerCmd("testApp")
            .withEnv("DISPLAY=" + dispayVarValue)
            .exec();
````

It that code runs on docker daemon you will get what you want.
