### ISSUE TITLE
Examples for using StdIn with experimental Netty in Wiki

### ISSUE THREAD

**Issue by artheus** [docker-java/docker-java#941]
Hi,

I have been trying for a while now to get Stdin to work with the experimental Netty client.
From what I can see while debugging is that the InputStream gets read, but the data never seems to go through to the container.

I placed a breakpoint(*) in the netty.InvocationBuilder inside the stdin reader thread.
```
   int read;
   while ((read = read(stdin, buffer)) != -1) {
*    channel.writeAndFlush(Unpooled.copiedBuffer(buffer, 0, read));
   }
```

Debugging my application I can see that the read waits for data, then reads the stdin data correctly and invokes the writeAndFlush method with the correct byte array.
But from there the stdin data never gets sent to the container. I've tried in several ways, but nothing seems to actually work.
Therefore, I would like to see an example of how to use the Experimental Netty client for hijacking the http request and sending a stdin message to the container, correctly.

I've been searching for an example here on github, and also on google. But I've not been able to find one.

**Comment by artheus** [comment]
Right after posting, I saw this #859
I am on MacOS, will run on linux instead then.

**Comment by artheus** [comment]
Though now as I look closer, the macos kqueue netty native is a dependency. But it seems that if will try to connect to /var/run/docker.sock, completely disregarding the environmental variable DOCKER_HOST.
```
#Debug output of channel type in netty client:
KQueueDomainSocketChannel@5465 "[id: 0x0dc75abb, L:null ! R:/var/run/docker.sock]"
```

I will look more into this, to see if I can get it to work for macos too.

**Comment by scddev** [comment]
I did a small sample to send data to stdin myself, dont know if you still need it ...

```
public class SomeTest {
	public static void main(String[] args) {
		DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().withDockerHost("tcp://localhost:2375")
				.build();

		DockerClient docker = DockerClientBuilder.getInstance(config).withDockerCmdExecFactory(new NettyDockerCmdExecFactory())
				.build();

		CreateContainerCmd createContainerCmd = docker.createContainerCmd("ubuntu:16.04").withCmd("cat").withStdinOpen(true)
				.withTty(false);
		CreateContainerResponse createContainerResponse = createContainerCmd.exec();

		StartContainerCmd startContainerCmd = docker.startContainerCmd(createContainerResponse.getId());
		startContainerCmd.exec();

		try (PipedOutputStream out = new PipedOutputStream();
				PipedInputStream in = new PipedInputStream(out);
				BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(out));
				BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {
			AttachContainerCmd attachContainerCmd = docker.attachContainerCmd(createContainerResponse.getId()).withStdIn(in)
					.withStdOut(true).withStdErr(true).withFollowStream(true);
			attachContainerCmd.exec(new AttachContainerResultCallback());

			String line = "Hello World!";
			while (!"q".equals(line)) {
				writer.write(line + "\n");

				writer.flush();

				line = reader.readLine();
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		RemoveContainerCmd removeContainerCmd = docker.removeContainerCmd(createContainerResponse.getId()).withRemoveVolumes(true)
				.withForce(true);
		removeContainerCmd.exec();
	}
}
```

**Comment by galderz** [comment]
@scddev Tried that example on macos but doesn't seem to do anything. Then modified it to run `/bin/sh` and nothing gets printed out. With `/bin/sh` typed `ls` but nothing.

**Comment by scddev** [comment]
@galderz The sample above relied on the logging config, just replace the

`attachContainerCmd.exec(new AttachContainerResultCallback());`

with 

```
            attachContainerCmd.exec(new ResultCallbackTemplate<AttachContainerResultCallback, Frame>() {
                @Override
                public void onNext(Frame object) {
                    System.out.println(object);
                }
            });
```

**Comment by bsideup** [comment]
Wiki is no longer used. Please see https://github.com/docker-java/docker-java/tree/master/docs

**Comment by wilmercastrillon** [comment]
@scddev I tried your example, but this code doesn't print anything
