### ISSUE TITLE
Close does not close all streams

### ISSUE THREAD

**Issue by tlf30** [docker-java/docker-java#942]
So, I have built a simple example project to link java's stdio to a containers. It works fine, but when I close the streams, there is still a read from a FileInputStream blocking the application from exiting. 

The example project is here: https://github.com/tlf30/docker-stdio-example

Thank you,
Trevor Flynn

**Comment by scddev** [comment]
As far as I have seen, the threads in NettyDockerCmdExecFactory are not created with daemon=true. So they keep alive after the main thread has ended.

When creating the EventLoopGroup the DefaultThreadFactory is created with:

```
new DefaultThreadFactory(threadPrefix)
```

instead of

```
new DefaultThreadFactory(threadPrefix, true)
```

**Comment by tlf30** [comment]
@scddev thank you for looking into this. Do you know of any work around for this at the moment. I am interested in using this inside of a jboss application and have concerns about the threads not terminating when jboss terminates the application.

**Comment by scddev** [comment]
As far as I can tell it is used in jenkins docker plugins and jenkins exits in my case without problems. When used in a standalone project, calling System.exit also terminates your application. The only case not covered, is when the main thread ends, all other threads will stay alive.

**Comment by tlf30** [comment]
@scddev OK, thank you for checking that. I will be running some tests with jboss to see how it handles the shutdown of the application, I am thinking that jboss will just terminate the threads, but I do not know yet.
