### ISSUE TITLE
Please add Javadoc

### ISSUE THREAD

**Issue by cowwoc** [docker-java/docker-java#944]
Most of the methods are missing Javadoc. While it might be obvious to the committer what each method does, adding Javadoc would certainly help users do the same.

**Comment by KostyaSha** [comment]
Sorry, but we have no time for copy-pasting huge docker API docs, just read docker API docs, we are trying to keep library close to API models

**Comment by cowwoc** [comment]
@KostyaSha I'm not asking you to copy-paste the docker docs. Please document the API-specific portions, such as `ExecStartResultCallback`'s constructor.

**Comment by cowwoc** [comment]
Another example: users have no way of knowing that `DockerClient.stopContainerCmd()` may throw `com.github.dockerjava.api.exception.NotModifiedException` as it isn't documented anywhere.

**Comment by KostyaSha** [comment]
#366
