### ISSUE TITLE
Please add support for the --init flag in create container

### ISSUE THREAD

**Issue by sergioramirezm** [docker-java/docker-java#946]
$ docker create --help
...
--init                           Run an init inside the container that forwards signals and reaps processes

https://github.com/moby/moby/commit/ee3ac3aa66bfb27b7c21dfb253fdaa113baedd4e

**Comment by mschaefers** [comment]
+1 this is an important feature. Docker supports this since version 1.12

**Comment by jhubberts** [comment]
+1, we also need this feature
