### ISSUE TITLE
Cannot build project - Bundlor class ManifestWriterFactory not found

### ISSUE THREAD

**Issue by henriquevcosta** [docker-java/docker-java#948]
I'm trying to build the project (mvn clean install) and I get the following error.

> [INFO] --- org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor (bundlor) @ docker-java ---
>[WARNING] Error injecting: org.eclipse.virgo.bundlor.maven.plugin.BundlorMojo
>java.lang.NoClassDefFoundError: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory
>	at java.lang.Class.getDeclaredConstructors0(Native Method)

The only way I could get it to build was to change the declaration of the bundlor plugin to have the following two dependencies:
```
<plugin>
    <groupId>org.eclipse.virgo.bundlor</groupId>
    <artifactId>org.eclipse.virgo.bundlor.maven</artifactId>
    <version>${maven-bundlor-plugin.version}</version>
    <dependencies>
        <dependency>
            <groupId>org.eclipse.virgo.bundlor</groupId>
            <artifactId>org.eclipse.virgo.bundlor</artifactId>
            <version>1.1.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.virgo.bundlor</groupId>
            <artifactId>org.eclipse.virgo.bundlor.blint</artifactId>
            <version>1.1.2.RELEASE</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <id>bundlor</id>
            <goals>
                <goal>bundlor</goal>
            </goals>
            <configuration>
                <failOnWarnings>true</failOnWarnings>
            </configuration>
        </execution>
    </executions>
</plugin>
```
Is there any additional setup that should be in the building instructions but isn't?

**Comment by orzeh** [comment]
@henriquevcosta Which JDK are you using?

**Comment by KostyaSha** [comment]
Should we move it to profile?

**Comment by orzeh** [comment]
Sure we can, however it would be better to fix the issue.

**Comment by henriquevcosta** [comment]
```
> [~/code/docker-java]:±master ▴$ javac -version
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
javac 1.8.0_144
> [~/code/docker-java]:±master ▴$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by KostyaSha** [comment]
What IDE?

**Comment by henriquevcosta** [comment]
Just doing mvn clean install on the command line.

**Comment by fengxx** [comment]
ci build for pullrequest 996 failed for the same reason
https://travis-ci.org/docker-java/docker-java/jobs/348101921
