### ISSUE TITLE
Exec Start in detach mode fails when using Netty as client

### ISSUE THREAD

**Issue by harijvs6** [docker-java/docker-java#949]
Below are the sample responses from docker 17.06.0-ce

**Exec Start Api with detach as false**
POST /v1.30/exec/1c3edba359a09e2c5c485e088f58f07461ea3ff3446b05061537f1d7132a9b2b/start HTTP/1.1
Content-Type: application/json
Content-Length: 2
Host: localhost
Connection: upgrade
upgrade: tcp

{}
HTTP/1.1 101 UPGRADED
Api-Version: 1.30
Connection: Upgrade
Content-Type: application/vnd.docker.raw-stream
Docker-Experimental: false
Ostype: linux
Server: Docker/17.06.0-ce (linux)
Upgrade: tcp

**Exec Start Api with detach as true**
POST /v1.30/exec/17faf49d29d18c2879085c5705043944eb0faeaa4e9fd87a590b24d4b4dd152d/start HTTP/1.1
Content-Type: application/json
Content-Length: 15
Host: localhost
Connection: upgrade
upgrade: tcp

{"Detach":true}
HTTP/1.1 200 OK
Api-Version: 1.30
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Mon, 13 Nov 2017 12:25:45 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/17.06.0-ce (linux)

I think there is no guarantee that docker responds with 101 UPGRADED for every upgrade request. But Netty Exec Start api is waiting indefinitely for upgrade response from docker.Below is the stack trace for your reference.

java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
com.github.dockerjava.netty.handler.HttpConnectionHijackHandler.awaitUpgrade(HttpConnectionHijackHandler.java:41)
com.github.dockerjava.netty.InvocationBuilder.post(InvocationBuilder.java:300)
com.github.dockerjava.netty.exec.ExecStartCmdExec.execute0(ExecStartCmdExec.java:25)
com.github.dockerjava.netty.exec.ExecStartCmdExec.execute0(ExecStartCmdExec.java:13)
com.github.dockerjava.netty.exec.AbstrAsyncDockerCmdExec.execute(AbstrAsyncDockerCmdExec.java:56)
com.github.dockerjava.netty.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:21)
com.github.dockerjava.netty.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:12)
com.github.dockerjava.core.command.AbstrAsyncDockerCmd.exec(AbstrAsyncDockerCmd.java:21)
com.github.dockerjava.core.command.ExecStartCmdImpl.exec(ExecStartCmdImpl.java:88)
scoops.scoops_docker_java.App.execStart(App.java:135)

Am I missing something? Can you confirm?

**Comment by marcuslinke** [comment]
Probably you're right. Seems `ExecStartCmdExec` should be implemented like this:

```
if(command.hasDetachEnabled()) {
   webTarget.request().accept(MediaType.APPLICATION_JSON).post(command);
} else {
   webTarget.request().accept(MediaType.APPLICATION_JSON).post(command, command.getStdin(), resultCallback);
}
```

**Comment by dprunier** [comment]
The problem with this is that the callback doesn't quite fit when running detached. In the snippet above, I think it would never be called (even though it doesn't make a whole lot of sense to wait for completion if you detach...).

**Comment by daigaigai520** [comment]
is this problem solved?
