### ISSUE TITLE
CPU always at 100% with containers created by docker-java

### ISSUE THREAD

**Issue by PatoTheBest** [docker-java/docker-java#951]
Hello!
I'm currently creating the containers with 

```
System.out.println("[Docker] Creating container with image " + serverType + "-" + mapName);

CreateContainerResponse container = docker
        .createContainerCmd(imageName)
        .withExposedPorts(exposedServerPort)
        .withPortBindings(portBindings)
        .withCpuPeriod(0)
        .withCpuShares(0)
        .exec();

System.out.println("[Docker] Container " + container.getId() + " created with image " + serverType + "-" + mapName);
System.out.println("[Docker] Starting container " + container.getId());

docker.startContainerCmd(container.getId()).exec();

System.out.println("[Docker] Started container " + container.getId());
```

Everything works great, except CPU utilization

When I execute the htop command, the containers use at least 100% of the cpu, constantly, but when I create the containers with

```
 docker run -it --rm (image name here)
```

or

```
 docker run -it --cpus=0 --rm (image name here)
```

The usage is at 5-20%.

Here is an example, with the same exact docker image (the one with less CPU usage started via command, the one with more CPU usage started with the docker-client code). Both process are idling.
https://i.imgur.com/niCiGv8.gifv

Some information using the docker inspect command
The container with low CPU usage https://pastebin.com/GWXkcnbr
The container with high CPU usage https://pastebin.com/KwRmrSPR

I've tried creating the container without the CPU period and CPU shares options and got the same results. Any help will be appreciated.

**Comment by PatoTheBest** [comment]
It was an issue on our end, a poorly coded service trying to read from a non-existent console

**Comment by seabamirum** [comment]
> It was an issue on our end, a poorly coded service trying to read from a non-existent console

@PatoTheBest how did you fix this? I have a number of command-line java apps that I'm trying to run in Docker swarm mode. The only way I can get the program not to exit immediately is by looping and having it looking for input from the console.

**Comment by seabamirum** [comment]
> > It was an issue on our end, a poorly coded service trying to read from a non-existent console
> 
> @PatoTheBest how did you fix this? I have a number of command-line java apps that I'm trying to run in Docker swarm mode. The only way I can get container not to exit immediately is by looping and having it looking for input from the console.

Nevermind. I fixed the CPU issue by using Thread.currentThread().join() in the main method instead of checking for user input.
