### ISSUE TITLE
Can InspectContainerResponse.getNode() method in master branch merge into 3.0.x?

### ISSUE THREAD

**Issue by yx1989** [docker-java/docker-java#961]
The getNode() method in 
src/main/java/com/github/dockerjava/api/command/InspectContainerResponse.java was committed 2 years ago in commit dd9f01d646b2340d4a87522d19a9c5cccec0400c.

This method is very useful to get container Node info.

Can this method merge into 3.0.x?

Thanks a lot.

**Comment by yx1989** [comment]
@fbuecklers Could you please create a pull request for this commit?

Thanks a lot.

**Comment by fbuecklers** [comment]
As far as I know it will be only available in the next 3.1 release, since 3.1 has the scope to support swarm. It is already merged in the master branch.
