### ISSUE TITLE
Problem to getHostPort

### ISSUE THREAD

**Issue by LADIESDIV** [docker-java/docker-java#968]
Hey !

Thank to share your project, it's very nice.
I use your wiki to create new Docker container and start it with exposed ports et I would like get the host port. I use with commande for this but it doesn't work : 
dockerClient.inspectContainerCmd(createContainer().getId()).exec().getNetworkSettings().getPorts();
This line give and I think there are un problem :
22/tcp=null, 8585/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@6fb628, 443/tcp=null, 80/tcp=null

Can you help my to get Host port please ? 

Thank you very much

**Comment by bhowell2** [comment]
I dont really see the problem with what you're doing. The list of ports are there. Can you not just parse the port you're looking for? What do you mean by "host" port? Host address?

**Comment by LADIESDIV** [comment]
How parse the port ? 
I would like the value of port mapping, ie the number of port mapping for container port "8585" in my example. In the command I use, I obtain this : 8585/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@6fb628 and I would like obtain a mapping like this : 8585/tcp=32540 for exemple.

**Comment by bhowell2** [comment]
Gotcha, didn't understand what you were looking for. You want the binding. Here's what I did in groovy (gradle script): 
```groovy
        networkSettings.ports.bindings.forEach({ exposedPort, bindings ->
            if (bindings.size() > 1) {
                throw new RuntimeException("Not expecting a binding larger than size 1... Exposed Port: $exposedPort, Bindings: $bindings")
            }
            if (bindings[0].getHostPortSpec().contains("-")) {
                def portRangeSplit = bindings[0].getHostPortSpec().split("-")
                if (portRangeSplit.size() > 2) {
                    throw new RuntimeException("Don't know what to do with multiple hyphens in port range")
                }
                def beginningRange = portRangeSplit[0]
                def endingRange = portRangeSplit[0]
                for (def i = beginningRange; i <= endingRange; i++) {
                    publicPorts.add(Integer.parseInt(i))
                }
            }
            publicPorts.add(Integer.parseInt(bindings[0].getHostPortSpec()))
        })
```

**Comment by bhowell2** [comment]
Note that `bindings.forEach` gives you a `Map<ExposedPort, Binding[]>`

**Comment by KostyaSha** [comment]
docker-java is just an object model to docker API, please reference docker API docs for descriptions.

**Comment by LADIESDIV** [comment]
I try with API doc and I don't success...
I try to make a auto mapping (binding) for the ExposePort 8585. I use the api doc and I make this like that :
                        ExposedPort tcp8585 = ExposedPort.tcp(8585);
			Binding tcpE = Binding.bindPortSpec(null);
			Ports portBindings = new Ports();
			portBindings.bind(tcp8585, tcpE);
                        container = dockerClient.createContainerCmd(imageId).withExposedPorts(tcp8585).withPortBindings(portBindings).exec();
I use the auto mapping to be sure that host port is not use.
I start the container (with java project) and I see (in the docker host) the mapping (binding) for port 8585 is with host port 32650. I need the have the number of the host port in my java project. So, I try to have the value but I don't success. The command I use is : 
Map<ExposedPort, Binding[]> toto = dockerClient.inspectContainerCmd(createContainer().getId()).exec().getNetworkSettings().getPorts().getBindings();
And the Binding value (host port) for port 8585 is not 32650 but this :[Lcom.github.dockerjava.api.model.Ports$Binding;@6fb628

Do you more understand my issue ? Can you help me ? I don't success to use your recommendations.

**Comment by bhowell2** [comment]
should call `bindings[0].getHostPortSpec()` and parse it. that should give you the 32650

**Comment by KostyaSha** [comment]
Place breakpoint in your java code and look at what you have, that will help you understand where is value that you want.

**Comment by LADIESDIV** [comment]
Thank, It works :+1:
