### ISSUE TITLE
Exception when closing ResultCallbackTemplate stream

### ISSUE THREAD

**Issue by SarahAbdo** [docker-java/docker-java#971]
I am calling DockerClient stats command like this:

`statsCallback = docker.statsCmd(container.getId()).exec(new StatsCallback(countDownLatch));
`
StatsCallBack is a class that extends ResultCallbackTemplate like this:

[private class StatsCallback extends ResultCallbackTemplate<StatsCallback, Statistics> {  
   private final CountDownLatch countDownLatch;      
   private Boolean gotStats = false;     
   private Statistics stats;      
   public StatsCallback(CountDownLatch countDownLatch) {       
         this.countDownLatch = countDownLatch;     
    }      
   @Override     
    public void onNext(Statistics stats) {       
         this.stats = stats;       
         if (stats != null) {         
             gotStats = true;       
         }       
         countDownLatch.countDown();     
    }      
    public Boolean gotStats() {       
         return gotStats;     
    }      
    public Statistics getStats() {       
         return stats;     
    }   
}](url)

When I attempt to close the stream (statsCallback.close();), it always throws an exception: "Error Closing Content Input Stream: Bad File Descriptor"Does anyone have a clue about this ?

Thanks!

**Comment by SarahAbdo** [comment]
@marcuslinke @KostyaSha @rtimush @iGabon @fbuecklers @carlossg Could you check this please ?

**Comment by bhaab01** [comment]
Same issue for me as well ?

Any clue from anybody ?

**Comment by bhaab01** [comment]
I would just collect 1 stream from the container stat command but I am getting a continuous stream when I follow StatsCallbackTest in the repo
