### ISSUE TITLE
Add support for HostConfig#AutoRemove for server-side "--rm" option in API v1.25+

### ISSUE THREAD

**Issue by borlander** [docker-java/docker-java#979]
Starting from Engine API v1.25, the HostConfig has [an "AutoRemove" parameter](https://docs.docker.com/engine/api/v1.25/#operation/ContainerCreate) which is 
[directly mapped](https://github.com/docker/cli/blob/master/cli/command/container/opts.go#L185) to `--rm` option. 

Could you please reconsider the old decision from #336? 
I am ready to provide PR but would like to get the confirmation first.

**Comment by smattheis** [comment]
What's the status here? Is it possible that API version 1.25 is, as it's a bigger change, in development right now?

**Comment by rnacher** [comment]
@KostyaSha, I think you can close this issue, It is already merged in master branch.
