### ISSUE TITLE
How to pull an image

### ISSUE THREAD

**Issue by Geaper** [docker-java/docker-java#981]
I'm doing this simple code but no matter what I type I get 

> java.nio.file.InvalidPathException: UNC path is missing sharename: /\config.json

What is this error?

      ` public static String pullImage(String imageName) {
      
        DockerClient dockerClient = dockerClient();
        dockerClient.pullImageCmd(imageName)                
                    .exec(new PullImageResultCallback());

        return "";
    }`

**Comment by Graham42** [comment]
Maybe the client isn't configured properly? What if you try:

```java
DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().build();
DockerClient docker = DockerClientBuilder.getInstance(config).build();
```

**Comment by satheesh2746** [comment]
This works with docker-java 3.1.5:
  
dockerClient.pullImageCmd("imagename").withTag("latest")
                .exec(new PullImageResultCallback(){
                    @Override
                    public void onNext(PullResponseItem item) {
                        super.onNext(item);
                    } })
                .awaitSuccess();
