### ISSUE TITLE
Allow "Dockerfile", ".dockerignore" entries to be listed in .dockerignore

### ISSUE THREAD

**Issue by gloomybrain** [docker-java/docker-java#983]
https://github.com/docker-java/docker-java/blob/fcb791a5eb5c2f95342e5559584e03543e04d538/src/main/java/com/github/dockerjava/core/dockerfile/Dockerfile.java#L185

This assertion is redundant and may (actually it already does) affect third-party users. E.g. IntelliJ IDEA which uses `docker-java` internally for it's docker plugin is unable to handle the following setup:

**.dockerignore**
```
# exclude everything in the root directory
*/

# except the sources, tests and project configuration
!src
!test
!config.json
```

Whereas `docker build -t name:tag .` command works perfectly, it's still restricted to do exactly the same thing through the `docker-java` library.
Here's [the CHANGELOG](https://github.com/moby/moby/blob/master/CHANGELOG.md#150-2015-02-10) that depicts it's been allowed for quite a while now:

**Comment by vidhu** [comment]
To add to this, `Dockerfile` can be ignore. From the docker docs:

> **You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files**. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

https://docs.docker.com/engine/reference/builder/#dockerignore-file
