### ISSUE TITLE
Custom class-loader?

### ISSUE THREAD

**Issue by cdancy** [docker-java/docker-java#994]
Does docker-java use a custom classloader anywhere within the codebase? Working on an issue with the `gradle-docker-plugin` to load all docker-java jars dynamically into their own classloader, and things get off the ground well enough, but anytime we start playing around with docker-java-callbacks for various functions we get ClassNotFoundExceptions thrown. I poked around and couldn't find anything. Am I missing something obvious?

```
dockerClient.logContainerCmd(getContainerId()).exec(some-callback-object).awaitCompletion()
```

**Comment by KostyaSha** [comment]
Do you use jersey or netty? Do you have full stracktrace? Is it on master (rc)?

**Comment by cdancy** [comment]
Nothing special just pull down `docker-java` as-is so whatever the default is that's what is getting used. We are on the latest release. The scenario is a bit complex as we are attempting to use cglib, also within our custom classloader, to create the callback and then pass that to the invocation above.

**Comment by cdancy** [comment]
Issue with the custom classloader we were using. Sorry for bothering you guys.
